### ISSUE TITLE
Add tests that kube types added as CRDs show the expected columns

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#1003]
We have custom code that makes sure that when CRDs are added for built-in kube types (deployments, services, pods, etc.), `kubectl get <resource>` returns the same columns as the user expects, by replacing the CRD table converter with the go code for the printers for the internal built-in types. We should add tests that ensure we don't regress.

Example - deployments - if we regress:
```
NAME    AGE
kuard   104m
```

This is what's expected:
```
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
kuard   0/1     1            0           3s
```

These can be both API and CLI tests.

cc @kasturinarra

**Comment by kasturinarra** [comment]
ACK & we will add these tests, thanks !!

**Comment by kasturinarra** [comment]
Added a test case in polarion and here is the link for the same https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-50878

**Comment by kasturinarra** [comment]
@ncdc one question for the API tests would you want me to test the CRD additionalPrinterColumns ?? 

oc get crd catalogsources.operators.coreos.com -o yaml
...
  - additionalPrinterColumns:
    - description: The pretty name of the catalog
      jsonPath: .spec.displayName
      name: Display
      type: string
    - description: The type of the catalog
      jsonPath: .spec.sourceType
      name: Type
      type: string
    - description: The publisher of the catalog
      jsonPath: .spec.publisher
      name: Publisher
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date

**Comment by ncdc** [comment]
It's fine to test them, but it's not related to this code/issue

**Comment by kasturinarra** [comment]
> It's fine to test them, but it's not related to this code/issue

okay, i have added CLI test in polarion to ensure we get all the right columns , but how do we cover the api test  ?

**Comment by ncdc** [comment]
For all built in Kubernetes types that someone could import as a CRD, verify that `kubectl get` output between kcp & kube matches.

**Comment by kasturinarra** [comment]
> For all built in Kubernetes types that someone could import as a CRD, verify that `kubectl get` output between kcp & kube matches.

ah, okay, thanks !!
