### ISSUE TITLE
Confusing error message when trying to list workspaces in organization workspace that doesn't exist

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#1004]
**Describe the bug**
When trying to access `/clusters/root:$someOrg` and the request is denied (e.g. that org workspace does not exist), the server returns a confusing error message:

```
error: workspaces.tenancy.kcp.dev "someOrg" is forbidden: "root" workspace access not permitted
```

**To Reproduce**
1. Start kcp
2. `kubectl get --raw /clusters/root:someorg/apis/tenancy.kcp.dev/v1beta1/workspaces`
3. `Error from server (Forbidden): workspaces.tenancy.kcp.dev "someorg" is forbidden: "root" workspace access not permitted`

**Expected behavior**
A clear, meaningful error message.

**Additional context**

**Comment by sttts** [comment]
We cannot leak whether the org exists or access is not allowed. So we need one message for both. But we can say something like "Access to the organization / top-level workspace root:foo not permitted".
