### ISSUE TITLE
Add Authorizer that let's APIExport owner restrict what a user can do with objects of an APIBinding

### ISSUE THREAD

**Issue by shawn-hurley** [kcp-dev/kcp#1013]
**Is your feature request related to a problem? Please describe.**
As an exported set of resources owner, I would like to restrict what a user can do with those resources once bound to a workspace.

**Describe the solution you'd like**
There should be a virtual workspace for a policy that an API export owner can create RBAC rules that will be applied by a new authorizer that will use this RBAC. 
 
**Open Questions**

~~1. I don't understand the type of RBAC rules as an example for this feature. Would we have deny rules?~~
1. Are the RBAC Rules going to all be cluster scoped for the same workspace that the APIExport is created in?

**Current Implementation Plan:**
1. Add an authorizer that will determine if a call to a resource is bound, if it is, and the workspace is defined, and make new RBAC requests against that workspace. if it passes, then delegate down, if it fails return.
2. if the request is not bound, delegate it down the flow chain.

**User Stories:** 
1. API Export where every user is able to create, but only a pre-determined SA can update the status. -> most users should be restricted from updating status, SA should be able to update status.
2. API Export with no additional roles, but the workspace admin has configured RBAC to only allow get/list for a particular user. -> user should be denied to create, but can list
3. API Export where every user can create/get/list/update but not update status. The workspace also has an RBAC that only allows get/list. -> user should be denied to create, should be able to list
4. API Export allows users to get/list but not create/update etc. SA can create and update. No RBAC policy should be allowed to be created in bound workspace that allows for create/update.

**Comment by ncdc** [comment]
> I don't understand the type of RBAC rules as an example for this feature. Would we have deny rules?

Kube's RBAC mechanism only supports adding permissions, not taking them away.

**Comment by ncdc** [comment]
Example use case: users generally (always?) must be forbidden from updating status of CRs for bound CRDs (CRDs coming from an APIBinding/APIExport)

**Comment by shawn-hurley** [comment]
I agree with that use case but am having a hard time understanding the use of roles for this when we don't have to deny rules.

**Comment by sttts** [comment]
The rules will be an upper bound. Compare https://github.com/kcp-dev/kcp/blob/main/docs/authorization.md#authorizers. We would have another block in that flow that checks requests against APIBinding resources.

Note: the new policy is still positive, i.e. adding a role or binding will always allow more or the same, never forbid anything that was allowed before.

**Comment by shawn-hurley** [comment]
updated the issue to incorporate my understanding of the ask and the current high-level plan. Please let me know what you think.

**Comment by ncdc** [comment]
> Add a new field on APIExportSpec that is a reference to a workspace

Why/what for? Why can't this be the workspace in which the APIExport resides?

**Comment by shawn-hurley** [comment]
@ncdc @sttts update the proposed path without changing the APIExport just using the RBAC that is allowed.
