### ISSUE TITLE
Vote for a kcp logo (closes May 25th)

### ISSUE THREAD

**Issue by robszumski** [kcp-dev/kcp#1021]
The kcp project needs a logo! This will be used on GitHub, a future website and possibly on social channels.

**Goals:**
Have the logo represent kcp but not conflict too much with other projects in the [CNCF landscape](https://landscape.cncf.io/images/landscape.pdf). A few concepts or topics that could be represented: control plane, applications, building blocks, application-centric, declarative, open APIs.

**Instructions:**
Use the 👍 emoji reaction on any of the commented logos you see below. All other emoji reactions will not be counted. Voting will close on May 25th and a down-selection will occur with the top 2 for further discussion on the community call.

**Comment by robszumski** [comment]
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/755540/167668429-e00654d1-f790-420f-bd73-4f57c4d60a12.png">

**Comment by robszumski** [comment]
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/755540/167668546-8502cadc-cf65-4099-a03d-1ea0aaba3f65.png">

**Comment by robszumski** [comment]
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/755540/167668601-cd83b041-16a1-4259-9490-74d734126ea8.png">

**Comment by robszumski** [comment]
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/755540/167668637-a5592b86-bf41-44e5-b919-b9fdb5c079b6.png">

**Comment by robszumski** [comment]
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/755540/167668672-6c9ae3ac-c26c-49e4-9cb2-291c7677526c.png">

**Comment by robszumski** [comment]
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/755540/167668722-88913ee1-7198-42d5-bd31-123d846c8058.png">

**Comment by robszumski** [comment]
Tallying the results:

[Option 1](https://github.com/kcp-dev/kcp/issues/1021#issuecomment-1122561935): 1 vote
[Option 2](): 
[Option 2](): 
[Option 2]():

**Comment by sttts** [comment]
For further discussion in next week's community call. Form your opinion:

<img width="1283" alt="Bildschirmfoto 2022-05-26 um 22 02 56" src="https://user-images.githubusercontent.com/730123/170569207-c24c4533-e652-4aa8-ba70-7e05b8eaed03.png">

**Comment by sttts** [comment]
@Roming22 compare https://github.com/kcp-dev/kcp/blob/f7698650f5787df8da1f81b272286f92416a850c/contrib/logo/README.md in https://github.com/kcp-dev/kcp/pull/1210.

**Comment by sttts** [comment]
Decision has long been made and commited to the repo https://github.com/kcp-dev/kcp/tree/main/contrib/logo.
