### ISSUE TITLE
Unable to connect to the server: x509: certificate is valid for 10.201.133.11, not 192.168.0.4

### ISSUE THREAD

**Issue by guymguym** [kcp-dev/kcp#1032]
**Describe the bug**
I moved my laptop between wifi networks with kcp running and then I get this certificate ip mismatch error, tried to stop and start kcp server but it didn't resolve. Do I need some manual cleanup?

```
$ echo $KUBECONFIG   
.kcp/admin.kubeconfig
$ kubectl ws use root
Current workspace is "root".
$ kubectl get ns
Unable to connect to the server: x509: certificate is valid for 10.201.133.11, not 192.168.0.4
```

**To Reproduce**
1. Start kcp at work
2. Drive home
3. Try to use it at home

**Expected behavior**
No certificate error

**Additional context**
Running kcp from repo on Mac (arm64), with workload cluster running in kind (in podman machine).

**Comment by guymguym** [comment]
I deleted `.kcp/apiserver.{key,crt}` and restarted the server and it got resovled.

**Comment by pdettori** [comment]
Deleting `.kcp/apiserver.{key,crt}` helps with re-generation of certs, however if there are existing workspaces they keep the old IP in the URL and they are no longer accessible without manually editing the `admin.kubeconfig` file.
