### ISSUE TITLE
virtualworkspace: forwardingregistry: are we at the correct level of abstraction?

### ISSUE THREAD

**Issue by stevekuznetsov** [kcp-dev/kcp#1060]
Right now, the implementation in `pkg/virtual/framework/forwardingregistry` is implementing `rest.StandardStorage`, which lives at a level in the stack that is low enough that incoming requests have had their bodies + query parameters parsed into Go-objects and functions. Furthermore, it expects as output Go objects, so there are a couple of implications:

 - we are not able to pass along the incoming request bodies in e.g. UPDATE or CREATE calls without parsing them
   - this leads us to drive the GET -> apply -> validate -> UPDATE flow, which is *supposed* to happen between the API server and the database
   - this leads to more network traffic, more apiserver + database load, and bugs like https://github.com/kcp-dev/kcp/pull/1059
 - we are doubling serialization and deserialization cost (especially egregious on WATCH streams)

I ran into this type of conundrum in the sharding server implementation a long time ago. At the time, I was also looking to implement `rest.StandardStorage`, so had to hack around things like [this](https://github.com/kcp-dev/kcp/blob/50e3ab2dcfe2e17dc0bd9d0adf1517e98b59c55d/pkg/sharding/apiserver/handler.go#L212-L239) ... the multi-shard handlers actually did want to mess with the `resourceVersion` for objects on the wire, so I stuck with `rest.StandardStorage`, and expected to find some more minimal deserialization later. For the forwarding registry, if we expect *not* to change the underlying fields in the data, perhaps we can be implementing it at a different layer of abstraction altogether to side-step these issues?

/cc @ncdc @sttts @davidfestal

**Comment by davidfestal** [comment]
> For the forwarding registry, if we expect not to change the underlying fields in the data

At least for the syncer virtual workspace we expect to change the resources "on-the-fly" while forwarding. This is the whole point of the per-workloadcluster transformations that will be performed on the syncer virtual workspace side, and which would be the basis for the future implementation of syncing "strategies" (whatever we call them) like deployment splitter, etc ...

**Comment by stevekuznetsov** [comment]
@davidfestal what mutations are you speaking of?

**Comment by davidfestal** [comment]
cf https://github.com/kcp-dev/kcp/issues/487:

> explore:
> - a mechanism to plug-in live, golang-based transformations (one-object-to-one-object) of objects in kcp
> - a mechanism to plug-in live, golang-based transformations that do 1:n mapping of an object in kcp to multiple objects to be synced.

For now only the 1rst as been prototyped.

cf. also:
- and https://github.com/kcp-dev/kcp/issues/751#issuecomment-1075338469
- https://github.com/kcp-dev/kcp/issues/786#issuecomment-1081933596
- https://kubernetes.slack.com/archives/C021U8WSAFK/p1649367172590119?thread_ts=1649334621.955789&cid=C021U8WSAFK

**Comment by stevekuznetsov** [comment]
Interesting. 1:n sounds very tricky to do in e.g. WATCH. Might be something we should try to design up-front to make sure we get it right.

As it stands, one side-effect of the current approach is that we do `PrepareForUpdate()` in the intermediate server (and validation) - I think this is clearly wrong, as the storage responsible for the object should (e.g.) decide when the generation changes, not some generic intermediary.
