### ISSUE TITLE
Rename WorkloadCluster to SyncTarget

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#1074]
WorkloadCluster is a bit misleading and has some overlap with other APIs out there, naming wise. A more appropriate name is something like SyncTarget, because the only thing we're using the API for is as a scheduling target.

**Comment by UtkarshChaurasia** [comment]
Hi @ncdc, I would like to work on this!

**Comment by ncdc** [comment]
@UtkarshChaurasia assigned!

**Comment by ncdc** [comment]
@kcp-dev/kcp-contributors are we ok with SyncTarget?

**Comment by stevekuznetsov** [comment]
:shipit:

**Comment by pweil-** [comment]
@UtkarshChaurasia let's move forward with SyncTarget, we can change it if we need to.  

Are you able to work on this in 0.6?

**Comment by UtkarshChaurasia** [comment]
Hi @pweil- , sure. Also the changes have to be made in code as well as in documentation right as I can see the term WorkloadCluster is mentioned in few markdowns as well?

**Comment by pweil-** [comment]
doc updates are always appreciated. If you could include those it would be great.  Thanks!

**Comment by ncdc** [comment]
@UtkarshChaurasia checking in - will you have time to do this soon? Or should we reassign it? Thanks!

**Comment by sttts** [comment]
We want this before tagging of v0.6.

**Comment by UtkarshChaurasia** [comment]
Hi @sttts really sorry, would not be able to complete it before v0.6 due to some other commitments.
