### ISSUE TITLE
Org level APIs

### ISSUE THREAD

**Issue by maleck13** [kcp-dev/kcp#1085]
As the provider of a set of APIs, I would like to be able to offer certain APIs at the "org" level. The idea is these APIs would provide capabilities focused around applying configuration and policy across end user workspaces within an org.

Example Use Case:
As an org administrator, I want to specify a set of domains that can be used for exposing services via ingress in my org workspaces. The API I am using needs me to verify ownership of the domain via a DNS txt record. I can do this at the workspace level, but this means re-verifying the domain for each individual workspace. Instead I would like to verify my domain once with the org workspace, and then have it be available for use within any workspace under my org.  

@sttts  @chirino @ncdc

**Comment by sttts** [comment]
The workspace type work @stevekuznetsov is one will allow addition of APIBindings. With @ncdc's APIExport virtual workpace you will then be able to access those API objects in all workspaces. tl/dr: we are near.
