### ISSUE TITLE
Workload APIExport controller stomps on user-defined APIExport latestResourceSchemas

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#1088]
**Describe the bug**
User-created APIExports are modified by the workload apiexport controller unexpectedly, changing latestResourceSchemas.

**To Reproduce**
1. Create an APIResourceSchema
2. Create an APIExport that exports the schema
3. Create a WorkloadCluster
4. Start the syncer
5. The spec.latestResourceSchemas in the APIExport from 2 are modified to include the APIs imported by the syncer

**Expected behavior**
No changes to a user-supplied APIExport

**Additional context**
The controller has a comment saying it only applies to an APIExport named `workloads` but that doesn't appear to be implemented.

**Comment by sttts** [comment]
This is expected with the current behaviour (under feature gate). Medium term we probably will need ThingComputeService. Short term we could just care about "compute" APIExport only.

**Comment by sttts** [comment]
Alternative: only touch APIExport with `workloads.kcp.dev/compute: true` label.
