### ISSUE TITLE
Adding binaries to the releases

### ISSUE THREAD

**Issue by fgiloux** [kcp-dev/kcp#1092]
**Description**
It would be nice to have the kcp and kubectl plugin binaries added to the [releases](https://github.com/kcp-dev/kcp/releases).
Today when I want to distribute the kubectl plugin I need to download the source and compile it. It is surely doable but having the binaries at the distance of a curl would be handy.

**Additional context**
I will be using the kcp plugin inside a container.
It is really just a nice to have but may not cost much effort either.

**Comment by ncdc** [comment]
👍. We should look into using goreleaser

**Comment by sttts** [comment]
Maybe through https://github.com/softprops/action-gh-release ?
