### ISSUE TITLE
Downstream PODs can't connect to KCP if proxied with a TLS cert not signed by KCP CA.

### ISSUE THREAD

**Issue by jmprusi** [kcp-dev/kcp#1096]
**Describe the bug**

When trying to connect from a POD running in a pcluster to KCP, using client-go `inClusterConfig()`, if KCP is using an external certificate the connection will fail with "x509: certificate signed by unknown authority".

#### Why does that happen?

The syncer will mutate the downstream deployment to mount into the pods:
* Secret `kcp-default-token`: URL + Token
* Configmap `kcp-root-ca.crt`: Internal public CA cert of KCP. 

When the client loads the CA Data from `kcp-root-ca.crt` it tries to validate the server certificate against it, failing, as the KCP instance is proxied by an external service, using a certificate signed by another CA.

**To Reproduce**
1. Deploy KCP and proxy it using a Let's Encrypt TLS cert.
2. Create a workspace etc... 
3. Create a Deployment in your workspace, use an image that contains kubectl.
4. From the PCluster, exec in the POD `kubectl get deployments`
5. See error

**Expected behavior**
The kubeClient should be able to connect, and not fail with "x509: certificate signed by unknown authority" if the certificate is valid.

**Comment by ncdc** [comment]
@jmprusi does that mean we can close this?

**Comment by jmprusi** [comment]
@ncdc Yes! Closing.
