### ISSUE TITLE
CI to build/publish images

### ISSUE THREAD

**Issue by imjasonh** [kcp-dev/kcp#111]
Right now if someone wants to run kcp they have to build and run the code themselves. This isn't too bad for `cmd/kcp` and `cmd/cluster-controller`, but for users that want to run the in-cluster ("pull") syncer, this requires them to build that image themselves.

It'd be better if that image was automatically built and available for them somewhere, so they could just run the Cluster Controller directly. We should run some CI to build and publish [`quay.io/kcp-dev/kcp-syncer:latest`](https://quay.io/kcp-dev/kcp-syncer) on every merged PR.

This would also be good practice for an eventual future where we have actual releases.

**Comment by 2uasimojo** [comment]
You want to do this from prow? appsre?

**Comment by imjasonh** [comment]
I was planning to do it with GitHub Actions for now, because it's easiest. Maybe even publishing to ghcr.io because auth would be easy. This wouldn't have to be the place it lives forever.

If there are preferences for some other way I'm open to discussing it.

**Comment by davidfestal** [comment]
Last month I had already created the quay.io/kcp-dev organization, as well as the quay.io/kcp-dev/kcp-syncer repository.
Do we still plan to use it (which is also possible from GH action through a Quay.io robot token) ? or will we use ghcr.io in anycase ? cc @smarterclayton 
With quay.io there is the lightweight way of setting a triggered build directly from quay.
@imjasonh If you provide me with your quay.io login, I'd be able add you as an owner of the org and repo.

**Comment by imjasonh** [comment]
I don't have a strong preference for ghcr or quay either way, it was nice to be able to set up ghcr build+push with just a few additional lines to ci.yaml. If you'd prefer to set up quay that's fine too.

In order to use ghcr with GitHub Actions we need an org admin (currently only @smarterclayton) to [enable ghcr](https://docs.github.com/en/packages/working-with-a-github-packages-registry/enabling-improved-container-support-with-the-container-registry#enabling-the-container-registry-for-your-organization-account) for the org.

**Comment by imjasonh** [comment]
The image is now pushed to https://github.com/kcp-dev/kcp/pkgs/container/kcp%2Fsyncer-c2e3073d5026a8f7f2c47a50c16bdbec -- we can change the name if we want to, but at least something is better than nothing.
