### ISSUE TITLE
Syncer won't connect to KCP when KCP is running in a pod 

### ISSUE THREAD

**Issue by mvazquezc** [kcp-dev/kcp#1130]
**Describe the bug**
We are deploying KCP in a pod and then exposing it using an OpenShift Route. We can access the KCP instance using the kubectl and kcp plugin (although we need to use the `--insecure-skip-tls-verify`).

When we try to add a WorkloadCluster, it fails to start because the certificate is not valid for the external hostname that we configured in KCP. This is the log we see:

~~~sh
E0523 16:05:54.520348       1 run.go:74] "command failed" err="Get \"https://kcp-kcp.apps.kni1.cloud.lab.eng.bos.redhat.com:443/clusters/root:telcops:team-a/apis/workload.kcp.dev/v1alpha1/workloadclusters/hypershift\": x509: certificate is valid for localhost, not kcp-kcp.apps.kni1.cloud.lab.eng.bos.redhat.com"
~~~

**To Reproduce**
1. Deploy KCP on OCP and expose it using an OpenShift Passthrough Route.
2. Create a WorkloadCluster and apply the syncer yaml in the destination cluster
3. Check the logs

**Expected behavior**
Syncer should be able to skip certificate verifications.

**Additional context**
This may be related to #1096 

cc: @e-minguez

**Comment by ncdc** [comment]
@mvazquezc are you using `kubectl kcp workload sync` to set up the WorkloadCluster & then taking the yaml it outputs and passing that to `kubectl apply` in the destination cluster?

**Comment by mvazquezc** [comment]
@ncdc correct. This is the command we used:

`kcp workload sync hypershift --syncer-image ghcr.io/kcp-dev/kcp/syncer:main --resources virtualmachineinstances.kubevirt.io --resources virtualmachines.kubevirt.io > syncer-hypershift.yaml`

Then applied the manifest to the pcluster:

`oc --kubeconfig=hosted0.kubeconfig apply -f syncer-hypershift.yaml`

If it helps, we can provide access to the cluster.

**Comment by ncdc** [comment]
This is different than #1096 because you aren't going through that path (where you create the deployment in kcp, kcp mutates it and sends to to the pcluster)

**Comment by csams** [comment]
As a workaround try terminating TLS at the route (could re-encrypt to the backend) and removing any CA data from the generated workload cluster yaml.

**Comment by ncdc** [comment]
I chatted with @mvazquezc and it sounds like this is something specific to how they deployed kcp. Would it be ok to close this (and reopen if needed)?
