### ISSUE TITLE
Lock down kcp labels and annotations

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#1138]
We use labels and annotations for many security sensitive purposes. We need admission to protect those to be only touched by system components.

**Comment by s-urbaniak** [comment]
This needs to be solved generically, using a separate admission controller.

**Comment by sttts** [comment]
Would suggest to go with `system:masters` group membership.

**Comment by s-urbaniak** [comment]
@sttts "system components", how can I identify those? (next to the `system:masters` group membership)

**Comment by s-urbaniak** [comment]
as discussed OOB just `system:masters` for now.

**Comment by s-urbaniak** [comment]
In addition we want:
- protecting labels from the `kcp.dev` domain
- have a (hardcoded for now) allow-list of annotatins/labels to skip
