### ISSUE TITLE
Add authorization checks (SAR) for APIExport virtual workspace

### ISSUE THREAD

**Issue by shawn-hurley** [kcp-dev/kcp#1151]
We want to make sure that the user's access the Virtual Workspace for an APIExport, that they have permissions.

I believe that that this means the user has access to the sub resource '/content' on the given workspace type being used.

It sounds like this to me, is the check that we will run for every interaction with a given virtual workspace.

**Comment by ncdc** [comment]
This is more going to be a ServiceAccount accessing the endpoint, but that's nit-picky 😄 

The client will request `/services/apiexport/$clusterContainingAPIExport/$apiExportName/clusters/...`. We need to perform a SAR that the client is authorized for that request. The SAR for this is probably something like

```
authorizer.AttributesRecord{
		APIGroup:        "apis.kcp.dev",
		APIVersion:      "v1alpha1",
		Resource:        "apiexports",
		Name:            "$apiExportName",
		ResourceRequest: true,
		User:            user,
		Verb:            "<not sure but something other than get/list/etc>",
	}
```

**Comment by sttts** [comment]
Alternative:
```
authorizer.AttributesRecord{
		APIGroup:        "apis.kcp.dev",
		APIVersion:      "v1alpha1",
		Resource:        "apiexports",
		SubResource: "objects"
		Name:            "$apiExportName",
		ResourceRequest: true,
		User:            user,
		Verb:            "access",
	}
```

**Comment by shawn-hurley** [comment]
I think it might be good to make sure that I know what the goal is. 

IIUC, this Virutal Workspace is for the ServiceProvider to watch/list/update the resources that they are exporting.

I think, that a quick win of the subresource of Content, with a followup on the more "andriod permission" model when binding, should allow more granular control. I could see something where when someone "accepts" these permissions they are added in the workspace and we can forward the request to the underlying workspace. 

What do folks think?

**Comment by ncdc** [comment]
@shawn-hurley can you fill out an AttributesRecord with your proposal?

**Comment by shawn-hurley** [comment]
```authorizer.AttributesRecord{
		APIGroup:        "apis.kcp.dev",
		APIVersion:      "v1alpha1",
		Resource:        "certificates",
		SubResource: "",
		Name:            "<actual-object-name>",
		ResourceRequest: true,
		User:            user,
		Verb:            "<actual-verb>",
	}

**Comment by ncdc** [comment]
Ok, so it's similar to https://github.com/kcp-dev/kcp/issues/1151#issuecomment-1138684431, but with objects->content, and access->actual-verb

**Comment by sttts** [comment]
I like that variant because we can give other service account read access. For example, some controller authors already asked for ClusterWorkspace list/watch.
