### ISSUE TITLE
`kubectl-kcp ws --help` documents neither `--use` nor `--enter`

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/kcp#1189]
**Describe the bug**
`kubectl kcp workspace --help` allegedly describes the available flags, but does not mention either `--use` or `--enter`.  It also outputs some examples, one of which uses the flag `--use`.  When I try that example, I am told that `--use` is deprecated and I should use `--enter` instead.

**To Reproduce**

1. `kubectl kcp workspace --help`
2. `kubectl kcp workspace create my-workspace --use`

**Expected behavior**
I expected all the flags to be documented in the help output.  I expected the examples to be current.

**Additional context**
This is from the current `main`, commit 62dd95ce10e7cdefc502129414e60b4a52a79aa0 .

**Comment by sttts** [comment]
```
Creates a new personal workspace

Usage:
  kcp workspace create [flags]

Examples:
kcp workspace create <workspace name> [--type=<type>] [--enter [--ignore-not-ready]] --ignore-existing

Flags:
      --enter             Immediately enter the created workspace
  -h, --help              help for create
      --ignore-existing   Ignore if the workspace already exists
      --type string       A workspace type (default: Universal)
```

The flag `--use` is deprecated (in the code) afaik.
