### ISSUE TITLE
`kubectl kcp ws ju:nk` succeeds to create bad state

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/kcp#1190]
**Describe the bug**
The `kubectl kcp ws` subcommand will accept a workspace argument that is nonsense if it contains a colon, leading to a state that is difficult to recover from.

**To Reproduce**
1. Start with `Current workspace is "root".`
2. `kubectl kcp ws junk` .  Observe `error: clusterworkspaces.tenancy.kcp.dev "junk" not found`
3. `kubectl kcp ws ju:nk` .  Observe `Current workspace is the URL "https://1.2.3.4:6443/clusters/ju:nk`.  But there is not really any such thing.
4. `kubectl kcp ws ..` .  Observe `error: current URL "https://1.2.3.4:6443/clusters/ju:nk" does not point to cluster workspace`.
5. `kubectl kcp ws root:default` .  Observe `error: current URL "https://1.2.3.4:6443/clusters/ju:nk" does not point to cluster workspace`.

**Expected behavior**
Invalid input is rejected even if it contains a colon.

**Additional context**
current `main`, commit 62dd95ce10e7cdefc502129414e60b4a52a79aa0

**Comment by sttts** [comment]
- `kubectl kcp ws -`
- `kubectl kcp ws root` or any other valid workspaces 

bring you back.

A simple check that one can access the workspace, e.g. at least discovery works, certainly makes sense.

**Comment by sm43** [comment]
/assign
hello, I was trying to fix this so if we check if the logical cluster and workspace exist and if not found then return
would that work for this case?
so something like this
```
if strings.Contains(name, ":") {
	splittedName := strings.Split(name, ":")
	workspaceName := splittedName[len(splittedName)-1]
	clusterName := logicalcluster.New(strings.TrimSuffix(name, ":"+workspaceName))
	_, err := kc.personalClient.Cluster(clusterName).TenancyV1beta1().Workspaces().Get(ctx, workspaceName, metav1.GetOptions{})
	if err != nil {
		if apierrors.IsNotFound(err) {
			return fmt.Errorf("invalid input")
		}
		return err
	}
}
```

**Comment by MikeSpreitzer** [comment]
No, trying to change to a valid workspace does not work.  `kubectl kcp ws -` is the _only_ thing that works.  Here is a longer typescript.

```
(base) mspreitz@mjs12 kcp % kubectl kcp ws root
Current workspace is "root".
(base) mspreitz@mjs12 kcp % kubectl kcp ws root:default
Current workspace is "root:default".
(base) mspreitz@mjs12 kcp % kubectl kcp ws ju:nk       
Current workspace is the URL "https://1.2.3.4:6443/clusters/ju:nk".
(base) mspreitz@mjs12 kcp % kubectl kcp ws list 
error: current URL "https://1.2.3.4:6443/clusters/ju:nk" does not point to cluster workspace
(base) mspreitz@mjs12 kcp % kubectl kcp ws ..  
error: current URL "https://1.2.3.4:6443/clusters/ju:nk" does not point to cluster workspace
(base) mspreitz@mjs12 kcp % kubectl kcp ws root
error: current URL "https://1.2.3.4:6443/clusters/ju:nk" does not point to cluster workspace
(base) mspreitz@mjs12 kcp % kubectl kcp ws root:default
error: current URL "https://1.2.3.4:6443/clusters/ju:nk" does not point to cluster workspace
(base) mspreitz@mjs12 kcp % kubectl kcp ws -
Current workspace is "root:default".
```

**Comment by MikeSpreitzer** [comment]
@sm43 , thanks for the suggestion.  I am new to this code base, so am not sure I understood your suggestion correctly, but I tried it.  I made https://github.com/MikeSpreitzer/kcp-dev-kcp/tree/dontfix-1190 and tested it.  The problem remains.

**Comment by sttts** [comment]
`kcp ws root:default` should definitely work. If it doesn't that's a bug.

Btw, we could and maybe should reject `kcp ws ju:nk` because it is not starting with `root:`. In any installation with a front-proxy everything other than `root/root:*` will stop working. It would only work if talking directly to a shard.

**Comment by sm43** [comment]
> @sm43 , thanks for the suggestion. I am new to this code base, so am not sure I understood your suggestion correctly, but I tried it. I made https://github.com/MikeSpreitzer/kcp-dev-kcp/tree/dontfix-1190 and tested it. The problem remains.

Thank you @MikeSpreitzer for trying out. I am also new to the code base 🙃 
I have tried again and also added a check as @sttts  suggested in the above comment. I have made https://github.com/sm43/kcp/tree/kcp-1190-fix with my changes.
 
Based on the changes here is the output

**Current workspaces in the cluster**
```
 > ~ > k kcp ws
Current workspace is "root".
 > ~ > k kcp ws list
NAME      TYPE           PHASE   URL
default   Organization   Ready   https://10.76.98.68:6443/clusters/root:default
green     Organization   Ready   https://10.76.98.68:6443/clusters/root:green
 > ~ > k kcp ws use green
Current workspace is "root:green" (type "Organization").
 > ~ > k kcp ws list
NAME   TYPE        PHASE   URL
g1     Universal   Ready   https://10.76.98.68:6443/clusters/root:green:g1
g2     Universal   Ready   https://10.76.98.68:6443/clusters/root:green:g2
```

**CLI output for invalid workspaces**
```
 > ~ > k kcp ws junk
error: clusterworkspaces.tenancy.kcp.dev "junk" not found
 > ~ > k kcp ws ju:nk
error: invalid workspace: ju:nk
 > ~ > k kcp ws root:abc
error: invalid workspace: root:abc
 > ~ > k kcp ws root:green:g3
error: invalid workspace: root:green:g3
 > ~ > k kcp ws
Current workspace is "root".
 > ~ > k kcp ws root:default
Current workspace is "root:default".
```
let me know what do you all think about this solution :)

**Comment by MikeSpreitzer** [comment]
This looks like an improvement.  At least the error messages are in terms the user is using, rather than coming from deep in the code.

From an outside-in perspective, I see some surprising irregularities in the examples shown above.  `k kcp ws root:abc` _could_ be legitimate, if someone had created a workspace by that name, right?  Does "invalid workspace" mean syntactically invalid (as in a pathname  not starting with "root") or not existent or either?  The first example shows a different error message for a workspace that does not exist.

**Comment by sm43** [comment]
Yeah invalid workspace meant the format is incorrect.
 ```
 > ~ > k kcp ws root:green:g3
error: invalid workspace: root:green:g3
```
in this case the workspace doesn't exist, I was explicitly handling the error
but I have updated code in pull req, now it would return not found 
```error: clusterworkspaces.tenancy.kcp.dev "g3" not found```
