### ISSUE TITLE
Difficult to understand error message when trying to create child workspace named "root"

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/kcp#1214]
**Describe the bug**
I tried to make a little mischief.  I was rebuffed, but the error message will not be understandable to someone who is not familiar with the code.

```
(base) mspreitz@mjs12 kcp % kubectl kcp ws default
Current workspace is "root:default" (type "Organization").

(base) mspreitz@mjs12 kcp % kubectl kcp ws create root
error: ClusterWorkspace.tenancy.kcp.dev "root" is invalid: <nil>: Invalid value: "": "metadata.name" must not validate the schema (not)

(base) mspreitz@mjs12 kcp % kubectl kcp ws create rooty
Workspace "rooty" (type "Universal") created. Waiting for being ready.
```

That last command makes it clear that the string appearing last is not an absolute pathname but just the last step.

**To Reproduce**
Shown above.

**Expected behavior**
When the particular step name is bad, the error message should clearly say that.

**Additional context**

**Comment by sttts** [comment]
That's an OpenAPI error message. We could move it from the OpenAPI pattern to admission to produce a nicer message.
