### ISSUE TITLE
Add new API Spec Fields for PermissionClaims that allows for addition of resources to the virtual workspace

### ISSUE THREAD

**Issue by shawn-hurley** [kcp-dev/kcp#1221]
In the initial work, we will only deal with the identity hash and GVR. 

When Binding in the first step it will implicitly grant full access to the claims defined in the spec.

If you want to follow along with the more full API Design: https://docs.google.com/document/d/1cGsIXPovMEj-ZgIEY5ZKjpib4wFKuRH02Pwj9ukepd4/edit

**Comment by shawn-hurley** [comment]
I wanted to create a place to discuss the shape of the API in the Opens as I am building it to get some early eyes on it. 

The spec is pretty much what is described in: https://docs.google.com/document/d/1CB3QEyn90u_S6q_teOoWtk0f_Dp0Obo9JH2AUGbifPg/edit#

```go
type APIExportSpec struct {
.......

// +optional
PermissionsClaims []PermissionClaim `json:"permissionClaims"`
}

type PermissionClaim struct {
	metav1.GroupVersionResource
	Identity string       `json:"identity"`
	Verbs    metav1.Verbs `json:"verbs"`
	Objects  []APIObject  `json:"objects"`
}

// TODO: Add more types of API Objects References in the future
// Examples include Patterns, Json Path's to read, and Label Selectors.
type APIObject struct {
	ObjectRef *corev1.ObjectReference
	LabelRefs *LabelRefs
}

type LabelRefs struct {
        Labels metav1.Labels
}
```

For the status, I am thinking that we need to create a hash/identity for each permission claim, that can be referenced in the APIBinding when accepting a specific claim.

```go
type APIExportStatus struct {
....
APIExportPermissionClaims []APIExportPermissionClaimIDs
}

type APIExportPermissionClaimIDs struct {
	Identity string       `json:"identity"`
	Verbs    metav1.Verbs `json:"verbs"`
	metav1.GroupVersionResource
        Objects []APIObject 
}
```

**Comment by sttts** [comment]
Can we move the API discussion into a gdoc? Here it is tedious.

**Comment by shawn-hurley** [comment]
As part of this work, we will need to create a new controller and admission plugin. These will be responsible for handling labeling the resources in KCP that are allowed by a specific permissionClaim.

We will then re-write the list for any resource that is not the exported resource to filter on the label passed on the permission claim that grants access. 

in the future, the binding being accepted will be a part of the controller and the admission plugin.

**Comment by sttts** [comment]
as addition: in the future, we might inject predicate support into server-side filtering, like label filters and some field selectors are implement. That might allow us to get rid of the controller.

Note: we cannot filter in the vw. That would not scale.
