### ISSUE TITLE
commands executed directly after creating workspace with "--enter" option occasionally fail

### ISSUE THREAD

**Issue by xinredhat** [kcp-dev/kcp#1274]
**Describe the bug**
I observed that the commands executed directly after creating workspace with the "--enter" option **occasionally** fail. I guess workspace needs a little bit more time. After I added logic in script to check if new workspace is ready. The issue doesn't happen again.

**To Reproduce**
1. Create an Universal workspace with `--enter` option
`$ KUBECONFIG="$KUBECONFIG_KCP" kubectl get workspaces demo --enter`
2. Create WorkloadCluster in the new workspace  immediately
`$ KUBECONFIG="$KUBECONFIG_KCP" kubectl kcp workload sync local  --syncer-image ghcr.io/kcp-dev/kcp/syncer:release-0.4  > "$kube_dir/syncer.yaml"`
it reported error 
```
error: failed to create WorkloadCluster: the server could not find the requested resource (post workloadclusters.workload.kcp.dev)
```

**Expected behavior**
It should create resources such as WorkloadCluster in the newly created workspace.

**Comment by kasturinarra** [comment]
@xinredhat AFAIU the minimum we need to wait for the workspace to be intialized and ready before performing next steps so IMO this is not a bug but i will wait for the development team to comment more on it, thanks !!

**Comment by stevekuznetsov** [comment]
It looks like we do attempt to do that, so this is a bug for sure:

https://github.com/kcp-dev/kcp/blob/9882f39bd32659e7696ac3e49841870727160fc6/pkg/cliplugins/workspace/plugin/kubeconfig.go#L373-L387

**Comment by sttts** [comment]
might be a race between pkg/server/apiextensions logic depending on informers, and the bootstrap controller having created the CRDs and removing its initializer?

**Comment by stevekuznetsov** [comment]
Maybe the apiextensions server should have it's own initializer? :)

**Comment by mjudeikis** [comment]
/close
reopen if still needed
