### ISSUE TITLE
Increase coverage for pkg/schemacompat

### ISSUE THREAD

**Issue by imjasonh** [kcp-dev/kcp#128]
```
$ go test -cover ./pkg/schemacompat
ok  	github.com/kcp-dev/kcp/pkg/schemacompat	0.469s	coverage: 34.0% of statements
```

To see which lines aren't covered (GitHub won't let me attach it):

```
go test -coverprofile=coverage.out ./pkg/schemacompat && go tool cover -html=coverage.out
```

More coverage of this code should give us more confidence in the implementation, and it should be fairly easy to cover. We can maintain high coverage using [codecov](https://github.com/codecov/codecov-action), to note coverage deltas in PR comments.

(As always, the goal isn't 100% coverage, it's confidence in the code, whatever coverage %age is reported)

Once coverage is higher we can also consider adding mutation tests, using e.g., https://github.com/zimmski/go-mutesting, which can help us find even more behavior that isn't tested, for example cases where the input to a method doesn't affect test failure.

**Comment by imjasonh** [comment]
After #129 we have shareable coverage reports: https://codecov.io/gh/kcp-dev/kcp/src/main/pkg/schemacompat/schemacompat.go

**Comment by dgoodwin** [comment]
I'll take a look at this one for hack day.

/assign
