### ISSUE TITLE
💣 – workload labels+finalizers are not fully qualified

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#1281]
- label`state.internal.workload.kcp.dev/<workload-cluster-name>`
- finalizer `workload.kcp.dev/syncer-<workload-cluster-name>`

We should generally fully qualify these, and hash the result (see workspace initializer labels as example).

**Comment by sttts** [comment]
cc @jmprusi @davidfestal

**Comment by ncdc** [comment]
This was fixed in #1600
