### ISSUE TITLE
Workspace sharing

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#1319]
**Is your feature request related to a problem? Please describe.**
Whenever I want to share a workspace in my org (e.g. root:myorg:myapp) with someone else in my org, I am not able to do it myself. I have to ask an org/root admin to do it for me.

**Describe the solution you'd like**
I'd like to be able to self-service sharing of a workspace.

**Describe alternatives you've considered**
None

**Additional context**
The authorizers currently require the ClusterRole/ClusterRoleBinding to live in the parent workspace (root:myorg), but most users won't have permissions to create there.

**Comment by davidfestal** [comment]
At least workspace sharing of workspaces created inside a user home workspace would work, right (at when, in a near future, the user is cluster-admin in his home workspace)  ?

**Comment by ncdc** [comment]
Correct, this is outside of home workspaces
