### ISSUE TITLE
Community Meeting Jun 21, 2022

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#1320]
At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/ohf-kwvd-mrp
Or dial: ‪(US) +1 617-675-4444‬ PIN: ‪936 182 087 7398‬#
More phone numbers: https://tel.meet/ohf-kwvd-mrp?pin=9361820877398
Or join via SIP: sip:9361820877398@gmeet.redhat.com

Meeting recordings available on YouTube at https://www.youtube.com/channel/UCfP_yS5uYix0ppSbm2ltS5Q

This issue will collect prospective agenda topics. Add topics you'd like to discuss below!

**Comment by sttts** [comment]
Incoming issues: https://github.com/kcp-dev/kcp/issues?q=is%3Aopen+is%3Aissue+-label%3Acommunity-meeting+no%3Amilestone

**Comment by s-urbaniak** [comment]
- question: how to effectively find labels/annotations meant to be set by users/external controllers, aka not "internal" labels/annotations.

**Comment by s-urbaniak** [comment]
please give suggestions in https://github.com/kcp-dev/kcp/issues/1138

**Comment by ncdc** [comment]
Shout out: @davidfestal's demo of WIP user home workspaces: https://www.youtube.com/watch?v=lUBhf261d3I

**Comment by michaeladda** [comment]
Thanks for making this meeting publicly available on YouTube. I want to suggest a more convenient way of viewing it. At [mtngs.io](http://mtngs.io/) we're huge fans of open meetings. So we built a free public library of recorded meetings. We enrich them with video-synced clickable transcript and other features. There are already about a hundred open source projects on the site. Our system processed this meeting (from YouTube) and made it available at https://mtngs.io/kcp/community/X4_8fsn_VeU.html. You can browse previous kcp community meetings at https://mtngs.io/kcp/community/.
It’s a work in progress. I’d love it if you try it out and I hope it will be useful for you and the community. If we missed anything, or if you have any feedback, we would love to hear it.
