### ISSUE TITLE
KCP sever is down been trying for over three hours anyone experience this?Unable to connect to the server: dial tcp 192.168.59.100:8443: i/o timeout

### ISSUE THREAD

**Issue by Bianca2-be** [kcp-dev/kcp#1327]
### Discussed in https://github.com/kcp-dev/kcp/discussions/1285

<div type='discussions-op-text'>

<sup>Originally posted by **ppatierno** June 17, 2022</sup>
I have build and started kcp as described in the landing README page and was taking a look at the last demo video.
First off all if I understood correctly (as the video mentions) I should have an Organization workspace created by default but I cannot see it.

```shell
kubectl get workspaces
No resources found
```

It seems I am on the "root:default" workspace anyway by running

```shell
kubectl kcp ws
Current workspace is "root:default".
```

But when try to create a new workspace as in the demo I got the following error.

```shell
kubectl kcp ws create --type Organization green
error: clusterworkspaces.tenancy.kcp.dev "green" is forbidden: spec.type "Organization" in workspace "root:default" does not exist
```

Any idea what's going on? I am just trying to follow the guide and video steps.
</div>

**Comment by kasturinarra** [comment]
May be you need to do below ?
kubectl kcp ws .. (which will bring you to the root)
kubectl kcp ws create --type Organization green ?

**Comment by ncdc** [comment]
@Bianca2-be any updates on your end?

**Comment by Bianca2-be** [comment]
Hi Andy, yes I got passed the server issue. However, I am still unable to create a deployment because each time I syn the kind cluster image it shows the changes. But when I do the command : k api- resources | grew deployments.
 There is no deployments in the workspace.  I see that the pod is being created but I can’t find where and can’t get it to show up. So, I haven’t made it to complete the full trial of the demo. How about you ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ncdc** [comment]
@Bianca2-be if you're able to, please post every exact command that you are running, along with the output. Thanks.

**Comment by mjudeikis** [comment]
/close
reopen if still needed
