### ISSUE TITLE
Support clients for negotiated APIs from multiple compute service workspaces

### ISSUE THREAD

**Issue by astefanutti** [kcp-dev/kcp#1334]
Controllers that rely on core Kubernetes APIs, like Deployment, Service, or Ingress, negotiated via workload clusters, now initialize the corresponding clients using the APIExport virtual workspace server URL, from the compute service workspace, where those workload clusters live. That limits these controllers to operating on the set of user workspaces, that have bound that particular APIExport, missing the other workspaces, that have bound some other compute service APIExports. 

**Describe the solution you'd like**

Multi-workspace aware controllers should not be limited to a single compute service workspace "domain".

**Additional context**

One example of such controller is [kcp-glbc](https://github.com/Kuadrant/kcp-glbc), whose architecture is illustrated at https://github.com/Kuadrant/kcp-glbc/blob/main/docs/architecture.md.

**Comment by maleck13** [comment]
@ncdc @sttts is support for this planned as part of 0.7 ?

**Comment by maleck13** [comment]
@sttts I believe your design https://docs.google.com/drawings/d/1aiX_1xc-dpvYJZBXVhD8g0maKFNFT-M3M31DjFWsZSo/edit for supported APIs is the solution to this issue

**Comment by sttts** [comment]
It is being worked on. See https://github.com/kcp-dev/kcp/pull/1571 for the API changes.

**Comment by astefanutti** [comment]
Let's close this as it's been addressed as part of #1895.
