### ISSUE TITLE
test-e2e-shared relies on service account tokens which has changed in k8s 1.24

### ISSUE THREAD

**Issue by jmprusi** [kcp-dev/kcp#1336]
**Describe the bug**
When trying to run the test-e2e-shared against a Kind cluster using the k8s v1.24 it fails.

**To Reproduce**
1. kind create cluster
2. make test-e2e-shared
4. See errors:
```
        fixture.go:690:
            	Error Trace:	fixture.go:690
            	            				fixture.go:448
            	            				virtualworkspace_test.go:590
            	Error:      	Condition never satisfied
            	Test:       	TestSyncerVirtualWorkspace/access_kcp_resources_through_syncer_virtual_workspace,_from_a_other_workspace_to_the_wildwest_resources_through_an_APIBinding
            	Messages:   	token secret for syncer service account not found
``` 

**Expected behaviour**
It should work.

**Additional context**

a solution for now is to revert to k8s 1.23.0:
`kind create cluster --image kindest/node:v1.23.0`

**Comment by harshanarayana** [comment]
@jmprusi The alternative is to use the `token-request` API which is supported all the way from 1.18+. But 1.18 and 1.19 needs the feature flags to be enabled. 

I would be happy to take a stab at it. What is the minimum version supported for e2e-tests ?

**Comment by ncdc** [comment]
Or manually create a secret with the appropriate annotation to get the controller to turn it into a token secret

**Comment by s-urbaniak** [comment]
The question is for what versions of k8s we want to stay compatible in terms of e2e tests. A secret annotated with `kubernetes.io/service-account.name` still works however has the drawback of not being a bound token (it has no expiry, has no target audience)

@harshanarayana if you have cycles give it a stab 👍 My preference is to use the token request API with the drawback of being less backwards compatible as @harshanarayana mentioned. @ncdc wdyt?

**Comment by sttts** [comment]
token-requests are done by kubelet afaik. So this probably means we have to take over that role in the syncer.

**Comment by liggitt** [comment]
https://github.com/kcp-dev/kcp/issues/1336#issuecomment-1167509423 is a good starting point for keeping parity with the existing code in a way that works with all versions

**Comment by sttts** [comment]
Stopping the bleeding in https://github.com/kcp-dev/kcp/pull/1613.
