### ISSUE TITLE
Dynamic discovery shared informer factory: fix problems :smile:

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#1350]
(1) The "dynamic discovery" nature won't scale beyond a small number of workspaces.

We are currently iterating through every workspace, getting discovery for it (live http call), collecting all the namespace-scoped GVRs that support list+watch, creating a big union of all of the GVRs (to dedupe), and then ensuring informers are started for any newly-seen GVRs, and stopped for any now defunct GVRs.

We don't need to do this, because every GVR in the system is the deduped sum of
a. built-in types from upstream kube
b. built-in types from kcp (from `system:system-crds`)
c. bound types from apiexports/apibindings (from `system:bound-crds`)
d. "normal" CRDs from any/all workspaces

We hopefully can switch to a mechanism where we list/watch all CRDs and recalculate informers (additions, removals) based on CRD events.

Maybe we could even make it the intersection of all the GVRs we know about, restricted to only those resources that are being synced to clusters. In other words, once we move `--resources` from the syncer CLI flags to the WorkloadCluster/SyncTarget spec, we'll know everything being synced, and we can perform this calculation. If it's mostly deployments/secrets/configmaps/pvcs being synced, this has the potential to reduce unnecessary load (informers + labeling resources we don't really need to).

(2) It only supports namespace-scoped resources because it was initially built for labeling resources for scheduling, but other consumers are wanting to use it (quota, APIExport claims/labeling)

We should find a way to support both use cases (driving placement labeling, and other non placement needs), or split this into multiple factories maybe?

**Comment by stevekuznetsov** [comment]
@ncdc is _d._ possible without first adding `CustomResourceDefinition` to a workspace?

**Comment by ncdc** [comment]
@stevekuznetsov no, you still have to add a CRD to a workspace. What are you thinking?
