### ISSUE TITLE
prow: Github action based CI branch jobs are marked optional continuously

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#1366]
The required CI jobs for a branch in Github are continuously reset by prow. The two jobs "e2e-sharded" and "e2e-shared-server" are supposed to be required, but become optional automatically after some time.

<img width="739" alt="Bildschirmfoto 2022-06-27 um 10 28 23" src="https://user-images.githubusercontent.com/730123/175895168-38766803-ab31-4887-8409-6b9a0a5eadf0.png">

**Comment by stevekuznetsov** [comment]
@sttts I think this is our own foot-gun - we need to add [`required_status_checks`](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/branchprotector/README.md#fields) or they get stomped.

/close
