### ISSUE TITLE
Describe use cases and possible requirements for "enabling self-service of logical clusters"

### ISSUE THREAD

**Issue by smarterclayton** [kcp-dev/kcp#138]
A key component of large Kubernetes clusters is shared use, where the usage pattern might vary from externally controlled (via gitops / existing operational tools) to a permissive self-service model.  The most common partitioning model in Kubernetes is namespace, and the second most common model is cluster.  Self-service is currently limited by the set of resources that are namespace scoped for the former, and by the need to parameterize and configure multiple clusters consistently for the later. Cluster partitioning can uniquely offer distinct sets of APIs to consumers. Namespace partitioning is cheap up until the scale limits of the cluster (~10k namespaces), while cluster partitioning usually has a fixed cost per cluster in operational and resource usage, as well as lower total utilization.  Once a deployment reaches the scale limit of a single cluster, operators often need to redefine their policies and tools to work in a multi-cluster environment. Many large deployers create their own systems for managing self-service policy above their clusters and leverage individual subsystems within Kubernetes to accomplish those goals.

Explore the goal

> logical clusters + api composition + policy should allow organizations to provide teams "chunks of capacity" that they can use for workloads and services in a more comprehensive way than a single Kubernetes cluster.

Output

> an investigation doc

**Comment by smarterclayton** [comment]
Hoping to have a google doc soon to share, been canvassing various public projects, user stories I've heard, ecosystem reports, and asking questions ilke "how can self-service/tenancy for teams be abstracted like containers abstracted linux processes and kube abstracted rollouts"

**Comment by pweil-** [comment]
@smarterclayton bump on question from @ncdc ☝️

**Comment by ncdc** [comment]
Looks like it does; closing.
