### ISSUE TITLE
Inconsistent requirements for ClusterWorkspaceType name

### ISSUE THREAD

**Issue by MatousJobanek** [kcp-dev/kcp#1398]
**Describe the bug**

I've been playing with CWTs and found a small complication with the expected name formats. As expected, the name of the actual CWT resource needs to meet the standard format for `metadata.name` field. So let's say that I create CWT called `foo`. However, when I want to create a workspace of the type `foo`:
```
k ws create foo-workspace --type foo
```
then it fails with 
```
Error: ClusterWorkspace.tenancy.kcp.dev "foo-workspace" is invalid: spec.type.name: Invalid value: "foo": spec.type.name in body should match '^[A-Z][a-zA-Z0-9]+$'
```
because it expects that the name should start with a capital https://github.com/kcp-dev/kcp/blob/main/pkg/apis/tenancy/v1alpha1/types.go#L135.
When I try to use `--type Foo` then it fails (as expected) that it cannot find that CWT as there is no such resource with that name.

**To Reproduce**
1. Create CWT `foo`
2. run `k ws create foo-workspace --type foo`

**Expected behavior**
It should accept names that start with lower-case

**Comment by stevekuznetsov** [comment]
I can't reproduce this.

```
$ cat /tmp/cwt.yaml 
apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspaceType
metadata:
  name: foo
spec:
  defaultChildWorkspaceType: Universal
  allowedChildWorkspaceTypes:
  - Any
  allowedParentWorkspaceTypes:
  - Any
$ kubectl kcp workspace use root
Current workspace is "root".
$ kubectl apply -f /tmp/cwt.yaml 
clusterworkspacetype.tenancy.kcp.dev/foo created
$ kubectl kcp workspace create foo-workspace --type Foo
Workspace "foo-workspace" (type root:Foo) created. Waiting for being ready.
$ kubectl kcp workspace use foo-workspace
Current workspace is "root:foo-workspace" (type "root:Foo").
```

**Comment by stevekuznetsov** [comment]
test

**Comment by MatousJobanek** [comment]
May I know why the name has to start with capital? Couldn't we just use lower-case names as is used across the whole k8s?
This format - that I create CWT with a lower-case name, but the reference in ClusterWorksapce starts with capital - is a bit confusing TBH.

**Comment by MatousJobanek** [comment]
ok, now I see that you used `--type Foo` and when I try it it works:
```
$ k ws create foo-worksapce --type Foo
Workspace "foo-worksapce" (type root:Foo) created. Waiting for it to be ready...
Workspace "foo-worksapce" (type root:Foo) is ready to use.
```
_(after creating the CWT and the workspace in root)_

I think that I tried it yesterday and that it failed and that it did not exist... It was probably a typo in the name or another error between my chair and my keyboard.

Anyway, making the names more consistent would really help.

**Comment by sttts** [comment]
The capital case comes from kube constants to be CapitalCamlCase.

**Comment by MatousJobanek** [comment]
ok, didn't realize it. Thanks for your answer.
Do you think that we could make the plugin a bit more flexible: https://github.com/kcp-dev/kcp/pull/1416
