### ISSUE TITLE
Make APIBinding readible in APIExport VirtualWorkspace

### ISSUE THREAD

**Issue by MatousJobanek** [kcp-dev/kcp#1421]
**Is your feature request related to a problem? Please describe.**
Consider that we have a service provider called "build". That service provider needs some things to be present in the user's workspace to fully function. Let's say that these resources are:
* namespace
* ConfigMap & Secret
* NetworkPolicies, plus maybe something more

The first thought of how to meet this requirement is to use CWT and the initializer. Initializer creates the APIBinding for the service provider plus all needed resources. So far so good.
However, after some time the logic of the service provider is changed and it needs something more to be created or with different parameters. How should we meet such a requirement?
If we change the logic of the CWT initializer, then it applies the change only for the new workspaces, but not the existing ones.
Instead of using CWTs, we could move the creation of the resources into the service provider logic, but the "build" controller is watching a VirtualWorkspace of its APIExport (within the boundaries of the API that is defined in the APIExport), so it doesn't know when a new workspace is created.

**Describe the solution you'd like**
The VirtualWorkspace should include also all APIBindings of the particular APIExport automatically. In that way, the service provider could have a controller watching the APIBindings so it would be notified when a new one is created. Just to be clear, the controller wouldn't do anything with the APIBindings, it would only watch them.

**Describe alternatives you've considered**
The APIExport could technically claim the APIBindings, but it would get all of them. It would be great if the VirtualWorkspace logic could filter them out so it would get only the ones that were created for the particular APIExport.

**Comment by sttts** [comment]
+1 for this

**Comment by sttts** [comment]
This is already implemented. @mikenairn @fgiloux @MatousJobanek please confirm.

**Comment by MatousJobanek** [comment]
I've just tested it and the APIBinding is missing in the APIs of the VirtualWorkspace:
```
$ k api-resources --server https://kcp-stable.apps.kcp-internal-1.52p3.p1.openshiftapps.com:443/services/apiexport/root:redhat-appstudio/application-api/clusters/*
NAME                                     SHORTNAMES           APIVERSION                      NAMESPACED   KIND
configmaps                                                    v1                              true         ConfigMap
namespaces                                                    v1                              false        Namespace
secrets                                                       v1                              true         Secret
applicationpromotionruns                 apr,promotion        appstudio.redhat.com/v1alpha1   true         ApplicationPromotionRun
applications                             hasapp,ha,app        appstudio.redhat.com/v1alpha1   true         Application
applicationsnapshotenvironmentbindings   aseb,binding         appstudio.redhat.com/v1alpha1   true         ApplicationSnapshotEnvironmentBinding
applicationsnapshots                     as,snapshot          appstudio.redhat.com/v1alpha1   true         ApplicationSnapshot
componentdetectionqueries                hcdq,compdetection   appstudio.redhat.com/v1alpha1   true         ComponentDetectionQuery
components                               hascmp,hc,comp       appstudio.redhat.com/v1alpha1   true         Component
environments                             env                  appstudio.redhat.com/v1alpha1   true         Environment
```

so when I try to list them, then it fails:
```
$ k get apibindings.apis.kcp.dev --server https://kcp-stable.apps.kcp-internal-1.52p3.p1.openshiftapps.com:443/services/apiexport/root:redhat-appstudio/application-api/clusters/*
error: the server doesn't have a resource type "apibindings"
```
Am I missing something there?

**Comment by sttts** [comment]
Probably discovery is broken.

I would claim discovery is broken also for claims. cc @ncdc

**Comment by ncdc** [comment]
Will look today
