### ISSUE TITLE
Do webhooks have a place in KCP

### ISSUE THREAD

**Issue by maleck13** [kcp-dev/kcp#143]
Wondering if things like the validating and mutating webhooks have a place in KCP? Maybe they are already present?

**Comment by imjasonh** [comment]
They're not currently implemented, but we will have to support them, to be able to support the ecosystem of controllers that expect/require them.

We're working through how Services work in a multicluster setup now, and as part of that we'll have to make sure the kcp layer can call those services too as webhooks.

**Comment by sttts** [comment]
@maleck13 https://github.com/kubernetes/enhancements/pull/2877

**Comment by sttts** [comment]
True. Everything that is not self-contained and calls out to other resources or services won't fit into CEL.

**Comment by sttts** [comment]
Which leads us to a nice problem: if we have our copy of the webhook, it will be based on different resources than the one in the downstream cluster.

**Comment by maleck13** [comment]
Example use cases: An ingress controller that wants to control the hosts that can be used for ingress. A controller that wants to ensure some quota / subscription is enabled based on a resource it provides.

**Comment by ncdc** [comment]
We are adding support for validating and mutating webhooks for full external URLs (not service URLs), at least as step 1.

**Comment by shawn-hurley** [comment]
Step 1 Implementation is here: https://github.com/kcp-dev/kcp/pull/818

**Comment by ncdc** [comment]
Closing this now that 818 is merged. We can open additional issues if needed
