### ISSUE TITLE
Support for multiple IPs for certificate of locally deployed KCP server

### ISSUE THREAD

**Issue by doru1004** [kcp-dev/kcp#1452]
I am running a KCP server locally but it seems that if I deploy the server and I am connected to a particular network, then that KCP server really only works when I am connected to that same network since the IP is connected to the certificate.

Is there a way (or a plan to add a way) to have multiple valid IPs associated with 1 certificate? Or maybe some other solution to this problem?

For example when I try to interact with the server after I redeploy it after changing networks I get:

```
Unable to connect to the server: x509: certificate is valid for X.X.X.X, not Y.Y.Y.Y
```

**Comment by stevekuznetsov** [comment]
The GoDoc on `clusterworkspaceshard.tenancy.kcp.dev` field `.spec.externalURL` reads:

> 	// ExternalURL is the externally visible address presented to users in Workspace URLs.
	// Changing this will break all existing workspaces on that shard, i.e. existing
	// kubeconfigs of clients will be invalid. Hence, when changing this value, the old
	// URL used by clients must keep working.

So, it seems like the reboot-into-a-new-IP case is not really something we want to support. I wonder if there's something we can do to make the dev ux here better?

/cc @sttts @csams

**Comment by pdettori** [comment]
I noted however that certificates are not signed for the hostname provided at startup with external-hostname, which is a different issue, so that would not work either at this time.

**Comment by pdettori** [comment]
Also created a PR https://github.com/kcp-dev/kubernetes/pull/80 to address it
