### ISSUE TITLE
When kcp start is used with the --external-hostname flag, serving certificates are not signed for that hostname

### ISSUE THREAD

**Issue by pdettori** [kcp-dev/kcp#1471]
**Describe the bug**
When kcp start is used with the --external-hostname flag, serving certificates are not signed for that hostname

**To Reproduce**
1. run `kcp start --external-hostname=<hostname>`
2. verify that `.kcp/admin.kubeconfig` is using the external hostname in the server URL
3. Run `KUBECONFIG=.kcp/admin.kubeconfig kubectl get ns`
4. Get error `Unable to connect to the server: x509: certificate is valid for localhost, not <hostname>`

**Expected behavior**
Command should work for specified hostname

**Additional context**

**Comment by ncdc** [comment]
@sttts is there any harm in this, or do we want to direct people to a topology that requires a front proxy that is aligned with a serving cert w/the external hostname?

**Comment by sttts** [comment]
@csams
