### ISSUE TITLE
Error while trying to sync Knative Service

### ISSUE THREAD

**Issue by garg-dhruv** [kcp-dev/kcp#148]
### Steps to recreate the error:
1. Setup Knative serving on physical clusters.
2. Run _startKcpAndClusterController.sh_ script after making the following update in the script (as we want to sync knative service):
> ${KCP_ROOT}/bin/cluster-controller -push_mode=true -pull_mode=false -kubeconfig=${KUBECONFIG} **services.serving.knative.dev** &> cluster-controller.log &
CC_PID=$!

### Error received in the cluster-controller logs:

> I0819 16:36:36.719458  254618 discovery.go:157] processing discovery for resource services (services.serving.knative.dev)
I0819 16:36:36.726736  254618 discovery.go:157] processing discovery for resource services (services.serving.knative.dev)
E0819 16:36:36.740409  254618 apiimporter.go:178] error creating APIResourceImport services.us-west1.v1.serving.knative.dev: APIResourceImport.apiresource.kcp.dev "services.us-west1.v1.serving.knative.dev" is invalid: [spec.columnDefinitions.format: Invalid value: "null": spec.columnDefinitions.format in body must be of type string: "null", spec.columnDefinitions.description: Invalid value: "null": spec.columnDefinitions.description in body must be of type string: "null"]
E0819 16:36:36.746479  254618 apiimporter.go:178] error creating APIResourceImport services.us-east1.v1.serving.knative.dev: APIResourceImport.apiresource.kcp.dev "services.us-east1.v1.serving.knative.dev" is invalid: [spec.columnDefinitions.description: Invalid value: "null": spec.columnDefinitions.description in body must be of type string: "null", spec.columnDefinitions.format: Invalid value: "null": spec.columnDefinitions.format in body must be of type string: "null"]

**Comment by pweil-** [comment]
This issue is fairly old and there has been quite a few changes as we've worked through prototypes.  Mind confirming that you're still seeing this? Thanks!

**Comment by ncdc** [comment]
I am not able to reproduce:

1. Start kcp as a "physical cluster"
1. Start kcp (which now runs the cluster controller by default) configured to sync services.serving.knative.dev
1. Register the "physical cluster" kcp as a `Cluster` with the regular kcp

```
$ kubectl get apiresourceimports.apiresource.kcp.dev -o wide
NAME                                   LOCATION   SCHEMA UPDATE STRATEGY   API VERSION              API RESOURCE   COMPATIBLE   AVAILABLE
services.kcp2.v1.serving.knative.dev   kcp2       UpdateUnpublished        serving.knative.dev/v1   services       True
```

If you are able to reproduce, please reopen and we'll investigate!
