### ISSUE TITLE
Kubectl `workspace` plugin semantic change proposal

### ISSUE THREAD

**Issue by davidfestal** [kcp-dev/kcp#1502]
Kubectl `workspace` plugin change proposal, now that Home workspaces PR is merged:
- Change a bit the semantic of the `ws` command to  better match the typical `cd` semantics:
  - `ws` without parameters == `ws '~'` == use the home workspace
  - `ws .` == show the current workspace
  - `ws ..`  == use the parent workspace
  - `ws -`  == use the previous workspace

**Comment by stevekuznetsov** [comment]
- `cd` takes me home
- `cd .` takes me nowhere
- `cd ..` takes me up one
- `cd -` takes me to last

sgtm

**Comment by sttts** [comment]
+1 from me for the change

**Comment by sttts** [comment]
We better change this with v0.6 such that users don't get a breaking change in a few weeks.
