### ISSUE TITLE
To use CWT the user needs to have "access" permissions in workspaces where the CWT exists

### ISSUE THREAD

**Issue by MatousJobanek** [kcp-dev/kcp#1518]
**Describe the bug**
Consider that there is a CWT `Foo` in a workspace `root:org:plane`. The workspace contains also a CR & CRB granting `use` permissions to the `system:authenticated` group.
Then a user `bob` wants to create a workspace of the type `Foo` in his home workspace, but this fails:
```
$ k ws create bar --type root:org:plane:Foo
Error: workspaces.tenancy.kcp.dev "bar" is forbidden: use of the cluster workspace type "root:org:plane:Foo" in workspace "root:users:qa:kh:bob" is not allowed
```
the kcp logs contain:
```
E0713 14:19:32.825814  472150 rest.go:629] user "bob" lacks (denied) clusterworkspacetypes "use" permission for "foo" in root:users:qa:kh:bob: workspace access not permitted
```
This is because the user `bob` doesn't have any permission in the `root:org:plane` workspace. When kcp does SAR for the CWT then it expects that the user has `access` permissions in the workspace (and also all parent workspaces).

**To Reproduce**
1. Create CWT `Foo` in `root:org:plane` (with the necessary CR & CRB granting `use` permissions)
2. `k ws create bar --type root:org:plane:Foo`

**Expected behavior**
it should not require `access` permissions in the workspace where CWT is defined.

**Additional context**
https://coreos.slack.com/archives/C020QAF9D46/p1657716975579069

**Comment by MatousJobanek** [comment]
This technically applies to all SARs that are executed for any other resource - for example an APIExport

**Comment by ncdc** [comment]
This might be helped with a generic Export mechanism, where users could export things (CWT, APIExport) into a "catalog" in the root
