### ISSUE TITLE
Adding readiness checkups in KCP

### ISSUE THREAD

**Issue by samyak-jn** [kcp-dev/kcp#1526]
**Is your feature request related to a problem? Please describe.**

When deploying ArgoCD to KCP, one of the initial blocker we face is due to the readyz and health checkups by ArgoCD on the cluster, which as per my knowledge KCP still don't support.
So while deploying the argocd, the argo looks for some health and readiness checks from the cluster, while doing so it looks for a port service for checking if the cluster is ready or not, which while doing so on KCP turns out to be the blocker, As `stts mentioned readiness in the sense of kube-apiserver /readyz; basically to serve /clusters/root:org:ws/readyz`

**Describe the solution you'd like**

Enable readiness and health probes checkup in KCP in each workspace, for ex: /clusters/root:org:ws/readyz 
so, in case I'm deploying argocd in org->A ws->test then, the readiness can be checked at /clusters/root:A:test/readyz 

**Describe alternatives you've considered**
For now, to make ArgoCD deploy on KCP, we have disabled those checks hence this feature request will unblock us form that.

CC: @sttts, in case I missed some details, feel free to chime in, thanks!

**Comment by pradeepnnv** [comment]
I would like to work on this please.
