### ISSUE TITLE
Add known internal types to internalschemas for the virtual workspace to use (RBAC)

### ISSUE THREAD

**Issue by shawn-hurley** [kcp-dev/kcp#1544]
The main set of tests that we need to consider is {Cluster}RoleBindings and {Cluster}Roles.

**Comment by ncdc** [comment]
Need to discuss if this should be for all virtual workspace types, or only for APIExport/permission claims

**Comment by shawn-hurley** [comment]
It sounds like the fix is:

1. a way for a given virtual workspace to ask for a set of APIs that it considers to be internal.
2. Add RBAC resources for the APIExport virtual workspace.
3. Update the CEL validation for permission claims (#1529) to allow claiming the RBAC resources.

If a cluster admin is accepting these claims, I would like them to see what rules the services provider will be controlling or needing access to and potentially locking this down. I wonder if this is a follow-up, though.

**Comment by ncdc** [comment]
@robinbobbitt do you still have bandwidth to work on this?
