### ISSUE TITLE
kcp OWNERS files

### ISSUE THREAD

**Issue by pweil-** [kcp-dev/kcp#1557]
As we keep growing it may make sense to start implementing more granular OWNERS files so that we can build our cadre of reviewers and approvers like other upstream communities.

References
* kubernetes review/approver roles: https://github.com/kubernetes/community/blob/master/community-membership.md#reviewer
* kubernetes owners file process: https://www.kubernetes.dev/docs/guide/owners/

Goals:

* Agree that we want to use OWNERS files 
* Seed areas where people are already comfortable reviewing

If you like this idea and have an area you feel like you have enough context to review please note that in this issue.

**Comment by ncdc** [comment]
At least in the repo root

**Comment by shawn-hurley** [comment]
I think this would be really helpful, another thing to consider would be to implement a reviewer to approver guidelines and maybe seed the root files with reviewers?
