### ISSUE TITLE
Write Tests for the API Negotiation controller

### ISSUE THREAD

**Issue by davidfestal** [kcp-dev/kcp#156]
It would be greatly useful to write tests for the API Negotiation controller.
The idea is to write declarative tests that clearly and formally capture the intent of the API Negotiation.
Preferred framework would be KUTTL.

**Comment by sttts** [comment]
Would wait until post-prototype-2 when we add APIImport/Export

**Comment by davidfestal** [comment]
Merged with https://github.com/kcp-dev/kcp/issues/158
