### ISSUE TITLE
unable to use namespace added directly to a logical cluster 

### ISSUE THREAD

**Issue by TheRealHaoLiu** [kcp-dev/kcp#157]
when a namespace is created on the logical cluster and not created on the KCP admin cluster no resource can be created on in the namespace 

step to reproduce:
- ensure that the .kcp directory is empty (prevent contamination from existing data in etcd)
```
rm -rf .kcp
```
- compile and run kcp
```
make build
./bin/kcp start
```
- set kubeconfig to KCP
```
export KUBECONFIG=.kcp/data/admin.kubeconfig
```
- switch context to user
```
kubectl use-context user
```
- add deployment crd 
```
kubectl apply -f ./contrib/crds/apps/apps_deployments.yaml
```
- create deployment 
```
kubectl apply -f ./contrib/examples/deployment.yaml
```
- create namespace default
```
kubectl create namespace default
```
- receive the following error 
```
Error from server (NotFound): error when creating "./contrib/examples/deployment.yaml": namespaces "yoloswag" not found
```

the above scenario have been performed for non "default" namespace with the same result

further experimentation show that after a namespace is created on the admin cluster the namespace can than be use by other logical cluster

**Comment by smarterclayton** [comment]
Ah, this is because the namespace admission cache is reading from the root logical cluster, not per logical cluster.  The cache should perform list across logical cluster then partition by cluster-name.  That's actually a great opportunity to tweak client-go's default MetaNamespaceNameFunc

**Comment by davidfestal** [comment]
> tweak client-go's default MetaNamespaceNameFunc
 
Already done (in a hacky way, sure) in the context of the CRD tenancy work. So the changes to fix this issue are simple and quite the same as those already made in the CRD controllers.
See the attached PR in the Kubernetes feature branch.
