### ISSUE TITLE
Incomplete Usage message from kubectl kcp workspace plugin

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/kcp#1579]
**Describe the bug**
The usage message is incomplete.

```console
(base) mspreitz@mjs12 kcp % kubectl ws --help
Manages KCP workspaces

Usage:
  workspace [list|create|create-context|<workspace>|..|.|-|~|<root:absolute:workspace>] [flags]
...
```

That listing does not mention `use` or `current`.

**To Reproduce**
1. `kubectl ws --help`
2. Observe the incomplete synopsis

**Expected behavior**
The synopsis includes all the available commands, or none of them, or an explicit indication that the list is incomplete.

**Additional context**
N/A

**Comment by apoorvajagtap** [comment]
Hello, I would like to work on this one. @sttts should it be ok, if I assign this to myself?
Also, if you can let me know, which approach we are gonna follow to be displayed for the usage (all the commands, or none)?

**Comment by sttts** [comment]
Welcome @apoorvajagtap! have assigned it.

**Comment by apoorvajagtap** [comment]
Thanks, @sttts! I have used the generic approach to just keep is as `workspace [command] [flags]`. Let me know your thoughts about #1756
