### ISSUE TITLE
`kubectl ws ~` fails

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/kcp#1582]
**Describe the bug**
`kubectl ws ~` is supposed to switch to my home workspace (which _does_ exist and is accessible via a different command).  Instead it gives an error message and makes no change.

```console
(base) mspreitz@mjs12 kcp % kubectl ws use root
Current workspace is "root".

(base) mspreitz@mjs12 kcp % kubectl ws ~
Error: invalid resource name "/Users/mspreitz": [may not contain '/']

(base) mspreitz@mjs12 kcp % kubectl ws current
Current workspace is "root".

(base) mspreitz@mjs12 kcp % kubectl ws
Current workspace is "root:users:zu:yc:kcp-admin".
Note: 'kubectl ws' now matches 'cd' semantics: go to home workspace. 'kubectl ws -' to go back. 'kubectl ws .' to print current workspace.
```

**To Reproduce**
See above

**Expected behavior**
I expected `kubectl ws ~` to do the same thing as `kubectl ws`.

**Additional context**
kcp commit 8a36261dd4a653961bd9029eb29f7dd01172147b .
MacOS 12.4 on Intel.
go version 1.18.4.

**Comment by davidfestal** [comment]
That's probably due to the fact that the `~` character is expanded by the system.

On Linux and Mac, using quotes to block expansion works : `kubectl ws '~'`
That's not nice but in this case the simple `kubectl ws` is there.

**Comment by MikeSpreitzer** [comment]
D'Oh!

```console
(base) mspreitz@mjs12 kcp % kubectl ws '~'
Current workspace is "root:users:zu:yc:kcp-admin".
```
