### ISSUE TITLE
Clarfiy / Simplify Home Bucket Options

### ISSUE THREAD

**Issue by stevekuznetsov** [kcp-dev/kcp#1592]
e.g. choosing bucket length > 2 leads to a performance issue. So, we have the following options:

User-names have `[a-z][a-zA-Z0-9-.]{0,61}[a-zA-Z0-9]` -> (26 * [(26 + 10 + 2) * 61] * 36 = 2169648) permutations, and buckets are made up of lowercase-alpha chars, so:

|length|depth|sub-buckets|users|valid|
|------|-----|-----------|-----|-----|
|1     |1    |26 * 1 = 26|2169648 / (26) = 83448 | :red_circle: |
|1     |2    |26 * 1 = 26|2169648 / (26)^2 = 3209 | :red_circle: |
|1     |3    |26 * 1 = 26|2169648 / (26)^3 = 124 | :green_circle: |
|1     |4    |26 * 1 = 26|2169648 / (26)^4 = 5 | :green_circle: |
|2     |1    |26 * 26 = 676|2169648 / (26*26) = 3209 | :red_circle: |
|2     |2    |26 * 26 = 676|2169648 / (26*26)^2 = 5 | :green_circle: |
|2     |3    |26 * 26 = 676|2169648 / (26*26)^3 = .007 | :red_circle: |
|3     |1    |26 * 26 * 26 = 17576|2169648 / (26*26*26) = 124 | :red_circle: |
|3     |2    |26 * 26 * 26 = 17576|2169648 / (26*26*26)^2 = .007 | :red_circle: |

The ones labeled :red_circle:  break the scale limit in sub-buckets, or users. Every single other option not listed is not useful. We should not have more than ~1000 sub-buckets per bucket, and we don't want fewer than 5 users per bucket .... 

IMHO we hard-code length = 1, depth = 3, and just go with it. Exposing these options is an illusion of choice.

_Originally posted by @stevekuznetsov in https://github.com/kcp-dev/kcp/pull/1561#discussion_r926899198_

**Comment by pweil-** [comment]
copying over from my dupe issue:

Per https://github.com/kcp-dev/kcp/pull/1561#discussion_r926886232 there are very few configuration options that are valid for bucket configurations and quite a few (ie most) that would be detrimental to performance.

We can consider:

* strong flag value validation
* named configuration sets (ie. can we classify when one valid config might be better than the other and have CONFIG_A, CONFIG_B, etc)
* removal of the configuration option
* leaving as-is and hoping documentation does the trick

**Comment by markmc** [comment]
> User-names have `[a-z][a-zA-Z0-9-.]{0,61}[a-zA-Z0-9]` -> (26 * [(26 + 10 + 2) * 61] * 36 = 2169648) permutations

Maybe I'm terribly misunderstanding, but isn't this:

```
[26 * (26 + 26 + 10)] + [26 * (26 + 26 + 10 + 2) * (26 + 26 + 10)] + [26 * ((26 + 26 + 10 + 2)**2) * (26 + 26 + 10)] + ... + [26 * ((26 + 26 + 10 + 2)**61) * (26 + 26 + 10)]
```

which is a rather more large number!

```
$ python3
...
>>> sum([26*(26+26+10)*((26+26+10+2)**i) for i in range(62)])
246140384690398299890694028403364898986965757161420743538925505982003749285611605226933737920365528944151027407180
```

That's roughly a bajillion, right? I think we should plan a scaling limit other than the capacity of the username field!

**Comment by stevekuznetsov** [comment]
Yes, sorry, there are a) shorter user-names and b) upper-case letters ... so the number of possible names is as you say:

$$ \sum_{n=0}^{61} 26 \times (26+26+10+2)^n \times (26 + 26 + 10) = 246140384690398299890694028403364898986965757161420743538925505982003749285611605226933737920365528944151027407180 $$

This is roughly $26^80$, so if we want ~1k sub-buckets per bucket, we want two chars per bucket and need a depth of ~40 ...

It seems like we should hard-code the length of a bucket to 2, as we are certain(?) that we don't want 17k sub-buckets in a bucket, and then ask the admin to set depth based on the size of their user-base.

**Comment by ncdc** [comment]
We will soon be removing home buckets as part of https://github.com/kcp-dev/kcp/pull/2435, so this will not be needed any more.

**Comment by kasturinarra** [comment]
cc: @xingxingxia 

Based on andy comments above i am not sure if we needed to draft cases for home workspaces. I guess not.

**Comment by ncdc** [comment]
@kasturinarra we will still have home workspaces post-refactor, but the implementation will be different.

**Comment by xingxingxia** [comment]
> We will soon be removing home buckets as part of https://github.com/kcp-dev/kcp/pull/2435, so this will not be needed any more.

I see https://github.com/kcp-dev/kcp/pull/2435 was closed.

> Based on andy comments above i am not sure if we needed to draft cases for home workspaces. I guess not.

Home buckets are, for example the `dn` and `eb` in path `root:users:dn:eb:rh-sso-xxiakcp`, per the comment above `removing home buckets as part of #2435, so this will not be needed any more`, home buckets will be removed. Thus, I agree that we need not to draft specially for this removal IMO.

**Comment by kasturinarra** [comment]
@xingxingxia agree with what you said, just to be a little clear here what i meant from above was not to start drafting cases for home workspaces as it will be different than how it is right now. I should have been more clearer.
