### ISSUE TITLE
Demo 2 Goals

### ISSUE THREAD

**Issue by smarterclayton** [kcp-dev/kcp#163]
Demo 2 should build on the first demo and show concrete progress towards the three exploration goals of KCP:

1. A minimal kube-apiserver as a library that can be forked and easily customized in code at the necessary layers
2. Transparent multi-cluster of Kube-native applications that preserves 95% of existing developer expectations
3. Kube-like control plane as a service enabling developer team infrastructure self-service (under policy control!) that scales horizontally

Demo 2 would be a Kubecon or post-Kubecon update of the current demo and validate progress towards these goals.

## Minimum demo

1. Minimal kube-apiserver
    * User can fork a repo in our tree (kcp-dev/kubernetes) and assemble a simple `go build` able `main` function that starts a new kube-apiserver and defines hooks
    * TODO: exactly what the interfaces look like (should do a session and sketch something)
2. Transparent multi-cluster
    * Flow
        * Start kcp with two kind clusters
        * Switch to a logical cluster
        * Create a deployment
        * Show the deployment not assigned with a condition 'Unschedulable' (no locations)
        * Create a location and expose it to the logical cluster (somehow)
        * Scheduler places the workload, syncer agent on the kind cluster performs the spec down -> status up dance
        * Add a second location
        * Stop the first kind cluster
        * Show the deployment moved
    * Parts
        * Add ingress to a single deployment with a single hostname, show traffic flowing to whichever kind cluster has the deployment
3. Policy, organizations, and sharding
    * Show an "organization workspace" that you can create `Workspace` kinds in
    * Show creation of `Workspace` gating the ability to access to a workspace
    * Create a controller that LIST/WATCH across a resource in all workspaces and does useful work
    * Create a `Shard` type, add assignment to a shard to a `Workspace` object, then show LIST/WATCH across two independent KCP instances
        * Show the same controller from above working unchanged

**Comment by sttts** [comment]
WIP script doc: https://docs.google.com/document/d/1jN6BdhUUIESeHw3_f6HwsNwVM2Ytabr6usUQhYMcNd8/edit#
