### ISSUE TITLE
Editing the namespaceSelector in the placement and setting it back to the old one make workload in the syncTarget gets stuck in containerCreating state

### ISSUE THREAD

**Issue by kasturinarra** [kcp-dev/kcp#1644]
**Describe the bug**
Editing the namespaceselector and setting it back to the old one makes the pod in syncTarget get stuck in ContainerCreating state until a new syncTarget is added and pod is moved to that.

```
Events:
===================
  Type     Reason       Age                    From               Message
  ----     ------       ----                   ----               -------
  Normal   Scheduled    147m                   default-scheduler  Successfully assigned kcp-dcufo07pgowb/kuard-6d9d6cf96-kw4rh to ip-10-0-173-140.us-east-2.compute.internal by ip-10-0-133-178
  Warning  FailedMount  6m34s (x77 over 147m)  kubelet            MountVolume.SetUp failed for volume "kcp-api-access" : [secret "kcp-default-token-wtzfn" not found, configmap "kcp-root-ca.crt" not found]
  Warning  FailedMount  116s (x64 over 144m)   kubelet            Unable to attach or mount volumes: unmounted volumes=[kcp-api-access], unattached volumes=[kcp-api-access]: timed out waiting for the condition
[knarra@knarra root-org]$ oc get pods --all-namespaces | grep kuard
kcp-dcufo07pgowb                                   kuard-6d9d6cf96-kw4rh                                                       0/1     ContainerCreating   0               147m
```

```
kubectl version -o yaml
clientVersion:
  buildDate: "2022-07-07T20:21:05Z"
  compiler: gc
  gitCommit: f17f1aa456e00569e88a0e8206c5b360e44055dd
  gitTreeState: clean
  gitVersion: v1.24.1
  goVersion: go1.18.1
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-07-28T21:47:25Z"
  compiler: gc
  gitCommit: b09f169
  gitTreeState: dirty
  gitVersion: v1.24.3+kcp-v0.0.0-b09f169
  goVersion: go1.17.12
  major: "1"
  minor: "24"
  platform: linux/amd64
```

**To Reproduce**
1. Deploy kcp on openshift cluster
2. Create a workspace using the command `kubectl ws create test1 --enter`
3. Use the same cluster where kcp is deployed and add that as a syncTarget by running the command `kubectl kcp workload sync knarracluster1 --syncer-image ghcr.io/kcp-dev/kcp/syncer:8ad1c4a -o - | KUBECONFIG=/home/knarra/Downloads/kubeconfig_411 kubectl apply -f -`
4. Wait for the syncTarget to become ready
5. Once syncTarget is added we will have apibinding, placement and location created in the workspace we are currently working in
6. Label the location using the command `kubectl label location default cluster1=ocpcluster`
7. Create deployment using the command `kubectl create deployment kuard --image gcr.io/kuar-demo/kuard-amd64:blue --dry-run=client -o yaml > kuard.yaml && kubectl apply -f kuard.yaml`
8. Wait for the deployment to be running and synced to syncTarget i.e the cluster.
9. Now edit the placement to set namespaceSelector to something that exist or do not exist. For example something as below

```
spec:
    locationResource:
      group: workload.kcp.dev
      resource: synctargets
      version: v1alpha1
    locationSelectors:
    - matchLabels:
        cluster1: ocpcluster
    locationWorkspace: root:rh-sso-15878744:knarratest1
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: <namespac_name_that_does_not_exist>
```

11. Now verify that default namespace shows “No placements available” when run `oc get namespace default -o yaml`.
12. Also verify that syncTarget does not have the deployment running
13. Now Try to bring back the deployment by setting namespace selector to the right namespace name i.e default.
14. You could see that pods in the syncTarget gets stuck in ‘containerCreating’ state by with error as below

```
Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    14m                  default-scheduler  Successfully assigned kcp-dcufo07pgowb/kuard-6d9d6cf96-kw4rh to ip-10-0-173-140.us-east-2.compute.internal by ip-10-0-133-178
  Warning  FailedMount  102s (x14 over 14m)  kubelet            MountVolume.SetUp failed for volume "kcp-api-access" : [secret "kcp-default-token-wtzfn" not found, configmap "kcp-root-ca.crt" not found]
  Warning  FailedMount  40s (x6 over 11m)    kubelet            Unable to attach or mount volumes: unmounted volumes=[kcp-api-access], unattached volumes=[kcp-api-access]: timed out waiting for the condition
```

**Expected behavior**
Pods should not get stuck in containerCreating state.

**Additional context**
Logs seen in syncer.log file

```
E0729 06:20:08.442428       1 spec_controller.go:235] kcp-workload-syncer-spec failed to sync {{"" "v1" "secrets"} "default/root:rh-sso-15878744:knarratest1|kcp-syncer-knarracluster1-121xvgpf-token-sxtfk"}, err: namespaces "kcp-dcufo07pgowb" already exists
E0729 06:26:20.545319       1 finalizer.go:81] Failed updating after removing the finalizers of resource root:rh-sso-15878744:knarratest1|kcp-system/kubernetes: secrets "kubernetes" not found
E0729 06:26:20.545339       1 spec_controller.go:235] kcp-workload-syncer-spec failed to sync {{"" "v1" "secrets"} "kcp-system/root:rh-sso-15878744:knarratest1|kubernetes"}, err: secrets "kubernetes" not found
E0729 06:26:25.132134       1 spec_process.go:262] Failed adding finalizer upstream on resource root:rh-sso-15878744:knarratest1|kcp-system/default: serviceaccounts "default" not found
E0729 06:26:25.132158       1 spec_controller.go:235] kcp-workload-syncer-spec failed to sync {{"" "v1" "serviceaccounts"} "kcp-system/root:rh-sso-15878744:knarratest1|default"}, err: serviceaccounts "default" not found
E0729 06:26:25.332518       1 spec_process.go:262] Failed adding finalizer upstream on resource root:rh-sso-15878744:knarratest1|kcp-system/kubernetes: Operation cannot be fulfilled on secrets "kubernetes": the object has been modified; please apply your changes to the latest version and try again
E0729 06:26:25.332547       1 spec_controller.go:235] kcp-workload-syncer-spec failed to sync {{"" "v1" "secrets"} "kcp-system/root:rh-sso-15878744:knarratest1|kubernetes"}, err: Operation cannot be fulfilled on secrets "kubernetes": the object has been modified; please apply your changes to the latest version and try again
E0729 06:27:17.365604       1 spec_process.go:262] Failed adding finalizer upstream on resource root:rh-sso-15878744:knarratest1|default/default: serviceaccounts "default" not found
E0729 06:27:17.365632       1 spec_controller.go:235] kcp-workload-syncer-spec failed to sync {{"" "v1" "serviceaccounts"} "default/root:rh-sso-15878744:knarratest1|default"}, err: serviceaccounts "default" not found
```

**Comment by kasturinarra** [comment]
Also deleteing the existing deployment and recreating it on the same syncTarget gives similar error

KCP:
===============
[knarra@knarra root-org]$ kubectl create deployment hello-openshift2 --image=quay.io/openshifttest/hello-openshift@sha256:1e70b596c05f46425c39add70bf749177d78c1e98b2893df4e5ae3883c2ffb5e --dry-run=client -o yaml > hello-openshift.yaml
[knarra@knarra root-org]$ vi hello-openshift.yaml 
[knarra@knarra root-org]$ kubectl apply -f hello-openshift.yaml 
deployment.apps/hello-openshift2 created
[knarra@knarra root-org]$ kubectl get deployment
NAME               READY   UP-TO-DATE   AVAILABLE   AGE
hello-openshift2   0/1     1            0           6s

syncTarget:
=================
Events:
  Type     Reason       Age                 From               Message
  ----     ------       ----                ----               -------
  Normal   Scheduled    107s                default-scheduler  Successfully assigned kcp-dcufo07pgowb/hello-openshift2-84966fd79d-h99nk to ip-10-0-173-140.us-east-2.compute.internal by ip-10-0-133-178
  Warning  FailedMount  44s (x8 over 107s)  kubelet            MountVolume.SetUp failed for volume "kcp-api-access" : [secret "kcp-default-token-wtzfn" not found, configmap "kcp-root-ca.crt" not found]

**Comment by shaunaksen09** [comment]
I would like to take it up and do some deep dive @ncdc

**Comment by chetan-rns** [comment]
```
MountVolume.SetUp failed for volume "kcp-api-access" : [secret "kcp-default-token-wtzfn" not found, configmap "kcp-root-ca.crt" not found]
```

I've observed the same issue intermittently without updating any namespaceSelector
