### ISSUE TITLE
Namespace deletion (via kubectl) hangs

### ISSUE THREAD

**Issue by karolz-ms** [kcp-dev/kcp#165]
**Repro steps**
```shell
make build
./bin/kcp start

# In a separate shell:
export KUBECONFIG=.kcp/data/admin.kubeconfig
kubectl create namespace some-test
kubectl delete namespace some-test
```

**Expected**
The namespace should be deleted immediately (there is nothing in it)

**Actual**
`kubectl` says `namespace some-test deleted`, but then it never returns.
If `kubectl` is interrupted (`^C`) and re-run, the same thing happens.

**Comment by metacosm** [comment]
A finalizer issue, maybe?

**Comment by karolz-ms** [comment]
Finalizer on what object though? 🤔

**Comment by karolz-ms** [comment]
thanks for quick resolution! ❤️
