### ISSUE TITLE
kcp log is being flooded with message “quota monitor not synced”

### ISSUE THREAD

**Issue by kasturinarra** [kcp-dev/kcp#1654]
**Describe the bug**
Kcp log is being flooded with below message
I0801 10:48:01.339684       1 resource_quota_monitor.go:288] root:rh-sso-6340056: quota monitor not synced: tenancy.kcp.dev/v1beta1, Resource=workspaces

**Version**
[knarra@knarra ~]$ kubectl version -o yaml
clientVersion:
  buildDate: "2022-07-07T20:21:05Z"
  compiler: gc
  gitCommit: f17f1aa456e00569e88a0e8206c5b360e44055dd
  gitTreeState: clean
  gitVersion: v1.24.1
  goVersion: go1.18.1
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-07-31T20:17:55Z"
  compiler: gc
  gitCommit: ac174c6
  gitTreeState: dirty
  gitVersion: v1.24.3+kcp-v0.0.0-ac174c6
  goVersion: go1.17.12
  major: "1"
  minor: "24"

**To Reproduce**
1. Deploy kcp on openshift cluster
2. Now add workload cluster using the command ‘kubectl kcp workload sync qetestcluster1 --syncer-image ghcr.io/kcp-dev/kcp/syncer:8ad1c4a -o - | KUBECONFIG=<pcluster-kubeconfig> kubectl apply -f -’
3. Now check the kcp pod logs by running the command ‘oc logs -f <kcppod>’
4. You could see that the pod logs are being flooded with messages as described below
I0801 11:09:28.761136       1 resource_quota_monitor.go:288] root:rh-sso-16080397: quota monitor not synced: tenancy.kcp.dev/v1beta1, Resource=workspaces
I0801 11:09:28.761143       1 resource_quota_monitor.go:288] root:rh-sso-13800399: quota monitor not synced: tenancy.kcp.dev/v1beta1, Resource=workspaces
I0801 11:09:28.761163       1 resource_quota_monitor.go:288] root:rh-sso-6658818: quota monitor not synced: tenancy.kcp.dev/v1beta1, Resource=workspaces
I0801 11:09:28.761182       1 resource_quota_monitor.go:288] root:rh-sso-7770862: quota monitor not synced: tenancy.kcp.dev/v1beta1, Resource=workspaces
I0801 11:09:28.761189       1 resource_quota_monitor.go:288] root:rh-sso-6429421: quota monitor not synced: tenancy.kcp.dev/v1beta1, Resource=workspaces
I0801 11:09:28.821642       1 resource_quota_monitor.go:288] root:rh-sso-6419545: quota monitor not synced: tenancy.kcp.dev/v1beta1, Resource=workspaces
I0801 11:09:28.821681       1 resource_quota_monitor.go:288] root:rh-sso-15878744: quota monitor not synced: tenancy.kcp.dev/v1beta1, Resource=workspaces
I0801 11:09:28.821765       1 resource_quota_monitor.go:288] root:rh-sso-13800399: quota monitor not synced: tenancy.kcp.dev/v1beta1, Resource=workspaces
I0801 11:09:28.823311       1 resource_quota_monitor.go:288] root:rh-sso-16080397: quota monitor not synced: tenancy.kcp.dev/v1beta1, Resource=workspaces
I0801 11:09:28.823333       1 resource_quota_monitor.go:288] root:users:dn:eb: quota monitor not synced: tenancy.kcp.dev/v1beta1, Resource=workspaces
I0801 11:09:28.823460       1 resource_quota_monitor.go:288] root:rh-sso-7770862: quota monitor not synced: tenancy.kcp.dev/v1beta1, Resource=workspaces

**Expected behavior**
kcp pod logs should not be flooded with the message in the description

**Additional context**

**Comment by ncdc** [comment]
Unable to reproduce locally. My current theory is it has something to do with the deployment topology where there is a separate virtual workspaces container. Might not be it, but it's hard to do an apples-to-apples test without that.

**Comment by ncdc** [comment]
Just filed #1702 for the virtual workspaces standalone test mode

**Comment by ncdc** [comment]
Am able to reproduce now. The partial metadata informer is trying to request `/clusters/*/apis/tenancy.kcp.dev/v1beta1/workspaces` from the kcp process, which gets redirected via the front proxy to the virtual-workspaces container, and we see this error

```
W0819 11:41:35.676289       1 reflector.go:324] k8s.io/client-go@v0.0.0-20220803191238-b6a732dbd013/tools/cache/reflector.go:167: failed to list *unstructured.Unstructured: Get "https://<external url>/services/workspaces/%2A/apis/tenancy.kcp.dev/v1beta1/workspaces?limit=500&resourceVersion=0": x509: certificate is valid for [REDACTED], not apiserver-loopback-client```

**Comment by ncdc** [comment]
This is happening because the partial metadata informer client is the loopback client, which is not valid against an external virtual workspaces process
