### ISSUE TITLE
insecure: claimed.internal.apis.kcp.dev/<hash> is not APIExport dependent

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#1666]
Attack vector:
1. APIExport A claims resource R and workspace W bound against A has accepted the claim.
2. APIExport B claims resource R and workspace W bound against B has **NOT** accepted the claim.
3. The APIExport VW filters by `claimed.internal.apis.kcp.dev/<hash[:8]>: hash`, which is equal for A and B. Hence, owner of B gets access despite the user not accepting its claim.

**Comment by ncdc** [comment]
This was fixed in #1617
/close
