### ISSUE TITLE
Lots of test flakes due to slow kcp server startup/bootstrapping

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#1675]
The `e2e` and `e2e-multiple-runs` jobs use `E2E_PARALLELISM=3`, which translates to `-p 3 -parallel 3`.

`-p 3` means build/run 3 separate test packages simultaneously.

`-parallel 3` means run up to 3 tests opting in to parallelism via `t.Parallel()` simultaneously.

Both `e2e` and `e2e-parallel` start at least 1 kcp instance per package (and sometimes more, for a small handful of tests that can't use a shared instance). I am wondering if trying to start up and bootstrap 3 kcp instances at the same time (`-p 3`) is potentially overwhelming the pod in which our tests run, causing some tests to fail because it takes more than 1 minute for kcp to become live + ready - https://github.com/kcp-dev/kcp/blob/2bb2dea985eaa8593a8402d6490d09a718a9e69f/test/e2e/framework/kcp.go#L656

I suggest we consider changing this to `-p 1 -parallel 3` (1 test package at a time, up to 3 tests concurrently). Or perhaps we need to increase our wait time to longer than 1 minute?

**Comment by ncdc** [comment]
Example failure https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/kcp-dev_kcp/1663/pull-ci-kcp-dev-kcp-main-e2e-multiple-runs/1554539330989461504

**Comment by stevekuznetsov** [comment]
What's our thought on having one (shared, sharded) server for all tests? We're eating the cost of not cleaning up correctly already, so the non-shared e2e does not have a huge benefit in CI.

**Comment by ncdc** [comment]
I am 💯 in favor of getting rid of the CI tests that spin up 1 kcp per test package, i.e. switch to shared everywhere we can

**Comment by ncdc** [comment]
> not cleaning up correctly already

in what regard?

**Comment by stevekuznetsov** [comment]
The way I see it, the cost of shared tests is that test logic needs to handle multi-tenancy. The benefit of single-kcp-per-test is that it's hermetic. Since we run shared tests in CI anyway, we already need to handle the extra issues, so the hermetic benefit is kind of moot, since you only merge when all suites pass.
