### ISSUE TITLE
When synctarget is being deleted and added back all the pods running in the previous syncer namespaces starts to run again

### ISSUE THREAD

**Issue by kasturinarra** [kcp-dev/kcp#1679]
**Describe the bug**
When the synctarget is deleted and added back i see that pod comes back and starts running in the previous syncer namespaces

[knarra@knarra ~]$ oc get pods --all-namespaces | grep kuard
kcp-27tnpxttv54u                                   kuard-5bdc44b494-hf62w                                                      1/1     Running             0              13m
kcp-hv00zupix4tz                                   kuard-5bdc44b494-lq5rs                                                      1/1     Running             0              14m

**To Reproduce**
1. Deploy kcp on openshift cluster
2. Add a workload cluster by running the command `kubectl kcp workload sync qecluster1 --syncer-image ghcr.io/kcp-dev/kcp/syncer:8ad1c4a -o - | KUBECONFIG=<pcluster> kubectl apply -f - `
3. Now verify that it has been added successfully using the command `kubectl get synctarget -o wide’
4. Create deployment using the command ` kubectl create deployment kuard --image gcr.io/kuar-demo/kuard-amd64:blue --dry-run=client -o yaml > kuard.yaml`
5. Apply the kuard.yaml using the command `kubectl apply -f kuard.yaml`
6. Now verify that deployment has been synced to downstream cluster by running the command ‘oc get pods --all-namespaces | grep kuard’
[knarra@knarra ~]$ oc get pods --all-namespaces | grep kuard
kcp-27tnpxttv54u                                   kuard-5bdc44b494-twcbt                                                      1/1     Running             0              11s
7. Now add another synctarget by running the command `kubectl kcp workload sync qecluster1 --syncer-image ghcr.io/kcp-dev/kcp/syncer:8ad1c4a -o - | KUBECONFIG=/home/knarra/Downloads/kubeconfig_411 kubectl apply -f -`
8. Wait for the synctarget to be added successfully
9. Now delete the first synctarget by running the command `kubectl delete synctarget qecluster1`
10. Verify that deployment moved to the second synctarget added which is `qecluster2` by running the command `oc get pods --all-namespaces | grep kuard`
[knarra@knarra ~]$ oc get pods --all-namespaces | grep kuard
kcp-1cmkuvs9epei                                   kuard-5bdc44b494-45dhs                                                      1/1     Running     0              11m
11. Now add back the qecluster1 synctarget using the command `kubectl kcp workload sync qecluster1 --syncer-image ghcr.io/kcp-dev/kcp/syncer:8ad1c4a -o - | KUBECONFIG=<pcluster> kubectl apply -f - `
12. Delete the qecluster2 sync target using the command `kubectl delete synctarget qecluster2`
13. Now verify that pods related to deployment does not run on qecluster2 and make sure they run on qecluster1
14. Run the command on qecluster1 to see if the pods run fine `oc get pods --all-namespaces | grep kuard`
 15. See that there are two pods with same name running in two different namespaces
 [knarra@knarra ~]$ oc get pods --all-namespaces | grep kuard
kcp-27tnpxttv54u                                   kuard-5bdc44b494-hf62w                                                      1/1     Running             0              46s
kcp-hv00zupix4tz                                   kuard-5bdc44b494-lq5rs                                                      1/1     Running             0              47s

**Expected behavior**
Pods should be running in the namespace created recently when the cluster was added back and not in the previous namespace.

**Additional context**

**Comment by sttts** [comment]
Today a new SyncTarget UID means a new set of downstream namespaces (because the namespace locator changes by UID).

What we definitely want: 
1. `kubectl kcp workload sync` must be idem-potent if the SyncTarget UID does not change.
2. if the UID changes, the syncer namespace changes. We should not reuse the service account.

Two options I see
1. we could get rid of the UID in the namespace locator again, but then there is a possible overlap with different kcp instances and SyncTargets in the same workspaces names.
2. we could extend `kubectl kcp workload sync` to check the service account to belong to the sync target. For that we could add synctarget UID annotation to the SA, and also owner-ref the SyncTarget from the SA and its secret. The cli plugin would refuse to continue if the synctarget UID annotation does not match.

**Comment by jmprusi** [comment]
@sttts, as we discussed on slack, let's go with the second option but add a flag to the syncer deployment with the "original" synctarget UID, so the syncer will refuse to sync if it detects that the synctarget UID doesn't match.

**Comment by ncdc** [comment]
Fixed by #1687 
/close
