### ISSUE TITLE
Issue navigating with "kubectl kcp workspace use"

### ISSUE THREAD

**Issue by fgiloux** [kcp-dev/kcp#1684]
**Describe the bug**
After creating a workspace (org in this case) navigating back to root I am not able to navigate back to the organisation using `kubectl kcp workspace use`

**To Reproduce**
~~~
$ kubectl kcp workspace .
Current workspace is "root".
$ cat /tmp/ctrler/org.yaml 
apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspace
metadata:
  name: test
spec:
  type:
    name: organization
    path: root
$ kubectl create -f /tmp/ctrler/org.yaml 
clusterworkspace.tenancy.kcp.dev/test created
$ kubectl get clusterworkspace
NAME                PHASE   TYPE           URL                                                          AGE
test                Ready   organization   https://192.168.0.149:6443/clusters/root:test                12s
users               Ready   homeroot       https://192.168.0.149:6443/clusters/root:users               23h
$ kubectl kcp workspace use root:test
error: workspaces.tenancy.kcp.dev "test" not found
# Modify the kubeconfig to directly point to https://192.168.0.149:6443/clusters/root:test
$ vi $KUBECONFIG
$ kubectl kcp workspace .
Current workspace is "root:test".
$ kubectl api-resources
NAME                              SHORTNAMES   APIVERSION                             NAMESPACED   KIND
configmaps                        cm           v1                                     true         ConfigMap
events                            ev           v1                                     true         Event
[...]

**Expected behavior**
To be able to navigate to the workspace that has been created

cc @davidfestal

**Comment by fgiloux** [comment]
cc @davidfestal

**Comment by fgiloux** [comment]
For the sake of completeness:
~~~
$ kubectl get workspaces
No resources found
$ kubectl get clusterworkspace
NAME                PHASE   TYPE           URL                                                          AGE
test                Ready   organization   https://192.168.0.149:6443/clusters/root:test                12s
users               Ready   homeroot       https://192.168.0.149:6443/clusters/root:users               23h
~~~

**Comment by davidfestal** [comment]
In order to have the `test` organization listed by `kubectl get workspaces`, you will need to be bound to the following permissions in the `root` workspace:
```
- apiGroups:
  - tenancy.kcp.dev
  resources:
  - clusterworkspaces/workspace
  resourceNames:
  - test
  verbs:
  - get
```
In addition with the typical permission you need to have access to the `test` workspace content:
```
- apiGroups:
  - tenancy.kcp.dev
  resources:
  - clusterworkspaces/content
  resourceNames:
  - test
  verbs:
  - access
```
Listing/getting **workspaces definitions** and having access to **workspace contents** are now 2 things orthogonal. And the permissions related to a workspace definition (`clusterworkspaces/workspace`).

_Note:_ Requiring the `get` permission on `clusterworkspaces/workspace` to have the workspace appear in the `kubectl list workspaces` call allows expresing Workspace ownership and this is managed by the `workspaces` virtual workspace.

**Comment by davidfestal** [comment]
@fgiloux Can you check that adding the 2 permissions mentioned [above](https://github.com/kcp-dev/kcp/issues/1684#issuecomment-1205469791) in a cluster role bound to your user fixes your problem ?

**Comment by stevekuznetsov** [comment]
Does `kubectl kcp workspace create --enter` handle the RBAC for the user? Do users always need to remember to do the RBAC>

**Comment by davidfestal** [comment]
Good question @stevekuznetsov.

`kubectl kcp workspace create --enter` creates the required named `get` and `delete` permissions for the created workspace. 

So in the initial org the user can `get` the newly-created worspace or `delete` it any without additional action.
And if the user already had the `list` permission on `clusterworkspaces/workspace` in the initial org, he would also see the newly-create workspace when doing a `kubectl list workspaces` in the initial org workspace.

But in @fgiloux use-case, the top-level org workspace having been created directly as a `clusterworkspace`, those roles have not been created afaict.

**Comment by fgiloux** [comment]
Thanks @davidfestal and @stevekuznetsov both worked and both are good to know.

**Comment by ncdc** [comment]
The remaining work to improve the UX here is tracked in #1319 
/close
