### ISSUE TITLE
Add option to cmd/test-server and/or cmd/sharded-test-server to deploy the virtual workspaces server standalone

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#1702]
This should be optional, and match the way the Helm chart deploys the virtual workspaces server in a standalone container, e.g.

https://github.com/kcp-dev/helm-charts/blob/d3c0a50c6dc3f61421305156b5c7e93fd83c35db/charts/kcp/templates/kcp.yaml#L205-L206

https://github.com/kcp-dev/helm-charts/blob/d3c0a50c6dc3f61421305156b5c7e93fd83c35db/charts/kcp/templates/kcp.yaml#L283-L304

**Comment by stevekuznetsov** [comment]
@sttts and I were talking about this - sounds like we might want three tests in the end:

- non-sharded e2e for control plane, in-process
- sharded e2e for control plane, deployed to a k8s cluster (this issue would fit here)
- e2e for TMC, deployed to k8s
