### ISSUE TITLE
Delete specific worksapce multi times, server output fake messages

### ISSUE THREAD

**Issue by Phaow** [kcp-dev/kcp#1723]
**Describe the bug**
Delete worksapce multi times, server output fake messages since the second time 
If we already delete 1 ws, delete the second time it should report `not found` err info. But actually  the result is still `[workspace.tenancy.kcp.dev](http://workspace.tenancy.kcp.dev/) "xxxx" deleted` makes confusing. 
kcp server version is v0.7.1

**To Reproduce**
1. Create workspace "myws-test" under user home workspace.
2. Delete the "myws-test".
3. Get the workspaces.
4. Delete the "myws-test" the second time.

**Expected behavior**
At Step 4 output should report `not found` err info.

**Actual result**
At Step 4 output stiil report `[workspace.tenancy.kcp.dev](http://workspace.tenancy.kcp.dev/) "myws-test" deleted`.

```
✘$ kubectl ws .
Current workspace is "root:users:rp:pv:rh-sso-xxxx".
$ kubectl ws
$ kubectl ws create myws-test
$ kubectl delete myws-test
workspace.tenancy.kcp.dev "myws-test" deleted
$ kubectl get workspaces
No resources found
$ kubectl delete myws-test
workspace.tenancy.kcp.dev "myws-test" deleted
```

**Comment by sttts** [comment]
Fixed in https://github.com/kcp-dev/kcp/issues/1776.
