### ISSUE TITLE
Deliver kubectl-kcp in a container

### ISSUE THREAD

**Issue by Roming22** [kcp-dev/kcp#1734]
**Is your feature request related to a problem? Please describe.**
Our project is using the kubectl-kcp plugin. We'd like to have access to a pre-built binary. 

**Describe the solution you'd like**
We'd like to be able to copy the binary from an image delivered by the kcp project.

**Describe alternatives you've considered**
We currently build the plugin ourselves in each of our Dockerfiles.
We could build and publish an image with all the kcp binaries we require and reference that in our Dockerfiles.

**Comment by ncdc** [comment]
Xref #1092
