### ISSUE TITLE
APIExports virtual workspace broken when virtual workspaces are run standalone and an APIExport has permission claims

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#1752]
When the virtual workspaces process is run standalone, the virtual workspace for an APIExport with permission claims is broken because `indexers.IndexAPIExportByIdentity` is not configured (this only currently happens when the APIExport controller is instantiated, which does not happen in the virtual workspaces process).

**Comment by ncdc** [comment]
FYI @sttts @shawn-hurley

**Comment by ncdc** [comment]
We need a better/more organized way of installing custom index functions 😄

**Comment by ncdc** [comment]
The index is needed here https://github.com/kcp-dev/kcp/blob/137c9c5a2327aa8099a8b242677b8a25e02a9295/pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go#L124

**Comment by ncdc** [comment]
Possible quick fix: we could add the index function in this controller too (if it doesn't already exist).

**Comment by sttts** [comment]
IMO we should have shared and idempotent index adding code used by all controllers/components.

**Comment by shawn-hurley** [comment]
I agree. Also probably should have a test case that runs the VW server standalone and runs the e2e tests against it. 

I wonder if it can still be shared code from the indexer's package, but each controller during construction calls the add this index function. 

is that what y'all were thinking?

**Comment by ncdc** [comment]
> IMO we should have shared and idempotent index adding code used by all controllers/components.

Agreed, but what does it look like? Do we have some central place where we collect all the index functions along with a one-line call we can invoke to add them?

> Also probably should have a test case that runs the VW server standalone and runs the e2e tests against it.

#1702

**Comment by sttts** [comment]
> Agreed, but what does it look like? Do we have some central place where we collect all the index functions along with a one-line call we can invoke to add them?

we do. You added it :D pkg/indexers

The code would try to add and skip the complaint if it already exists. If we make the index names unique enough, no unwanted conflict should ever happen, i.e. around `kcp-global-byFooBar`.

**Comment by ncdc** [comment]
Right, although I was more asking about the overall structure/invocation pattern. e.g. do we remove every index addition from individual controller files and centralize the setup in pkg/indexers?

**Comment by shawn-hurley** [comment]
Adding my two cents, I think it would be helpful if each controller made sure to ask for the indexers that it needs during construction. It would allow, say API export virtual workspace to be run standalone someday if that was ever needed.

**Comment by ncdc** [comment]
@shawn-hurley see what I've started in #1762 & let me know what you think
