### ISSUE TITLE
e2e flake: TestWatchCacheEnabledForBuiltinTypes

### ISSUE THREAD

**Issue by s-urbaniak** [kcp-dev/kcp#1759]
**Describe the bug**
The `TestWatchCacheEnabledForBuiltinTypes` e2e test failed unexpectedly.

**To Reproduce**
Executing `TestWatchCacheEnabledForBuiltinTypes` does not reproduce unfortunately.

**Expected behavior**
e2e to pass green.

**Additional context**
some clue from logs:
![image](https://user-images.githubusercontent.com/375856/184891597-79bdd675-44db-4935-9e37-1cc570d7b4fd.png)

```
I0816 12:04:28.364745   60830 trace.go:205] Trace[361965121]: "DeltaFIFO Pop Process" ID:root|e2e-org-p65s2-admin-access,Depth:50,Reason:slow event handlers blocking the queue (16-Aug-2022 12:04:28.202) (total time: 160ms):
```

logs: https://github.com/kcp-dev/kcp/runs/7856772391?check_suite_focus=true

**Comment by p0lyn0mial** [comment]
```
   watchcache_enabled_test.go:279: DynamicDiscoverySharedInformerFactory hasn't synced apis.kcp.dev/v1alpha1, Resource=apibindings yet
    watchcache_enabled_test.go:276: 
        	Error Trace:	util.go:303
        	            				watchcache_enabled_test.go:276
        	            				watchcache_enabled_test.go:219
        	Error:      	Condition never satisfied
        	Test:       	TestWatchCacheEnabledForBuiltinTypes
        	Messages:   	DynamicDiscoverySharedInformerFactory hasn't observed /v1, Resource=secrets with name topsecret in root:e2e-org-9vvsj:e2e-workspace-mqk2w cluster
```

^ suggest that the test failed on waiting for all informers to synced, for some reason some weren't. 

I'll try to see if I can find something that would explain slow informers in the logs

**Comment by p0lyn0mial** [comment]
https://github.com/kcp-dev/kcp/pull/1761 - will put less load on the server

**Comment by p0lyn0mial** [comment]
resolved by https://github.com/kcp-dev/kcp/pull/1761

/close
