### ISSUE TITLE
Syncer doesn't remove the downstream namespace once delete upstream

### ISSUE THREAD

**Issue by jmprusi** [kcp-dev/kcp#1760]
**Describe the bug**
When deleting a namespace in kcp (upstream) the resources are removed from the downstream namespace, but the downstream namespace itself is not removed.

**To Reproduce**
1. setup kcp with one synctarget
2. create a namespace
3. delete the namespace
4. See the downstream namespace still existing in the synctarget cluster.

**Expected behavior**
The downstream namespace should be deleted when the upstream namespace is deleted.

**Comment by ncdc** [comment]
@jmprusi is this a duplicate of #398?

**Comment by jmprusi** [comment]
> @jmprusi is this a duplicate of #398?

yes! sorry!
