### ISSUE TITLE
specify apiexport in synctarget

### ISSUE THREAD

**Issue by qiujian16** [kcp-dev/kcp#1777]
it should be able to specify apiexports of another workspace in synctarget. The controller should updated the status.syncedResource in syncatarget indicating whether the resource schema from the APIExport is compatible with the API schema on the physical cluster.

This is part of the epic https://github.com/kcp-dev/kcp/issues/912 to support location(compute) workspace.

- [x] synctarget API update https://github.com/kcp-dev/kcp/pull/1571
- [x] controller to update status.syncedResource  https://github.com/kcp-dev/kcp/pull/1624

**Comment by stevekuznetsov** [comment]
@qiujian16 it looks like this might be finished - if that's true, are we ready to close this out?

**Comment by qiujian16** [comment]
yes. it can be closed
/close
