### ISSUE TITLE
only serve compatible APIs from synctarget virtual workspace

### ISSUE THREAD

**Issue by qiujian16** [kcp-dev/kcp#1778]
followup of https://github.com/kcp-dev/kcp/issues/1777

the synctarget virtual workspace should only serve compatible APIs to the synctarget. 

This is part of the epic https://github.com/kcp-dev/kcp/issues/912 to support location(compute) workspace.

**Comment by sttts** [comment]
Fixed in https://github.com/kcp-dev/kcp/pull/1828.
