### ISSUE TITLE
Schedule synctarget based on compatible API

### ISSUE THREAD

**Issue by qiujian16** [kcp-dev/kcp#1779]
followup of https://github.com/kcp-dev/kcp/issues/1777

in the user workspace, when user creates a placement to schedule workloads to a synctarget in a location. The scheduler should select the synctarget that has the compatible API with workload APIBinding in this user workspace.

This is part of the epic https://github.com/kcp-dev/kcp/issues/1895 to support compute type management.

**Comment by davidfestal** [comment]
Linked with the wrong PR.
Let's reopen.
