### ISSUE TITLE
Cannot sync horizontalpodautoscalers.autoscaling

### ISSUE THREAD

**Issue by lionelvillard** [kcp-dev/kcp#1784]
**Describe the bug**

I'm getting this error when trying to sync `horizontalpodautoscalers.autoscaling`:

```
E0817 14:43:12.562410   33147 workload_apiexport_controller.go:211] "kcp-workload-apiexport" controller failed to sync "root:my-workspace|kubernetes", err: apiresourceschemas.apis.kcp.dev "rev-552.horizontalpodautoscalers.autoscaling" is forbidden: [spec.group: Invalid value: "autoscaling": should be a domain with at least one dot]
```

This is strange because it works for `deployments.apps` and `poddisruptionbudgets.policy`.

**To Reproduce**

Create a syncer with `--resources=horizontalpodautoscalers.autoscaling`, apply it and observe error aforementioned.

**Expected behavior**

No errors

**Additional context**

**Comment by ncdc** [comment]
Need to add `autoscaling` to https://github.com/kcp-dev/kcp/blob/11138a2647f6bd4fb636746b6a1f093ffab988d1/pkg/admission/apiresourceschema/validation.go#L41

/help
/good-first-issue
