### ISSUE TITLE
Add support for group membership via the front-proxy

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#1794]
For setups where an identity provider does not necessarily provide user groups that align with the workspace hierarchy in kcp, it would be nice to have a stop-gap solution to manage group membership in kcp itself.

The idea we'd like to explore is modifying the front proxy so it can read group membership data from somewhere with kcp itself, such as one or more configmaps. When a user makes a request to the front proxy, the proxy looks up group membership for the user and includes any groups found in the `--requestheader-group-headers` header on the request. See https://kubernetes.io/docs/reference/access-authn-authz/authentication/#authenticating-proxy for more details.

**Comment by ncdc** [comment]
cc @s-urbaniak

**Comment by stevekuznetsov** [comment]
cc @csams

**Comment by csams** [comment]
I'm working on this in https://github.com/redhat-cps/front-proxy/pull/3
