### ISSUE TITLE
Community Meeting August 23, 2022

### ISSUE THREAD

**Issue by stevekuznetsov** [kcp-dev/kcp#1814]
At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/mpd-cypd-sdp
Or dial: ‪(DE) +49 30 300195060‬ PIN: ‪500 599 130 5702‬#
More phone numbers: https://tel.meet/mpd-cypd-sdp?pin=5005991305702
Or join via SIP: sip:[5005991305702@gmeet.redhat.com](mailto:5005991305702@gmeet.redhat.com)

Meeting recordings available on YouTube at https://www.youtube.com/channel/UCfP_yS5uYix0ppSbm2ltS5Q

This issue will collect prospective agenda topics.

### Agenda Topics

- structured logging revamp update & call to action

**Comment by pweil-** [comment]
General announcement:  0.8 target closing date is 2 Sep.  It's time to think about 0.9 work items.  I've seeded the work packages doc with our continue/new topics for people to revise: https://docs.google.com/document/d/1jN6BdhUUIESeHw3_f6HwsNwVM2Ytabr6usUQhYMcNd8/edit#heading=h.xcoe1xfb45ca

**Comment by stevekuznetsov** [comment]
Incoming issues: https://github.com/kcp-dev/kcp/issues?q=is%3Aopen+is%3Aissue+-label%3Acommunity-meeting+no%3Amilestone

Milestone epics: https://github.com/kcp-dev/kcp/issues?q=is%3Aopen+is%3Aissue+label%3Amilestone-blocker+label%3Aepic

**Comment by pweil-** [comment]
Recording: https://drive.google.com/file/d/1PpPt-ivEYx6SJmw0oe4Dt-BtbkwDfelH/view?usp=drive_web

(will need shared once the owner is back)

**Comment by ncdc** [comment]
Recording: https://www.youtube.com/watch?v=k7DbS5sHlnY
