### ISSUE TITLE
feat: Transparent Discovery API calls to APIExport virtual workspace server

### ISSUE THREAD

**Issue by astefanutti** [kcp-dev/kcp#1823]
### Feature Description

Currently, the APIExport VW API server rejects any requests that does not specify a logical cluster, i.e., that does not have the `/clusters/<logical_cluster>` segment:

https://github.com/kcp-dev/kcp/blob/a1cbfc55ef10d9671f824de8f7921ebd59465ae9/pkg/virtual/apiexport/builder/build.go#L97-L103

That prevents some existing controllers / operators to run on kcp, as they construct the Discovery API client from the manager client configuration, that's been built from the APIExport virtual workspace URL, but that does not contain/inject any logical cluster information.

The issue can be reproduced by calling the APIExport VW API server directly, e.g.:

``` console
$ kubectl --server https://192.168.0.24:6443/services/apiexport/root:default:control/camel-kcp api-resources --v=9
Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"forbidden: User \"kcp-admin\" cannot get path \"/services/apiexport/root:default:control/camel-kcp/apis\": Path not resolved to a valid virtual workspace","reason":"Forbidden","details":{},"code":403}
```

Interestingly, passing any random string as logical cluster works, e.g.:

```console
$ kubectl --server https://192.168.0.24:6443/services/apiexport/root:default:control/camel-kcp/clusters/RANDOM_STRING api-resources

NAME         SHORTNAMES APIVERSION          NAMESPACED KIND
configmaps              v1                  true       ConfigMap
secrets                 v1                  true       Secret
integrations it         camel.apache.org/v1 true       Integration
```

It seems symptomatic that the logical cluster information is irrelevant in the context of Discovery API calls over APIExport VW API Server, as the results are entirely defined by the APIExport and constant over the workspaces / logical clusters.

### Proposed Solution

Ideally, the solution would require no code modification for existing controllers / operators. As there is no Discovery API client associated to the controller-runtime manager, those controllers / operators usually retrieve the manager client configuration and instantiate a Discovery API client from that configuration, making it difficult / impossible to rely on a client-side solution. Hence it would be ideal that the APIExport server would allow requests to `/api` and `/apis` without logical clusters.

That solution would have the advantage to work with any clients, like `kubectl`.

### Alternative Solutions

A client-side solution, relying for example on a round-tripper that would inject the wildcard logical cluster segment, would probably be possible, but would require some refactoring for existing controllers / operators, in order to inject the modified Discovery API client wherever used.

### Want to contribute?

✅ I would like to work on this issue.

**Comment by stevekuznetsov** [comment]
>  making it difficult / impossible to rely on a client-side solution.

A round-tripper in the `*rest.Config` should be able to rewrite the host correctly for this case. There are related questions about creating "bare" controller-runtime clients and using them

/cc @ncdc

**Comment by ncdc** [comment]
> Ideally, the solution would require no code modification for existing controllers / operators

An existing controller/operator that you want to run without code changes must be pointed at a single workspace. You can't point it at the APIExport virtual workspace URL and have it work. Even if we fix discovery to support `/api` and `/apis` without requiring `/clusters/<something>`, the existing code won't know how to act across different workspaces.

> That solution would have the advantage to work with any clients, like kubectl.

The APIExport virtual workspace URL is not meant for use with kubectl.


I'm curious about what you're trying to do here. What do you want an existing controller/operator to do?

**Comment by astefanutti** [comment]
> I'm curious about what you're trying to do here. What do you want an existing controller/operator to do?

I'm aiming at porting an existing operator to work on kcp, with a single instance able to work across workspaces, while minimising the code changes required, to increase their "acceptability". Naively, I have initially assumed that changing the controller-runtime manager, configured with the APIExport VW URL, and propagating the logical cluster context would be enough. I've faced that issue with discovery API as I'm experimenting. I imagine there will be more changes, but the less friction, the better.

**Comment by ncdc** [comment]
Is your code using discovery directly?

**Comment by astefanutti** [comment]
> Is your code using discovery directly?

Yes.

To give a bit more details, here is the existing operator: https://github.com/apache/camel-k, and an example of how discovery is called:

https://github.com/apache/camel-k/blob/36076ffc257ab62e265c9d45c9c97f697a3cefc8/pkg/util/kubernetes/discovery.go#L26

The current approach I'm exploring first, in order to avoid forking the operator code if possible, is to wrap the operator in a separate project https://github.com/astefanutti/camel-kcp, with the kcp dependencies, a main injecting the APIExport / kcp aware controller-runtime config, and ideally find a way to automagically propagate the logical cluster context in the controllers reconcile methods. So as to re-use a maximum of the existing operator code, from a kcp-aware wrapper of it.

**Comment by sttts** [comment]
> Hence it would be ideal that the APIExport server would allow requests to /api and /apis without logical clusters.

Has been discussed before and it was intentionally removed / disabled. The fact that a virtual workspace serves the same APIs for every cluster or for clusters and wildcards requests is a conincidence that cannot be guaranteed. There might be a virtual workspace servicing different resources on each cluster.

**Comment by astefanutti** [comment]
Thanks, I thought that in the case of APIExport virtual workspaces, the discovery was entirely defined by the APIExport spec.

I'll override the client config to use wildcard clusters requests in our case.
