### ISSUE TITLE
bug: cache-server misses the scope client

### ISSUE THREAD

**Issue by p0lyn0mial** [kcp-dev/kcp#1829]
### Describe the bug

The [ApiExtensionsClusterClient](https://github.com/kcp-dev/kcp/blob/fe9bf899d5b95029fe50ed44258628b781c5bde9/pkg/cache/server/config.go#L147) in the cache server should use scope clients instead of `NewClusterForConfig`

### Steps To Reproduce

I tried to wire in a context-based client as advised in https://github.com/kcp-dev/kcp/pull/1815#discussion_r954151311 by using `SetMultiClusterRoundTripper` along with `SetCluster` 

So basically I did ` apiextensionsclient.NewForConfig( kcpclienthelper.SetMultiClusterRoundTripper(kcpclienthelper.SetCluster(rest.CopyConfig(cfg), logicalcluster.Wildcard))`. 

Then when I tried to create a CRD with a ctx with a logical cluster name set it failed because the path was incorrect.
The path was set to `/clusters/*/clusters/system:system-crds/apis/apiextensions.k8s.io/v1/customresourcedefinitions/apiresourceschemas.apis.kcp.dev`

### Expected Behaviour

Either something is broken or I don't know how to use a context-based client. I'd expect the path to be correctly set to the cluster from the context.

**Comment by p0lyn0mial** [comment]
/cc @varshaprasad96 

I'm happy to prepare a PR if you could provide some input here. Thanks!

**Comment by varshaprasad96** [comment]
@p0lyn0mial The process which I usually follow to scope clients is:
Option 1:
1. Wrap an existing config with the cluster round tripper - (ie) using https://pkg.go.dev/github.com/kcp-dev/apimachinery/pkg/client#SetMultiClusterRoundTripper 
2. Pass a scoped context while making client calls (`logical cluster.WithContext(ctx, someCluster)`

Option 2:
1. Set the cluster in the rest config directly (ie) with https://github.com/kcp-dev/apimachinery/blob/dbb759406933f20051f134e5d2cd740bcda53900/pkg/client/cluster_config.go#L43. If we do this, then we need **not** pass a scoped context, or even use cluster aware round tripper.

Based on the url, it looks like both options are being performed. If the rest config is directly being modified, we shouldn't be passing scoped context.

**Comment by p0lyn0mial** [comment]
@varshaprasad96 yes, it looks like I applied both options at the same time. 

Would you accept a PR that would allow for overwriting the cluster set by `Option 2` when a cluster is also set in the context (`Option 1`)?

/cc @stevekuznetsov

**Comment by stevekuznetsov** [comment]
Hm, I thought both at once should have worked. In any case, I think for now we are pausing this so let's re-consider it when we have more clarity about how we're moving forward.
