### ISSUE TITLE
feat: add a workspace tree subcommand

### ISSUE THREAD

**Issue by lburgazzoli** [kcp-dev/kcp#1838]
### Feature Description

It would be nice to have a workspace tree subcommand to visualize the hierarchy of workspaces, i.e.

```
NAME           TYPE           PHASE   URL
------------- ------------- -------- -----
root           universal      Ready   ...
 ├─ org1       organization   Ready   ...
 │   ├─ team1  organization   Ready   ...
 │   └─ team2  organization   Ready   ...
 └─ foo        user           Ready   ...
```

There are some similar tools:
1. https://github.com/ahmetb/kubectl-tree
2. https://github.com/nimakaviani/knative-inspect/

### Proposed Solution

Ass a kubectl-ws tree subcommand 

### Want to contribute?

- [X] I would like to work on this issue.

**Comment by ncdc** [comment]
FYI, as of today, this will require multiple requests (1 per level)

**Comment by stevekuznetsov** [comment]
@ncdc or access to the tenancy APIExport?

**Comment by ncdc** [comment]
That doesn't give you a list of all workspaces hierarchically though

**Comment by lburgazzoli** [comment]
> FYI, as of today, this will require multiple requests (1 per level)

Yes I had a look at the code and it is probably be a little bit convoluted to implement so may need some help, but I'll :)

**Comment by stevekuznetsov** [comment]
@ncdc not sure I understand what you mean - it gives you a cross-cluster list, which you could then reorder in hierarchical order?

**Comment by ncdc** [comment]
hmm, maybe? although when we have 2+ shards, that might require multiple calls?

**Comment by lburgazzoli** [comment]
> I imagine that would be hidden behind the virtual workspace, no?

can you point me to some code ?

**Comment by lburgazzoli** [comment]
> I'm not sure exactly what you mean - but if you request a cross-cluster list of some resource from an APIExport virtual workspace, you will get all of them, without shard distinctions (today).

Just that I'm not yet deeply expert in KCP so some exemplar code could be very helpful :)
