### ISSUE TITLE
Community Meeting August 30, 2022

### ISSUE THREAD

**Issue by pweil-** [kcp-dev/kcp#1849]
At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/mpd-cypd-sdp
Or dial: ‪(DE) +49 30 300195060‬ PIN: ‪500 599 130 5702‬#
More phone numbers: https://tel.meet/mpd-cypd-sdp?pin=5005991305702
Or join via SIP: sip:[5005991305702@gmeet.redhat.com](mailto:5005991305702@gmeet.redhat.com)

Meeting recordings available on YouTube at https://www.youtube.com/channel/UCfP_yS5uYix0ppSbm2ltS5Q

This issue will collect prospective agenda topics.

Incoming issues: https://github.com/kcp-dev/kcp/issues?q=is%3Aopen+is%3Aissue+-label%3Acommunity-meeting+no%3Amilestone

Milestone epics: https://github.com/kcp-dev/kcp/issues?q=is%3Aopen+is%3Aissue+label%3Amilestone-blocker+label%3Aepic

**Comment by pweil-** [comment]
@adambkaplan do you want to talk about https://github.com/kcp-dev/kcp/issues/1847 at the meeting?

**Comment by pweil-** [comment]
@varshaprasad96 do you want to mention details on https://github.com/kcp-dev/kcp/issues/1490#issuecomment-1230956599 in relation to 0.9 work?

**Comment by pweil-** [comment]
@dinhxuanvu for catalog design overview https://kubernetes.slack.com/archives/C021U8WSAFK/p1661348947897289?thread_ts=1661284823.509559&cid=C021U8WSAFK

**Comment by sttts** [comment]
Proposal: two **doc-days** after tagging v0.8.

**Comment by pweil-** [comment]
@stevekuznetsov request for feedback on client-go changes for cluster-aware clients: https://github.com/kcp-dev/apimachinery/pull/53

**Comment by dinhxuanvu** [comment]
Catalog API: https://github.com/kcp-dev/catalog/pull/3

**Comment by ncdc** [comment]
cluster-scoped quota #1846

**Comment by varshaprasad96** [comment]
Update on https://github.com/kcp-dev/kcp/issues/1490#issuecomment-1230956599

**Comment by lionelvillard** [comment]
DNS Support https://github.com/kcp-dev/kcp/pull/1708
