### ISSUE TITLE
bug: Server-side apply requests to virtual workspace API server fail for non-existent objects

### ISSUE THREAD

**Issue by astefanutti** [kcp-dev/kcp#1852]
### Describe the bug

A SSA patch request to the APIExport virtual workspace API server returns 404 when the corresponding object does not already exists.

### Steps To Reproduce

```golang
config := corev1apply.ConfigMap("config", "default").WithData(map[string]string{})
err = client.Patch(ctx, config, ctrl.Apply, ctrl.ForceOwnership, ctrl.FieldOwner("manager"))
```

### Expected Behaviour

SSA patch requests should succeed even when objects do not already exist.

**Comment by sttts** [comment]
Is this a regression against kube? Does it happen with kube too?

**Comment by astefanutti** [comment]
> Is this a regression against kube? Does it happen with kube too?

I don't think it's a regression in kube. My current understanding is that it's caused by the forwarding registry implementation that does not cover that use case and assumes the object must exist.

**Comment by ncdc** [comment]
@astefanutti could you please test this against a kube server and report back what the behavior is? Thanks!

**Comment by astefanutti** [comment]
> @astefanutti could you please test this against a kube server and report back what the behavior is? Thanks!

I confirm this works against a vanilla kube server. This can also be tested with `kubectl apply --server-side ...`.

Quoting https://kubernetes.io/docs/reference/using-api/server-side-apply/#introduction that explicitly mentions the "create or patch" behavior:

> A fully specified intent is a partial object that only includes the fields and values for which the user has an opinion. That intent either creates a new object or is [combined](https://kubernetes.io/docs/reference/using-api/server-side-apply/#merge-strategy), by the server, with the existing object.

**Comment by ncdc** [comment]
Thanks!
