### ISSUE TITLE
bug/cleanup: kcp-front-proxy should use flags for shard forwarding

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#1857]
### Describe the bug

kcp-front-proxy uses a mapping file that suggests freedom to configure backends like shards in a flexible way, while in reality the behaviour for shards (i.e. URLs like `/clusters/<ws>/...`) is hardcoded and special.

### Steps To Reproduce

-

### Expected Behaviour

We should turn the shard forwarding configuration into well-defined, well-documented flags instead of relying on a mapping file with custom logic.

Whether we keep the mapping file for other URLs, I don't have a strong opinion. Maybe.

### Additional Context

Note: forwarding the virtual workspace apiserver URLs starting with `/services` is wrong and will breaks as soon as we need multiple shard virtual workspace apiservers. We should also remove that from the testing mapping file. Clients should use the URLs published e.g. in `APIExport.status` or `SyncTarget.status` when talking to virtual workspaces. They not necessarily point to a front-proxy.

**Comment by csams** [comment]
@sttts What cardinality do you envision between virtual-workspace servers and kcp instances? Between the front proxy and kcp instances?

**Comment by sttts** [comment]
Logically 1:1 for shard:VW, physically potentially n:1, but only if we see value there.

front-proxy:shards n:m

**Comment by mjudeikis** [comment]
/close
reopen if still needed
