### ISSUE TITLE
Community Meeting October 19, 2021

### ISSUE THREAD

**Issue by imjasonh** [kcp-dev/kcp#187]
At noon Eastern, 9am Pacific, 4pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T160000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/ohf-kwvd-mrp
Or dial: ‪(US) +1 617-675-4444‬ PIN: ‪936 182 087 7398‬#
More phone numbers: https://tel.meet/ohf-kwvd-mrp?pin=9361820877398
Or join via SIP: sip:9361820877398@gmeet.redhat.com

This issue will collect prospective agenda topics. Add topics you'd like to discuss below!

**Comment by karolz-ms** [comment]
I would love to hear thoughts on using `kcp` as a foundational building block for (application) developer tooling--I described briefly the scenario [here](https://groups.google.com/g/kcp-users/c/UE1QrVXvTNY). 

More specifically (judging from recent community calls), the main focus of current work on `kcp` is on multi-cluster orchestration problem space, which is a different from mine. I can successfully run `kcp` as-is, without any configuration, but it is a bit more chatty than I would expect, and I suspect there are pieces related to multi-cluster orchestration that are included in the default configuration, but that I do not really need or want. So I would appreciate some advice as to:

1. Whether the "developer tooling" scenario is even in scope for `kcp`? Based [on this](https://github.com/kcp-dev/kcp#embeddedlow-resource-scenarios) I assume the answer is "generally yes", but I would like to hear a confirmation from main contributor(s)
2. What would be a good way to incorporate `kcp` into developer tooling, where my team could benefit from improvements to core `kcp` components, and contribute back, while the work on multi-cluster orchestration could proceed at full speed, unimpeded.

This is not super-urgent--if there are more urgent topics to discuss, feel free to postpone this topic to the next community meeting. Thanks!

**Comment by imjasonh** [comment]
Recording: https://youtu.be/rUOwpAHVw20
