### ISSUE TITLE
feature: Scheduling of cluster-wide resources

### ISSUE THREAD

**Issue by jmprusi** [kcp-dev/kcp#1890]
### Feature Description

Cluster-wide resources (non-namespaced) are not currently scheduled by KCP, some transparent multicluster cases require handling this type of resources, for example in the case of Storage with PhysicalVolumes.

### Proposed Solution

1. Implement a cluster-wide resource controller that adds (labels) all the possible SyncTargets, based on the workspace placements, to the non-namespaced resource, in an empty state ("" instead of "Sync"). 

For example, given a placement with a location that holds 3 SyncTargets (A, B, C), a cluster-wide resource should be labeled as follows:

```
state.internal.workloads.kcp.dev/A: ""
state.internal.workloads.kcp.dev/B: ""
state.internal.workloads.kcp.dev/C: ""
``` 

Note that this controller will not set the desired state (Sync) of the resource; it will expose all the possible SyncTargets so a coordination controller can select the desired state based on resource-specific logic, for example, a PV controller.

2. Make the required changes to the Syncer so it will handle cluster-wide resources. 

### Want to contribute?

- [X] I would like to work on this issue.

### Additional Context

* https://docs.google.com/document/d/1lxrF_9Kzxh3IWO66Ec0WNCR-mD0U33gACDeKJWqIO0c/edit#heading=h.wu97vvetf0he

**Comment by davidfestal** [comment]
cc @sttts

**Comment by stevekuznetsov** [comment]
part of #1615
