### ISSUE TITLE
bug: Infinite loop of reconciles when finalizer applied to deleting resource 

### ISSUE THREAD

**Issue by philbrookes** [kcp-dev/kcp#1891]
### Describe the bug

In the scenario where a synctarget is set to use advanced scheduling, and a resource has been created with a finalizer, and that resource is then deleted, the resource will reconcile (adding and removing the deletion timestamp annotation) so rapidly that it is impossible for another controller to remove the finalizer, and so preventing the deletion of this resource.

Tested and confirmed on ingresses, services and deployments, so I assume it affects all resources.

### Steps To Reproduce

1. Create synctarget with advanced scheduling enabled.
2. Create a synced resource with a regular finalizer
3. Delete the resource
4. Watch the resource: (e.g. `kubectl get <resource> <resource-name> -w -o yaml | yq eval ".metadata.resourceVersion" -`)
5. See very rapid updates being applied to the resource
6. This appears to be related to the deletion timestamp (`deletion.internal.workload.kcp.dev/...`) annotation being added and removed rapidly, see the output from: `kubectl get <resource> <ingress-name> -w -o yaml | yq eval ".metadata.annotations" -`

### Expected Behaviour

I would expect the resource to have the deletion timestamp annotation permanently and not be reconciled so aggressively - allowing my controller to remove the finalizer from the resource.

### Additional Context

This is occurring in 0.7.0 and 0.8.0

**Comment by philbrookes** [comment]
After further investigation, this appears to happen regardless of whether or not the sync target has advanced scheduling enabled.

**Comment by stevekuznetsov** [comment]
Sounds like this is not a well-supported use-case today. Filed as a bug for 0.9
