### ISSUE TITLE
bug: Mac binaries don't run out of the box

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#1899]
### Describe the bug

When you download Mac assets from one of our GitHub releases and try to run them, you can't because they're not signed.

![image](https://user-images.githubusercontent.com/354/188657105-33de00a3-525b-4b21-ace8-646318df17aa.png)

### Steps To Reproduce

1. Download Mac assets from a release
2. Extract them
3. Try to run them e.g. `bin/kcp start`

### Expected Behaviour

Running

### Additional Context

The binaries are not signed

**Comment by ncdc** [comment]
If you open the settings app and go to Security & Privacy, you can override this:

![image](https://user-images.githubusercontent.com/354/188657816-f88b2472-0727-4aac-824d-b1838dd2e8dc.png)

But that isn't an experience we want end users to need to go through...

**Comment by ncdc** [comment]
Some useful info:
- https://localazy.com/blog/how-to-automatically-sign-macos-apps-using-github-actions
- https://github.com/mitchellh/gon

**Comment by cmoulliard** [comment]
The side effect of this non signed binary is also that you have to configure the Firewall on your mac too to allow `kcp` to accept the incoming traffic

![Screenshot 2022-09-07 at 08 33 58](https://user-images.githubusercontent.com/463790/188805943-00ccdfe3-8b23-47e3-8233-c77555687814.png)
