### ISSUE TITLE
Allow passing flags for OIDC

### ISSUE THREAD

**Issue by nicolaferraro** [kcp-dev/kcp#190]
I've seen an attempt to use OIDC with KCP in https://www.youtube.com/watch?v=FD_kY3Ey2pI (incomplete). I'm thinking to create a demo based on that feature, so it would be nice if kcp could accept oidc/rbac related flags on startup without having to hack on code.

Is this something planned? I could also help.

**Comment by imjasonh** [comment]
This is something we're interested in adding. If you're still interested in contributing it, I'd happily help answer any questions or review any PRs.
