### ISSUE TITLE
Community Meeting September 6, 2022

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#1902]
At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/mpd-cypd-sdp
Or dial: ‪(DE) +49 30 300195060‬ PIN: ‪500 599 130 5702‬#
More phone numbers: https://tel.meet/mpd-cypd-sdp?pin=5005991305702
Or join via SIP: sip:[5005991305702@gmeet.redhat.com](mailto:5005991305702@gmeet.redhat.com)

Meeting recordings available on YouTube at https://www.youtube.com/channel/UCfP_yS5uYix0ppSbm2ltS5Q

This issue will collect prospective agenda topics.

**Comment by ncdc** [comment]
* 0.8 🎉 
* README hackmd: https://hackmd.io/-YpPqiVsQZyiPIjyoxLiKw?both

**Comment by philbrookes** [comment]
https://github.com/kcp-dev/kcp/issues/1891

**Comment by davidfestal** [comment]
Split of EPIC [Multi-Release-Epic: Consume Compute via Transparent Multi Cluster set up in a different workspace](https://github.com/kcp-dev/kcp/issues/912).
Some remaining issues moved to new epics:
- [Compute type Management](https://github.com/kcp-dev/kcp/issues/1895)
- [Support for multiple SyncTargets syncing and coordination controllers](https://github.com/kcp-dev/kcp/issues/1898)

**Comment by ncdc** [comment]
Recording: https://www.youtube.com/watch?v=6zK66ajsZPI
