### ISSUE TITLE
Cascading deletion not working - need to enable the garbage collection controller

### ISSUE THREAD

**Issue by lburgazzoli** [kcp-dev/kcp#191]
**Describe the bug**
I'm experimenting with [camel-k](https://camel.apache.org/camel-k/latest/index.html) to get it working with KCP as a Kubernetes control plane and I noticed that as opposite as when running on a "classic" Kubernetes cluster, when a camel-k custom resource is deleted, the related CRs and standard Kubernetes created by the camel-k operator are not automatically delete. 

As example, following a creation of a `KameletBinding` CR, the camel-k operator creates the following resources and Kubernetes objects all linked by using owner references:

- `Integration`
- `Secret`
- `ConfigMap`
- `Deployment`

But when the `KameletBinding` is gets deleted, the other CRs and standard Kubernetes are not deleted.

**Expected behavior**
When cascading deletion is used, KCP should delete the object's dependents automatically.

**Comment by pweil-** [comment]
@ncdc do you want to leave this open (maybe with a retitle) as a reminder to enable gc at a later date or can it be closed?

**Comment by ncdc** [comment]
Need to leave it open

**Comment by pweil-** [comment]
ack, thanks for reviewing
