### ISSUE TITLE
Revisit "creating a workspace under a universal type workspace is not supported" error

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#1932]
From https://github.com/kcp-dev/kcp/blob/8e8e985b5f57e0d8522f93e0380d95a1186c8bab/pkg/cliplugins/workspace/plugin/kubeconfig.go#L465

The error message is not necessarily correct any more, as universal workspaces can/do support child workspaces.

**Comment by xrstf** [comment]
The offending code has been removed in #2562.
