### ISSUE TITLE
bug: It's Possible to Break Our Generated API Resource Schemas

### ISSUE THREAD

**Issue by stevekuznetsov** [kcp-dev/kcp#1938]
### Describe the bug

If you change the Go types and also change the generated `APIResourceSchemas` to perfectly match what the generator would have created, the result is that the generator won't know that the name of the APIRS needs to be bumped (generated values are equal to previous on-disk values).

### Steps To Reproduce

Update a comment on a type. Update the API Resource Schema to have the new comment. Run `make codegen` and see no changes.

### Expected Behaviour

If you change the body of a generated APIRS but not the name, something should fix that for you.

**Comment by stevekuznetsov** [comment]
cc @ncdc

**Comment by ncdc** [comment]
At the very least, we should have CI verify that if a generated APIResourceSchema has diffs, metadata.name is included
