### ISSUE TITLE
Standalone run of kcp complaints about failing to list v1.Service and v1.Endpoint resources

### ISSUE THREAD

**Issue by karolz-ms** [kcp-dev/kcp#194]
### To Reproduce
1. build and run cmd/kcp
2. Watch the output

### Expected behavior
No errors in the output

### Actual behavior
Repeated errors like

```shell
E1028 09:29:31.971025   21064 reflector.go:138] k8s.io/client-go@v0.0.0-20211004150937-c954268bf177/tools/cache/reflector.go:167: Failed to watch *v1.Service: failed to list *v1.Service: the server could not find the requested resource
E1028 09:29:33.665019   21064 reflector.go:138] k8s.io/client-go@v0.0.0-20211004150937-c954268bf177/tools/cache/reflector.go:167: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: the server could not find the requested resource
```

### Additional context

This happens because "AvailableConditionController" that is part of API Aggregator server [is trying to list v1.Services and v1.Endpoints](https://github.com/kcp-dev/kubernetes/blob/feature-logical-clusters-1.22/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go#L263), but these API resources are not part of default resource mix when KCP is started. So either Services and Endpoint resources should be installed by default, or the AvailableConditionController should be an opt-in component, one that is not on by default.

**Comment by ncdc** [comment]
This was fixed first by kcp-dev/kubernetes#16 and then by switching away from using kube-aggregator.
