### ISSUE TITLE
feature: Build Tooling To Automatically Migrate Users to Cluster-Aware Clients

### ISSUE THREAD

**Issue by stevekuznetsov** [kcp-dev/kcp#1944]
### Feature Description

When we merge in the cluster-aware clients from https://github.com/kcp-dev/kcp/issues/1943 , we're going to incur a huge refactoring cost. Furthermore, when any controller author attempts to migrate their single-cluster-context controller or program to kcp, they will incur the same cost. This can be done programatically and should be automated.

### Proposed Solution

As an author of a pre-existing controller in a single-cluster-context
I want to migrate to using cluster-aware clients using a tool, without manual refactoring
So that my onboarding onto kcp is seamless and easy.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by stevekuznetsov** [comment]
https://github.com/kcp-dev/code-generator/pull/53

**Comment by ncdc** [comment]
I don't believe this is a blocker for v0.10; moving to v0.11
