### ISSUE TITLE
Community Meeting September 13, 2022

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#1946]
At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/mpd-cypd-sdp
Or dial: ‪(DE) +49 30 300195060‬ PIN: ‪500 599 130 5702‬#
More phone numbers: https://tel.meet/mpd-cypd-sdp?pin=5005991305702
Or join via SIP: sip:[5005991305702@gmeet.redhat.com](mailto:5005991305702@gmeet.redhat.com)

Meeting recordings available on YouTube at https://www.youtube.com/channel/UCfP_yS5uYix0ppSbm2ltS5Q

This issue will collect prospective agenda topics.

**Comment by sttts** [comment]
How to get to better user docs

Some thoughts from Slack https://kubernetes.slack.com/archives/C021U8WSAFK/p1662735653971629:
- avoid silos and low bus factors
- we desperately need user-facing docs
- we need cross-discipline doc review
- well written user docs are hard, and doc days are not enough.  User docs shouldn't be a side-effect or do-it-later of development.

**Comment by sttts** [comment]
Incoming issues: https://github.com/kcp-dev/kcp/issues?q=is%3Aopen+is%3Aissue+-label%3Acommunity-meeting+no%3Amilestone

Milestone epics: https://github.com/kcp-dev/kcp/issues?q=is%3Aopen+is%3Aissue+label%3Amilestone-blocker+label%3Aepic

**Comment by pweil-** [comment]
public site contributions https://github.com/kcp-dev/kcp/issues/1950

**Comment by sttts** [comment]
Propsal: TBD milestone -> project "in progress"

**Comment by ncdc** [comment]
Recording https://www.youtube.com/watch?v=gcvaXw_7LaI
