### ISSUE TITLE
feature: kcp public site

### ISSUE THREAD

**Issue by pweil-** [kcp-dev/kcp#1950]
### Feature Description

Let's decide on how we will contribute and build to a public site to start providing better visibility into our project.  Opening this issue to record decisions.  

Please also note that https://github.com/kcp-dev/kcp.io repo has been created as a suggestion of where we could accept contributions since that is a common pattern in communities already.

### Proposed Solution

Make the site!

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by sttts** [comment]
Next to the main site, there is the side topic: user documentation and API reference docs. Most other projects have both of them in the same system, e.g. using https://gohugo.io/ and one of the API reference generators. Hugo afaik is by far the most common solution for open source projects these days.

**Comment by ncdc** [comment]
cluster-api hosts via netlify (https://github.com/kubernetes-sigs/cluster-api/blob/main/netlify.toml) and uses mdbook (https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/book/Makefile). (I don't have any preferences for what we use to generate.)

**Comment by stevekuznetsov** [comment]
I've had good experiences with netlify + hugo in the past.

**Comment by sttts** [comment]
@stevekuznetsov Why not github pages? Probably gets us going much quicker.

**Comment by stevekuznetsov** [comment]
It took a previous team ~3h to bootstrap those two, but any approach is fine honestly.

**Comment by sttts** [comment]
x-ref some content gathering for the front-page https://docs.google.com/document/d/1kyKgZXnkolvLB-mrDbeQB0FmJY4k63LaY8IzrjLf-GQ/edit#heading=h.9kwldvxi5zq7

**Comment by andybraren** [comment]
I vaguely remember the KubeVirt and Metal3 communities debating GH Pages/Jekyll, Netlify, maybe Hugo, etc.

@matthewcarleton do you remember anything related to those that might be worth considering for KCP's site?

Examples:
* http://kubevirt.io
* https://metal3.io
* https://open-cluster-management.io

**Comment by matthewcarleton** [comment]
ya I've been a couple of these sites. They're not all using the same stuff so I can't say what the recommendation is. Netlify is pretty common across all of them though. 
How does redhat.com factor in here? Aren't we trying to keep everything central there now?

**Comment by andybraren** [comment]
@matthewcarleton Thanks! And this'll be a site for the KCP community, outside of Red Hat.

**Comment by ncdc** [comment]
Closing as the web site is live. Let's file new issues if needed for any future work.
/close
