### ISSUE TITLE
Setup a root compute workspace where global compute APIExports will live,

### ISSUE THREAD

**Issue by qiujian16** [kcp-dev/kcp#1959]
### Feature Description

for transparent workload service, we should have a global APIExport defining kubernetes apis.

### Proposed Solution

create a root:compute workspace, and kubernetes APIExport in it. The schema should include ingress/service/deployment as the minimum. 

### Want to contribute?

- [X] I would like to work on this issue.

**Comment by qiujian16** [comment]
still have some questions about this:
1. should we create a specific workspace type for this workspace? 
2. RBAC requirement?

**Comment by stevekuznetsov** [comment]
Let's keep it simple to start. If we end up with N workspaces like this and they share some functionality we can pull into a type, so be it.

**Comment by davidfestal** [comment]
> Let's keep it simple to start. If we end up with N workspaces like this and they share some functionality we can pull into a type, so be it.

Yeah, that was my thought as well, but I don't want to exclude that, for various reasons, as security / restriction reasons for this internal "read-only" workspace, a dedicated CWT and specific RBAC rules would be required.
Of course this could possibly be done in a dedicated issue later on.
cc @sttts

**Comment by stevekuznetsov** [comment]
Why would a CWT be required? Wouldn't bootstrapping some RBAC be sufficient on startup?

**Comment by sttts** [comment]
There is one compute workspace. No need for a type, no need for special RBAC beyond that everybody can bind the export.

**Comment by sttts** [comment]
> Why would a CWT be required? Wouldn't bootstrapping some RBAC be sufficient on startup?

Yes, pure bootstrapping of that workspace within `kcp start` is enough. And I would call that a "battery included" and make it possible to disable it. In a prod deployment one likely does not want to have it pre-created.
