### ISSUE TITLE
Add the global `kubernetes` APIExport by default in the SyncTarget `supportedAPIExports`

### ISSUE THREAD

**Issue by davidfestal** [kcp-dev/kcp#1960]
- Remove the default value in the `SyncTarget` API for field `supportedAPIExports`
- Keep the `--resource` argument for now in the `workload sync` CLI command
- Update the `workload sync` CLI to specify a list of supported `apiexport`s, and add them in the `supportedAPIExports` field of the applied `SyncTarget`
- In an admission controller, add the global and local `kubernetes` `APIExport`s in the `supportedAPIExport` field of the `SyncTarget`, if the field is empty.
- Modify the [workload_apiexport_reconcile.go](https://github.com/davidfestal/kcp/blob/identity-strategy-in-syncer-virtual-workspace/pkg/reconciler/workload/apiexport/workload_apiexport_reconcile.go) controller to only add the resources that are *not* part of the global `kubernetes` APIExport and at least one SyncTarget of the location workspace supports the global kubernetes APIExport
- Modify the [defaultplacement_controller.go](https://github.com/davidfestal/kcp/blob/identity-strategy-in-syncer-virtual-workspace/pkg/reconciler/workload/defaultplacement/defaultplacement_controller.go#L225) to add a binding to the global `kubernetes` APIExport when there is the binding to the local `kubernetes` `APIExport` and at least one `SyncTarget` of the location workspace supports the global `kubernetes` `APIExport`.
- In the CLI add in the generated YAML the required RBAC based on the GVRs of the `supportedAPIExports` field of the applied `SyncTarget`, potentially filled by the admission controller during creation

**Comment by qiujian16** [comment]
When we default the global kubernetes apiexport in synctarget, we would also need to remove the `--resources` flag in syncer. That will change the user experience when installing syncer:

Currently `kubectl kcp workload sync` has `--resources` flag also, we cannot directly remove this flag, since it also sets the correct rbac for syncer on physical cluster. 

Should we use another flag to specifically set the permission? It could be letting user to specify a maximal list of resources that the syncer suppose to sync, or a clusterrole that syncer should bind.

**Comment by davidfestal** [comment]
> When we default the global kubernetes apiexport in synctarget, we would also need to remove the `--resources` flag in syncer. That will change the user experience when installing syncer:
> 
> Currently `kubectl kcp workload sync` has `--resources` flag also, we cannot directly remove this flag, since it also sets the correct rbac for syncer on physical cluster.
> 
> Should we use another flag to specifically set the permission? It could be letting user to specify a maximal list of resources that the syncer suppose to sync, or a clusterrole that syncer should bind.

In a next PR, we would effectively add the `--exports` argument in the CLI. In this case we would add the correct RBAC for all the GVR related to the `exports` passed to the command line. And if none is passed, we would create the correct RBAC for the resources associated with the default global APIExport (`kubernetes`).
