### ISSUE TITLE
bug: user loses access to workspace being deleted if content has finalizers remaining

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#1964]
### Describe the bug

When deleting a workspace, if any of the content in the workspace, its namespaces, its subworkspaces, etc. has finalizers, it may take time for all the content to be deleted. Or sometimes the finalizers might never be removed (for whatever reason).... this is all fine, except our workspace deletion logic deletes the owner ClusterRole and ClusterRoleBinding as soon as the delete-workspace requests succeeds (which usually happens, as it just sets the deletion timestamp).

As a result, the user will be able to see their workspace is terminating/still being deleted, but they won't be able to access any content in the workspace to see why it's "stuck".

### Steps To Reproduce

1. Go to your home workspace
2. Create a child workspace
3. In the child workspace, add a finalizer to a resource
4. Back in the home workspace, delete the child workspace
5. See the workspace is being deleted
6. Try to use the child workspace and then do anything, e.g. `kubectl api-resources`
7. You won't see any APIs

### Expected Behaviour

User still has access to child workspace

**Comment by hasheddan** [comment]
@ncdc I'd be happy to pick this one up

**Comment by ncdc** [comment]
@hasheddan go for it! Happy to discuss first if you'd like for how to approach (I'll admit I haven't thought about it yet).

/assign @hasheddan

**Comment by hasheddan** [comment]
Thanks @ncdc! It looked like there was a relatively lightweight option for providing a solution here, so I went ahead and opened https://github.com/kcp-dev/kcp/pull/2113 which I am happy to discuss on!
