### ISSUE TITLE
Shard the kcp Control Plane

### ISSUE THREAD

**Issue by stevekuznetsov** [kcp-dev/kcp#1999]
`kcp` bring a lot of value from being one unified control plane. This will require a sharded deployment, whether it's to drive availability & resiliency across regions/geographies, or to facilitate scaling needs inside of one region.

Tasks for this epic are tracked in [this](https://github.com/orgs/kcp-dev/projects/1/views/44) project view.

**Comment by mjudeikis** [comment]
/close
will replan
