### ISSUE TITLE
bug: single character lowercase workspace names are valid

### ISSUE THREAD

**Issue by markmc** [kcp-dev/kcp#2018]
Create workspaces `root:foo:bar`, all good!

```
$ kubectl get workspaces
NAME    TYPE       PHASE   URL
users   homeroot   Ready   https://10.8.1.136:6443/clusters/root:users

$ kubectl ws .
Current workspace is "root".

$ kubectl ws create --enter foo
Workspace "foo" (type root:organization) created. Waiting for it to be ready...
Workspace "foo" (type root:organization) is ready to use.
Current workspace is "root:foo".

$ kubectl ws create --enter bar
Workspace "bar" (type root:universal) created. Waiting for it to be ready...
Workspace "bar" (type root:universal) is ready to use.
Current workspace is "root:foo:bar".
```

Try to repeat with `root:a:b` - you can do it, but get weird errors!

```
$ kubectl ws root
Current workspace is "root".

$ kubectl ws create --enter a
Workspace "a" (type root:organization) created. Waiting for it to be ready...
Workspace "a" (type root:organization) is ready to use.
Current workspace is the URL "https://10.8.1.136:6443/clusters/root:a".

$ kubectl ws create --enter b
Error: current URL "https://10.8.1.136:6443/clusters/root:a" does not point to cluster workspace

$ kubectl apply -f - <<EOF
apiVersion: tenancy.kcp.dev/v1beta1
kind: Workspace
metadata:
  name: b
spec:
  type:
    name: universal
    path: root
EOF
workspace.tenancy.kcp.dev/b created

$ kubectl ws b
Error: current URL "https://10.8.1.136:6443/clusters/root:a" does not point to cluster workspace

$ kubectl ws root:a:b
Error: current URL "https://10.8.1.136:6443/clusters/root:a" does not point to cluster workspace

$ kubectl ws -
Current workspace is "root".

$ kubectl ws root:a:b
Current workspace is the URL "https://10.8.1.136:6443/clusters/root:a:b".

$ kubectl ws root
Error: current URL "https://10.8.1.136:6443/clusters/root:a:b" does not point to cluster workspace

$ kubectl ws -
Current workspace is "root".

$ kubectl get workspaces
NAME    TYPE           PHASE   URL
a       organization   Ready   https://10.8.1.136:6443/clusters/root:a
foo     organization   Ready   https://10.8.1.136:6443/clusters/root:foo
users   homeroot       Ready   https://10.8.1.136:6443/clusters/root:users
```

The restriction comes from:

```
lclusterRegExp = regexp.MustCompile(`^[a-z0-9][a-z0-9-]*[a-z0-9](:[a-z0-9][a-z0-9-]*[a-z0-9])*$`)
```

Which was first introduced in commit 68f4e6d7 via kcp-dev/kcp#744 and has since proliferated to kcp-dev/logicalcluster

and we seem pretty determined that single-character workspace names are not valid:

```
        tests := []struct {
                name  string
                valid bool
        }{
                {"elephant:foo", true},
                ...
                {"elephant:a", false},
```

But what exactly is allowed?

```
But what should it be?

$ kubectl apply -f - <<EOF
apiVersion: tenancy.kcp.dev/v1beta1
kind: Workspace
metadata:
  name: A
spec:
  type:
    name: organization
    path: root
EOF
The ClusterWorkspace "A" is invalid:
* metadata.name: Invalid value: "A": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'exam\
ple.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
* metadata.name: Invalid value: "A": metadata.name in body should match '^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$'
```

It seems it's RFC 1035 label names only ? i.e. must start with a lowercase alphabetic character? See https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names

**Comment by stevekuznetsov** [comment]
@sttts unless you have some larger context for us to worry about, I think the fix proposed by @markmc seems reasonable?

@markmc thank you for taking the time to dig into this! I think this is what we dream every bug report would look like, right? :)

**Comment by ncdc** [comment]
I'd like a few minutes to dig into this to make sure everything ends up consistent, will report back in a bit

**Comment by ncdc** [comment]
Ok, there are 2 validations at play here:

```
* metadata.name: Invalid value: "A": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

This comes from https://github.com/kcp-dev/kubernetes/blob/eeba459ad2a11c1472a84f0b33042d9c479c6aeb/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L215 and is the standard validation that applies to all metadata.name values for custom resources.

```
* metadata.name: Invalid value: "A": metadata.name in body should match '^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$'
```

This comes from kcp: https://github.com/kcp-dev/kcp/blob/b583994d0ccd7aecae7410dbda9608b674ffeb58/config/crds/tenancy.kcp.dev_workspaces.yaml-patch

We need to align everything so it's consistent. I think the only thing that's not is `lclusterRegExp` in pkg/apis/tenancy/v1alpha1/helper/helper.go?

**Comment by markmc** [comment]
The other issue I notice is that a name with a beginning with `0-9` is allowed for things like namespaces, but we're rejecting it for workspaces

```
$ kubectl apply -f ns.yaml
namespace/0ns created
$ kubectl apply -f ws.yaml
The ClusterWorkspace "0ws" is invalid: metadata.name: Invalid value: "0ws": metadata.name in body should match '^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$'
```

It's an easy fix if we're agreed there's no reason for us to be rejecting these?

**Comment by ncdc** [comment]
Do we expect that a workspace's `metadata.name` would ever be used as part of a routable DNS entry? @sttts

**Comment by sttts** [comment]
> Do we expect that a workspace's metadata.name would ever be used as part of a routable DNS entry? @sttts

We have no choice. Kube decided long ago that a CRD is a RFC 1123 label. But I wasn't aware that digits are allowed at the beginning of such a label:

```
const dns1123LabelFmt string = "[a-z0-9]([-a-z0-9]*[a-z0-9])?"
```

Am not aware of technical reasons why we cannot allow digits as first character. No strong opinions.

**Comment by ncdc** [comment]
Rephrase: do we need the workspace name to be part of a DNS domain/subdomain such that it's part of a DNS query? i.e. `<somews>.something.example.io/api/v1/configmaps`
