### ISSUE TITLE
Community Meeting Sept 20, 2022

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#2035]
At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/mpd-cypd-sdp
Or dial: ‪(DE) +49 30 300195060‬ PIN: ‪500 599 130 5702‬#
More phone numbers: https://tel.meet/mpd-cypd-sdp?pin=5005991305702
Or join via SIP: sip:[5005991305702@gmeet.redhat.com](mailto:5005991305702@gmeet.redhat.com)

Meeting recordings available on YouTube at https://www.youtube.com/channel/UCfP_yS5uYix0ppSbm2ltS5Q

This issue will collect prospective agenda topics.

**Comment by sttts** [comment]
Incoming issues: https://github.com/kcp-dev/kcp/issues?q=is%3Aopen+is%3Aissue+-label%3Acommunity-meeting+no%3Amilestone – https://github.com/orgs/kcp-dev/projects/1/views/22

Milestone epics: https://github.com/kcp-dev/kcp/issues?q=is%3Aopen+is%3Aissue+label%3Amilestone-blocker+label%3Aepic

**Comment by sttts** [comment]
kcp.io front page content gathering https://docs.google.com/document/d/1kyKgZXnkolvLB-mrDbeQB0FmJY4k63LaY8IzrjLf-GQ/edit#heading=h.9kwldvxi5zq7

**Comment by stevekuznetsov** [comment]
- logging update #1694 
- keyfunc update #1958

**Comment by pweil-** [comment]
milestone reminder
