### ISSUE TITLE
bug: Resourcequotas can't be claimed

### ISSUE THREAD

**Issue by fgiloux** [kcp-dev/kcp#2052]
### Describe the bug

APIBinding fails when trying to claim resourcequotas:

~~~
  - lastTransitionTime: "2022-09-22T09:41:22Z"
    message: '1 unexpected and/or invalid permission claims (showing first 1): unexpected/invalid
      claim for resourcequotas. (identity "")'
    reason: InvalidPermissionClaims
    severity: Error
    status: "False"
    type: PermissionClaimsValid
~~~

### Steps To Reproduce

1. Create an APIExport claiming a resourcequota
2. Create an APIBinding to the APIExport accepting the resourcequota
3. See that the claim fails
4. The controller does not get notified of changes made to resourcequotas

### Expected Behaviour

The claim succeeds
The controller gets notified of the changes made to resourcequotas

### Additional Context

APIExport
~~~
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: configuration.pipeline-service.io
spec:
  latestResourceSchemas:
    - today.settings.configuration.pipeline-service.io
  permissionClaims:
  - group: "apis.kcp.dev"
    resource: "apibindings"
  - group: "networking.k8s.io"
    resource: networkpolicies
    # identityHash needs to match the export of the workload cluster
    identityHash: "a1171f89c2274572ac14ee99f6f733069ae14ce41db83ba550da58e8f4802b72"
  - group: ""
    resource: "resourcequotas"
  - group: ""
    resource: "namespaces"
~~~

APIBinding
~~~
apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: settings-configuration.pipeline-service.io
spec:
  reference:
    workspace:
      exportName: settings-configuration.pipeline-service.io
      # the path needs to match the location of the apiexport
      path: root:pipeline-service:management
  permissionClaims:
  - group: "apis.kcp.dev"
    resource: "apibindings"
    state: Accepted
  - group: "networking.k8s.io"
    resource: networkpolicies
    state: Accepted
    # identityHash needs to match the export of the workload cluster
    identityHash: "a1171f89c2274572ac14ee99f6f733069ae14ce41db83ba550da58e8f4802b72"
  - group: ""
    resource: "resourcequotas"
    state: Accepted
  - group: ""
    resource: "namespaces"
    state: Accepted
~~~

**Comment by fgiloux** [comment]
Adding
~~~
{
		Names: apiextensionsv1.CustomResourceDefinitionNames{
			Plural:   "resourcequotas",
			Singular: "resourcequota",
			Kind:     "ResourceQuota",
		},
		GroupVersion:  schema.GroupVersion{Group: "", Version: "v1"},
		Instance:      &corev1.ResourceQuota{},
		ResourceScope: apiextensionsv1.NamespaceScoped,
	},
~~~
to the list of internal resources seem to fix the issue

**Comment by ncdc** [comment]
@stevekuznetsov do you want to look at this or assign?

**Comment by ncdc** [comment]
Note, https://github.com/kcp-dev/kcp/blob/3c4e7937b80aac7b2f20878393e957417702969a/pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go#L300 already has ResourceQuotas. Need to dig into why it's not working for you.

**Comment by stevekuznetsov** [comment]
@fgiloux do you have logs from the `kcp` API server here?

**Comment by fgiloux** [comment]
I tested twice with a fresh new install (latest version of main branch) and it worked. I am not sure what I did wrong yesterday and how I managed to get this:
~~~
 - lastTransitionTime: "2022-09-22T09:41:22Z"
    message: '1 unexpected and/or invalid permission claims (showing first 1): unexpected/invalid
      claim for resourcequotas. (identity "")'
    reason: InvalidPermissionClaims
    severity: Error
    status: "False"
    type: PermissionClaimsValid
~~~

Also I saw yesterday that other people had similar issues with apibindings referencing other resources (with identityhash), deleting the apibinding and recreating it (identical) solved the issue with the claim. For them the first creation was done with a service account the second one with the cluster admin user and I thought it may have been the reason. I am not so sure anymore.

Anyways, I am happy with closing this issue as I can't reproduce except if you want to keep it open for further investigation.

**Comment by fgiloux** [comment]
@stevekuznetsov sorry I don't have my logs anymore. However I have the entry on the kcp side for the other person having a similar issue (but not knowing if it is the same):
~~~
E0922 17:29:01.123660       1 permissionclaim_labeler.go:103] "error getting APIBinding" err="apibinding.apis.kcp.dev \"root:default:pipeline-service-compute|jvmbuildservice-binding\" not found" bindingName="jvmbuildservice-binding"
~~~
At the time I did check and there was an apibinding called jvmbuildservice-binding in the workspace root:default:pipeline-service-compute

**Comment by nrb** [comment]
Closing for now, but if you re-encounter it, please reopen and provide logs.
