### ISSUE TITLE
Design & Implement Cross-Cluster Listers and Informers

### ISSUE THREAD

**Issue by stevekuznetsov** [kcp-dev/kcp#209]
Right now, a cross-cluster informer can be created by simply passing in a cross-cluster client (using `*`) for the source client in constructor. As the `MetaNamespaceKeyFunc()` is already cluster-aware, all of the internal machinery seems to work correctly.

On the consumer end, though, we need to:
- expose a simple splitter func for the cluster/namespace/name
- expose new interfaces for listing that are first clustered, then namespaced, then named, eg.:

```go
cluster, namespace, name, err := cache.SplitMetaClusterNamespaceKey(key) // or whatever
obj, err := c.lister.Cluster(cluster).ObjectType(namespace).Get(name)
```

/cc @ncdc

**Comment by ncdc** [comment]
client-go's hand-written base code for the cache store and shared index informers all are written based on a hard-coded key function that only knows how to encode an object's namespace (optionally) and name. The generated informers and listers follow from this, therefore only supporting namespace and name.

Do we want to...

1. change the key funcs to assume <cluster, namespace, name> always (i.e. force k/k to support logical clusters)?
2. hack this on top of client-go (i.e. in kcp) with our own generators that can generate informers & listers that support logical clusters?
3. some other option?

@smarterclayton @sttts any thoughts?

**Comment by stevekuznetsov** [comment]
I think we must do something on top - a user of the listers that is not cluster aware should not need to know that the key they are using will contain cluster information, especially since naive clients will be within one lcluster anyway.

**Comment by ncdc** [comment]
Also worth remembering that in our kube fork, we have made a change to `cache.MetaNamespaceKeyFunc` to include the cluster name as part of the name segment. At the very least, this has to be resolved & finalized for going back into upstream kube, even if we don't have direct support for informers/listers that are logical cluster aware.

**Comment by sttts** [comment]
Question is also how to opt into the "*" behaviour. If cross-shard client access is only possible through a virtual workspace, the default behaviour with empty cluster name could be cross-shard. So the user actually opts into queries for specific shards.

**Comment by stevekuznetsov** [comment]
I guess as a straw-man, I expect:

- a new pair of funcs to encode and decode a cluster-aware key
- the ability to configure the func used in the reflector/store
- explicit opt-in to a cross-cluster lister and informer by using the cross-cluster client

Without explicit choice, no client call will ever cross cluster boundaries.

**Comment by pweil-** [comment]
0.8 check in here.  Still on track to land in 0.8?

**Comment by stevekuznetsov** [comment]
This requires #1813 ... hard maybe.

**Comment by stevekuznetsov** [comment]
There's a rough design doc [here](https://docs.google.com/document/d/12RtZL9rnEYGYUjhkZbxc_qbXSuUFULuRXArpJvoqOo4/edit#heading=h.uts53tyl4jgs) and a draft/WIP PR [here](https://github.com/kcp-dev/apimachinery/pull/53)

**Comment by stevekuznetsov** [comment]
OK, rough items to do:

 - [ ] update the generator to create cluster-aware listers and informers "on top" of other generated clients (like for k8s client-go) in a way that users who choose to generate those, do NOT need to pass around cluster-unaware types and cast
 - [ ] publish the above for k8s client-go in `kcp-dev/client-go`
 - [ ] update the AST refactor tool to move from k8s client -> kcp client (making sure `clusterName` gets passed around will likely be impossible with any fidelity)
 - [ ] use the above tool to move kcp reconcilers over

**Comment by stevekuznetsov** [comment]
We need a refactor to grab the cluster from the controller-runtime key and to inject it into controller-runtime requests as well. For that we need to refactor the controller-runtime client request object I think.
