### ISSUE TITLE
Community Meeting October 11, 2022

### ISSUE THREAD

**Issue by clubanderson** [kcp-dev/kcp#2128]
### Overview

At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/mpd-cypd-sdp
Or dial: ‪(DE) +49 30 300195060‬ PIN: ‪500 599 130 5702‬#
More phone numbers: https://tel.meet/mpd-cypd-sdp?pin=5005991305702
Or join via SIP: sip:5005991305702@gmeet.redhat.com

Meeting recordings available on YouTube at https://www.youtube.com/playlist?list=PLqN7RcoCwL96nXIIW6O51l8Lu_J-f5D27

Add topics you'd like to discuss below!

**Comment by clubanderson** [comment]
Incoming issues: https://github.com/kcp-dev/kcp/issues?q=is%3Aopen+is%3Aissue+-label%3Acommunity-meeting+no%3Amilestone – https://github.com/orgs/kcp-dev/projects/1/views/22

Milestone epics: https://github.com/kcp-dev/kcp/issues?q=is%3Aopen+is%3Aissue+label%3Amilestone-blocker+label%3Aepic

**Comment by clubanderson** [comment]
- Edge workload distribution using location, placement, deployment, kustomize (15 min)

**Comment by s-urbaniak** [comment]
reverse permission claims: https://docs.google.com/presentation/d/1u3YY71GXUxJAIqrrIlFYGrFYM1B0ZbFMpl0VQmDqSOA/edit#slide=id.g1648e8bbd33_0_0

**Comment by stevekuznetsov** [comment]
fake clients: https://github.com/kcp-dev/kcp/issues/2167

**Comment by nrb** [comment]
Reverse permission claims presented by @s-urbaniak: https://docs.google.com/presentation/d/1u3YY71GXUxJAIqrrIlFYGrFYM1B0ZbFMpl0VQmDqSOA/edit#slide=id.g1648e8bbd33_0_0

WIP PR: https://github.com/kcp-dev/kcp/pull/2089

Related issue for object selection for permissionclaims: https://github.com/kcp-dev/kcp/issues/1937

**Comment by stevekuznetsov** [comment]
From Paolo, about TMC use-cases:

- think through a more resilient connection between the syncer and kcp, to allow for network fragmentation or disconnected states
- allow scheduling one workload to N placements/locations, perhaps with placement-specific edits (https://github.com/kcp-dev/kcp/issues/752)
- allow opting kcp-scheduled workloads out of connections back to kcp itself
- ensure that scaling limits for `SyncTargets` can support O(10k) compute clusters
