### ISSUE TITLE
bug: softimpersonation has likely mutation issues

### ISSUE THREAD

**Issue by stevekuznetsov** [kcp-dev/kcp#2136]
### Describe the bug

https://github.com/kcp-dev/kcp/blob/main/pkg/softimpersonation/softimpersonation.go#L39

@enj says that `.Wrap` below this line might mutate the original config, and the round tripper mutates the original request. This might cause errors and we should look into it.

### Steps To Reproduce

na

### Expected Behaviour

na

**Comment by stevekuznetsov** [comment]
cc @s-urbaniak @sttts

**Comment by s-urbaniak** [comment]
`.Wrap` mutates the `WrapTransport` of the given config. This should be covered as part of the shallow copy, however I am submitting a PR which uses `rest.CopyConfig` to have a guaranteed deep copy of the original config.
