### ISSUE TITLE
feature: Display the tree of the workspaces from root or sub-level

### ISSUE THREAD

**Issue by cmoulliard** [kcp-dev/kcp#2165]
### Feature Description

As I user managing the workspaces on a kcp control plane, I would be interested to display as a tree the workspaces starting from root or a `level` passed as parameter.

### Proposed Solution

Add a new command to `kubectl kcp ws` such as `kubectl kcp ws tree`, `kubectl kcp ws tree --level <level>` 

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by nrb** [comment]
What would the value be for `kubectl kcp ws tree --level <level>`, a workspace name? Or a number?

**Comment by cmoulliard** [comment]
> What would the value be for `kubectl kcp ws tree --level <level>`, a workspace name? Or a number?

One of the level name. Example: `kcp-admin`

**Comment by ncdc** [comment]
Maybe we could do an option `--from PATH` e.g. `k ws tree --from root:my-org`?

**Comment by cmoulliard** [comment]
I like a lot `--from` :-)

**Comment by andybraren** [comment]
I can imagine API-level support for this being useful for GUIs as well.

**Comment by mjudeikis** [comment]
API story really depends where we go with the discussion from @sttts for flattening workspaces and keeping stucture only in proxy layer as metadata (if I got the idea right). In that case API is bit complicated.
