### ISSUE TITLE
feature: Add status column to APIBinding/APIExports CLI

### ISSUE THREAD

**Issue by mjudeikis** [kcp-dev/kcp#2182]
### Feature Description

There are multiple improvments in flight at the moment to add better status reporting to APIExport and APIBindings as such.

Current behaviour of those object can lead to partially working component (lack of identity, informers issues, etc).

In proper production environments this should be picked by monitoring tools, but in development sometimes its hard to pick-up if something failed.

### Proposed Solution

Add status field into CLI get command of those components. Quick win, and will give insights into component health.

### Want to contribute?

- [X] I would like to work on this issue.

**Comment by ncdc** [comment]
What specific data from status would you include?

**Comment by mjudeikis** [comment]
Ready/not ready condition aggregate. So if we get false possitive - we fix
conditions :)
