### ISSUE TITLE
Community Meeting November 1, 2022

### ISSUE THREAD

**Issue by clubanderson** [kcp-dev/kcp#2229]
### Overview

At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/mpd-cypd-sdp
Or dial: ‪(DE) +49 30 300195060‬ PIN: ‪500 599 130 5702‬#
More phone numbers: https://tel.meet/mpd-cypd-sdp?pin=5005991305702
Or join via SIP: sip:5005991305702@gmeet.redhat.com

Meeting recordings available on YouTube at https://www.youtube.com/playlist?list=PLqN7RcoCwL96nXIIW6O51l8Lu_J-f5D27

Add topics you'd like to discuss below!

EDIT (nrb): Adding issue dashboards.

Incoming issues: https://github.com/orgs/kcp-dev/projects/1/views/22

Milestone epics: https://github.com/kcp-dev/kcp/issues?q=is%3Aopen+is%3Aissue+label%3Amilestone-blocker+label%3Aepic

**Comment by clubanderson** [comment]
Introduction of SIG-Edge working group (Paolo, Mike, Ezra).  Call for participants.

**Comment by nrb** [comment]
FYI, we'll be cancelling the November 2, 2022 meeting for Kubecon. [See Slack](https://kubernetes.slack.com/archives/C021U8WSAFK/p1666272534955959).

Let's repurpose this issue for the following week, November 9.

**Comment by clubanderson** [comment]
in the slack I see that next Tuesday is cancelled which is Oct. 25th.  This agenda should be used for Nov 1st which is not cancelled.  Please advise @nrb

**Comment by nrb** [comment]
Ack, you're right, my mistake :)

**Comment by stevekuznetsov** [comment]
Strongly-typed cluster-aware clients, listers & informers

**Comment by fgiloux** [comment]
Discussing the options for the discovery and selection of kcp shards by controller manager instances (the processes spawning controllers and informers). Here is the [current state of investigation](https://docs.google.com/document/d/1zI9KOpLp6H_tAcKpGbLpQu_iUK9VbpgUSo0OFEd7Mig/edit#).

**Comment by nrb** [comment]
[Narrowly-scoped permission claims](https://docs.google.com/document/d/1IHai7FlVQXPCD_MZObT0CzAkdOFSZuWGokHa_kn72HQ/edit#) doc. Issue #1937

**Comment by stevekuznetsov** [comment]
#2196 before we cut the next release?
