### ISSUE TITLE
Race in Autoregister Controller Startup

### ISSUE THREAD

**Issue by stevekuznetsov** [kcp-dev/kcp#225]
Very infrequently when starting `kcp`, I see:

```
E1119 15:27:58.467926 1269340 autoregister_controller.go:197] clusters.cluster.example.dev#$#v1alpha1.cluster.example.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:58.468550 1269340 autoregister_controller.go:197] apiresourceimports.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:58.468592 1269340 autoregister_controller.go:197] negotiatedapiresources.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
```

Full logs (I sent `SIGINT` midway, when we cancel all and the stacktraces begin):

<details>
<summary><code>kcp.log</code></summary>
<code>
$ make build && rm -rf .kcp/ && ./bin/kcp start --install_cluster_controller
go build -o bin ./cmd/...
I1119 15:27:56.192827 1269340 etcd.go:40] Creating embedded etcd server
Connected to etcd 12037351334381611957 default
I1119 15:27:57.413205 1269340 serving.go:341] Generated self-signed cert (.kcp/data/apiserver.crt, .kcp/data/apiserver.key)
I1119 15:27:57.413221 1269340 server.go:471] external host was not specified, using 192.168.0.168
I1119 15:27:57.704735 1269340 plugins.go:158] Loaded 1 mutating admission controller(s) successfully in the following order: NamespaceLifecycle.
W1119 15:27:58.160200 1269340 genericapiserver.go:454] Skipping API authentication.k8s.io/v1beta1 because it has no resources.
W1119 15:27:58.161920 1269340 genericapiserver.go:454] Skipping API authorization.k8s.io/v1beta1 because it has no resources.
W1119 15:27:58.163475 1269340 genericapiserver.go:454] Skipping API certificates.k8s.io/v1beta1 because it has no resources.
W1119 15:27:58.163968 1269340 genericapiserver.go:454] Skipping API coordination.k8s.io/v1beta1 because it has no resources.
W1119 15:27:58.164937 1269340 genericapiserver.go:454] Skipping API rbac.authorization.k8s.io/v1beta1 because it has no resources.
W1119 15:27:58.164944 1269340 genericapiserver.go:454] Skipping API rbac.authorization.k8s.io/v1alpha1 because it has no resources.
W1119 15:27:58.165693 1269340 genericapiserver.go:454] Skipping API flowcontrol.apiserver.k8s.io/v1alpha1 because it has no resources.
W1119 15:27:58.166114 1269340 genericapiserver.go:454] Skipping API events.k8s.io/v1beta1 because it has no resources.
I1119 15:27:58.166374 1269340 plugins.go:158] Loaded 1 mutating admission controller(s) successfully in the following order: NamespaceLifecycle.
I1119 15:27:58.219139 1269340 aggregator.go:179] Skipping APIService creation for apiextensions.k8s.io/v1beta1
I1119 15:27:58.363996 1269340 dynamic_serving_content.go:129] "Starting controller" name="serving-cert::.kcp/data/apiserver.crt::.kcp/data/apiserver.key"
I1119 15:27:58.364033 1269340 secure_serving.go:256] Serving securely on [::]:6443
I1119 15:27:58.364091 1269340 tlsconfig.go:240] "Starting DynamicServingCertificateController"
I1119 15:27:58.364099 1269340 available_controller.go:475] Starting AvailableConditionController
I1119 15:27:58.364107 1269340 cache.go:32] Waiting for caches to sync for AvailableConditionController controller
I1119 15:27:58.364133 1269340 customresource_discovery_controller.go:237] Starting DiscoveryController
I1119 15:27:58.364152 1269340 apiservice_controller.go:97] Starting APIServiceRegistrationController
I1119 15:27:58.364167 1269340 cache.go:32] Waiting for caches to sync for APIServiceRegistrationController controller
I1119 15:27:58.364309 1269340 naming_controller.go:296] Starting NamingConditionController
I1119 15:27:58.364375 1269340 crd_finalizer.go:269] Starting CRDFinalizer
I1119 15:27:58.364332 1269340 bootstrap.go:54] bootstrapping clusters.cluster.example.dev
I1119 15:27:58.364389 1269340 nonstructuralschema_controller.go:192] Starting NonStructuralSchemaConditionController
I1119 15:27:58.364340 1269340 bootstrap.go:54] bootstrapping apiresourceimports.apiresource.kcp.dev
I1119 15:27:58.364447 1269340 controller.go:129] Starting OpenAPI controller
I1119 15:27:58.364494 1269340 cluster_authentication_trust_controller.go:440] Starting cluster_authentication_trust_controller controller
I1119 15:27:58.364503 1269340 shared_informer.go:240] Waiting for caches to sync for cluster_authentication_trust_controller
I1119 15:27:58.364345 1269340 bootstrap.go:54] bootstrapping negotiatedapiresources.apiresource.kcp.dev
I1119 15:27:58.364358 1269340 apiapproval_controller.go:186] Starting KubernetesAPIApprovalPolicyConformantConditionController
I1119 15:27:58.364364 1269340 autoregister_controller.go:143] Starting autoregister controller
I1119 15:27:58.364739 1269340 cache.go:32] Waiting for caches to sync for autoregister controller
I1119 15:27:58.364369 1269340 establishing_controller.go:77] Starting EstablishingController
I1119 15:27:58.364415 1269340 crdregistration_controller.go:112] Starting crd-autoregister controller
I1119 15:27:58.364783 1269340 shared_informer.go:240] Waiting for caches to sync for crd-autoregister
I1119 15:27:58.364777 1269340 namespace_controller.go:200] Starting namespace controller
I1119 15:27:58.364806 1269340 shared_informer.go:240] Waiting for caches to sync for namespace
W1119 15:27:58.371607 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.375945 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.386921 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.390942 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.393381 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.396415 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.398043 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.400460 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.401867 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.403537 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.404691 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.406203 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.407251 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.408649 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.409660 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.411117 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.412110 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.413278 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.414093 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.415349 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.416260 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.417806 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.418581 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.419585 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.420276 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.421300 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.422017 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.422996 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.423756 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.424759 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.425427 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.426364 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.427154 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.428235 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.428997 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.430129 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.430935 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.431948 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.432691 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.433596 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.434806 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.436572 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.437842 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.438700 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.440672 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.442508 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.443698 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.445243 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.447039 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.449103 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.450025 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.450821 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.451592 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.452341 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.453064 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.453686 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.454327 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.454995 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.455661 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.459724 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.460843 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.461654 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.462669 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1119 15:27:58.463780 1269340 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+
I1119 15:27:58.464870 1269340 cache.go:39] Caches are synced for APIServiceRegistrationController controller
I1119 15:27:58.464879 1269340 shared_informer.go:247] Caches are synced for namespace 
I1119 15:27:58.464883 1269340 cache.go:39] Caches are synced for autoregister controller
I1119 15:27:58.464892 1269340 shared_informer.go:247] Caches are synced for crd-autoregister 
I1119 15:27:58.464945 1269340 shared_informer.go:247] Caches are synced for cluster_authentication_trust_controller 
I1119 15:27:58.464995 1269340 cache.go:39] Caches are synced for AvailableConditionController controller
E1119 15:27:58.465909 1269340 fieldmanager.go:197] "[SHOULD NOT HAPPEN] failed to update managedFields" err="failed to convert new object (apiregistration.k8s.io/v1, Kind=APIService) to smd typed: no corresponding type for apiregistration.k8s.io/v1, Kind=APIService" VersionKind="/, Kind="
E1119 15:27:58.467926 1269340 autoregister_controller.go:197] clusters.cluster.example.dev#$#v1alpha1.cluster.example.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:58.468550 1269340 autoregister_controller.go:197] apiresourceimports.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:58.468592 1269340 autoregister_controller.go:197] negotiatedapiresources.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:58.474019 1269340 autoregister_controller.go:197] clusters.cluster.example.dev#$#v1alpha1.cluster.example.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:58.476142 1269340 autoregister_controller.go:197] apiresourceimports.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:58.476343 1269340 autoregister_controller.go:197] negotiatedapiresources.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:58.485128 1269340 autoregister_controller.go:197] clusters.cluster.example.dev#$#v1alpha1.cluster.example.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:58.486597 1269340 autoregister_controller.go:197] apiresourceimports.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:58.487973 1269340 autoregister_controller.go:197] negotiatedapiresources.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:58.507126 1269340 autoregister_controller.go:197] clusters.cluster.example.dev#$#v1alpha1.cluster.example.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:58.507218 1269340 autoregister_controller.go:197] apiresourceimports.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:58.509163 1269340 autoregister_controller.go:197] negotiatedapiresources.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:58.548284 1269340 autoregister_controller.go:197] clusters.cluster.example.dev#$#v1alpha1.cluster.example.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:58.549786 1269340 autoregister_controller.go:197] apiresourceimports.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:58.550896 1269340 autoregister_controller.go:197] negotiatedapiresources.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:58.629085 1269340 autoregister_controller.go:197] clusters.cluster.example.dev#$#v1alpha1.cluster.example.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:58.630871 1269340 autoregister_controller.go:197] apiresourceimports.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:58.631383 1269340 autoregister_controller.go:197] negotiatedapiresources.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:58.789841 1269340 autoregister_controller.go:197] clusters.cluster.example.dev#$#v1alpha1.cluster.example.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:58.791399 1269340 autoregister_controller.go:197] apiresourceimports.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:58.792942 1269340 autoregister_controller.go:197] negotiatedapiresources.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:59.112266 1269340 autoregister_controller.go:197] clusters.cluster.example.dev#$#v1alpha1.cluster.example.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:59.113086 1269340 autoregister_controller.go:197] apiresourceimports.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:59.114353 1269340 autoregister_controller.go:197] negotiatedapiresources.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:59.752809 1269340 autoregister_controller.go:197] clusters.cluster.example.dev#$#v1alpha1.cluster.example.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:59.754145 1269340 autoregister_controller.go:197] apiresourceimports.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:27:59.756060 1269340 autoregister_controller.go:197] negotiatedapiresources.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:28:01.035749 1269340 autoregister_controller.go:197] clusters.cluster.example.dev#$#v1alpha1.cluster.example.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:28:01.036036 1269340 autoregister_controller.go:197] apiresourceimports.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:28:01.038297 1269340 autoregister_controller.go:197] negotiatedapiresources.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:28:03.597955 1269340 autoregister_controller.go:197] clusters.cluster.example.dev#$#v1alpha1.cluster.example.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:28:03.598394 1269340 autoregister_controller.go:197] apiresourceimports.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:28:03.599649 1269340 autoregister_controller.go:197] negotiatedapiresources.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:28:08.719940 1269340 autoregister_controller.go:197] clusters.cluster.example.dev#$#v1alpha1.cluster.example.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:28:08.720291 1269340 autoregister_controller.go:197] apiresourceimports.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:28:08.722840 1269340 autoregister_controller.go:197] negotiatedapiresources.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:28:18.962282 1269340 autoregister_controller.go:197] clusters.cluster.example.dev#$#v1alpha1.cluster.example.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:28:18.963003 1269340 autoregister_controller.go:197] apiresourceimports.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:28:18.964508 1269340 autoregister_controller.go:197] negotiatedapiresources.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:28:39.444611 1269340 autoregister_controller.go:197] clusters.cluster.example.dev#$#v1alpha1.cluster.example.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:28:39.445289 1269340 autoregister_controller.go:197] apiresourceimports.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
E1119 15:28:39.447945 1269340 autoregister_controller.go:197] negotiatedapiresources.apiresource.kcp.dev#$#v1alpha1.apiresource.kcp.dev failed with : the server could not find the requested resource (post apiservices.apiregistration.k8s.io)
^CI1119 15:28:40.156362 1269340 bootstrap.go:87] bootstrapped clusters.cluster.example.dev after 66.576µs
I1119 15:28:40.156539 1269340 autoregister_controller.go:167] Shutting down autoregister controller
I1119 15:28:40.156611 1269340 crd_finalizer.go:281] Shutting down CRDFinalizer
I1119 15:28:40.157643 1269340 dynamic_serving_content.go:144] "Shutting down controller" name="serving-cert::.kcp/data/apiserver.crt::.kcp/data/apiserver.key"
I1119 15:28:40.156545 1269340 bootstrap.go:87] bootstrapped apiresourceimports.apiresource.kcp.dev after 93.378µs
I1119 15:28:40.156560 1269340 establishing_controller.go:88] Shutting down EstablishingController
I1119 15:28:40.158314 1269340 secure_serving.go:301] Stopped listening on [::]:6443
I1119 15:28:40.158388 1269340 tlsconfig.go:255] "Shutting down DynamicServingCertificateController"
I1119 15:28:40.156583 1269340 namespace_controller.go:212] Shutting down namespace controller
I1119 15:28:40.156599 1269340 apiservice_controller.go:131] Shutting down APIServiceRegistrationController
I1119 15:28:40.156590 1269340 bootstrap.go:87] bootstrapped negotiatedapiresources.apiresource.kcp.dev after 173.682µs
F1119 15:28:40.159722 1269340 hooks.go:202] PostStartHook "Install Cluster Controller" failed: could not bootstrap CRDs: [failed to wait for CRD clusters.cluster.example.dev to be established: context canceled, failed to wait for CRD apiresourceimports.apiresource.kcp.dev to be established: context canceled, failed to wait for CRD negotiatedapiresources.apiresource.kcp.dev to be established: context canceled]
goroutine 1164 [running]:
k8s.io/klog/v2.stacks(0x1)
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:1026 +0x8a
k8s.io/klog/v2.(*loggingT).output(0x442a360, 0x3, {0x0, 0x0}, 0xc00065e4d0, 0x0, {0x3526ca3, 0x8}, 0x0, 0x0)
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:975 +0x63d
k8s.io/klog/v2.(*loggingT).printf(0xc0025aac00, 0x12b8c0, {0x0, 0x0}, {0x0, 0x0}, {0x290f255, 0x1b}, {0xc003eed7a0, 0x2, ...})
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:753 +0x1e5
k8s.io/klog/v2.Fatalf(...)
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:1514
k8s.io/apiserver/pkg/server.runPostStartHook({0x290c6f4, 0x1a}, {0xc001daaa80, {0xc0023e3700, 0x2d953e8}, 0xc0025aac00}, {0xc00012b8c0, 0xc0002bcc00})
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20211118181850-ab2ca04a5894/pkg/server/hooks.go:202 +0x185
created by k8s.io/apiserver/pkg/server.(*GenericAPIServer).RunPostStartHooks
	/home/stevekuznetsov/code/kcp-dev/kcp/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20211118181850-ab2ca04a5894/pkg/server/hooks.go:165 +0xf6
...
</code>
</details>

**Comment by stevekuznetsov** [comment]
This doesn't seem to heal, either - so something is not creating `apiservices.apiregistration.k8s.io` silently?

**Comment by stevekuznetsov** [comment]
These keys are also suspicious ... `clusters.cluster.example.dev#$#v1alpha1.cluster.example.dev` means that the *cluster* on the `APIService` was `v1alpha1.cluster.example.dev` ?

**Comment by ncdc** [comment]
Fixed by #224

**Comment by ncdc** [comment]
Actually, is that right @stevekuznetsov? (I was closing this based on your comment in #224 that it fixes this.)

**Comment by stevekuznetsov** [comment]
Yeah, I think this was caused by creating CRDs with `cluster=*` and not actually a race.
