### ISSUE TITLE
bug: sharded-test-server does not work with `run-virtual-workspaces=false`

### ISSUE THREAD

**Issue by mjudeikis** [kcp-dev/kcp#2254]
### Describe the bug

If you run `./sharded-test-server --shard-run-virtual-workspaces=false` , it never starts
```
KCP-0 [-]poststarthook/kcp-start-kcp-apibinder-initializer failed: not finished
KCP-0 I1022 16:45:28.583005 3997122 httplog.go:131] "HTTP" verb="GET" URI="/readyz" latency="3.807285ms" userAgent="sharded-test-server/v0.0.0 (linux/amd64) kubernetes/$Format" audit-ID="2ca3425a-80e8-4cdf-914d-b27807feaba7" srcIP="192.168.1.138:54444" apf_pl="exempt" apf_fs="exempt" apf_execution_time="3.546496ms" resp=500
KCP-0 I1022 16:45:29.589317 3997122 shared_informer.go:332] caches populated
KCP-0 I1022 16:45:29.589576 3997122 healthz.go:257] poststarthook/kcp-start-kcp-apibinder-initializer check failed: readyz
```

### Steps To Reproduce

```
./sharded-test-server --shard-run-virtual-workspaces=false
```

### Expected Behaviour

Should work. 

### Additional Context

I observed similar when trying to deploy KCP outside single binary where KCP and VirtualWorkspaces container never becomes ready if ran separatly

**Comment by mjudeikis** [comment]
Cna `poststarthook/kcp-start-kcp-apibinder-initializer` succedd without VirtualWorkspace running? Is this not circular dependency?

**Comment by stevekuznetsov** [comment]
I think there's ongoing work in this space, @ncdc and @nrb know the status there.

**Comment by ncdc** [comment]
I have started this but haven't finished

**Comment by mjudeikis** [comment]
So its clear to assume that running VW outside main process is not yet supported. If so happy to close this

**Comment by ncdc** [comment]
Not supported yet. It's ok to keep it open so we can close it when it's fixed
