### ISSUE TITLE
bug: e2e-sharded failed to list *v1alpha1.ClusterWorkspace: Unauthorized

### ISSUE THREAD

**Issue by hardys** [kcp-dev/kcp#2274]
### Describe the bug

In `e2e-sharded` runs we're seeing an error like this (this doesn't actually stop the job from passing so perhaps we need to look at additional test coverage)

```
PROXY  W1025 18:20:39.100256   31146 reflector.go:324] k8s.io/client-go@v0.0.0-20221025160842-38c73163e766/tools/cache/reflector.go:167: failed to list *v1alpha1.ClusterWorkspace: Unauthorized
PROXY  E1025 18:20:39.101457   31146 reflector.go:138] k8s.io/client-go@v0.0.0-20221025160842-38c73163e766/tools/cache/reflector.go:167: Failed to watch *v1alpha1.ClusterWorkspace: failed to list *v1alpha1.ClusterWorkspace: Unauthorized
```

After debugging locally, it appears to be because we're using the root shard-admin token for all shards [when creating the clients](https://github.com/kcp-dev/kcp/blob/main/pkg/proxy/server.go#L65) used by the clusterworkspace informer

We can see here in some local debug log output  that the shard-admin token hitting `kcp-1` is actually the token from `kcp-0`:

```
$ grep "invalid bearer token" kcp-1.log | head -n1
E1027 14:04:04.549596  929593 authentication.go:63] "Unable to authenticate the request SHDEBUG" err="invalid bearer token" req=&{Method:GET URL:/apis/tenancy.kcp.dev/v1alpha1/clusterworkspaces:5678dc3ffb5f4156924efc5c9a4732f12e73fadca3592faa5c762f91fd0fc3f5?limit=500&resourceVersion=0 Proto:HTTP/2.0 ProtoMajor:2 ProtoMinor:0 Header:map[Accept:[application/json, */*] Accept-Encoding:[gzip] Authorization:[Bearer 4ae09225-6a3b-4413-a5a7-d105b45a4466] User-Agent:[kcp-front-proxy/v1.24.3+kcp (linux/amd64) kubernetes/574fe23]] Body:0xc0071db1a0 GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:10.19.133.66:6445 Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:10.19.133.66:37122 RequestURI:/clusters/%2A/apis/tenancy.kcp.dev/v1alpha1/clusterworkspaces:5678dc3ffb5f4156924efc5c9a4732f12e73fadca3592faa5c762f91fd0fc3f5?limit=500&resourceVersion=0 TLS:0xc00e689080 Cancel:<nil> Response:<nil> ctx:0xc00fe05d70}

$ grep -B2 4ae09225-6a3b-4413-a5a7-d105b45a4466 ../.kcp-0/admin.kubeconfig 
- name: shard-admin
  user:
    token: 4ae09225-6a3b-4413-a5a7-d105b45a4466
```

### Steps To Reproduce

Check e2e-sharded logs, or run `make test-e2e-sharded` locally

### Expected Behaviour

IIUC we need the proxy informer to be able to list/watch clusterworkspace objects on all shards, so we have to use an authentication method which isn't limited to the root shard.

Some ideas were [discussed on slack](https://kubernetes.slack.com/archives/C021U8WSAFK/p1666784746750299) and it seems like switching to cert based auth may be the best option - this should mean we can authenticate with any shard, and avoid modifying the proxy config when a shard gets added/removed.

**Comment by p0lyn0mial** [comment]
sgtm, thanks for picking it up.

**Comment by hardys** [comment]
So looking at the history here, I see that the current per-shard client code landed in https://github.com/kcp-dev/kcp/pull/1203 - so it would be helpful to get input from @sttts before I start changing it :) 

If we switch this to use client certs, then I think we need to handle the case where each shard has a different cert, and the method to enable that appears to be the mapping file, however in the `sharded-test-server` case, we seem to only create mappings to the root shard:

```
$ grep "server:" .kcp-0/admin.kubeconfig 
    server: https://10.19.133.66:6444
    server: https://10.19.133.66:6444/clusters/root
$ grep "server:" .kcp-1/admin.kubeconfig 
    server: https://10.19.133.66:6445
    server: https://10.19.133.66:6445/clusters/root

$ cat .kcp-front-proxy/mapping.yaml 
- backend: https://localhost:6444
  backend_server_ca: .kcp/serving-ca.crt
  path: /services/
  proxy_client_cert: .kcp-front-proxy/requestheader.crt
  proxy_client_key: .kcp-front-proxy/requestheader.key
- backend: https://localhost:6444
  backend_server_ca: .kcp/serving-ca.crt
  path: /clusters/
  proxy_client_cert: .kcp-front-proxy/requestheader.crt
  proxy_client_key: .kcp-front-proxy/requestheader.key
```

So I think for multi-shard deployments we need to specify each shard as a `backend` (using the IP, not `localhost`), then we can look up the necessary client cert/key using the [shard BaseURL](https://github.com/kcp-dev/kcp/blob/main/pkg/proxy/server.go#L66), does that sound reasonable?

**Comment by p0lyn0mial** [comment]
> If we switch this to use client certs, then I think we need to handle the case where each shard has a different cert,

I think that should be okay, I think that the proxy could specify a well-known `ServerName` during bootstrapping a TLS connection to a shard. That would give us a certificate that would much a well-known `CA`. Does it make sense?

**Comment by hardys** [comment]
> > If we switch this to use client certs, then I think we need to handle the case where each shard has a different cert,
> 
> I think that should be okay, I think that the proxy could specify a well-known `ServerName` during bootstrapping a TLS connection to a shard. That would give us a certificate that would much a well-known `CA`. Does it make sense?

Thanks for the feedback @p0lyn0mial  - I get that the `ServerName` has to match the CN/SAN in the server cert, but I'm unclear if the proxy has to do anything special here - the user provides the server/client certs, and the `ServerName` will be derived from the `ClusterWorkspaceShard` spec in the indexer, so the hostname (or potentially IP for CI/dev testing) just has to match?

I think leveraging the client certs from the mapping file is definitely viable, and probably optimal if we want to ensure the informer uses per-shard credentials.

I can't help wondering if we should just pass an admin kubeconfig to the proxy though which would be potentially much simpler, any thoughts on that?  The main disadvantage AFAICS is that we'll need to rename/replace the `--root-kubeconfig` CLI flag

**Comment by hardys** [comment]
Summary of some discussion with @ncdc and @p0lyn0mial

- @ncdc has some related [work in progress](https://github.com/ncdc/kcp/commit/a3ddd82075be2b2d1eb703116f32a6d00e0fc76e) which we can possibly revive then use the same client-cert pattern to solve this (convert the informer client to use a proxy->shard client cert instead of the shard-admin token)
- We can't easily use an admin kubeconfig to switch to client certs, since in the sharded case the client cert terminates at the proxy, then we use request-header at the shard (so, we can't use the same kubeconfig for the proxy->shard auth)

**Comment by ncdc** [comment]
Accidentally marked as fixed by 2297
/reopen

**Comment by hardys** [comment]
/assign @p0lyn0mial 

This should be resolved via https://github.com/kcp-dev/kcp/pull/2382
