### ISSUE TITLE
bug: initializing workspaces vw allows access to any workspace regardless of status or initializer name

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#2308]
### Describe the bug

/services/initializingworkspaces/$initializerName/ allows GET/UPDATE access to individual workspaces by name. It is only supposed to expose initializing workspaces for the given $initializerName. It actually exposes all workspaces, regardless of status, and regardless of initializer name.

### Steps To Reproduce

1. Create a new ClusterWorkspaceType with spec.initializer=true
2. `k ws create foo --type $yourType`
3. When it says it's waiting for the workspace to be ready, hit ctrl-c
4. `k --user shard-admin --server https://localhost:6443 get --raw /services/initializingworkspaces/bleep:bloop/clusters/root/apis/tenancy.kcp.dev/v1alpha1/clusterworkspaces/compute`
5. ClusterWorkspace is returned

### Expected Behaviour

Get a not found error

**Comment by ncdc** [comment]
I have a fix for this pending
/assign

**Comment by ncdc** [comment]
FYI @nrb @stevekuznetsov

**Comment by stevekuznetsov** [comment]
Yikes
