### ISSUE TITLE
feature: create an in-cluster authorizer to avoid checking with parent workspaces

### ISSUE THREAD

**Issue by salaboy** [kcp-dev/kcp#2315]
### Feature Description

As described here: https://hackmd.io/Qb3HX2XGRV63Rt-83dZXNg#

This issue is focused on implementing an in-cluster authorizer to implement

```
We (eventually, step 2) remove workspaces/content RBAC semantics and replace it with:

a) access to a workspace is authorized through verb=access, non-resource=/ inside of a workspace
b) admin access is given through in-workspace binding of a */* RBAC role
c) deletion of a workspace is authorized through verb=delete, non-resource=/ inside of a workspace and via delete verb on the Workspace object of primary type.

```

### Proposed Solution

I will start by implementing `a` by copying the `workspace-authorizer.go` and adding in-cluster validations instead of the parent checks that are being used here: https://github.com/kcp-dev/kcp/blob/main/pkg/authorization/workspace_content_authorizer.go#L144 

### Want to contribute?

- [X] I would like to work on this issue.

### Additional Context

I had an intro discussion with @sttts , but @s-urbaniak if you want to provide more context feel free to share more pointers with me. Those will be appreciated.

**Comment by salaboy** [comment]
I will add more information after looking into the code more closely.

**Comment by ncdc** [comment]
@sttts @s-urbaniak this is done now that the workspace refactor is in?

**Comment by s-urbaniak** [comment]
this is done using the workspace refactor
