### ISSUE TITLE
bug: should not list synctarget when running bind compute command 

### ISSUE THREAD

**Issue by qiujian16** [kcp-dev/kcp#2349]
### Describe the bug

a user who wants to `bind compute` may not have permission to list synctarget in the location workspace, which will cause the command failure.

We should have a controller to check the synctarget's supported apiexport, and then reflects in the condition of apibindings. With that the user does not need to access location workspace.

### Steps To Reproduce

1. create a synctarget in the location with workspace with admin permission.
2. create a user workspace with admin permission.
3. switch to another user that can only access user workspace.
4. run `kubeclt kcp bind compute` will fail with error of unauthorized to list synctargets

### Expected Behaviour

user with only user workspace access can run `bind compute`.

**Comment by davidfestal** [comment]
Probably we can simply come back to these defaults:
- if no `--apiexport` argument was provided, add the `root:compute:kubernetes` APIExport
- if at least one `--resource` has been added, add the local `kubernetes` APIExport

without testing for the `supportedAPIExports` is on the SyncTarget.

Does it make sense to you @qiujian16 ?

BTW while we're at it, why not rename the `local` APIExport from `kubernetes` to something like `custom` or `imported` or `local` ? That would make more sense IMO.
cc @sttts

**Comment by stevekuznetsov** [comment]
Why not just make it explicit and required to choose the APIExport?

**Comment by davidfestal** [comment]
Because we want to make it simple when people use the default. The root `kubernetes` `APIExport` is added by default on `SyncTarget`s. So it would make sense that it would be added by default here as well, unless the use mentions another APIExport of course.

**Comment by qiujian16** [comment]
how about we by default only bind root:compute APIExport? and we could and a separated flag, something like `--bind-location-workspace`?

**Comment by davidfestal** [comment]
> how about we by default only bind root:compute APIExport?

I'm also OK with this simplest approach 

>and we could and a separated flag, something like --bind-location-workspace?

Not sure that we need a distinct flag then. i'd rather have a dedicated name for the local `APIExport` that will contain imported resources as mentioned in a comment above), and then use the normal `--apiexport` argument to add it with the `bind compute` command, just with `--apiexport=imported` (if the location workspace imported resources APIExport is named `imported`)
