### ISSUE TITLE
CRUD operations via APIExport VW on resources claimed from root workspace with local maximum permission policy always return 403 

### ISSUE THREAD

**Issue by astefanutti** [kcp-dev/kcp#2384]
### Describe the bug

CRUD operations via APIExport VW on resources claimed from root workspace with local maximum permission policy always return 403.

### Steps To Reproduce

1. Create an APIExport that claims permission on `scheduling.kcp.dev/placements` from the `scheduling.kcp.dev` APIExport in the `root` workspace
2. Bind that APIExport in a consumer workspace with the claim permission accepted
3. Create a placement resource via the APIExport VW API server
4. This returns 403, while any authenticated user is granted permission via the local maximum permission policy defined in the `root` workspace

### Expected Behaviour

The local maximum permission policy should correctly apply to requests made to the APIExport VW API server.

**Comment by sttts** [comment]
The solution IMO is incorrect.
