### ISSUE TITLE
bug: When switching between a home and a root workspace an error is thrown which reads "Forbidden to get apibindings" but a meaningful messag would help users not to get confused

### ISSUE THREAD

**Issue by kasturinarra** [kcp-dev/kcp#2390]
### Describe the bug

When switching between a home and a root workspace if user is not allowed to enter the root workspace then a meaningful  error should be thrown something like "You are not a member of workspace "root" instead an error message as below is thrown which is confusing to the user.

kubectl ws root
error checking APIBindings: apibindings.apis.kcp.dev is forbidden: User "rh-sso:knarrakcp" cannot list resource "apibindings" in API group "apis.kcp.dev" at the cluster scopeCurrent workspace is "root".

### Steps To Reproduce

1. Export kubeconfig of the env
2. Enter into home workspace by running the  command 'kubectl kcp ws'
3. Now run command 'kubectl ws root' to enter to 'root' workspace

### Expected Behaviour

A meaning ful error message should be thrown something like below

You are not a member of workspace "root"
Current workspace is "root".

**Comment by nrb** [comment]
This originates from #2046, I'll take a look at it.
