### ISSUE TITLE
Define prototype goals

### ISSUE THREAD

**Issue by smarterclayton** [kcp-dev/kcp#24]
Roughly make https://github.com/kcp-dev/kcp#what-does-it-do-for-me real

Demo

1. CRD Tenancy - A user can try out "logical clusters" and CRD tenancy
2. Kube-above-Kube - A user can "import a cluster's objects", see workload end up on one or more clusters
3. Extending KCP with controllers - A user can write or adapt a simple controller with CRD against KCP that doesn't 

Meta-goals:

* Lots of flexibility added to Kube in a way that benefits different teams
* The lifecycle of app infra APIs can be managed, composed, and reused
* KCP enables higher security by separating out teams / roles / users / problems

User goals:

1. 95% workload relevance for multi-cluster apps - We demonstrate that "95%" of kube apps could be deployed to KCP, end up on an underlying cluster, and then move/replicate between clusters with a combination of code and design drafts (services, deployments, volumes, etc) (reschedule app across clusters, active-passive, active-active)
2. Logical clusters allow isolation AND integration - We demonstrate how a controller could work across tens or thousands of logical clusters with list/watch and mutation, allowing teams AND integrations to scale with security
3. Within a logical cluster, a developer can have a PaaS like promotion flow with dev/stage/prod
4. Within a physical cluster, resources from multiple logical clusters are isolated

**Comment by smarterclayton** [comment]
Described use cases guiding transparent multi-cluster a bit more in #75 but will move that to a doc

**Comment by ncdc** [comment]
This has been superseded by new milestones and issues. If anything fell through the cracks, please let me know and we'll make sure to create new issues.
