### ISSUE TITLE
Conditions Library for Workspaces

### ISSUE THREAD

**Issue by stevekuznetsov** [kcp-dev/kcp#246]
We should take a look at the Cluster API Conditions library and see if we can somehow make it work with `kcp`. It's not clear if there is any downside to using one type of condition across the entire API like Cluster API does, or if there would be benefit to making their library generated code so as to mimic generics, but we should chat with the maintainers there to see what they suggest. As it is, it's not importable.

/cc @ncdc

**Comment by ncdc** [comment]
FYI @fabriziopandini @vincepri if you all would be open to chatting, please let us know. Thanks!

**Comment by vincepri** [comment]
Definitely interested! Is there a meeting we should be invited to?

**Comment by imjasonh** [comment]
I don't have a horse in the race, but I know of another alternative Conditions API library in Knative: https://pkg.go.dev/knative.dev/pkg/apis/duck/v1#Status

If you embed the `duckv1.Status` type in your `FooStatus` struct ([example](https://pkg.go.dev/knative.dev/serving/pkg/apis/serving/v1#ServiceStatus)), you can do basically `foo.Status.GetCondition(Ready).IsTrue()`

It's probably six of one and half a dozen of the other, but I thought I'd mention it.

**Comment by stevekuznetsov** [comment]
@imjasonh that library seems to collapse status to [one of two options](https://pkg.go.dev/knative.dev/pkg@v0.0.0-20211129153605-754f332c0c51/apis#ConditionType) - is my read correct? Already in `Workspace` we have a case for "unschedulable" conditions so I'm not sure if that would work. Although, I'm not *that* sure that strongly typed condition types make that much sense since it's not going to be enforced as an enum on instantiation or de-serialization anyway, so it's really just a set of useful constants as I see it?

**Comment by imjasonh** [comment]
> @imjasonh that library seems to collapse status to [one of two options](https://pkg.go.dev/knative.dev/pkg@v0.0.0-20211129153605-754f332c0c51/apis#ConditionType) - is my read correct?

Those are the only two that the `pkg/apis` package provides by default, but you can define your own with `ConditionType("Unschedulable")` or `ConditionType("IsAPony")` or whatever.

**Comment by ncdc** [comment]
@vincepri we have kcp community meetings Tuesdays at 11am ET. If that time works for you, we can add discussing conditions to a future meeting agenda and find a Tuesday that works for everyone. WDYT?

**Comment by imjasonh** [comment]
The CAPI Conditions package is here: https://pkg.go.dev/sigs.k8s.io/cluster-api/util/conditions

**Comment by fabriziopandini** [comment]
Happy to provide context on CAPI conditions if required

**Comment by stevekuznetsov** [comment]
We've pulled in a CAPI copy (lol) for now - and I noticed there's metav1.Condition, now, too - which supports multiple controllers each exposing their own resource version. I imagine k8s at large will want to see helpers that just build on top of that.

**Comment by fabriziopandini** [comment]
ACK
Currently the main difference between CAPI conditions are:
- the severity field, that helps in categorising reasons by relevance for the users. 
- the assumption about consistent polarity ("True = good"), that gives a key to interpreter status

It will be great If we can find a way to solve those problems (categorising reasons by severity, interpreter status polarity) while using metav1.Condition; the first idea that comes to my mind is some sort of conventions around reasons, but this seems kind of brittle
@ncdc @vincepri  opinions

**Comment by ncdc** [comment]
@fabriziopandini thanks for providing these details! I'm guessing that the severity field would probably be easier to suggest for upstream (request: add severity field - it's either accepted and added, or rejected).

Consistent polarity is probably harder to define as a requirement, although I guess if we combine it with helpers and UIs that consistently show "healthy" vs. "unhealthy" by interpreting the conditions consistently (true==good), then any developer who inverts the polarity would see false negatives in the helpers/UIs (e.g. it would like "unhealthy" because a condition had false==good).

**Comment by ncdc** [comment]
Closing, as we have copied in the CAPI conditions code. If we need to revisit anything with conditions, let's open new issues. Thanks!
