### ISSUE TITLE
Hyperlinks in the main documentation site are broken

### ISSUE THREAD

**Issue by vikrantest** [kcp-dev/kcp#2461]
All hyperlinks in the main documentation site are broken and pointing to the same URL i.e. https://docs.kcp.io/kcp/main/.
Looks like links are not rendered from README.md properly while importing it in [_index.md](https://github.com/kcp-dev/kcp/blob/main/docs/content/en/main/_index.md).

Below screenshot shows the hover url for in bottom left for all the hyper links.
<img width="1292" alt="Screenshot 2022-12-08 at 2 21 30 PM" src="https://user-images.githubusercontent.com/1941363/206402092-c584cd5e-3710-4067-a413-b0a58c631290.png">

**Comment by ncdc** [comment]
This has been fixed
