### ISSUE TITLE
bug: ppc64 CI action failing

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#2478]
### Describe the bug

https://github.com/kcp-dev/kcp/actions/workflows/e2e-ci-ppc64le.yml has been failing for the past several days

### Steps To Reproduce

1. Look at https://github.com/kcp-dev/kcp/actions/workflows/e2e-ci-ppc64le.yml
2. See failures

### Expected Behaviour

No failures

### Additional Context

Some part of the setup process is failing with `/bin/mkdir: cannot create directory 'cpuset': Read-only file system`

**Comment by ncdc** [comment]
I have manually disabled this workflow for now, so the job doesn't appear as failing on every branch and PR

**Comment by xrstf** [comment]
The related workflow has since been deleted, as we migrated most things to Prow.
