### ISSUE TITLE
feature: update website to include documentation for previous releases

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#2482]
### Feature Description

We should make sure that docs.kcp.io hosts documentation for:

* the current "stable" release
* main
* previous releases

### Proposed Solution

Update the website :smi

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by avinal** [comment]
Hi @hardys, yes I have already added the functionality in our current documentation. It was working successfully locally. The feature should kick in as soon a release is made. I won't be able to test till 20th Dec (On a vacation). If this isn't urgent I will solve this issue as soon I get back.

**Comment by ncdc** [comment]
This is done now that we're on mkdocs!
