### ISSUE TITLE
bug: home/doc page is not clear about the top-level modularity

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/kcp#2486]
### Describe the bug

https://docs.kcp.io/kcp/main/ , equivalently https://github.com/kcp-dev/kcp/blob/main/README.md , starts off with an overview that mixes up features from the three main layers and the rest of the document does nothing to clarify.

If I understand correctly, the top level structure of kcp is three layers: lowest is the "core", which focuses on apiserver virtualization (possibly further split into a lower layer that does logical clusters and a higher layer that provides workspaces); middle is the kcp version of kube-bind; top is TMC.  Although some of us are also working on adding Edge MC as a peer of Transparent MC.

### Steps To Reproduce

1. Read the doc

### Expected Behaviour

I think the modularity is a key part of the idea and should be clearly stated in the root document.

**Comment by ncdc** [comment]
I guess this is somewhat related to (or maybe a duplicate) of #1211? We are fully committed to rewriting the readme to be entirely clear, but are holding off doing so until after we split the repos (core, tenancy, tmc).
