### ISSUE TITLE
feature: allow maximum permission policy on native kube and kcp types

### ISSUE THREAD

**Issue by s-urbaniak** [kcp-dev/kcp#2493]
### Feature Description

Currently, we can't assert a maximum permission policy on native kube (i.e. configmaps, secrets, etc.) and kcp types (i.e. API bindings, API resource schemas, etc.)

This leads to bugs like https://github.com/kcp-dev/kcp/issues/2239 and current suggestion on hardcoding access rules around critical types as proposed in https://github.com/kcp-dev/kcp/pull/2491.

### Proposed Solution

Multiple options exist:

1. have somehow a possibility to enforce a maximal permission policy on native and kcp types i.e. in the `root` workspace

2. Leverage what we have today and what we plan to do anyways:

- specifically in the case of API bindings API binding admission controller checks against the `bind` verb. This is probably not hitting here because the call is done via the virtual API export apiserver user. A solution here would be to have soft impersonation working.
- for all the other types (native types, kcp types): since there is no clear “owner” of those types (except maybe admin in root WS) reverse permission claims actually can come to the rescue. Here, we’ll ask for the specific verbs that we want to execute and the consumer accepts this explicitly.

### Want to contribute?

- [X] I would like to work on this issue.

**Comment by s-urbaniak** [comment]
design doc https://docs.google.com/document/d/1lLI5D-tveStA4XmxuMaUlRfz2Vz6ABz-MM-4rUJwJyc/edit#heading=h.c4idh7huqcjb

**Comment by ncdc** [comment]
We don't have use cases for this currently, and as discussed in today's community meeting, we're going to close until/unless we need it in the future.
