### ISSUE TITLE
Confused about "user name permutations"

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/kcp#2498]
https://github.com/kcp-dev/kcp/blob/main/docs/content/en/main/concepts/workspaces.md#bucket-configuration-options says

> User-names have `(26 * [(26 + 10 + 2) * 61] * 36 = 2169648)` permutations

but it is not clear where that calculation comes from.  Every time I studied permutations in school, factorial was involved.  And it would really only be a matter of _permutations_ if a character could not be repeated; is username "adam" really forbidden?

**Comment by ncdc** [comment]
We don't have buckets any more in `main` so this is no longer used.
