### ISSUE TITLE
Demonstrate "read through" of a resource to underlying physical clusters

### ISSUE THREAD

**Issue by smarterclayton** [kcp-dev/kcp#25]
It should be possible to call `kubectl get pods / kubectl logs` and have the apiserver pass through the call directly to 0..N underlying clusters, which would open the door to keeping pods on the underlying cluster.  Then the next step is multiple source unification - a `kubectl get pods` could perform a merge between the underlying physical cluster and a pod stored directly in etcd at the kcp level.

This "blurring of the lines" would allow important behavior to be delegated to sub clusters without having to tell an end user "go get credentials to the underyling cluster" (note that is probably still valuable for other reasons, especially with unified identity)

**Comment by smarterclayton** [comment]
Noted in the investigation to logical clusters but keeping this open

**Comment by sttts** [comment]
@aojea can you link this in your epic, or close this one?
