### ISSUE TITLE
flake: bound CRD deleted by CRD cleanup controller too aggressively

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#2507]
### Describe the bug

During one of our e2e tests, creating a CR for a bound API was rejected because the bound CRD was terminating.

```
Failed  === RUN   TestAPIExportVirtualWorkspace
=== PAUSE TestAPIExportVirtualWorkspace
=== CONT  TestAPIExportVirtualWorkspace
    kcp.go:127: shared kcp server will target configuration "/go/src/github.com/kcp-dev/kcp/.kcp/admin.kubeconfig"
=== CONT  TestAPIExportVirtualWorkspace
    assertions.go:1691: Waiting for condition, but got: workspace phase is Initializing, not Ready
=== CONT  TestAPIExportVirtualWorkspace
    workspaces.go:196: Created organization workspace root:e2e-org-dhqjr
=== CONT  TestAPIExportVirtualWorkspace
    assertions.go:1691: Waiting for condition, but got: workspace phase is Initializing, not Ready
=== CONT  TestAPIExportVirtualWorkspace
    workspaces.go:126: Created root:universal workspace root:e2e-org-dhqjr:e2e-workspace-45l9k
=== CONT  TestAPIExportVirtualWorkspace
    assertions.go:1691: Waiting for condition, but got: workspace phase is Initializing, not Ready
=== CONT  TestAPIExportVirtualWorkspace
    workspaces.go:126: Created root:universal workspace root:e2e-org-dhqjr:e2e-workspace-5vxkg
    users.go:42: Giving users [user-1 user-2 user-3] member access to workspace "e2e-org-dhqjr" in "root"
    users.go:42: Giving users [user-1 user-2] member access to workspace "e2e-workspace-45l9k" in "root:e2e-org-dhqjr"
    users.go:42: Giving users [user-3] member access to workspace "e2e-workspace-5vxkg" in "root:e2e-org-dhqjr"
=== CONT  TestAPIExportVirtualWorkspace
    virtualworkspace_test.go:996: Install today cowboys APIResourceSchema into service provider workspace "root:e2e-org-dhqjr:e2e-workspace-45l9k"
=== CONT  TestAPIExportVirtualWorkspace
    virtualworkspace_test.go:1005: Create an APIExport for it
    virtualworkspace_test.go:110: test that the virtualWorkspaceURL is not set on initial APIExport creation
I1216 16:46:30.293914   29226 bootstrap.go:238] Bootstrapped APIResourceSchema root:e2e-org-8k5tt:provider|today.cowboys.wildwest.dev
=== CONT  TestAPIExportVirtualWorkspace
    virtualworkspace_test.go:1020: Create an APIBinding in consumer workspace "root:e2e-org-dhqjr:e2e-workspace-5vxkg" that points to the today-cowboys export from "root:e2e-org-dhqjr:e2e-workspace-45l9k"
=== CONT  TestAPIExportVirtualWorkspace
    virtualworkspace_test.go:1044: Make sure "wildwest.dev" API group shows up in consumer workspace "root:e2e-org-dhqjr:e2e-workspace-5vxkg" group discovery
=== CONT  TestAPIExportVirtualWorkspace
    virtualworkspace_test.go:1053: Make sure cowboys API resource shows up in consumer workspace "root:e2e-org-dhqjr:e2e-workspace-5vxkg" group version discovery
    virtualworkspace_test.go:1060: Make sure we can perform CRUD operations against consumer workspace "root:e2e-org-dhqjr:e2e-workspace-5vxkg" for the bound API
    virtualworkspace_test.go:1062: Make sure list shows nothing to start
=== CONT  TestAPIExportVirtualWorkspace
    virtualworkspace_test.go:1074: Create a cowboy CR in consumer workspace "root:e2e-org-dhqjr:e2e-workspace-5vxkg"
    virtualworkspace_test.go:1078: 
        	Error Trace:	virtualworkspace_test.go:1078
        	            				virtualworkspace_test.go:119
        	Error:      	Received unexpected error:
        	            	create not allowed while custom resource definition is terminating
        	Test:       	TestAPIExportVirtualWorkspace
        	Messages:   	error creating cowboy in consumer workspace "root:e2e-org-dhqjr:e2e-workspace-5vxkg"
--- FAIL: TestAPIExportVirtualWorkspace (77.87s)
```

### Steps To Reproduce

1. Run a test that involves APIBindings and creating CRs
2. Creating the CR sometimes fails because the bound CRD is already being terminated

### Expected Behaviour

No failure

### Additional Context

It looks like it this test environment was "slow" and it was taking a while for the CRD to become established and have its names approved. The APIBinding never had its status patched to indicate any bound resources. The CRD cleanup controller deletes bound CRDs if they are at least 10 seconds old and have no APIBindings with bound resources pointing at the CRD.

10 seconds may be too aggressive for our CI setup. We may need to consider raising this to something significantly higher, such as 1/5/10/30/60 minutes.

**Comment by ncdc** [comment]
FYI @kylape

**Comment by kylape** [comment]
There is [a test](https://github.com/kcp-dev/kcp/blob/2b5c1f10d964b2ddb682564a5bfc37c3e958243c/test/e2e/apibinding/apibinding_deletion_test.go#L244-L247) that checks that a CRD is deleted by the cleanup controller within `ForeverTestTimeout` (30s).  

A few options that I can think of:

1. Delete the above test.  This risks a regression that would introduce back the problem the CRD cleanup controller was built to solve, (i.e. unbounded CRD creation)
2. Increase the timeout of this test to be slightly longer than the timeout chosen for the requeue.  Not sure how this would affect test suite duration in practice, but it would at least put a lower bound on the completion of the suite equal to that of the requeue period configured in the CRD cleanup controller.
3. Do the `APIBinding` scan directly in the CRD cleanup controller.  I had actually implemented this in the original PR, but it was [considered too complex](https://github.com/kcp-dev/kcp/pull/2298#discussion_r1017999729).

**Comment by ncdc** [comment]
What about a unit test that uses a fake clock?

**Comment by kylape** [comment]
Do you have an example of a unit test that uses a fake clock? I imagine we'd have to wire up the controller to pull items from the queue etc in the unit test.

**Comment by ncdc** [comment]
See e.g. https://github.com/kcp-dev/kubernetes/blob/d4c55a52edb3cea4ab8bf44de207dca861fe45d3/pkg/proxy/healthcheck/healthcheck_test.go#L379-L407.

If you split `process` so it handles getting a CRD and APIBindings, you can then pass those into a new `reconcile` function that we can unit test without needing to fake out a full controller/lister/queue/etc.

**Comment by stevekuznetsov** [comment]
cc @nrb IIRC the 10s window was set to be small in order to de-flake something else ... can we somehow update status more aggressively instead?

**Comment by nrb** [comment]
@stevekuznetsov I assume you mean [this window](https://github.com/kcp-dev/kcp/blob/main/pkg/reconciler/apis/crdcleanup/crdcleanup_controller.go#L250)?

Are you referring to updating status on the APIBinding or CRD?

**Comment by stevekuznetsov** [comment]
@nrb yeah, that window - and the update would go to the binding.

**Comment by ncdc** [comment]
I think I'd prefer a solid unit test and no e2e on this one. We need the window large enough to avoid false positives
