### ISSUE TITLE
bug: Makefile calls for outdated release of logcheck

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/kcp#2538]
### Describe the bug

`logcheck -check-contextual` used to complain about uses of `klog.InitFlags`, even though those are not actually violations of contextual logging.  Witness the bogus complaints in `hack/logcheck.out`.  The latest release, v0.4.0, includes a fix to this.

### Steps To Reproduce

1.  Look for complaints about InitFlags in `hack/logcheck.out`

### Expected Behaviour

I expected no objections to using klog.InitFlags.

### Additional Context

The logcheck fix is https://github.com/kubernetes-sigs/logtools/pull/10

**Comment by nrb** [comment]
Also note that when logcheck is updated, it will bring with it a new check for logging keys that we'll likely want to disable, at least initially. See [the merge commit](https://github.com/kubernetes-sigs/logtools/commit/3a8e26d87c486c7511b65988fad0d897d0e7c289).

The check is named `check-keys` and will complain about our keys with include `.` in the string.

**Comment by MikeSpreitzer** [comment]
I am not clear on why logcheck objects to those and/or why kcp wants those.  Can someone elucidate?  Is there an option here that belongs in logcheck?

**Comment by nrb** [comment]
Logcheck is following the Kubernetes conventions at https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#name-arguments. Our approach has been to use a `.` to delineate a controller name from the variable name.

IMO, upon updating we should disable the check for now to reduce noise.

**Comment by MikeSpreitzer** [comment]
I tried switching to the latest release of logcheck, and many of its complaints are about different things.

The first example is the key "resource-types".  I presume that kcp could and should switch to using "resourceTypes" instead, to conform with the Kube norms.

The second example is "VirtualWorkspaceURL".  I presume that cound and should be changed to "virtualWorkspaceURL".

Here is another complaint:

```
/pkg/reconciler/core/logicalclusterdeletion/logicalcluster_deletion_controller.go:316:14: Key positional arguments "owner.cluster" are expected to no special characters. Please refer to https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#name-arguments.
```

If I understand correctly, that could and should be changed to "ownerCluster".

In fact, I do not see any example where the key is clearly controllerName + "." + controller-specific variable.  Perhaps ones like the following?

```
/pkg/virtual/syncer/transformations/transformer.go:110:11: Key positional arguments "syncerView.HasSyncerFinalizer" are expected to no special characters. Please refer to https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#name-arguments.
```

Could that be changed to "syncerViewHasSyncerFinalizer" ?

**Comment by ncdc** [comment]
Not sure if I'm in the minority, but I would like to be able to use `.` in our log keys.

**Comment by MikeSpreitzer** [comment]
If we are trying to be part of the Kubernetes community, do we want to diverge on this point?  Do we want to try to convince the larger community to change on this point?

**Comment by nrb** [comment]
I'd echo Andy's preference.

I don't know the reasons that the upstream project has decided on this requirement, so I don't know whether it's likely to be accepted or not. We can ask.

**Comment by stevekuznetsov** [comment]
Logging just seems to be a place that accrues more and more slightly pedantic and kind of confusing hard-line choices, like the new `logr.Logger` not allowing `Error()` calls without a literal Go `error` value, or choosing that nobody needs to be able to use `Warning()` - I get opinionated design, but supporting stuff like that is fairly trivial and removing it for ideological purity I feel are examples (along with perhaps not allowing `.`) of decisions that just make it hard for those tools to be broadly applicable.
