### ISSUE TITLE
Remove tenancy API version v1beta1 and move its types into v1alpha1

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#2563]
We were potentially a little overly optimistic that the v1beta1 Workspace was beta-quality. I would like to propose that we remove the tenancy v1beta1 API version entirely and move its types into the v1alpha1 version.

@kcp-dev/kcp-contributors @kcp-dev/kcp-maintainers thoughts?

**Comment by sttts** [comment]
If we want this, then before next tag is a must.

I personally tend to prefer just keep it in beta. It will force us to more discipline.

**Comment by stevekuznetsov** [comment]
@vincepri what about `tenancyv1alpha1` is deprecated? The types in there now are 100% live and useful. I'm fine with some other alpha version if we must - but mostly I don't think we gain anything from the discipline that @sttts mentions and would rather make the decision to push to beta when we've had some more time to think things through.

**Comment by stevekuznetsov** [comment]
@sttts happy to tackle this next, a clean move to `v1alpha1` is auto-gen-able and simple, surely done before next tag

**Comment by ncdc** [comment]
I don't believe it helps us to limit what we can change in the tenancy api at this time. When we are more confident in the shape of the types, then we can discuss graduating to beta.

**Comment by vincepri** [comment]
Isn't `ClusterWorkspace` type deprecated in v1alpha1? Or asked another way, which types in that package are not deprecated?

**Comment by ncdc** [comment]
We deleted ClusterWorkspace entirely

**Comment by vincepri** [comment]
Ah ok, so the package isn't deprecated, the type was just removed. That makes sense!

**Comment by ncdc** [comment]
This is done
