### ISSUE TITLE
maxPermissionPolicyAuth and systemCRDAuth should be part of deep SAR

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#2568]
_Originally posted by @sttts in https://github.com/kcp-dev/kcp/pull/2543#discussion_r1064995122_

**Comment by s-urbaniak** [comment]
See the comment in https://github.com/kcp-dev/kcp/pull/2543#discussion_r1067816521.

I verified and at least the system CRD authorizer is not skipped as part of deep SAR.
