### ISSUE TITLE
feature: Enable random workspace scheduling and work through e2e (without tmc)

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#2612]

**Comment by sttts** [comment]
https://github.com/kcp-dev/kcp/pull/2596

**Comment by p0lyn0mial** [comment]
It looks like we can close this issue, any objections ?

**Comment by stevekuznetsov** [comment]
@p0lyn0mial I think #2742 and the dozens of deflaking PRs from e.g. @ncdc  following up the initial work are still ongoing - perhaps we should make sure that the focus is there before closing out?

**Comment by ncdc** [comment]
I think we're at a much better place now so I'm closing this. @stevekuznetsov please reopen if you disagree 😄
