### ISSUE TITLE
bug: Syncer not working when running on openshift local cluster (Need Assistance)

### ISSUE THREAD

**Issue by vishnuchalla** [kcp-dev/kcp#2623]
### Describe the bug

I followed the steps in these docs:

* https://cloud.redhat.com/blog/an-introduction-to-kcp
* https://github.com/kcp-dev/kcp
* https://github.com/kcp-dev/kcp/blob/main/docs/content/en/main/concepts/syncer.md
* Syncer Used: https://github.com/kcp-dev/kcp/pkgs/container/kcp%2Fsyncer

But the syncer doesn't seems to be working. Need assistance on this issue. Attaching the commands executed and the error logs.

Commands executed:
```
./bin/kubectl-kcp workload sync 27fb7fae-1398-413a-ad45-eb0b1affb9fb --syncer-image ghcr.io/kcp-dev/kcp/syncer:9358474 -o syncer-kind-main.yaml

kubectl --kubeconfig /home/vchalla/.kube/config apply -f syncer-kind-main.yaml
```
Error logs in the pod of the physical cluster:
```
[vchalla@vchalla benchmark-operator]$ oc logs pod/kcp-syncer-27fb7fae-1398-413a-ad45-eb0b1affb9fb-1op1emwx-64npvn -f
I0114 22:51:20.969585       1 syncer.go:83] "syncing" resource-types=[]
I0114 22:51:20.970845       1 syncer.go:85] "starting syncer" syncTarget.workspace="1m2w8j4oqnq8bzr1" syncTarget.name="27fb7fae-1398-413a-ad45-eb0b1affb9fb"
I0114 22:51:20.971057       1 syncer.go:113] "attempting to retrieve the Syncer virtual workspace URL" syncTarget.workspace="1m2w8j4oqnq8bzr1" syncTarget.name="27fb7fae-1398-413a-ad45-eb0b1affb9fb"
E0114 22:51:20.974882       1 run.go:74] "command failed" err="Get \"https://192.168.86.24:6443/clusters/1m2w8j4oqnq8bzr1/apis/workload.kcp.io/v1alpha1/synctargets/27fb7fae-1398-413a-ad45-eb0b1affb9fb\": dial tcp 192.168.86.24:6443: connect: no route to host"
```

Becuase of this error couldn't see any deployment resources in the KCP workspace:
```
[vchalla@vchalla kcp]$ kubectl wait --for=condition=Ready synctarget/27fb7fae-1398-413a-ad45-eb0b1affb9fb 
error: timed out waiting for the condition on synctargets/27fb7fae-1398-413a-ad45-eb0b1affb9fb
[vchalla@vchalla kcp]$ kubectl api-resources | grep -i deployment
```

### Steps To Reproduce

1. Start KCP server on your local laptop
2. Along with that start CRC openshift single node cluster on your laptop and have its kubeconfig to deploy applications
3. Now from your workspace execute the follow commands
```
./bin/kubectl-kcp workload sync 27fb7fae-1398-413a-ad45-eb0b1affb9fb --syncer-image ghcr.io/kcp-dev/kcp/syncer:9358474 -o syncer-kind-main.yaml

kubectl --kubeconfig /home/vchalla/.kube/config apply -f syncer-kind-main.yaml
```
4. A namespace gets created in the cluster and syncer pod runs into error with the following message.
```
[vchalla@vchalla benchmark-operator]$ oc logs pod/kcp-syncer-27fb7fae-1398-413a-ad45-eb0b1affb9fb-1op1emwx-64npvn -f
I0114 22:51:20.969585       1 syncer.go:83] "syncing" resource-types=[]
I0114 22:51:20.970845       1 syncer.go:85] "starting syncer" syncTarget.workspace="1m2w8j4oqnq8bzr1" syncTarget.name="27fb7fae-1398-413a-ad45-eb0b1affb9fb"
I0114 22:51:20.971057       1 syncer.go:113] "attempting to retrieve the Syncer virtual workspace URL" syncTarget.workspace="1m2w8j4oqnq8bzr1" syncTarget.name="27fb7fae-1398-413a-ad45-eb0b1affb9fb"
E0114 22:51:20.974882       1 run.go:74] "command failed" err="Get \"https://192.168.86.24:6443/clusters/1m2w8j4oqnq8bzr1/apis/workload.kcp.io/v1alpha1/synctargets/27fb7fae-1398-413a-ad45-eb0b1affb9fb\": dial tcp 192.168.86.24:6443: connect: no route to host"
```
5. Due to this syncer is not working and couldn't proceed further.

### Expected Behaviour

Expecting syncer to work as specified in the docs and README.mds

**Comment by vishnuchalla** [comment]
Similar issues:
https://github.com/kcp-dev/kcp/issues/2439
https://github.com/kcp-dev/kcp/issues/1434

**Comment by nrb** [comment]
@davidfestal Could you please take a look at this?

**Comment by davidfestal** [comment]
@vishnuchalla Please have a look at this comment of issue #2439: https://github.com/kcp-dev/kcp/issues/2439#issuecomment-1387160462

**Comment by vishnuchalla** [comment]
Can you please elaborate a bit more on how this parameter should be used?
in the help section this is the description we see
```
--external-hostname string                                                                                                                                                                          
The hostname to use when generating externalized URLs for this master (e.g. Swagger API Docs or OpenID Discovery).
```
I have tried pointing out my CRC URL and used kcp start
```
./bin/kcp start --external-hostname=api.crc.testing
```
It has started but when i execute command i see the below error
```
error checking APIBindings: Get "https://api.crc.testing:6443/clusters/root/apis/apis.kcp.io/v1alpha1/apibindings": x509: certificate signed by unknown authority
Current workspace is "root".
```
@davidfestal  It will be very helpfull If you can share some examples of the above mentioned parameter or  the command which you use while testing with CRC/Kind. 

Thank You.

**Comment by fgiloux** [comment]
too many threads on the same thing:
- slack: https://kubernetes.slack.com/archives/C021U8WSAFK/p1673903469789369
- issue 2439 https://github.com/kcp-dev/kcp/issues/2439#issuecomment-1396089627
- this issue

**Comment by vishnuchalla** [comment]
Closing the issue as crc is able to reach syncer and the syncer pod is running. Followed the steps mentioned the slack discussion for resolution: https://kubernetes.slack.com/archives/C021U8WSAFK/p1673903469789369
