### ISSUE TITLE
Community Meeting January 24, 2023

### ISSUE THREAD

**Issue by nrb** [kcp-dev/kcp#2633]
### Overview

At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/mpd-cypd-sdp
Or dial: ‪(DE) +49 30 300195060‬ PIN: ‪500 599 130 5702‬#
More phone numbers: https://tel.meet/mpd-cypd-sdp?pin=5005991305702
Or join via SIP: sip:5005991305702@gmeet.redhat.com

Meeting recordings available on YouTube at https://www.youtube.com/playlist?list=PLqN7RcoCwL96nXIIW6O51l8Lu_J-f5D27

Add topics you'd like to discuss below!

**Comment by clubanderson** [comment]
- discuss the creation of a forum-kcpedge slack channel that can be used to post issue and PR information outside of the forum-kcp slack channel.  Would like to avoid making noise in the forum-kcp forum for items related to sigkcpedge.

**Comment by MikeSpreitzer** [comment]
Refactor to solve https://github.com/kcp-dev/kcp/issues/2668

**Comment by lionelvillard** [comment]
Service provider use case: https://kubernetes.slack.com/archives/C021U8WSAFK/p1674571037654829?thread_ts=1674500735.936609&cid=C021U8WSAFK
