### ISSUE TITLE
Something Goofy in CRD Bootstrapping Wastes 5s

### ISSUE THREAD

**Issue by stevekuznetsov** [kcp-dev/kcp#264]
The bootstrapping in `config/bootstrap.go` is supposed to be quick. Something about the ordering of it makes the process take *just* over 5s, making me think we're hitting some retry/backoff since we're rushing too early to create the CRD and perhaps need to wait on ... something?

```
I1201 13:36:33.618595   76053 bootstrap.go:61] bootstrapping clusters.cluster.example.dev
I1201 13:36:33.618641   76053 bootstrap.go:61] bootstrapping apiresourceimports.apiresource.kcp.dev
I1201 13:36:33.618649   76053 bootstrap.go:61] bootstrapping negotiatedapiresources.apiresource.kcp.dev
I1201 13:36:38.628173   76053 bootstrap.go:63] bootstrapped clusters.cluster.example.dev after 5.009579489s
I1201 13:36:38.630887   76053 bootstrap.go:63] bootstrapped apiresourceimports.apiresource.kcp.dev after 5.012248883s
I1201 13:36:38.635500   76053 bootstrap.go:63] bootstrapped negotiatedapiresources.apiresource.kcp.dev after 5.016852398s
```

**Comment by stevekuznetsov** [comment]
Actually now that I notice we're doing CRD bootstrapping in each logical cluster serially, 10s of the 10.2s of our e2e tests comes down to this. Would be super to cut it out.

**Comment by stevekuznetsov** [comment]
My first guess would be that we create the CRD before the controller that accepts them is ready to go or something or we hit a backoff/retry?

**Comment by kylape** [comment]
The CRD established condition is set to false with a reason of `Installing` immediately, and then 5 seconds later it is set to `True`with reason `InitialNamesAccepted`.

It seems like a 5 second delay is hard-coded into the CRD handler after the `Established` condition is `False` and the `NamesAccepted` condition is `True` (https://github.com/kcp-dev/kubernetes/blob/feature-logical-clusters-1.22/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go#L630-L637).

I figured that the master count was 1, but it is actually hard coded to 3: https://github.com/kcp-dev/kubernetes/commit/a18ab2fd16ef0070cc130652adabf0d8c5473860

**Comment by stevekuznetsov** [comment]
Ah, right - I remember reading that handler logic once, now... nice digging! Let's un-hardcode the master count, I think? @imjasonh @smarterclayton any downsides to that?

**Comment by ncdc** [comment]
To unblock us, resetting to 1 sounds reasonable. Perhaps we should also file an issue to come back to it, so we don't forget?

**Comment by stevekuznetsov** [comment]
@kylape went on PTO so I will take this one.
