### ISSUE TITLE
bug: documentation is outdated but allegedly current

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/kcp#2655]
### Describe the bug

I think we agreed that https://docs.kcp.io/kcp should have the capability to hold docs for multiple releases, and the existence of the "Releases" menu looks like an attempt to realize that.  But:

1. there is only one choice available now, "main", and
2. the documentation there is for older releases.

See the attached screenshot.

<img width="1027" alt="Screen Shot 2023-01-19 at 3 22 03 PM" src="https://user-images.githubusercontent.com/14296719/213552468-01ee4460-a92c-4153-8caa-9595183d5aa5.png">

I understand that it will take some time to update the documentation for the current release.  As we work through that process, it would probably be less confusing if there were at least two choices under the "Releases" menu, one getting updated for the current truth and one preserving the existing documentation (seems a shame to simply discard what has been written).

### Steps To Reproduce

1. Try to follow the documented steps with the currrent release

### Expected Behaviour

See above.

**Comment by MikeSpreitzer** [comment]
Issue #2615 mentions some ways in which the current documentation is not accurate.

There are also changes in workspace naming since v0.10.0, for another example.

**Comment by MikeSpreitzer** [comment]
Issue #2597 also mentions changes needed.

**Comment by ncdc** [comment]
Not quite fixed yet
/reopen

**Comment by ncdc** [comment]
We now have multiple versions!
