### ISSUE TITLE
bug: View lists a resource but does not allow it to be listed

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/kcp#2663]
### Describe the bug

I am trying my own APIExports for the first time, and getting a mysterious failure.  Help?

The text snippet here shows me trying to use the view associated with my APIExport, which you can find at https://github.com/MikeSpreitzer/kcp-edge-mc/blob/7bf49350822ba398e9ed0d5960d247ea21ec31a5/config/exports/apiexport-edge.kcp.io.yaml ; the associated things are nearby.

`kubectl api-resources` reports what I expect.  But `kubectl get` produces a server complaint that it does not know about the resource --- even though it is one of those reported in `kubectl api-resources`.  And when I try to get apibindings from that view, it works.  Also, not shown, when I try the analogous things with other APIExports, such as scheduling.kcp.io, even the `kubectl get` works as expected.

This is all done with commit 4506fdc06406 of kcp-dev/kcp, which is from Jan 19 morning.

```
(base) mspreitz@mjs12 edge-mc % kubectl get APIExport edge.kcp.io -o yaml
apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  annotations:
    kcp.io/cluster: root
    kcp.io/path: root
  creationTimestamp: "2023-01-20T19:32:48Z"
  generation: 2
  name: edge.kcp.io
  resourceVersion: "617"
  uid: d8fd0005-96f1-4246-b51d-8ba597c21966
spec:
  identity:
    secretRef:
      name: edge.kcp.io
      namespace: kcp-system
  latestResourceSchemas:
  - v230120-16735ad.edgeplacements.edge.kcp.io
  - v230120-16735ad.singleplacementslice.edge.kcp.io
status:
  conditions:
  - lastTransitionTime: "2023-01-20T19:32:48Z"
    status: "True"
    type: IdentityValid
  - lastTransitionTime: "2023-01-20T19:32:48Z"
    status: "True"
    type: VirtualWorkspaceURLsReady
  identityHash: c0cd9248affbddd74999b89845ae64d7b74224782c55588138922431b56350c2
  virtualWorkspaces:
  - url: https://192.168.58.123:6443/services/apiexport/root/edge.kcp.io
  
(base) mspreitz@mjs12 edge-mc % kubectl api-resources --server https://192.168.58.123:6443/services/apiexport/root/edge.kcp.io/clusters/%2a
NAME                   SHORTNAMES   APIVERSION             NAMESPACED   KIND
apibindings                         apis.kcp.io/v1alpha1   false        APIBinding
edgeplacements                      edge.kcp.io/v1alpha1   false        EdgePlacement
singleplacementslice                edge.kcp.io/v1alpha1   false        SinglePlacementSlice

(base) mspreitz@mjs12 edge-mc % kubectl get --server https://192.168.58.123:6443/services/apiexport/root/edge.kcp.io/clusters/%2a edgeplacements
Error from server (NotFound): Unable to list "edge.kcp.io/v1alpha1, Resource=edgeplacements": the server could not find the requested resource

(base) mspreitz@mjs12 edge-mc % kubectl get --server https://192.168.58.123:6443/services/apiexport/root/edge.kcp.io/clusters/%2a apibindings
No resources found
```

Then I added -v=8 to get more details.  Following are the failing GET for edgeplacements and the successful GET for apibindings.

```
I0120 14:59:26.253925   37632 round_trippers.go:463] GET https://192.168.58.123:6443/services/apiexport/root/edge.kcp.io/clusters/%2A/apis/edge.kcp.io/v1alpha1/edgeplacements?limit=500
I0120 14:59:26.253934   37632 round_trippers.go:469] Request Headers:
I0120 14:59:26.253942   37632 round_trippers.go:473]     Accept: application/json;as=Table;v=v1;g=meta.k8s.io,application/json;as=Table;v=v1beta1;g=meta.k8s.io,application/json
I0120 14:59:26.253948   37632 round_trippers.go:473]     User-Agent: kubectl/v1.25.0 (darwin/amd64) kubernetes/a866cbe
I0120 14:59:26.253955   37632 round_trippers.go:473]     Authorization: Bearer <masked>
I0120 14:59:26.255536   37632 round_trippers.go:574] Response Status: 404 Not Found in 1 milliseconds
I0120 14:59:26.255550   37632 round_trippers.go:577] Response Headers:
I0120 14:59:26.255556   37632 round_trippers.go:580]     Audit-Id: de6f3dd4-3c17-4297-8dc9-8d2acac95c73
I0120 14:59:26.255562   37632 round_trippers.go:580]     Cache-Control: no-cache, private
I0120 14:59:26.255567   37632 round_trippers.go:580]     Content-Type: application/json
I0120 14:59:26.255573   37632 round_trippers.go:580]     Content-Length: 253
I0120 14:59:26.255578   37632 round_trippers.go:580]     Date: Fri, 20 Jan 2023 19:59:26 GMT
I0120 14:59:26.255596   37632 request.go:1073] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{"causes":[{"reason":"UnexpectedServerResponse","message":"404 page not found"}]},"code":404}
```

```
I0120 15:01:48.096642   37639 round_trippers.go:463] GET https://192.168.58.123:6443/services/apiexport/root/edge.kcp.io/clusters/%2A/apis/apis.kcp.io/v1alpha1/apibindings?limit=500
I0120 15:01:48.096651   37639 round_trippers.go:469] Request Headers:
I0120 15:01:48.096659   37639 round_trippers.go:473]     Authorization: Bearer <masked>
I0120 15:01:48.096665   37639 round_trippers.go:473]     Accept: application/json;as=Table;v=v1;g=meta.k8s.io,application/json;as=Table;v=v1beta1;g=meta.k8s.io,application/json
I0120 15:01:48.096671   37639 round_trippers.go:473]     User-Agent: kubectl/v1.25.0 (darwin/amd64) kubernetes/a866cbe
I0120 15:01:48.103386   37639 round_trippers.go:574] Response Status: 200 OK in 6 milliseconds
I0120 15:01:48.103400   37639 round_trippers.go:577] Response Headers:
I0120 15:01:48.103407   37639 round_trippers.go:580]     Content-Length: 698
I0120 15:01:48.103413   37639 round_trippers.go:580]     Date: Fri, 20 Jan 2023 20:01:48 GMT
I0120 15:01:48.103418   37639 round_trippers.go:580]     Audit-Id: f3ec4d78-2377-42b6-9b08-83f40c49db90
I0120 15:01:48.103423   37639 round_trippers.go:580]     Cache-Control: no-cache, private
I0120 15:01:48.103430   37639 round_trippers.go:580]     Content-Type: application/json
I0120 15:01:48.103444   37639 request.go:1073] Response Body: {"kind":"Table","apiVersion":"meta.k8s.io/v1","metadata":{"resourceVersion":"625"},"columnDefinitions":[{"name":"Name","type":"string","format":"name","description":"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names","priority":0},{"name":"Age","type":"date","format":"","description":"Custom resource definition column (in JSONPath format): .metadata.creationTimestamp","priority":0}],"rows":[]}
```

### Steps To Reproduce

1. `kubectl create -f config/crds`
2. `kubectl create -f config/exports`
3. Examine as shown above.

### Expected Behaviour

I expected the server to return a list of zero edgeplacements rather than an error about not knowing about edgeplacements.

### Additional Context

I am told that if there were APIBindings against that export then the view would work as expected.

**Comment by MikeSpreitzer** [comment]
I have experimentally confirmed that creating an APIBinding against my APIExport causes the view to work as expected.

**Comment by p0lyn0mial** [comment]
@MikeSpreitzer are you planning to work on a fix ? If not then I can pick it up. Please just let me know.

**Comment by p0lyn0mial** [comment]
> I am told that if there were APIBindings against that export then the view would work as expected.

that is correct, creating an APIBinding essentially installs the API in the server.

I can think of at least a few potential fixes for the issue. I'm not sure which one is the best, comments are welcome.


1. We could map the error in the VW server and simply return an empty list. The biggest drawback is that controllers would connect to VW servers which hasn't bound to the APIExport.

2. We could filter `APIExporot.virtualWorkspaces` (`APIExportEndpointSlice` in the future) down to VW servers that have already bound to the APIExport. It seems to be easy on a single-shard but a bit compliated on a multi-shard env.

    2.1. The APIExport controller could try to hit an VW server before updating `APIExporot.virtualWorkspaces`/`APIExportEndpointSlice`. 

    2.1.1. Each shard reconcile `global` APIExports driven by updates to local `APIBinding`. This approach would require a way of updating global resources from each shard/controller (possibly via the front-proxy). 

    2.1.2. The APIExport controller reconciles `local` APIExports and tries `all/applicable` shards. This approach would require some sort of periodic reconcilation as we have a no way of knowing if somebody has bound to us on a different shard.

3. We add a new resource or extend an existing one that would let us deterime if an APIBinding on some shard has bound to an APIExport.

4. ?

**Comment by fgiloux** [comment]
(1) When we discussed it with @sttts I think  that (1) was the preferred approach.
By using Partitions service providers have the option to filter out Shards, hence  VirtualWorkspaces they are not interested in or to take the opposite approach and select Shards they want to serve. The cost of (1):
- on the API side: an unnecessary watch connection till an APIBinding is created on the shard
- on the service provider side: a thread connected to the VW not processing any payload
I would think that it may be acceptable in a production phase where the number of controllers is limited, pretty stable and carefully configured. What about a development phase? I would expect controller developers to use defaults and have an APIExportEndpointSlice without Partitions. It means with the current design that all the VW URLs would be listed when controllers would actually interact with a single VW most of the time during the tests. A possibility would be to change the defaults and only have the VW URL of the local shard when no Partition is set. We may have done the other way around to be consistent with the previous mechanism in APIExport.
 
 (2) I am not a fan of it. I would avoid any cross-shard communication as part of any reconciliation mechanism. I would not take for granted that communication across all shards is possible.
 
 (3) I would see it as an option, although it puts more load onto the cache server, which should be avoided whenever possible
 
 (4) I don't have any better idea
