### ISSUE TITLE
bug: generated listers report $kind.$group instead of $resource.$group not found

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#2679]
### Describe the bug

When using one of our generated listers to get an object, if it's not found, the error comes back like this:

```
Error from server (NotFound): APIExport.apis.kcp.io "today-cowboys" not found
```

Note the use of `APIExport`. To be consistent with the rest of the code, it should be `apiexports.apis.kcp.io` (resource, not kind).

### Steps To Reproduce

See above

### Expected Behaviour

See above

**Comment by ncdc** [comment]
FYI @stevekuznetsov

**Comment by stevekuznetsov** [comment]
/assign

Upstream fix: https://github.com/kcp-dev/code-generator/pull/79

**Comment by stevekuznetsov** [comment]
https://github.com/kcp-dev/client-go/pull/22
