### ISSUE TITLE
bug: Possible to schedule a workspace onto a just-deleted Shard

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#2686]
### Describe the bug

Due to a timing issue, it's sometimes possible to schedule a Workspace onto a just-deleted Shard

### Steps To Reproduce

1. Delete a Shard
2. Immediately create a Workspace
3. Workspace is sometimes (rarely) scheduled to the just-deleted Shard

### Expected Behaviour

Workspace is not scheduled to just-deleted Shard

### Additional Context

This was originally seen in #2603. That test deletes the root shard, creates a workspace, and expects the workspace to remain unscheduled until a new shard is created. This happens (rarely) when the shard informer's cache is out of date. While the shard is legitimately deleted from etcd, the informer hasn't seen the deletion yet, and the workspace reconciler proceeds to schedule onto the shard.

**Comment by stevekuznetsov** [comment]
Do we need to add a live GET after we choose a shard from the cache?

**Comment by ncdc** [comment]
That and/or a way to prevent the deletion of a shard if it has workspaces scheduled to it
