### ISSUE TITLE
bug: confusing error message about workspace name

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/kcp#2692]
### Describe the bug

I tried creating a workspace with a funky name and it failed with a compound error message that:
(a) makes an incorrect English statement of what is allowed, and
(b) contains two different regular expressions describing what is allowed (these two regexes match different sets of strings).

```
(base) mspreitz@mjs12 kcp % kubectl ws create ab-.-cd-.-ef
Error: Workspace.tenancy.kcp.io "ab-.-cd-.-ef" is invalid: [metadata.name: Invalid value: "ab-.-cd-.-ef": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.name: Invalid value: "ab-.-cd-.-ef": metadata.name in body should match '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$']
```

Then I tried creating a workspace with a different funky name, and it failed with a shorter error message that only asserted one regex.

```
(base) mspreitz@mjs12 kcp % kubectl ws create ab-w.w-cd-w.w-ef
Error: Workspace.tenancy.kcp.io "ab-w.w-cd-w.w-ef" is invalid: metadata.name: Invalid value: "ab-w.w-cd-w.w-ef": metadata.name in body should match '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$'
```

### Steps To Reproduce

Shown above.

### Expected Behaviour

Consistency.

### Additional Context

This was using commit 4506fdc0 .

**Comment by stevekuznetsov** [comment]
Corollary nit: should not be capitalizing `Workspace.tenancy...`
