### ISSUE TITLE
test: e2e: allow "bring your own" kcp mode

### ISSUE THREAD

**Issue by stevekuznetsov** [kcp-dev/kcp#270]
Right now the e2e framework starts a `kcp` server or servers internally to the test. While this has many advantages, in some cases a dev may want to provide a running `kcp` to a test instead (for example when they control where break-points and/or debugging exist in the running server). We should allow for this somehow, but not try to check that the given `kcp` is conformant, etc.

/cc @sttts

**Comment by ncdc** [comment]
Is this something we still need, now that we can run tests with kcp in-process for debugging?

**Comment by marun** [comment]
I think we still need this. Running kcp in-process today still implies spinning up a server for ever test or set of tests. Ideally it will be possible for an e2e run to target a single persistent server/set of servers to minimize test runtime and resource utilization.

**Comment by ncdc** [comment]
Is "a persistent set of servers" equivalent to "BYO kcp", or can they be differentiated? In other words, if we could do persistent servers in the e2e (be they in-process or external), would we still **also** want BYO kcp?

**Comment by marun** [comment]
I don't think BYO is different from persistent servers. In either case, the server deployment would be performed before a starting a test run, and the run would need to be configured to use the servers. The heavy lifting here will be in ensuring our e2e tests are sufficiently isolated and idempotent to support running against a persistent server.

**Comment by ncdc** [comment]
This is done with `--use-default-kcp-server`
