### ISSUE TITLE
bug: inconsist required versions for cel-go

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/kcp#2700]
### Describe the bug

https://github.com/kcp-dev/kcp/blob/main/go.mod requires v0.12.6
https://github.com/kcp-dev/kubernetes/blob/kcp-feature-logical-clusters-1.24-v3/go.mod requires v0.10.1

### Steps To Reproduce

Read above

### Expected Behaviour

kcp-dev/kcp and kcp-dev/kubernetes require the same versions of stuff

**Comment by ncdc** [comment]
0.12.6 is correct. Would you be willing to fix?

**Comment by MikeSpreitzer** [comment]
Yes.

**Comment by MikeSpreitzer** [comment]
Thanks!
