### ISSUE TITLE
Document how to view gathered metrics from e2e tests

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#2706]
#2705 added gathering metrics for e2e tests. We should document how to view these metrics and what to look for when tests are flaky.

**Comment by stevekuznetsov** [comment]
@sttts can we use the OCP solution for metrics from tests here?

**Comment by s-urbaniak** [comment]
@stevekuznetsov I found the spot where we snapshot metrics in OCP, it's part of the gather-extra suite: https://github.com/openshift/release/blob/0da1c1404ba699a67c653a061947fee7b8dabdd6/ci-operator/step-registry/gather/extra/gather-extra-commands.sh#L208-L240

**Comment by s-urbaniak** [comment]
OCP though snapshots in-cluster monitoring only, kcp metrics won't be part of that. We have two possibilities:

- enable user workload monitoring (https://docs.openshift.com/container-platform/4.12/monitoring/enabling-monitoring-for-user-defined-projects.html), gather kcp metrics there, and snapshot that prometheus.
- deploy our own Prometheus instance, and snapshot that database

Once we have any prometheus instance running, we can leverage the gather-extra script above to dump metrics data.

**Comment by stevekuznetsov** [comment]
@s-urbaniak option 2 (our own Prom) sounds like the winner here -  we're running in-process, remember, not on any k8s :)

**Comment by s-urbaniak** [comment]
done:

- https://github.com/kcp-dev/kcp/pull/2774
- https://github.com/openshift/release/pull/36509
- https://github.com/vrutkovs/promecieus/pull/16
- https://kubernetes.slack.com/archives/C021U8WSAFK/p1676975581816679

**Comment by s-urbaniak** [comment]
oh, not so fast, we need a bit of documentation as well as the title says 😅
