### ISSUE TITLE
feature: Option to create a namespace in workload cluster with same name as it is in KCP workspace

### ISSUE THREAD

**Issue by vishnuchalla** [kcp-dev/kcp#2721]
### Feature Description

For Example:
if we create a namespace and create a deployment in our KCP workspace using the below commands:
`kubectl create namespace reverse-words`
`kubectl -n reverse-words create deployment reversewords --image quay.io/mavazque/reversewords:latest`

The Namespace that gets created in our workload cluster inorder to run the deployment is as follows with a random name and UID:
`kubectl --kubeconfig /root/ztp-sno-cluster/kubeconfig get pods -A -l app=reversewords`
`NAMESPACE             NAME                    READY   STATUS    RESTARTS   AGE`
`kcp3afd937aa6  reversewords-6776c6fccc-kr6vw   1/1    Running      0        7m2s`

This is creating problem in running our team's benchmarking workloads. 
We have an ansible operator: https://github.com/cloud-bulldozer/benchmark-operator. It creates all its resources with a namespace `benchmark-operator`. And all those workloads are strictly subjected to run under the same namespace `benchmark-operator`. And the problem is we cannot keep on modifying our Custom Resource Definitions (CRDs) in the runtime in order to make them run on that randomly named namespace through our operator code.

#### Related error in our operator:
`
{"level":"error","ts":1675211122.879487,"logger":"controller-runtime.manager.controller.benchmark-controller","msg":"Reconciler error","name":"uperf-benchmark","namespace":"benchmark-operator","error":"event runner on failed","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:302\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99"}
`

### Proposed Solution

Requesting to create the namespace with same name as it is in the KCP workspace.
For example, if we create a namespace and create a deployment in our KCP workspace using the below commands:
`kubectl create namespace reverse-words`
`kubectl -n reverse-words create deployment reversewords --image quay.io/mavazque/reversewords:latest`

The Namespace that gets created in our workload cluster should have the same name as `reverse-words`. And the deployment should be running inside it as follows:
`kubectl --kubeconfig /root/ztp-sno-cluster/kubeconfig get pods -A -l app=reversewords`
`NAMESPACE             NAME                    READY   STATUS    RESTARTS   AGE`
`reverse-words  reversewords-6776c6fccc-kr6vw   1/1    Running      0        7m2s`

### Alternative Solutions

Or else another approach would be simply create the namespace on the workload cluster with the same name as it has on KCP workspace by default.

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

Please let us know if you have any questions/concerns on this proposal.

**Comment by ncdc** [comment]
As discussed in today's community meeting, this is not needed at the moment
