### ISSUE TITLE
bug: menu bar of docs website is misleading when narrow

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/kcp#2723]
### Describe the bug

When viewing https://docs.kcp.io/kcp/main/ in a browser window of the width I typically use, the menu bar is incomplete and the user gets no clue that items are omitted.  The attached screenshot shows an example.

<img width="944" alt="Screen Shot 2023-01-31 at 10 46 26 PM" src="https://user-images.githubusercontent.com/14296719/215940705-2d1c0e4c-9919-4843-a0b9-99af287845be.png">

### Steps To Reproduce

Visit that web site and play around with the browser window width.

### Expected Behaviour

When items are omitted I expect a concise way to reach them (e.g., hamburger menu or "..."), or at least a visual clue that there is more to see.

**Comment by ncdc** [comment]
Closing as we've switched to mkdocs with a new theme and this should be resolved. @MikeSpreitzer please let me know if you see otherwise.
