### ISSUE TITLE
bug: sometimes preexisting resources don't get permission claims labels applied

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#2738]
From https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/kcp-dev_kcp/2736/pull-ci-kcp-dev-kcp-main-e2e-sharded/1621176724005851136

```
    virtualworkspace_test.go:693: Verify that two sherrifs are eventually returned
    assertions.go:1691: Waiting for condition, but got: did not find both objects:   []string{
          	"in-vw",
        - 	"in-vw-before",
          }
    virtualworkspace_test.go:694: 
        	Error Trace:	util.go:328
        	            				virtualworkspace_test.go:694
        	Error:      	Condition never satisfied
        	Test:       	TestAPIExportPermissionClaims
        	Messages:   	unable to wait for the two objects to be returned
--- FAIL: TestAPIExportPermissionClaims (70.31s)
```

**Comment by stevekuznetsov** [comment]
Huh, I had thought this was my mistake. Is it an eventuality issue with the export/binding data?

**Comment by ncdc** [comment]
I actually don't know :-/

**Comment by ncdc** [comment]
I think I've maybe seen this pre-sharding

**Comment by ncdc** [comment]
```
E0202 16:08:48.534393     692 watcher.go:349] failed to prepare current and previous objects: request to convert CR from an invalid group/version: wild.wild.west/v1
```

Something is up with wildcard partial metadata informers, multiple versions, and something thinking it needs to do a conversion

**Comment by ncdc** [comment]
Ok, making some progress:

## Issue 1

- For wildcard partial metadata requests, the `apiBindingAwareCRDLister` lists (via index) all CRDs that serve the requested group+resource (version is purposefully ignored) and returns the first matching CRD for use by the apiserver
- In k8s `crdHandler.ServeHTTP`,it checks to make sure the CRD returned from the lister actually serves the API version the user requested. It ends up returning a 404 if not, which is potentially a problem for us. For example:

* Workspace 1
    * CRD widgets.kcp.io
        * Only serves v1alpha1
* Workspace 2
    * CRD widgets.kcp.io
        * Only serves v1

If the partial metadata informers (DDSIF) ask for `/clusters/*/apis/kcp.io/v1/widgets`, there's a chance the flow will use the "wrong" CRD (from Workspace 1, which only knows about v1alpha1), and the response will end up being a 404.

**Possible fix:**

- Skip checking if the CRD serves the requested API version if it's a wildcard partial metadata request
- Also, in `crdHandler.serveResource`, because it uses the requested API version to pick the `requestScope` and `storage`, we'd need to pick any random scope+storage to use if the requested API version doesn't exist in the CRD from the lister
- It's probably also a good idea to set the converter used for wildcard partial metadata requests in `crdHandler.getOrCreateServingInfoFor` to a `nopConverter`

## Issue 2

- The watch cache for a "normal" (non wildcard partial metadata) CRD storage is configured to list data from etcd using a prefix of the form `/registry/$group/$resource/customresources`
- It creates a ListerWatcher that talks directly to etcd and it uses the standard CRD conversion logic to convert items if needed
- Unfortunately, because the etcd prefix is for **all** CRs for the group+resource, it potentially gets data for CRs whose version isn't served by the CRD (e.g., for the example above, the watch cache for widgets in Workspace 1 would only be able to process v1alpha1 widgets, but it would also receive v1 widgets and have problems w/them)
- Example error: `request to convert CR from an invalid group/version: kcp.io/v1`
- Also, this creates 1 cache per workspace+CRD

**Possible fix:**
- Maybe modify the watch cache code so it only creates 1 cache per CRD, instead of 1 per workspace+CRD
- This would need to support filtering, so each workspace had a cache with only its CRs
- This might be a pretty invasive change, so if there are easier/better options...

**Comment by ncdc** [comment]
cc @p0lyn0mial @sttts re watch cache
