### ISSUE TITLE
c.CacheDynamicClient uses default QPS/burst settings and gets throttled

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#2743]
We should choose a better default (or disable QPS entirely), and possibly make it configurable.

**Comment by p0lyn0mial** [comment]
I don't think we should disable QPS now. The cache-server is not protected by `Priority and Fairness`.
More shards will but more load on the cache-server. 
It looks like client-side rate limiting is our only option for now.

Not sure what it would take to enable `APF` on the server.
Now, I'm not even sure we use `max-requests-inflight` in the cache-server.

**Comment by ncdc** [comment]
Fair... but let's go with something with more than the default settings?

**Comment by p0lyn0mial** [comment]
> Fair... but let's go with something with more than the default settings?

+1

Should I prep something or leave it to you?

**Comment by ncdc** [comment]
Up to you 😀

**Comment by p0lyn0mial** [comment]
OK, I'll prepare a PR. Thanks for reporting!
