### ISSUE TITLE
Register a physical cluster with KCP: Syncer runs as an agent

### ISSUE THREAD

**Issue by pweil-** [kcp-dev/kcp#275]
Use Case: Register a physical cluster with KCP

Objectives

- [ ] User can register a physical cluster with KCP
- [ ] Syncer can be run as an agent in a cluster
- [ ] Syncer uses minimal permissions

Details: 

Syncer runs as an agent

Proposed: kcp start syncer --from SHARD_URL --to <implicit_in_cluster_Kubeconfig/explicit_kubeconfig>
Proposed: syncer emulates “watch workspaces in this location” by LISTing/WATCHing all workspaces on the shard
Proposed: syncer has a set of builtin strategies that can be easily contributed to

**Comment by pweil-** [comment]
/assign @imjasonh 

@imjasonh `syncer has a set of builtin strategies that can be easily contributed to` felt like maybe it was separate from the first two but I didn't break it out since it was under the same high level item in our doc.  I can do that if you agree.

**Comment by ncdc** [comment]
Replaced by #418
