### ISSUE TITLE
Workspace Administration and Tenancy: Prefill APIs

### ISSUE THREAD

**Issue by pweil-** [kcp-dev/kcp#277]
Use Case: Workspace Administration and Tenancy

Objectives:

- [x] https://github.com/kcp-dev/kcp/pull/302: An admin can prefill a workspace with a set of APIs that match a type
- [ ] A user can be granted workspace access with minimal object/etcd fanout, depending on https://github.com/kcp-dev/kcp/issues/278 without tons of RBAC objects in every workspace (bootstrap policy).
- [x] https://github.com/kcp-dev/kcp/pull/302: A workspace can be typed as “organizational” and contain other workspaces.  Initially there will be a single org workspace, admin
- [ ] https://github.com/kcp-dev/kcp/pull/302: Lack of workspace in org workspace gates user access, depending on 
  1. workspace authz (first authz level), part of https://github.com/kcp-dev/kcp/issues/278, checking the existence of Role+RoleBinding in the org workspace
  2. existence of org workspaces (could be admin for the prototype).

Details

- [x] 1. Add a field on Workspace that references a logical cluster to inherit types from, update the API virtualization logic to look there instead of root cluster, merge the default types still
- [X] 2. ~Add internal machinery for logical cluster abstraction into the serving chain to support “can user access this logical cluster”~ This is #278
- [x] 3. /apis decoration with CRDs depending on logical cluster 
- [x] 4. apiextensions-apiserver logical cluster inheritance

**Comment by pweil-** [comment]
Notes from slack:

```
I think I have 2 remaining pieces to the API inheritance puzzle:
Undo my SetCRDClient hack
Fix OpenAPI so it includes inherited CRDs
I did find & fix an issue w/OpenAPI not getting updated correctly for all logical clusters - https://github.com/ncdc/kubernetes/commit/a5f6a340084296b2105319a6cd8e15cca3926528
```

**Comment by ncdc** [comment]
#302 covers details 1, 3, and 4.

I'd recommend we file a separate issue for detail 2. Thoughts?

Also, my PR does not cover "organizational" workspaces - it hard codes the `admin` logical cluster as the only place that supports API inheritance via Workspaces. If that is sufficient for prototype 2, could we create new issue(s) for fleshing out org workspaces post-prototype 2?

@pweil- @smarterclayton

**Comment by pweil-** [comment]
> Also, my PR does not cover "organizational" workspaces - it hard codes the `admin` logical cluster as the only place that supports API inheritance via Workspaces. If that is sufficient for prototype 2, could we create new issue(s) for fleshing out org workspaces post-prototype 2?

Inheritance only from `admin` was fine during the last discussion so I think we're good to file a new issue to refine that post-prototype2.   

Created https://github.com/kcp-dev/kcp/issues/307, please refine as necessary

> I'd recommend we file a separate issue for detail 2. Thoughts?
https://github.com/kcp-dev/kcp/issues/306

**Comment by sttts** [comment]
Remaining (2) of details and 3rd objective is basically https://github.com/kcp-dev/kcp/issues/278, i.e. @s-urbaniak.

**Comment by ncdc** [comment]
This is done.
