### ISSUE TITLE
Workspace Administration and Tenancy: Workspace minimal RBAC

### ISSUE THREAD

**Issue by pweil-** [kcp-dev/kcp#278]
Use Case: Workspace Administration and Tenancy:

Objectives:

- [ ] An admin can prefill a workspace with a set of APIs that match a type
- [ ] A user can be granted workspace access with minimal object/etcd fanout
- [ ] A workspace can be typed as “organizational” and contain other workspaces.  Initially there will be a single org workspace, admin
- [ ] Lack of workspace in org workspace gates user access

Details:

Proposed: RBAC interfaces within logical clusters are virtualized so that custom logic can union a basic set of permissions “does this user have access to all workspaces” and a specific set of permissions outside the workspace (via some data in the root workspace) and then anything inside the workspace (user A can grant access to user B in the workspace)

Steps:
- wire two authorizers into kcp shard apiserver
   - [ ] taking roles and bindings from lcluster (those objects won't exist by default)
   - [ ] taking roles and bindings from some admin cluster (= inheritance)
- [ ] wire authorization (logical AND with the other authorizers) checking that the user has access to the lcluster in the first place

Maybe restrict to read-only requests if only read access on the workspace object exists.

Non-goals for prototype 2:
- add workspace/lcluster scope to Roles and SubjectAccessReviews
- do any advanced modelling of inheritance, policies, …
- do any multi-level authz in proxy

**Comment by pweil-** [comment]
@s-urbaniak

**Comment by s-urbaniak** [comment]
figuring out the best place to wire additional static authorizers centrally. Currently this place seems like the right spot: 

https://github.com/kcp-dev/kubernetes/blob/1f4695370a63cfc44e51573893ef97514c6c3ba6/pkg/genericcontrolplane/server.go#L402-L428

**Comment by s-urbaniak** [comment]
Initial work is available https://github.com/s-urbaniak/kcp/tree/multi-cluster-informers and https://github.com/s-urbaniak/kubernetes/tree/controllerz-config based on @ncdc's scope work.

**Comment by s-urbaniak** [comment]
done, demo will be available at https://www.youtube.com/channel/UCfP_yS5uYix0ppSbm2ltS5Q
