### ISSUE TITLE
bug: Unable to use KCP client set 

### ISSUE THREAD

**Issue by yogesh-reddy** [kcp-dev/kcp#2794]
### Describe the bug

Tried getting go module of KCP ..
 getting this logs
 

go: github.com/kcp-dev/kcp/pkg/apis@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
go: k8s.io/cloud-provider@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/component-helpers@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/controller-manager@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/kube-aggregator@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/kube-controller-manager@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/kubelet@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/mount-utils@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/pod-security-admission@v0.0.0: invalid version: unknown revision v0.0.0

### Steps To Reproduce

` go get github.com/kcp-dev/kcp@latest`
 

### Expected Behaviour

resolving deps should be done properly

**Comment by mjudeikis** [comment]
WIP: https://github.com/kcp-dev/kcp/pull/2676
