### ISSUE TITLE
Deploy an Application: ImagePullSecrets are copied to physical clusters

### ISSUE THREAD

**Issue by pweil-** [kcp-dev/kcp#281]
Use Case: ImagePullSecrets are copied to physical clusters

Objectives:

- [ ] User can switch to a workspace
- [ ] User can create a deployment
- [ ] Scheduler places the workload, syncer agent on the kind cluster performs the spec down -> status up dance
- [ ] Workspaces with no pclusters available show apps as unschedulable
- [ ] Ingress allows access to the application placed on a physical cluster

Details

When an application is deployed to KCP and run on a physical cluster the physical cluster may require pull secret credentials for the image.  Copy down any `imagePullSecrets` into the physical cluster that are tied to the workload's SA in the physical cluster.

**Comment by imjasonh** [comment]
I tested this a couple weeks ago, and to the best of my knowledge this works already, so long as you sync Secrets and SAs to the pcluster, any referenced imagePullSecrets are synced and used in the pcluster.
