### ISSUE TITLE
feature: Upsync Endpoints

### ISSUE THREAD

**Issue by davidfestal** [kcp-dev/kcp#2817]
Upsync Endpoints related to a Service, so that the standard KNative Service can find the Endpoints related to a deployment, and know that an Application is effectively being served.

**Comment by stevekuznetsov** [comment]
Is this KNative specific? Are we building a KNative-specific upsyncer? How does this plug into a broader model?

**Comment by davidfestal** [comment]
We're definitely not building a KNative-specific upsyncer. However we know (and knative is an example) that a number of controllers may rely on the existence of an `Endpoints` resource beside the corresponding service as a proof that the service is effectively serving at least one Pod.
So upsyncing Endpoints is part of bringing more of `Transparent` in TMC.

Of course we could depend on some generic annotation on the synced service, or some configuration on the Syncer side, to opt-in / opt-out from this upsyncing

**Comment by davidfestal** [comment]
cc @lionelvillard

**Comment by davidfestal** [comment]
> Of course we could depend on some generic annotation on the synced service, or some configuration on the Syncer side, to opt-in / opt-out from this upsyncing

@sttts @lionelvillard  wdyt of this ? Should we introduce some sort of Syncer parameters to defining a set of service annotations that will trigger the Upsyncing of the related `Endpoints` resource ?

**Comment by lionelvillard** [comment]
It feels to me the parameters should be set on the placement object requesting the location to upsync the `Endpoints`. 

The basic flow is this one:
- create a new workspace
- install Knative (or any controllers)
- bind (or place) the workspace to an existing workload workspace and ask to upsync endpoints (or any resources that needs to be upsynced). For Knative specifically, ideally only endpoints associated to Knative services must be upsynced. Maybe a label selector can be used, I don't know. I'll have to check.
