### ISSUE TITLE
Deploy an Application: Multi-location ingress

### ISSUE THREAD

**Issue by pweil-** [kcp-dev/kcp#282]
Use Case: ImagePullSecrets are copied to physical clusters

Objectives:

- [ ] User can switch to a workspace
- [x] User can create a deployment
- [x] Scheduler places the workload, syncer agent on the kind cluster performs the spec down -> status up dance
- [ ] Workspaces with no pclusters available show apps as unschedulable
- [x] Ingress allows access to the application placed on a physical cluster

Details

Accessing a deployed application requires a basic multi location ingress solution for Ingress or service load balancer that can be run locally but direct L7 traffic to a specific component on one of the clusters

**Comment by pweil-** [comment]
@jmprusi looks like we need to get you added to the org for assignments.  FYI @imjasonh @ncdc

**Comment by jmprusi** [comment]
@pweil- @sttts already added me to the kcp org (thanks!) going to self-assign this issue

**Comment by ncdc** [comment]
@jmprusi are you still working on this?

**Comment by jmprusi** [comment]
I think that switching workspaces is ongoing work, but the demo covering the ingress use-cases was already merged, so we can close this.
