### ISSUE TITLE
Transparent Multicluster: Logical/Physical Cluster Namespaces

### ISSUE THREAD

**Issue by pweil-** [kcp-dev/kcp#283]
Use Case: Transparent Multicluster

Objectives:

- [ ] User can add a second location
- [ ] Deployed application moves between locations when service is disrupted (cluster down)
- [ ] Ingress follows application

Details

Namespaces should be addressable by a name human readable name even when conflicts may exists at the physical cluster level.  Map namespace requests between the name given in a workspace to the physical cluster's actual namespace name

**Comment by pweil-** [comment]
@imjasonh I took a bit of liberty on the details based on how I interpreted the task in our breakdown doc, feel free to correct that as necessary.

**Comment by imjasonh** [comment]
To do this, we first need syncer to become multi-lcluster-aware, then to take the lcluster name into account when it puts things into namespaces in the pcluster.

For example, if a Deployment is created in lcluster `my-lcluster` in `my-namespace`, and gets scheduled/synced to `my-pcluster`, it could be created in the namespace `kcp--my-lcluster--my-namespace`, or hash either component to avoid name length limits.

Perfectly avoiding name length limits can happen later, just having something that avoids conflicts among two lclusters should be good enough for prototype2.

If someone wants to pick this up while I'm absent I'd be happy to help talk through it more, review code, etc., as much as I can.

**Comment by davidfestal** [comment]
Doesn't it imply building a syncer-dedicated virtual workspace that aggregates resources (by delegating to the shard proxy) and filter / present them (as well as the API themselves) in a way that corresponds to the syncer needs ? cc @sttts

**Comment by imjasonh** [comment]
> Doesn't it imply building a syncer-dedicated virtual workspace that aggregates resources (by delegating to the shard proxy) and filter / present them (as well as the API themselves) in a way that corresponds to the syncer needs ? cc @sttts

Maybe? Is it not possible/advisable to make a `*`-cluster informer with a label filter? I'll do whatever you tell me is most efficient.

The main issue on syncer's side is that it needs to transform the incoming lcluster+namespace into a non-colliding namespace, then transform it back when updating status upstream.

**Comment by stevekuznetsov** [comment]
As an aside we should consider a `*`-cluster informer a virtual workspace, since it is

**Comment by kylape** [comment]
Just saw this.  I'd be happy to work on this (though I'm off on Friday).

**Comment by kylape** [comment]
I've got something working, and I've written an e2e test.  Just trying to get the test to pass now :smile:.
