### ISSUE TITLE
Community Meeting February 28, 2023

### ISSUE THREAD

**Issue by mjudeikis** [kcp-dev/kcp#2849]
### Overview

At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/mpd-cypd-sdp
Or dial: ‪(DE) +49 30 300195060‬ PIN: ‪500 599 130 5702‬#
More phone numbers: https://tel.meet/mpd-cypd-sdp?pin=5005991305702
Or join via SIP: sip:5005991305702@gmeet.redhat.com

Meeting recordings available on YouTube at https://www.youtube.com/playlist?list=PLqN7RcoCwL96nXIIW6O51l8Lu_J-f5D27

Incoming issues: https://github.com/orgs/kcp-dev/projects/1/views/22

Milestone epics: https://github.com/kcp-dev/kcp/issues?q=is%3Aopen+is%3Aissue+label%3Amilestone-blocker+label%3Aepic

Add topics you'd like to discuss below!

**Comment by vincepri** [comment]
Overview / Demo of the work in progress PR for multi-cluster support in Controller Runtime (https://github.com/kubernetes-sigs/controller-runtime/pull/2207)

**Comment by mjudeikis** [comment]
[Faros](https://github.com/faroshq/faros) demo - Opinionated way to use KCP Or "Public KCP playground".

**Comment by davidfestal** [comment]
TMC behavior for `Pod`s (pointing back to KCP and Pod-Upyncing ), until now appmied only for `Deployment`s is now also applied to other `PodSpec`able resources: `StatefulSet`s and `ReplicaSet`s.

**Comment by mjudeikis** [comment]
Notes:
> Overview / Demo of the work in progress PR for multi-cluster support in Controller Runtime (https://github.com/kubernetes-sigs/controller-runtime/pull/2207)
Architecture doc: https://hackmd.io/hn7p1VsVSbaA2i3dt3f1vA
