### ISSUE TITLE
bug: Make kcp-docs-image does not works on linux/arm64

### ISSUE THREAD

**Issue by fabriziopandini** [kcp-dev/kcp#2850]
### Describe the bug

I'm trying to validate some docs changes locally, and `make kcp-docs-image` fails with

```
 => ERROR [internal] load metadata for docker.io/squidfunk/mkdocs-material:latest                                                                                                                                                          
```

Digging into this a little bit it seems there is no linux/arm64 image available:

```
docker pull docker.io/squidfunk/mkdocs-material:latest
latest: Pulling from squidfunk/mkdocs-material
no matching manifest for linux/arm64/v8 in the manifest list entries
```

### Steps To Reproduce

Try to run  `make kcp-docs-image` on a linux/arm64 machine

### Expected Behaviour

Tooling for the docs to work on linux/arm64.

### Additional Context

I can help fix this, I'm only a little bit short of time ATM so any pointers will be helpful.
Also, if someone wants to take this before me, feel free to do it

**Comment by ncdc** [comment]
It's probably easier to switch to a venv-based setup instead of docker. Let's maybe explore that?

**Comment by ncdc** [comment]
I have a fix almost ready
