### ISSUE TITLE
Run Kubernetes conformance tests against a compute workspace

### ISSUE THREAD

**Issue by lionelvillard** [kcp-dev/kcp#2883]
One of the TMC layer goals is to be enable to run 95% of the existing Kubernetes workload. Running the conformance tests would help identifying the gaps and the conformance report can be used to evaluate TMC.

The recommended way to run conformance tests is to use [Sonobuoy](https://sonobuoy.io).
How to run the conformance tests: https://github.com/cncf/k8s-conformance/blob/master/instructions.md#running

**Comment by stevekuznetsov** [comment]
In the distant past I ran all of the k8s API server conformance suites against kcp, but found quite a lot of code around e.g. the APIs that the framework expected to exist - like Nodes, etc, which simply don't exist in kcp normally. Even getting the API-specific tests to run was a frustrating exercise in removing framework code that made a bunch of assumptions (for e.g. cleanup, even) that did not apply and were not actually important to the test passing. I agree that this is a useful thing to do in theory but we will have to think about how to make sure this does not end up as a time-sink trying to glue two incompatible things together.
