### ISSUE TITLE
bug: Pod logs periodically fail with `"syncer tunnels: tunnel closed"`

### ISSUE THREAD

**Issue by astefanutti** [kcp-dev/kcp#2886]
### Describe the bug

Requests to the pod logs sub-resource sometimes fail with: 

```
Error from server (InternalError): an error on the server ("syncer tunnels: tunnel closed") has prevented the request from succeeding (get pods camel-kcp-86cc47559f-56jfc)
```

### Steps To Reproduce

1. Start kcp locally and a local KinD cluster as sync target:

    ```
    $ kcp start --batteries-included=+user --feature-gates=KCPSyncerTunnel=true
    $ kind create cluster --name pcluster --kubeconfig pcluster.kubeconfig
    $ kubectl kcp workload sync pcluster | kubectl --kubeconfig pcluster.kubeconfig apply -f -
    ```

2. Create a deployment and get the logs, e.g.:
    ```
    $ watch -n 1 -x kubectl logs <pod_name> --tail 1
   ```

### Expected Behaviour

The requests to pod logs should always succeed.

### Additional Context

Likely related, watching the pod logs fails after a couple a minutes, e.g.:

```
$ kubectl logs <pod_name> -f
error: stream error: stream ID 3; INTERNAL_ERROR; received from peer
```

**Comment by stevekuznetsov** [comment]
What's the connection between your `kcp` and physical clusters? If the underlying transport is closed, not sure we can do much - in e.g. deployments where k8s sits behind some router that has a timeout on connections, any `kubectl --watch` request exhibits the same behavior.

**Comment by astefanutti** [comment]
I've updated the description with more context about the setup to reproduce the issue. It's all local, with local KinD clusters, so the transport layer between kcp and the physical clusters should not be responsible for the issue.
