### ISSUE TITLE
Community Meeting Mar 14 2023

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#2887]
### Overview

At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/mpd-cypd-sdp
Or dial: ‪(DE) +49 30 300195060‬ PIN: ‪500 599 130 5702‬#
More phone numbers: https://tel.meet/mpd-cypd-sdp?pin=5005991305702
Or join via SIP: sip:5005991305702@gmeet.redhat.com

Meeting recordings available on YouTube at https://www.youtube.com/playlist?list=PLqN7RcoCwL96nXIIW6O51l8Lu_J-f5D27

Incoming issues: https://github.com/orgs/kcp-dev/projects/1/views/22

Milestone epics: https://github.com/kcp-dev/kcp/issues?q=is%3Aopen+is%3Aissue+label%3Amilestone-blocker+label%3Aepic

Add topics you'd like to discuss below!

**Comment by francostellari** [comment]
If there is time I would like to discuss https://github.com/kcp-dev/kcp/issues/2885

**Comment by mjudeikis** [comment]
The fallout from merging #2869 . Is there a better way to handle this split than what we did?
More background: https://kubernetes.slack.com/archives/C021U8WSAFK/p1678727016614579

**Comment by MikeSpreitzer** [comment]
- Rebase onto Kubernetes release 1.25
- Rebase onto Kubernetes release 1.26
- https://github.com/kcp-dev/kcp/pull/2787
- What goes in the next kcp release?

**Comment by ncdc** [comment]
FYI we are not planning a 1.25 rebase, just 1.26

**Comment by sttts** [comment]
Idea from @williamcaban: have a github.com/kcp-dev/awesome-kcp repo with a cronological lists of demo, video, blog post links.

**Comment by nrb** [comment]
Next release: minimum is reverse permission claims. [Community input welcome for other features and work](https://github.com/kcp-dev/kcp/discussions/2891)

**Comment by nrb** [comment]
For now, upsyncing is hardcoded for minimal use cases. An interface will require a full design process.

**Comment by nrb** [comment]
https://github.com/kcp-dev/awesome-kcp created, please feel free to make a PR if you have a demo, talk, or something else to KCP that you'd like to share.

https://github.com/kcp-dev/friends also created for introducing yourself and how you use KCP
