### ISSUE TITLE
Community Meeting Mar 21 2023

### ISSUE THREAD

**Issue by clubanderson** [kcp-dev/kcp#2909]
### Overview

At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/mpd-cypd-sdp
Or dial: ‪(DE) +49 30 300195060‬ PIN: ‪500 599 130 5702‬#
More phone numbers: https://tel.meet/mpd-cypd-sdp?pin=5005991305702
Or join via SIP: sip:5005991305702@gmeet.redhat.com

Meeting recordings available on YouTube at https://www.youtube.com/playlist?list=PLqN7RcoCwL96nXIIW6O51l8Lu_J-f5D27

Incoming issues: https://github.com/orgs/kcp-dev/projects/1/views/22

Milestone epics: https://github.com/kcp-dev/kcp/issues?q=is%3Aopen+is%3Aissue+label%3Amilestone-blocker+label%3Aepic

Add topics you'd like to discuss below!

**Comment by MikeSpreitzer** [comment]
- https://github.com/kcp-dev/kcp/issues/2905

**Comment by sttts** [comment]
### Cross-workspace impersonation problem 

https://docs.google.com/document/d/12WzYomoZfVy1c0NQjROQp17PVu4cFp_RyWcpgCL5vdo/edit

<img width="711" alt="Bildschirm­foto 2023-03-21 um 09 57 13" src="https://user-images.githubusercontent.com/730123/226558400-9e4ab76c-4a69-4c17-b697-c27f0aecbe6a.png">

### Workspace creation
<img width="648" alt="Bildschirm­foto 2023-03-21 um 09 57 31" src="https://user-images.githubusercontent.com/730123/226558475-f87d29bf-1dbe-45d6-b641-bf3b36842827.png">

**Comment by aknochow** [comment]
demo install-kcp ansible playbook
https://github.com/aknochow/install-kcp

**Comment by MikeSpreitzer** [comment]
- v0.12.0
