### ISSUE TITLE
feature: Define interface for upsyncing resources

### ISSUE THREAD

**Issue by nrb** [kcp-dev/kcp#2923]
### Feature Description

In a [recent community meeting](https://github.com/kcp-dev/kcp/issues/2887#issuecomment-1467378398), @MikeSpreitzer requested an interface allowing resources from the edge-mc project to upsynced like TMC resources currently work.

### Proposed Solution

The request was for some sort of interface defining what resources should be upsynced. I could also envision some sort of registration process for such resources, however I think a full design iteration is necessary to explore possible solutions.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by davidfestal** [comment]
@nrb Is this issue related to syncing or replication ? Not sure I understand the logic and requirement behind the issue.

**Comment by nrb** [comment]
Looks like my mistake.

The text from the community meeting was:

> Interface for identifying associated objects to upsync

I'll fix the issue description.

**Comment by davidfestal** [comment]
Isn't it a duplicate of this one: https://github.com/kcp-dev/kcp/issues/2804 ?

**Comment by nrb** [comment]
Yep, you're right. I misunderstood the initial request. Closing this one out.
