### ISSUE TITLE
Unify `workload[s]` names in the tmc `controller.go`

### ISSUE THREAD

**Issue by davidfestal** [kcp-dev/kcp#2936]
In the `/tmc/pkg/server/controllers.go`, some workload related controllers are installed with `installWorkload...` and some with `installWorkloads....`.
The relates to the fact that the import alias sometimes contains the `s`, sometimes not. 
It make sense to unify the names, as well as the names of the related methods.

This is a followup of this [PR comment](https://github.com/kcp-dev/kcp/pull/2933#discussion_r1153279300).

**Comment by dhanusaputra** [comment]
hi, can i help with this please, thanks

**Comment by p0lyn0mial** [comment]
> hi, can i help with this please, thanks

absolutely! please, feel free to self-assign the issue, thanks!

**Comment by davidfestal** [comment]
> > hi, can i help with this please, thanks
> 
> absolutely! please, feel free to self-assign the issue, thanks!

Yes, Thanks !

As for the change to be done, I would vote for keeping the `workload` **without an `s`**, since it is the package name.

What do other think  ?

Let's vote:
- add a :+1:  to this comment to use `workload` without an `s` everywhere
- add a :-1: to this comment to use `workloads` everywhere
