### ISSUE TITLE
 one workspace in kcp to synchronize different resources of different physical clusters

### ISSUE THREAD

**Issue by SakuraAxy** [kcp-dev/kcp#2967]
Great project!
How can I use a workspace in kcp to synchronize different resources of different physical clusters, for example, there is a physical cluster called workload, which accepts those ordinary workloads, such as pod, deployment..., and a physical cluster called provider-pg, which accepts postgresql

I tried creating two workspaces: provider-pg and provider-workspace, and then synced the corresponding resources, and then binded the two provider workspaces in front of the workspace named dev, but in fact I created workload or postgresql. They all ended up running in the provider-workspace physical cluster

I've seen some shared docs, but it seems only for different namespaces

**Comment by SakuraAxy** [comment]
Hi @ncdc , Is this feature currently supported by kcp?

**Comment by stevekuznetsov** [comment]
I believe what you'd want to do is:

- create a `SyncTarget` for each physical cluster (can be in your workspace, can be elsewhere)
- create a `Location` with both `SyncTarget`s selected (in the same workspace as the `SyncTarget`)
- create a `Placement` that targets the `Location` in your workspace

Then, workloads from your workspace will target either `SyncTarget`. See https://github.com/kcp-dev/kcp/blob/main/docs/content/concepts/placement-locations-and-scheduling.md for more info,

**Comment by SakuraAxy** [comment]
> 

Thank you for your reply, that is to say, the feature I mentioned is not supported yet, right? 
Only synctaget can be randomly selected, and some rules cannot be configured to specify which physical cluster a resource should be synchronized to

**Comment by clubanderson** [comment]
@SakuraAxy this can be done with kubestellar.io. Try it out at kubestellar.up/QuickStart

Our repo is at https://KCP-dev/edge-mc

**Comment by SakuraAxy** [comment]
@clubanderson thanks for your share
