### ISSUE TITLE
kcp synchronizes the resources of the physical cluster to the logical cluster

### ISSUE THREAD

**Issue by SakuraAxy** [kcp-dev/kcp#2972]
When I try to build a SaaS service
for example:
now I want to provide users with PostgreSQL instances using the PostgreSQL Operator. However, it seems that KCP can only synchronize the resources created by users in the workspace to the physical cluster and continuously keep them in sync. But when the PostgreSQL Operator creates a secret for the corresponding Custom Resource (CR) to store the authentication information, it seems that KCP is unable to sync this secret back to the workspace. If possible, please provide me with more detailed information. 
Thanks.

**Comment by embik** [comment]
Hi @SakuraAxy, for your awareness, kcp "core" (this repository) recently removed TMC (transparent multi-cluster) including the syncer in #2963. A note has been added to the README as well:

> NB: In May 2023, the kcp project was restructured and components related to workload scheduling (e.g. the syncer) and the transparent multi cluster (tmc) code were removed due to lack of interest/maintainers. Please refer to the [main-pre-tmc-removal branch](https://github.com/kcp-dev/kcp/tree/main-pre-tmc-removal) if you are interested in the related code.

Depending on your use case, maybe [KubeStellar](https://github.com/kcp-dev/edge-mc) would be of interest to you.
