### ISSUE TITLE
feature: How to add all K8s core object into root:compute apiresourceschemas

### ISSUE THREAD

**Issue by wuyexixi** [kcp-dev/kcp#2981]
### Feature Description

For now just 4 object apiresourceschema in root:compute

v124.deployments.apps              4d8h
v124.ingresses.networking.k8s.io   4d8h
v124.pods.core                     4d8h
v124.services.core                 4d8h

### Proposed Solution

There is no easy way to export K8s core objects (e.g.serviceaccount,V1.Node) to yaml file like CRD. should add those objects in default root:compute. or let apigen tool to auto generate it.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by bhavyastar** [comment]
Hey @embik 
I would like to work on this issue.

**Comment by embik** [comment]
@bhavyastar happy to hear that! We triaged this issue a while back during our community call as something that mostly requires adding documentation on how to add all Kubernetes core resources.

I'm fuzzy on the details, but if you want to drive this you are very welcome to our bi-weekly community call to further discuss it.
