### ISSUE TITLE
Community Meeting June 20, 2023

### ISSUE THREAD

**Issue by scheeles** [kcp-dev/kcp#2983]
### Overview

At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/bvb-qmdk-qwr
Or dial: ‪(DE) +49 40 8081619805‬ PIN: ‪475 948 161‬#
More phone numbers: https://meet.google.com/tel/qhs-tuik-kwj?pin=7061261814168&hs=1

Meeting recordings available on YouTube at https://www.youtube.com/playlist?list=PLqN7RcoCwL96nXIIW6O51l8Lu_J-f5D27

Add topics you'd like to discuss below!

Agenda:

- Summery of the current status
- Moving the community meeting
- Prow migration
- Cutting 0.20 release
- What to do with open issues and PRs.
- TMC
- Cleaning Repos

**Comment by embik** [comment]
As discussed [on Slack](https://kubernetes.slack.com/archives/C021U8WSAFK/p1686651856010159), lets talk about cutting a 0.20 release and what is missing before that?

**Comment by embik** [comment]
Another topic: What to do with open issues and PRs.

**Comment by mjudeikis** [comment]
TMC (https://github.com/faroshq/tmc/pull/4) We almost have it up-and-running again. Question to community: What would be acceptance criteria to promote to kcp-dev repo

**Comment by sttts** [comment]
Cleaning up repository, archiving unmaintained ones:

## edge-mc
KubeStellar - a flexible solution for challenges associated with multi-cluster configuration management for edge, multi-cloud, and hybrid cloud

**Decision:** to be moved out https://github.com/kcp-dev/edge-mc/issues/539

## code-generator
Generators for workspace-aware clientsets, informers, and listers

**Decision**: maintained

## infra
CI infrastructure

**Decision**: maintained

## apimachinery
API machinery library for logical-cluster-aware code

**Decision**: maintained

## kcp
kcp is a Kubernetes-like control plane for workloads on many clusters

**Decision**: maintained

## helm-charts
Helm chart repo for KCP

**Decision**: maintained

## client-go
Golang libraries for multi-cluster-aware Kubernetes clients, listers and informers.

**Decision**: maintained

## apiextensions-apiserver
Golang libraries for multi-cluster-aware Kubernetes API Extensions clients, listers and informers.

**Decision**: maintained

## controller-runtime-example

**Decision**: maintained

## controller-runtime
Adaption of the repo for the controller-runtime subproject of kubebuilder (sig-apimachinery)

**Decision**: maintained

## logicalcluster
Small library for logical cluster helpers

**Decision**: maintained

kubernetes
This repository is Kubernetes plus minimal modifications to add logical clusters. Rebased regularly.

## kcp-glbc
Global Ingress Controller for KCP

**Decision**: ?

## enhancements
Enhancements tracking repo for kcp projects

**Decision**: maintained

## kcp-tests
Tests against the publicly available interfaces (APIs, code, CLIs)

**Decision**: ?
**Proposal**: archive as these were additional blackbox tests by RH QE. The kcp project is relying on e2e inside of kcp repo only.

## awesome-kcp
Collection of demos, blog posts, talks, etc. about kcp

**Decision**: ?

## friends
Friends of kcp - let us know how you're using kcp at your organization!

**Decision**: ?

## cel-go
Fast, portable, non-Turing complete expression evaluation with gradual typing (Go)

**Decision**: obsolete?

## kcp.io
Website

**Decision**: maintained

## catalog
API catalog functionality for kcp

**Decision**: ?
**Proposal**: archive as it is incomplete and not maintained

## kcp-dev.github.io

**Decision**: maintained

**Comment by sttts** [comment]
Meeting time: vote in https://kubernetes.slack.com/archives/C021U8WSAFK/p1687246992334389?thread_ts=1687246051.543409&cid=C021U8WSAFK.

Proposal: move to Thursday, same time.

**Comment by scheeles** [comment]
Decision made: 
- Moving the community meeting -> Agree to move to Thursday same time
- Cutting 0.20 release -> Agreement on cutting a next release 
- What to do with open issues and PRs. -> Wait for the move of TMC as at least +100 issues are TMC related 
- TMC -> move TMC to a dedicated repo in the kcp-dev org
 - Cleaning Repos -> see https://github.com/kcp-dev/kcp/issues/2983#issuecomment-1598229928

**Comment by nikhita** [comment]
Closing since this is done

/close
