### ISSUE TITLE
Community Meeting July 6 2023

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#2987]
### Overview

At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/bvb-qmdk-qwr
Or dial: ‪(DE) +49 40 8081619805‬ PIN: ‪475 948 161‬#
More phone numbers: https://meet.google.com/tel/qhs-tuik-kwj?pin=7061261814168&hs=1

Meeting recordings available on YouTube at https://www.youtube.com/playlist?list=PLqN7RcoCwL96nXIIW6O51l8Lu_J-f5D27

Incoming issues: https://github.com/orgs/kcp-dev/projects/1/views/22

Milestone epics: https://github.com/kcp-dev/kcp/issues?q=is%3Aopen+is%3Aissue+label%3Amilestone-blocker+label%3Aepic

Add topics you'd like to discuss below!

**Comment by waltforme** [comment]
I tried [kube-bind](https://github.com/kube-bind/kube-bind) for some time, it is pretty cool!

I had some initial understanding by reading kube-bind code (and taking [notes](https://docs.google.com/document/d/1pKftNf4K1E1Ru_5YTZNPUJzbMUWNUKPYlQSw3A1rL6w)), but also want to learn more from higher (than code) level. One dumb question is: How should I understand the relationship between kcp apiexport/apibinding and kube-bind?

**Comment by MikeSpreitzer** [comment]
- Contributing the crd-puller to kube-bind
- Contributing an appropriately modified apigen to kube-bind

**Comment by clubanderson** [comment]
- review of new bugs and PRs not assigned to a person
- review bugs and PRs not assigned to a milestone

**Comment by embik** [comment]
I would like to briefly present my hobby project of [redesigning the kcp.io website](https://github.com/kcp-dev/kcp.io/pull/25) and get some feedback on whether I should continue with that.

**Comment by nikhita** [comment]
Rebasing to kube v1.27.3:

- When do we want to do it?
- I'd like to pair with someone to learn the rebase process.

**Comment by nikhita** [comment]
Moving TMC-related issues to https://github.com/kcp-dev/contrib-tmc.

We can use @MadhavJivrajani's approach here to automate this -  https://kubernetes.slack.com/archives/C021U8WSAFK/p1687761878063619?thread_ts=1687526017.944399&cid=C021U8WSAFK

We will first need to label all TMC related issues with the `area/transparent-multi-cluster` label. How do we ensure that all issues are triaged?

**Comment by sttts** [comment]
Short report on upstream kube:
1. [enhancement `#4080`](https://github.com/kubernetes/enhancements/issues/4080) **landed** for v1.28
2. kube-apiserver / generic-control-plane options split [**landed**](https://github.com/kubernetes/kubernetes/pull/118633)
3. kube-apiserver legacy storage split [**landed**](https://github.com/kubernetes/kubernetes/pull/119082)
4. kube-apiserver [legacy storage unification as "normal" `RESTStorageProvider`](https://github.com/kubernetes/kubernetes/pull/119042) **in review**
5. kube-apiserver config and server struct split (depending on (4)) in development, **nearly done**
6. sample-generic-controlplane cmd, **to be done**
7. move to `k8s.io/generic-controlplane-{apiserver,controllers}`, **to be done**, but more cosmetics, not really relevant for us

**Comment by embik** [comment]
Closing as we had the meeting yesterday.

/close
