### ISSUE TITLE
Community Meeting July 20, 2023

### ISSUE THREAD

**Issue by embik** [kcp-dev/kcp#2989]
### Overview

At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/bvb-qmdk-qwr
Or dial: ‪(DE) +49 40 8081619805‬ PIN: ‪475 948 161‬#
More phone numbers: https://meet.google.com/tel/qhs-tuik-kwj?pin=7061261814168&hs=1

Meeting recordings available on YouTube at https://www.youtube.com/playlist?list=PLqN7RcoCwL96nXIIW6O51l8Lu_J-f5D27

Incoming issues: https://github.com/orgs/kcp-dev/projects/1/views/22

Milestone epics: https://github.com/kcp-dev/kcp/issues?q=is%3Aopen+is%3Aissue+label%3Amilestone-blocker+label%3Aepic

Add topics you'd like to discuss below!

**Comment by sftim** [comment]
> Add topics you'd like to discuss below!

Image builds / releases

**Comment by nikhita** [comment]
This meeting was cancelled, so maybe we should close this issue? :)

cc @scheeles

**Comment by nikhita** [comment]
Closing since the meeting was cancelled.
