### ISSUE TITLE
Community Meeting December 7, 2021

### ISSUE THREAD

**Issue by imjasonh** [kcp-dev/kcp#299]
At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/ohf-kwvd-mrp
Or dial: ‪(US) +1 617-675-4444‬ PIN: ‪936 182 087 7398‬#
More phone numbers: https://tel.meet/ohf-kwvd-mrp?pin=9361820877398
Or join via SIP: sip:9361820877398@gmeet.redhat.com

This issue will collect prospective agenda topics. Add topics you'd like to discuss below!

**Comment by imjasonh** [comment]
- ...is this meeting agenda system working?
- KubeCon EU CFP closing soon: anybody want to propose a talk?
- namespace scheduler progress
  - e2e tests using framework, some startup issues?
  - DI cleaned up
  - kcp will be responsible for creating and setting RBAC on namespaces, not syncer

**Comment by pweil-** [comment]
help wanted/good first issue

**Comment by sttts** [comment]
Issue board: https://github.com/orgs/kcp-dev/projects/1/views/1?layout=board

**Comment by sttts** [comment]
Quick summary about ExternalSync API model: https://docs.google.com/document/d/1k72fgGBNJzbY1Rkxj9_1WksHZR0cNT5OeadCpWuc-zM/edit#

**Comment by kylape** [comment]
> Issue board: https://github.com/orgs/kcp-dev/projects/1/views/1?layout=board

This gives me a 404

**Comment by imjasonh** [comment]
Next: https://github.com/kcp-dev/kcp/issues/308

**Comment by imjasonh** [comment]
Recording: https://youtu.be/DMxcNnx4Ke8
