### ISSUE TITLE
Community Meeting August 10, 2023

### ISSUE THREAD

**Issue by embik** [kcp-dev/kcp#2997]
### Overview

At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20230810T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/bvb-qmdk-qwr
Or dial: ‪(DE) +49 40 8081619805‬ PIN: ‪475 948 161‬#
More phone numbers: https://meet.google.com/tel/qhs-tuik-kwj?pin=7061261814168&hs=1

Meeting recordings available on YouTube at https://www.youtube.com/playlist?list=PLqN7RcoCwL96nXIIW6O51l8Lu_J-f5D27

Incoming issues: https://github.com/orgs/kcp-dev/projects/1/views/22

Milestone epics: https://github.com/kcp-dev/kcp/issues?q=is%3Aopen+is%3Aissue+label%3Amilestone-blocker+label%3Aepic

Add topics you'd like to discuss below!

**Comment by embik** [comment]
@sftim you had a topic [when the last community meeting was canceled](https://github.com/kcp-dev/kcp/issues/2989#issuecomment-1643875789), do you want to discuss the topic on this meeting?

**Comment by embik** [comment]
Topic: Update on kcp.io website theme ([PR](https://github.com/kcp-dev/kcp.io/pull/25))

**Comment by mjudeikis** [comment]
TMC - whats next ?

**Comment by mjudeikis** [comment]
Rebase status

**Comment by MikeSpreitzer** [comment]
Helm chart

**Comment by sttts** [comment]
@ rebase: volunteering for 1.28 rebase. I have a local branch with the rest of https://github.com/kubernetes/enhancements/issues/4080. kcp is a good proof that 4080 is implemented well.

**Comment by embik** [comment]
## Meeting Notes

### TMC - whats next ? API Naming, sharding, etc

- Repository has been open-sourced
- API group naming under `kcp.io`, move to `tmc.kcp.io`
- There are still open issues, contributions are very appreciated
- An extension to kcp, but currently a library plugged into the codebase
- TMC was in early stages of sharding support
- Tunneler no longer working, required some code in the core, should be possible though

### Sharding Documentation (Intermission from previous topic)

- Sharding documentation needs to be created, it does not exist right now
- How should applications be built on top of kcp to be shard-aware?
- @MikeSpreitzer to create issue and assign it to @sttts 

### Rebase to 1.27

- Epic in #2986
- Not entirely clear what direction for the kubernetes/kubernetes fork to take
- Check in with folks in #kcp-dev about its status
- Potentially jump to 1.28 rebase immediately

### Helm Chart

- Status: Supported as a way to install kcp, but can still be broken in the future as with kcp releases
- Issue with filesystem access in OpenShift
- "Developer" mode that makes it easy to try it out
- Sharding is not supported in the Helm Chart
- For the future: One shard is one Helm chart installation
- Making the kcp-front-proxy component optional is probably possible
