### ISSUE TITLE
Community Meeting August 31, 2023

### ISSUE THREAD

**Issue by embik** [kcp-dev/kcp#3002]
### Overview

At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20230831T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/bvb-qmdk-qwr
Or dial: ‪(DE) +49 40 8081619805‬ PIN: ‪475 948 161‬#
More phone numbers: https://meet.google.com/tel/qhs-tuik-kwj?pin=7061261814168&hs=1

Meeting recordings available on YouTube at https://www.youtube.com/playlist?list=PLqN7RcoCwL96nXIIW6O51l8Lu_J-f5D27

Incoming issues: https://github.com/orgs/kcp-dev/projects/1/views/22

Milestone epics: https://github.com/kcp-dev/kcp/issues?q=is%3Aopen+is%3Aissue+label%3Amilestone-blocker+label%3Aepic

Add topics you'd like to discuss below!

**Comment by mjudeikis** [comment]
Replacement meeting: https://meet.google.com/kne-jxko-eje

**Comment by mjudeikis** [comment]
Rebase status;
next step is to try sttts branch into KCP branch to see what is missing: https://github.com/kubernetes/kubernetes/pull/120202

**Comment by mjudeikis** [comment]
@fgiloux: TMC syncing was fixed for cross-workspace access
The next step is making the TMC "plugin" no overlay. 

We will need `system:master` user for now for virtual workspaces to work (https://github.com/kcp-dev/kcp/blob/main-pre-tmc-removal/tmc/pkg/virtual/syncer/doc.go)

**Comment by embik** [comment]
This meeting happened. Closing it.
