### ISSUE TITLE
bug: `kubectl-ws '~'` changes hostname used in kubeconfig server URL

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/kcp#3011]
### Describe the bug

I have seen several people accidentally issue the command `kubectl ws` (with nothing else on the command line), and then be confused from then on.  This happened to me a few times too, I only tracked this down with some effort.

```
mspreitz@mjs12 kubestellar % cp k2.kubeconfig k3.kubeconfig
mspreitz@mjs12 kubestellar % KUBECONFIG=k3.kubeconfig kubectl ws
Current workspace is "kvdk2spgmbix".
Note: 'kubectl ws' now matches 'cd' semantics: go to home workspace. 'kubectl ws -' to go back. 'kubectl ws .' to print current workspace.
mspreitz@mjs12 kubestellar % diff k2.kubeconfig k3.kubeconfig | grep server
<       server: https://yep.yep:6443
<       server: https://yep.yep:6443/clusters/root
<       server: https://yep.yep:6443/clusters/root
<       server: https://yep.yep:6443/clusters/root:compute
>     server: https://yep.yep:6443
>     server: https://yep.yep:6443/clusters/root
>     server: https://10.244.0.9:6443/clusters/kvdk2spgmbix
>     server: https://yep.yep:6443/clusters/root
mspreitz@mjs12 kubestellar % 
```

This was using release v0.11.0 of kcp.

### Steps To Reproduce

1. Make a kubeconfig that uses a domain name for each "cluster" in the kubeconfig relevant to kcp.
2. `kubectl workspace` (nothing else on the command line)
3. Inspect those clusters in that kubeconfig, find that the one named "workspace.kcp.io/current" uses the server's local IP:port in the server URL.

### Expected Behaviour

When all the kcp-relevant clusters use a particular host:port, the `kubectl workspace` plugin should not switch to a different host:port.

**Comment by embik** [comment]
Does the `kcp` process you are running this against set `--external-hostname=yep.yep:6443` as flag? From a cursory review of the plugin code, it seems to pull the workspace URL directly from what kcp advertises the workspace status, which sounds more reliable to me than parsing the existing file and guess what might be right URL.

**Comment by MikeSpreitzer** [comment]
No, I have _not_ given the server `--external-hostname`.  I need a way to support two sets of clients: ones that are close to the server and contact it via a short network path, and those that are farther away and come in through a heavier longer network path.

**Comment by mjudeikis** [comment]
You could try using host aliasing from k8s. Helm chart already supports this:
```
  hostAliases:
    enabled: true
    values:
    - hostnames:
      - kcp.faros.sh
      ip: 127.0.0.1
  ```

Where Pod A calls kcp.faros.sh from inside the pod, using normal kubeconfig but kubernetes routes it to service IP.
And the IP in the example is being dynamically replaced by:
```
helm upgrade -i kcp ./kcp/charts/kcp/charts/kcp \
     --values ./kcp/values.yaml \
     --set kcp.hostAliases.values[0].ip=$(kubectl get svc kcp-internal -n kcp -o json  | jq -r .spec.clusterIP) \
     --set kcpFrontProxy.hostAliases.values[0].ip=$(kubectl get svc kcp-internal -n kcp -o json  | jq -r .spec.clusterIP) \
     --namespace kcp \
     --create-namespa
     ```

**Comment by MikeSpreitzer** [comment]
That will not cope with a port difference, right?
That will force other clients in the same kube cluster to go out and come in through the outer door, right?

**Comment by mjudeikis** [comment]
> No, I have _not_ given the server `--external-hostname`. I need a way to support two sets of clients: ones that are close to the server and contact it via a short network path, and those that are farther away and come in through a heavier longer network path.


can you elaborate on this? `--external-hostname` is used for "external path clients". So are you saying you need third way/url? Currently this url is backed into virtualWorkspace so it gets from URL in the status. 
This would require bigger change to change all the logic. 

I think we could do some override (hack) where if certain file/config is present we could use different url, but I don't think that changing how virtual workspaces works is feasible here. 

What im thinking something under lines:
If `.kube/kcp_config`  exists with override value, we could use that as base url.

This could be only `ws` change with no server side changes.

**Comment by sttts** [comment]
If I am not mistaken, also `kubectl ws <name>` "changes" the hostname in the URL, or more concretely reads it from the `Workspace` object's `spec.URL`. So the question is why that URL is fine, but the one returned through `~` is not.

**Comment by sttts** [comment]
What I read between the lines is that there is the desire for network environments. If a client is in network environment A with some `hostname:port`, then `kubectl ws` should stay in A. This does not neccessarily mean that A only has one `hostname:port`, but maybe all `hostname:port`s in A are internet-routable. Another user in environment B would work exclusively with `hostname:port`s that are intranet-routable.

**Comment by mjudeikis** [comment]
before we start writing code, why do you not using in your deployment `--external-hostname` ? This forces virtual workspaces urls to be with provided hostnames?

**Comment by mjudeikis** [comment]
Issue in the plugin with home workspace behaviour of `~`. Needs code change to match the behaviour of other commands

**Comment by sttts** [comment]
@MikeSpreitzer the line of code we talked about in the meeting: https://github.com/kcp-dev/kcp/blob/main/pkg/cliplugins/workspace/plugin/kubeconfig.go#L218
