### ISSUE TITLE
Pointer: NFD Feature request for MultiCluster environments

### ISSUE THREAD

**Issue by ArangoGutierrez** [kcp-dev/kcp#3034]
Hey KCP developer/maintainers, just wanted to bring your attention to:
 - https://github.com/kubernetes-sigs/node-feature-discovery/issues/1423 
 
***Please don't comment on this issue, let's take the conversation on the NFD issue***

Have a great day!
Cheers!

**Comment by embik** [comment]
Thank you for letting us know, we are following the KEP and will engage with it!
