### ISSUE TITLE
bug: no v0.21.0 image published

### ISSUE THREAD

**Issue by embik** [kcp-dev/kcp#3043]
### Describe the bug

Since [v0.21.0](https://github.com/kcp-dev/kcp/releases/tag/v0.21.0) has been released last month, a build of kcp at `ghcr.io/kcp-dev/kcp:v0.21.0` is expected. The tag does not exist though. This was brought up on [#kcp-dev](https://kubernetes.slack.com/archives/C021U8WSAFK/p1700228203057569).

### Steps To Reproduce

1. Try to pull `ghcr.io/kcp-dev/kcp:v0.21.0`

### Expected Behaviour

Releases have images available for usage

**Comment by xrstf** [comment]
```
branch="$(git rev-parse --abbrev-ref HEAD)"
branchImage="$repository:$branch"
```

yielded unexpected results, breaking the postsubmit:

```
Creating manifest ghcr.io/kcp-dev/kcp:v0.21.0 ...
2889cad2c43067cdb80c0c1ac24db9cf62b723c19a4a546522c5de4861615a6e
2889cad2c43067cdb80c0c1ac24db9cf62b723c19a4a546522c5de4861615a6e: sha256:1c3ca6a16cb636db0d1637808d70ab3e6e28cb31942a4cd57a9adfc323b425b1
2889cad2c43067cdb80c0c1ac24db9cf62b723c19a4a546522c5de4861615a6e: sha256:7707c52959492a9cbb25edca8b3234001cfed0ff813a0d4205607a129c19053e
2889cad2c43067cdb80c0c1ac24db9cf62b723c19a4a546522c5de4861615a6e: sha256:b6573d70b3526ead9d7c257cf6f02da6b7444c60942e10d6d5730143289e3ef2
Creating manifest ghcr.io/kcp-dev/kcp:heads/v0.21.0 ...
Error: encountered while expanding image name "ghcr.io/kcp-dev/kcp:heads/v0.21.0": parsing name "ghcr.io/kcp-dev/kcp:heads/v0.21.0": cannot parse input: "ghcr.io/kcp-dev/kcp:heads/v0.21.0": invalid reference format
```

**Comment by embik** [comment]
Image fixed, see [#kcp-dev](https://kubernetes.slack.com/archives/C021U8WSAFK/p1700677219924739).

(https://github.com/kcp-dev/kcp/pkgs/container/kcp/150430784?tag=v0.21.0)
