### ISSUE TITLE
Organizational Workspace

### ISSUE THREAD

**Issue by pweil-** [kcp-dev/kcp#307]
As part of prototype2 we've created a single "organizational" workspace for others to inherit from (https://github.com/kcp-dev/kcp/issues/277).  This admin workspace is untyped and hard coded.  This issue is to refine that work to provide the actual organizational type.

- [ ]  Review of https://github.com/kcp-dev/kcp/issues/277 and finalize design of organizational workspace type that supports api inheritance
- [ ]  Refinement of this issue or creation of new issues for implementation steps (which may be incremental)
- [ ]  Implementation of whatever is determined as the next phase of workspace support in the prototype

References

Note: documents shared with `kcp-dev` google group.

[Exploration of a kcp API model: Workspace, APIImport, APIExport, APIResourceSchema](https://docs.google.com/document/d/1k72fgGBNJzbY1Rkxj9_1WksHZR0cNT5OeadCpWuc-zM/edit#heading=h.5hl04ap2sjps)

[Exploration: Where do Workspaces live?](https://docs.google.com/document/d/1ifBSw9-KLT5uX3S6g5ObYX7p82m06v6Zq-J0p_51kzU/edit#)

**Comment by ncdc** [comment]
@sttts if you're able, please update the description and include checkbox tasks for each related issue and/or PR
