### ISSUE TITLE
Make all our flag names consistent with dashes instead of underscores

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#313]
Update all command line flags defined in this repo to be consistent, using dashes instead of underscores. For example, --install_cluster_controller should be --install-cluster-controller.

Make sure to update all references to changed flags, including e.g. demo scripts and e2e code.

**Comment by ncdc** [comment]
@kcp-dev/kcp-prototypers do you think we should do this?

**Comment by pweil-** [comment]
This is probably a perfect candidate for help-wanted and good-first-issue labels, if someone is looking for their first commit.  👍

**Comment by eddycharly** [comment]
👋 I would like to give a try to this one if it's ok.
