### ISSUE TITLE
All e2e errors that cause a test to fail are logged as test.go:135

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#316]
The logs appear to come from here

https://github.com/kcp-dev/kcp/blob/e2d9c50c339c052fd1f3f7ec42211ef05766f477/test/e2e/framework/test.go#L135

but actually they come from 

https://github.com/kcp-dev/kcp/blob/e2d9c50c339c052fd1f3f7ec42211ef05766f477/test/e2e/framework/t.go#L90

I'm not sure there's any easy way to retain the original error file:line location, given the errors are created in a different goroutine (actual test code) and passed via channels, but I figured I'd at least file this for discussion.

cc @stevekuznetsov

**Comment by stevekuznetsov** [comment]
Yeah, I don't think there's any good way around this one :| 

If I remember correctly (I wish I had written this down last year, I just accepted it as true this time around), only the main goroutine can call `t.Error()` on the main `*testing.T`.

**Comment by ncdc** [comment]
I wrote a couple of helpers for Velero to handle a situation like this:
- https://github.com/vmware-tanzu/velero/blob/main/pkg/util/logging/log_location_hook.go
- https://github.com/vmware-tanzu/velero/blob/main/pkg/util/logging/error_location_hook.go

Might be useful to do something similar?

**Comment by marun** [comment]
I think moving away from RunParallel magic - in progress - will ensure that `t.Testing` methods like `Log` work as expected.
