### ISSUE TITLE
bug: Broken links on page workspaces

### ISSUE THREAD

**Issue by dvgitit** [kcp-dev/kcp#3204]
### Describe the bug

Based on tag v0.26.0

Broken links on page https://docs.kcp.io/kcp/v0.26/concepts/workspaces/

The links in the left side menu work, but bot on the page itsself.

Pages
[Workspace Types](https://docs.kcp.io/kcp/v0.26/concepts/concepts/workspaces/workspace-types/)

What are workspaces and how to use them.
[Virtual Workspaces](https://docs.kcp.io/kcp/v0.26/concepts/concepts/workspaces/virtual-workspaces/)

What are virtual workspaces and how do they work?

### Steps To Reproduce

1. Go to page https://docs.kcp.io/kcp/v0.26/concepts/workspaces/
2. Try to click on any link below "Pages"
3. 404 occurs

### Expected Behaviour

Should lead to designated page

**Comment by mjudeikis** [comment]
Was missing this:
```

func newKCPRestConfig(restConfig *rest.Config) (*rest.Config, error) {
	clusterConfig := rest.CopyConfig(restConfig)
	u, err := url.Parse(restConfig.Host)
	if err != nil {
		return nil, err
	}
	u.Path = ""
	clusterConfig.Host = u.String()
	clusterConfig.UserAgent = rest.DefaultKubernetesUserAgent()
	return clusterConfig, nil
}

```
Wrong rest config
