### ISSUE TITLE
Naming challenge: cluster becomes

### ISSUE THREAD

**Issue by derrickburns** [kcp-dev/kcp#321]
The way you use cluster is a namespace for set of resources and namespaces.  How about ResourceDomain?

**Comment by sttts** [comment]
Had suggested the same name some time ago.

Workspace = Logical Cluster in a shard = ResourceDomain/ResourceSpace. 

But I doubt it is easy to understand from a user point of view.

**Comment by pweil-** [comment]
Should we wrap this into the other naming issue we have open and close? https://github.com/kcp-dev/kcp/issues/346

cc @stevekuznetsov

**Comment by stevekuznetsov** [comment]
@derrickburns great point! Let's continue the conversation in #346
