### ISSUE TITLE
bug: nested page links in documentation return 404

### ISSUE THREAD

**Issue by embik** [kcp-dev/kcp#3218]
### Describe the bug

On nested pages that have a section overview (e.g. https://docs.kcp.io/kcp/v0.26/concepts/workspaces/#pages), links 404. These are auto-generated but it looks like the generation is broken:

https://github.com/kcp-dev/kcp/blob/718bcb274f98cdf6c89457d9186b56550326c619/docs/content/concepts/workspaces/index.md?plain=1#L39

The same generation is used in different pages where it works fine: https://github.com/kcp-dev/kcp/blob/718bcb274f98cdf6c89457d9186b56550326c619/docs/content/concepts/index.md?plain=1#L3

### Steps To Reproduce

1. Go to https://docs.kcp.io/kcp/v0.26/concepts/workspaces/.
2. Try to click "Workspace Types" under the "Pages" headline.
3. It returns the GitHub pages 404 page.

### Expected Behaviour

The auto-generated sub-page links should work and link to the right page.

**Comment by jmcshane** [comment]
im taking this
