### ISSUE TITLE
feature: CLI doc update

### ISSUE THREAD

**Issue by mjudeikis** [kcp-dev/kcp#3222]
### Feature Description

Currently, we have 3 CLI modules, but only 1 is wired into documentation generation:
![image](https://github.com/user-attachments/assets/d11e2145-6d6a-4da9-b82e-318522e82352)
![Screenshot 2024-12-18 at 18 08 52](https://github.com/user-attachments/assets/37e69aec-bdd7-4e4b-96b7-02b93568d232)

While other modules are kinda reprinted in this as they are added in, this is bit confusing.

### Proposed Solution

We should extend rest of cli modules to generate docs same way we  do for `kubectl-kcp` one and so extend the docs. 

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by jmcshane** [comment]
I'm taking this
