### ISSUE TITLE
Move CI from GitHub Actions to Prow

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#324]
We have discussed in Slack a few times about moving to Prow. Many of us are more familiar with Prow and it is consistent with how Kubernetes/kubernetes-sigs/OpenShift projects do CI, which will likely be important if we ever donate this project to the CNCF.

Please vote 👍 or 👎 if you think we should move from GitHub Actions to Prow for our CI jobs.

If the decision is 👍, then let's add this to our scheduled list of tasks so we can properly plan for it.

**Comment by stevekuznetsov** [comment]
Some of the other things I've noticed with GitHub actions which Prow fixes for us (but is not the only tool to do so) are:

 - base PR on top of the branch it's merging into for testing
 - ensure PR is tested against latest branch before merging
 - support for jUnit or similar per-test views
 - support for an in-browser artifact viewer
 - able to trigger new jobs on existing PRs when new jobs are added or existing jobs change

**Comment by pweil-** [comment]
@ncdc - looks like this is ready to be added to the schedule somewhere.  If there is no urgency maybe we can stick `help-wanted` on it to see if anyone is interested or get it into P4's tech objectives.

**Comment by ncdc** [comment]
@pweil- this would potentially be a long-term thing, unless GH actions stop serving our needs sooner. I'm a bit hesitant on adding help-wanted, as it requires knowledge of and access to infra where Prow is currently running (either for OpenShift or Kube).

**Comment by stevekuznetsov** [comment]
Items left TODO:

 - [ ] finalize image builds, they are published but we need them to be 1:1 with existing ones (cc @kylape )
 - [ ] add jobs etc for release branches
 - [ ] figure out where jUnit files go for multiple-runs tests ...
 - [ ] get the e2e-shared-server setup/run into a reproducible `make` target and get it running in prow

**Comment by sttts** [comment]
- [ ] https://github.com/kcp-dev/kcp/issues/1209

**Comment by kylape** [comment]
When this issue is ready to be closed, does that mean we can remove the Github Action tasks that build images?

**Comment by ncdc** [comment]
If we're moving to Prow for image builds, yes
