### ISSUE TITLE
Community Meeting January 4, 2022

### ISSUE THREAD

**Issue by imjasonh** [kcp-dev/kcp#344]
At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/ohf-kwvd-mrp
Or dial: ‪(US) +1 617-675-4444‬ PIN: ‪936 182 087 7398‬#
More phone numbers: https://tel.meet/ohf-kwvd-mrp?pin=9361820877398
Or join via SIP: sip:9361820877398@gmeet.redhat.com

This issue will collect prospective agenda topics. Add topics you'd like to discuss below!

**Comment by imjasonh** [comment]
- Go over prototype 2 goals, project board: https://github.com/orgs/kcp-dev/projects/1
- @ncdc made some progress on transparently multi-lcluster shared informers before the break; demo?
- @stevekuznetsov wanted to talk about fixing our names for things

**Comment by stevekuznetsov** [comment]
Let's rally around putting some ideas into https://github.com/kcp-dev/kcp/issues/346 for naming

**Comment by imjasonh** [comment]
Next: #358
