### ISSUE TITLE
Let's Figure Out Some Names!

### ISSUE THREAD

**Issue by stevekuznetsov** [kcp-dev/kcp#346]
We've got some names/concepts/types that are named in a way that's either confusing or misleading, so let's brainstorm some ideas for how to make them better:

- `WorkspaceShard` is not sharding the content of workspaces, but the kcp key-space
- `OrgnizationalWorkspace` is a mouthful and could likely be shortened to be clearer
- `VirtualWorkspace` is not clear, some of these are virtual views into the keyspace, some are bona fide workspaces, etc

**Comment by stevekuznetsov** [comment]
Re: "Organization" - right now we loosely use this to mean a `Workspace` that holds other `Workspace` objects with some shared ownership model. My intuition says that it's surprising to have an organization made up of workspaces, rather than people, and we perhaps want some better distillation of the single-layer ownership that we are trying to create there.

**Comment by davidfestal** [comment]
As for `VirtualWorkspace`, after some brainstorming on the `kubernetes` channel, the old proposal `APIDomain` from @stts came back.
The proposal would be to name them `VirtualAPIDomain`s. More details below.

If we agree that:

A `Workspace` would be
_a URL following some URL schema that serves discovery, openapi, `/apis`_ 
**+ additional features like the ability to add types through CRDs + the basic kcp types (like config map, secrets, etc...)**

then:

**only** _a URL following some URL schema that serves discovery, openapi, `/apis`_
would strictly be an `APIDomain`

Design and implementation wise, it seems that what we started implementing as `VirtualWorkspaces` are more generally `VirtualAPIDomain`s
In some cases they would be used as `Workspaces` (as defined above), in other cases (mainly for KCP internal usage) they wouldn't (take the APIExports virtual workspace for example)

**Comment by sttts** [comment]
In daily communication with non-kcp-experts using "Virtual APIs under some separate http path with its own discovery+openapi" is a good wording, instead of using the technical term `VirtualAPIDomain`. The later is merely used in code.

**Comment by stevekuznetsov** [comment]
A short summary of terms that we've had issues with:

| Description | Current Nomenclature | 
| - | - |
| a `Workspace` object which refers to a logical cluster that holds other `Workspace` objects | _organization_ |
| a statically placed logical cluster on which `Workspace` objects implementing _organizations_ exist | _root organizational workspace_ |
| a URL under which the client finds discovery + openAPI + a kube-like API | _workspace_ |
| a _workspace_ implemented with a logical cluster, exposed through a central proxy | `Workspace` |

**Comment by ncdc** [comment]
Clearing milestone to re-triage

**Comment by ncdc** [comment]
ClusterWorkspaceShard -> Shard?

There is no OrganizationWorkspace or VirtualWorkspace CRD
