### ISSUE TITLE
Clients of the Caching Server Need to be Cross-workspace list/watch resilient

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#348]
Shards can go down or become unreliable, for planned maintenance or due to failures. Shards going being unavailable is a normal state we have to cope with, i.e. cross-shard list/watch must be resilient to this, i.e. an informer must keep working although its data is only partial.

Objectives:
- [ ] shutting down a shard (or complete region) that is watched must not stop an informer from working on different shards
- [ ] an unavailable shard (or complete region) must not stop an informer from start up (sync)
- [ ] slowing down requests to a shard (or complete region) must not stop an informer from start up (sync)

Details:
Informers today only have a black/white error logic, i.e. they are either synced or they are not. In a multi-shard world this is not enough. We probably need "partial cache sync" and make listers to work even on partial data, and return proper errors for shards that are unavailable.

**Comment by sttts** [comment]
cc @stevekuznetsov @marun

**Comment by sttts** [comment]
From https://docs.google.com/document/d/1MhfRk_VV5orvspx1OzU5De7nnE6va9lIpLUKBKnzuWE/edit#heading=h.pf3xelmd3qxe:

> the consistent list/watch server could notify down or lagging shards via extra events, and informers/listers could learn to process them and return "Unavailable" errors when trying to get or list items from them.
>
> There is a watch.Error type event already in upstream:
```golang
//  * If Type is Error: *api.Status is recommended; other types may make sense
//    depending on context.
```

**Comment by ncdc** [comment]
Clearing milestone to re-triage

**Comment by pweil-** [comment]
0.8 check in, on track to land?

**Comment by p0lyn0mial** [comment]
I think this will be part of https://github.com/kcp-dev/kcp/issues/1225 effort when we start using the cache server from shards.

Some work already has been done, like reading identities from a local config map https://github.com/kcp-dev/kcp/pull/1727

**Comment by stevekuznetsov** [comment]
We should get a better idea of what constitutes "done" for this - are we going to create a test suite that injects chaos into the cache server?

**Comment by p0lyn0mial** [comment]
After discussing it with @sttts we can close this issue. Most of the objectives will be replaced by the caching layer. 

Reporting stale/old data from an informer is only outstanding, which is captured in a separate issue. @stevekuznetsov could you share a link to that issue?

**Comment by pweil-** [comment]
Couple links that might be helpful:

[Sharding Project View](https://github.com/orgs/kcp-dev/projects/1/views/44)
[Provide Users With an API to Request Cached, Global/Regional Views of Data (ReplicationClaims)](https://github.com/kcp-dev/kcp/issues/2007) (mentions monitoring liveness/staleness)
[Caching Proxy MVP](https://github.com/kcp-dev/kcp/issues/342) (mentions stale reads)
