### ISSUE TITLE
Prototype Workspace Life Cycle on Shards

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#354]
# Workspace Life Cycle on a Shard

**Objective:** kill all other shards and the workspaces on that shard should keep working

A shard a workspace is scheduled to can store data under a lcluster (= etcd prefix) without knowing about the workspaces it hosts. But this has downsides:

1. everybody (with permission) can store and retrieve arbitrary lcluster data
2. there would not be a record of key ranges in etcd to clean up after or before workspace scheduling
3. critical data for autonomous operation would be missing, e.g. CRDs, RBAC data
4. as a consequence every shard has to call out to other shards, potentially in different availability zones or regions. This is harmful for availability and resilience to network issues.

To mitigate these, we propose that shards replicate (read-only) certain data into lclusters for their own consumption "reserved shard lclusters/workspaces", not exposed externally (to users or even admins via the proxy):

1. **partially:** the org workspaces for which workspaces are hosted:
    1. RBAC RoleBindings and Role relevant to allow access to Workspaces
    2. Workspace objects for those workspaces hosted, 
    3. and for limited time (e.g. 1h or 1d) Workspace objects for those workspaces that have been migrated away (for redirection).
2. **partially:** the root org workspaces with the org Workspace objects of org workspaces in (1).
3. an "apiimports" lcluster holding uniquely named CRDs generated and deduplicated for bound APIResourceSchemas of APIImports in workspaces hosted by the shard.

To implement these:

- [ ] We **add a number of controllers in the kcp shard** that will keep the upper (1)-(3) lclusters up-to-date, watching the org workspaces.
- [ ] We **guard Workspace object deletion** in (1b) with a workspace data deletion step e.g. via a finalizer on the replicated Workspace object.
- [ ] We **add readiness to a Workspace status** to state that the replication has finished. We report in a condition "InitialSharedDataReplication" about success or failure. The readiness is for the target shard, and it is reset to false when a new target shard is set (i.e. during initial scheduling or during/before movement)
- [ ] The **shard will reject traffic** for the lcluster until the Workspace is marked ready.
- [ ] Non-loopback **requests to these reserved shard lclusters are rejected** (via authz or a filter in the handler chain).

Copied from: https://docs.google.com/document/d/1MhfRk_VV5orvspx1OzU5De7nnE6va9lIpLUKBKnzuWE/edit#

**Comment by ncdc** [comment]
Clearing milestone to re-triage

**Comment by stevekuznetsov** [comment]
Superseded by #342
