### ISSUE TITLE
Community Meeting January 11, 2022

### ISSUE THREAD

**Issue by pweil-** [kcp-dev/kcp#358]
At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/ohf-kwvd-mrp
Or dial: ‪(US) +1 617-675-4444‬ PIN: ‪936 182 087 7398‬#
More phone numbers: https://tel.meet/ohf-kwvd-mrp?pin=9361820877398
Or join via SIP: sip:9361820877398@gmeet.redhat.com

This issue will collect prospective agenda topics. Add topics you'd like to discuss below!

**Comment by stevekuznetsov** [comment]
Update on single-integer-resource-version for workspace-scoped client interactions

**Comment by pweil-** [comment]
next milestone brainstorming

**Comment by sttts** [comment]
Andy's update about scopes in clients and informers.

**Comment by pweil-** [comment]
> next milestone brainstorming

Decision: @pweil- to add section to https://docs.google.com/document/d/1jN6BdhUUIESeHw3_f6HwsNwVM2Ytabr6usUQhYMcNd8/edit#heading=h.v0ybspmfdqn3. Team will refine the story of "what are the next useful pieces of the use case to add" as well as any tech requirements from medium-term objectives that need started.  Then will migrate to github issues as before.

**Comment by imjasonh** [comment]
Recording: https://youtu.be/HDb8BZCIzrs
