### ISSUE TITLE
Community Meeting January 18, 2022

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#368]
At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/ohf-kwvd-mrp
Or dial: ‪(US) +1 617-675-4444‬ PIN: ‪936 182 087 7398‬#
More phone numbers: https://tel.meet/ohf-kwvd-mrp?pin=9361820877398
Or join via SIP: sip:9361820877398@gmeet.redhat.com

Meeting recordings available on YouTube at https://www.youtube.com/channel/UCfP_yS5uYix0ppSbm2ltS5Q

This issue will collect prospective agenda topics. Add topics you'd like to discuss below!

**Comment by pweil-** [comment]
Prototype 3 brainstorming, thoughts welcome! https://docs.google.com/document/d/1jN6BdhUUIESeHw3_f6HwsNwVM2Ytabr6usUQhYMcNd8/edit#heading=h.wpdhxgis28cy

**Comment by ncdc** [comment]
Next: #378

**Comment by imjasonh** [comment]
Recording: https://youtu.be/_9ilcimFyec
