### ISSUE TITLE
Allow syncer to run out-of-cluster

### ISSUE THREAD

**Issue by imjasonh** [kcp-dev/kcp#37]
Currently, the prototype cluster-controller connects to the target cluster to install the syncer as a Pod (soon Deployment) in the cluster, where it connects to the local cluster's API server using [`rest.InClusterConfig`](https://github.com/kcp-dev/kcp/blob/f7c361ddeb87d4f2ce87cdfd2d9e168624585a22/cmd/syncer/main.go#L48).

This requires the user to [build and push an image for the syncer](https://github.com/kcp-dev/kcp/blob/main/DEVELOPMENT.md#build-and-run-cluster-controller), which isn't ideal, and isn't really strictly necessary.

Instead, syncer code should be agnostic to where it's run and not depend on `InClusterConfig`, just taking `targetKubeconfig` and `kcpKubeconfig` and construct clients from those.

That would make it portable to run outside the cluster, either as another loop in cluster-controller, or as a separate process. If it turns out we want the syncer to run in the cluster, we can still do that too.

**Comment by davidfestal** [comment]
This should be fixed by PR https://github.com/kcp-dev/kcp/pull/42
