### ISSUE TITLE
Define A Useful Readiness Check for Shard Proxy

### ISSUE THREAD

**Issue by stevekuznetsov** [kcp-dev/kcp#371]
In the current workspace index controller, we try to define readiness by checking that we have no currently-running workers and that our queues are empty (here). In a busy `kcp` deployment, it's not likely that this will be true often, so we risk having a constantly-unavailable index. We should figure out a more reliable and useful readiness check - one naive approach might be to just use `sync.Once` to latch ready once it's true at least once, but perhaps other approaches might be useful as well.

This is about this discussion https://github.com/kcp-dev/kcp/pull/353/files#r788603319.

**Comment by stevekuznetsov** [comment]
cc @sttts

**Comment by sttts** [comment]
Was thinking to synchronously get root workspace, and then create a shared map as a set for all org workspace names. Everytime one of them syncs once (the informer that is asynchronously created on the way deep in the controller) we remove the org name from the set. Something around these lines. Hope that's not too ugly.

**Comment by stevekuznetsov** [comment]
`sync.Once` with the current impl might be simpler by a long shot and get to the same place - as long as we think we'll settle down at least once.

**Comment by ncdc** [comment]
Clearing milestone to re-triage

**Comment by sttts** [comment]
Superseeded by sharded front-proxy work.
