### ISSUE TITLE
Prototype 2 Exit Criteria Tasks

### ISSUE THREAD

**Issue by pweil-** [kcp-dev/kcp#373]
[Milestone](https://github.com/orgs/kcp-dev/projects/1)

- [ ] Create prototype 2 demo 
- [ ] Create prototype 2 FAQ to address expected questions on demo highlighting things we expect future releases to address
- [ ] Update project documentation for latest project state including: build/deploy, development guide, links to demos, currently available features
- [ ] Update project visual messaging in organization and repo to capture latest blurb of what P2 KCP is (vs P1 KCP)
- [ ] Create P2 KCP public framing (clayton to sync with various people)
- [ ] Potentially update visual framing (icon, colors) of key visual elements (if not possible, defer to P3)

**Comment by sttts** [comment]
Temporary gdoc with the demo script https://docs.google.com/document/d/1ACwnb3On-QY4t-NdmxDdvXeZXw5BvuKO6L2Mmi5Nhtk/edit?userstoinvite=fvonfeil@redhat.com&actionButton=1#

**Comment by pweil-** [comment]
Closing this since the demo is recorded.  We still need to get some doc refinement but we're closing in on p3 dates so this has become moot for p2
