### ISSUE TITLE
Move pcluster namespace creation/deletion up into kcp layers

### ISSUE THREAD

**Issue by imjasonh** [kcp-dev/kcp#387]
Today, the syncer is responsible for creating namespaces in its pcluster if they don't already exist. This gives the syncer lots of access to the cluster, more than it should have.

Instead, the namespace scheduler (and deployment-splitter, for as long as it lives) should detect a missing pcluster namespace and create it, with name transformation taken into place a la #380.

In this way, a pcluster still has to grant kcp extensive access to the cluster, but the syncer running in the cluster will only use the minimal necessary to create/update/delete namespaced objects in kcp-managed pcluster namespaces.

**Comment by marun** [comment]
> Instead, the namespace scheduler (and deployment-splitter, for as long as it lives) should detect a missing pcluster namespace and create it, with name transformation taken into place a la #380.

Doesn't this presume that a pcluster is directly reachable from kcp? I thought one of the justifications for implementing reconciliation on pcluster (the syncer) was because kcp wouldn't be guaranteed direct access to pclusters. But as I'm writing that, how would the syncers be installed if kcp couldn't reach a pcluster?

**Comment by imjasonh** [comment]
Connectivity shouldn't be necessary to make progress on a workload, but kcp still needs to create and healthcheck syncers, so there's some intermittent connection assumed today.

We could be more resilient to connection issues by making the syncer retry if the namespace doesn't exist.

A degraded scenario would mean existing namespaces are unaffected but new ones can't be created, meaning pcluster reassignments might also not reach the disconnected cluster. I think that's probably mostly fine? Kcp should eventually detect that condition and reassign to a connected cluster.

**Comment by ncdc** [comment]
One way to do this is that a cluster admin would have to take action to register their cluster with kcp. This action would likely include installing the syncer on their cluster. The direction would be pull (syncer in cluster connects to kcp, kcp is not permitted to connect to cluster).

I believe this is the approach @jmprusi is taking. And health checks would mimic how Nodes behave today, where they heartbeat to the apiserver, and the control plane makes assumptions about Node health if too many heartbeats are missed.

**Comment by imjasonh** [comment]
In general I definitely think that's the approach we want, for lots of reasons.

If we go that route entirely, then the syncer (or some component in the cluster) has to have permission to create and delete namespaces. It doesn't have to be the syncer exactly, if we think it's easier to lock down a namespace-only syncer. That was roughly the approach we talked about a few weeks ago (or longer, time has no bearing on reality anymore), but the simplicity of just moving namespaces outside the cluster sounded nice. Maybe it's not better after all?

**Comment by sttts** [comment]
We don't want the syncer to have this far reaching access. Hence, we need a different actor. This can be kcp, but having pull and then kcp doing push is super odd. 

> moving namespaces outside the cluster sounded nice

What exactly is our requirement. This feel heavily connected to @jmprusi 's work, i.e. the UX of adding a pcluster. Is this joining on the pcluster side supposed to be a privileged operation?

We can have two components: 1) syncer 2) syncer namespace controller. (2) can be per syncer, or can be for multiple syncers. The result would be, when trying to add some kube cluster to kcp as a non-admin:

1. ask your admin to install the namespace controller
2. use your own credentials to install the syncer.

OpenShift also has projects which are non-admin-usable through ProjectRequests. So in such a setup we can have a custom mechanism that makes use of that.

**Comment by ncdc** [comment]
We are starting to trend toward adding more privileges to the syncer (e.g. PV manipulation), so we are going to close this for now. We can open a new issue if/when we need an unprivileged syncer.
