### ISSUE TITLE
Namespaces don't get deleted from pclusters when they're deleted from kcp.

### ISSUE THREAD

**Issue by kylape** [kcp-dev/kcp#398]
**Describe the bug**
Namespaces don't get deleted from pclusters when they're deleted from kcp.

**To Reproduce**
1. Set up kcp with at least one pcluster configured for the current workspace
2. Create a namespace in kcp
2. Create a resource in said namespace that gets sync'd to the pcluster
3. Delete said namespace in kcp

**Expected behavior**
Corresponding namespace will be deleted in pcluster

**Comment by wangke19** [comment]
Reproduced on v0.7.1

$ k version -o yaml
clientVersion:
  buildDate: "2022-06-15T14:22:29Z"
  compiler: gc
  gitCommit: f66044f4361b9f1f96f0053dd46cb7dce5e990a8
  gitTreeState: clean
  gitVersion: v1.24.2
  goVersion: go1.18.3
  major: "1"
  minor: "24"
  platform: darwin/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-08-09T18:22:25Z"
  compiler: gc
  gitCommit: c4c1214
  gitTreeState: dirty
  gitVersion: v1.24.3+kcp-v0.7.1
  goVersion: go1.17.13
  major: "1"
  minor: "24"
  platform: linux/amd64

Create one personal workspace.
$ kubectl kcp workspace create  kews1 --enter
Workspace "kews1" (type root:universal) created. Waiting for it to be ready...
Workspace "kews1" (type root:universal) is ready to use.
Current workspace is "root:rh-sso-xxx:kews1" (type "root:universal").

Attached personal workspace to the exist shared compute

$ k api-resources -o wide | grep namespace
namespaces                        ns           v1                                     false        Namespace                        [create delete get list patch update watch]

$ k create namespace test1
namespace/test1 created

$ k get namespaces
NAME      STATUS   AGE
default   Active   7h20m
test1     Active   9s

$ k delete namespace test1 &
namespace "test1" deleted

$ k edit ns test1 # change finalizers value is null
namespace/test1 edited

$ k get ns
NAME      STATUS        AGE
default   Active        12h
test1     Terminating   5h18m

$ k get namespace test1 -o yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kcp.dev/cluster: root:rh-sso-xxx:kews1
    scheduling.kcp.dev/placement: ""
  creationTimestamp: "2022-08-16T10:45:18Z"
  deletionTimestamp: "2022-08-16T10:45:56Z"
  labels:
    kubernetes.io/metadata.name: test1
    state.workload.kcp.dev/5Kty713PsPctnzYein2IeYFcolGMNIsfVcbi2Y: Sync
  name: test1
  resourceVersion: "364478"
  uid: 47147053-b092-4c42-a682-2d7d4b23a32e
spec:
  finalizers:
  - kubernetes
status:
  conditions:
  - lastTransitionTime: "2022-08-16T10:46:03Z"
    message: 'Some resources are remaining: configmaps. has 1 resource instances,
      secrets. has 1 resource instances'
    reason: SomeResourcesRemain
    status: "True"
    type: NamespaceContentRemaining
  - lastTransitionTime: "2022-08-16T10:46:03Z"
    message: All content successfully deleted, may be waiting on finalization
    reason: ContentDeleted
    status: "False"
    type: NamespaceDeletionContentFailure
  - lastTransitionTime: "2022-08-16T10:46:03Z"
    message: All resources successfully discovered
    reason: ResourcesDiscovered
    status: "False"
    type: NamespaceDeletionDiscoveryFailure
  - lastTransitionTime: "2022-08-16T10:46:03Z"
    message: All legacy kube types successfully parsed
    reason: ParsedGroupVersions
    status: "False"
    type: NamespaceDeletionGroupVersionParsingFailure
  - lastTransitionTime: "2022-08-16T10:46:03Z"
    message: 'Some content in the namespace has finalizers remaining: workload.kcp.dev/syncer-5Kty713PsPctnzYein2IeYFcolGMNIsfVcbi2Y
      in 2 resource instances'
    reason: SomeFinalizersRemain
    status: "True"
    type: NamespaceFinalizersRemaining
  - lastTransitionTime: "2022-08-16T10:45:18Z"
    status: "True"
    type: NamespaceScheduled
  phase: Terminating
