### ISSUE TITLE
Implement sharing of personal workspaces

### ISSUE THREAD

**Issue by davidfestal** [kcp-dev/kcp#403]
Implement personal workspace sharing.
This includes:
- [ ] Adding a share sub-resource to the *personal workspaces* virtual workspace implementation, that would implement sharing by creating the required cluster role bindings in the KCP org workspace
- [ ] Adding a `share` sub-command that points to the new sub-resource

**Comment by stevekuznetsov** [comment]
IMO we should keep as much of the RBAC as possible unless we really expect not to use it in the future, so no `share` but `add-role-to-user` ...

**Comment by slaskawi** [comment]
In https://github.com/kcp-dev/kcp/pull/726 I removed lister permissions from sharing. 

When discussing this with @davidfestal, we came to the conclusion, that workspace sharing will need to be redesigned and will potentially end up with a completely different solution.

**Comment by ncdc** [comment]
Clearing milestone to re-triage

**Comment by ncdc** [comment]
Will be replaced by #1069 and for any new UX work, we can add new tasks/issues
