### ISSUE TITLE
Missing README file in the demo folder (and broken link in the main README file)

### ISSUE THREAD

**Issue by e-minguez** [kcp-dev/kcp#410]
**Describe the bug**
The main README file links to a README located in the demo folder (https://github.com/kcp-dev/kcp/blob/main/README.md#whats-in-this-repo) which doesn't exists

**To Reproduce**
1. Go to https://github.com/kcp-dev/kcp
2. Get excited by kcp
3. Try to check the demo
4. 404 not found

**Expected behavior**
A brief README file with some details about the demo

**Additional context**

**Comment by pweil-** [comment]
FYI for whoever picks this one up, it looks like the original README was renamed during the move to dedicated subfolders in https://github.com/kcp-dev/kcp/commit/30a3d93d7debcd4b4758f8df03e29926cbd2199d

An index into those folders with a brief description is probably a good place to start and would probably be part of https://github.com/kcp-dev/kcp/issues/373
