### ISSUE TITLE
Prototype 3: API End-User Demo

### ISSUE THREAD

**Issue by pweil-** [kcp-dev/kcp#416]
# NOTE Work for this is being tracked in #417 

### Demo Objective
Need to establish the API operator and how it connects to the mission.  User thinks about the API, not the impl - transparent across physical clusters

1. Preferably something that the app can use directly
1. Preferably something that creates something that ends up with the app (config map, secret, or workload object)
1. Preferably something that really hits multi-cluster problems users have
1. We don’t want to create it, we don’t want it to distract

### Demo Steps
1. User begins journey at the end of the [Transparent Multi-Cluster End-User Demo](https://github.com/kcp-dev/kcp/issues/415)
1. User subscribes to a cert-manager API (APIImport).
1. User creates a stateless web application
1. User creates a cert-manager CR for the app to use. Certificates show up.
1. ~~User decides to migrate the app between Locations for Reasons~~
1. ~~Client-facing traffic sees no interruption(?)~~
1. [v0.5] **In another workspace another API sub-version can be installed.**
1. [v0.5] **In yet another workspace a bring-your-own CRD and operator can be installed (optional part: deploy it via TMC).**

### Action Items

- [X] Scope the current demo as necessary to fit in prototype boundaries
- [X] Contribute to final demo script and recording = #763

**Comment by pweil-** [comment]
For easy access, I believe this is the current doc on [APIImport/Export](https://docs.google.com/document/d/1k72fgGBNJzbY1Rkxj9_1WksHZR0cNT5OeadCpWuc-zM/edit)

**Comment by kylape** [comment]
My impression is that this demo is the same as transparent multi-cluster but it's just adding an APIImport into the mix and watching kcp do the right thing with the CR.

**Comment by pweil-** [comment]
> I don't see what this is showing from an API export / import perspective - is that not just transparent multi-cluster?

This is defining the demo that the group wanted to show.  Yes, it re-highlights the feature of transparent multi-cluster.  I think we can assume that the work for 5&6 would be scoped to the TMC demo so we just need to define what else is needed to complete the flow here for p3.

**Comment by pweil-** [comment]
Community call where these were defined if it helps refresh context to the conversation here: https://www.youtube.com/watch?v=_9ilcimFyec

**Comment by sttts** [comment]
+1 for removing the location part. We should rather replace it with:

- multiple users with their own workspaces can enable the API
- maybe that the user can also install his own version of the CRD, with a bring-your-own cert-manager. The last part maybe we cannot show yet, but we can show that the platform cert-manager does not the see the CR of the foreign cert APIs.
