### ISSUE TITLE
Prototype 3 Exit Criteria

### ISSUE THREAD

**Issue by pweil-** [kcp-dev/kcp#419]
[Milestone](https://github.com/orgs/kcp-dev/projects/1/views/14)

- [x] Create prototype 3 demo 
- [ ] Create prototype 3 FAQ to address expected questions on demo highlighting things we expect future releases to address
- [ ] Update project documentation for latest project state including: build/deploy, development guide, links to demos, currently available features

**Comment by ncdc** [comment]
Even if we haven't necessarily completed all the tasks above, we are well past 0.3 and into 0.4, so closing this.
