### ISSUE TITLE
Syncer has a hot-loop

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#482]
It doesn't return after calling AddRateLimited, so it immediately calls Forget on the key, which resets the rate limiter back to 0.

**Comment by imjasonh** [comment]
Hey, nice catch!

https://github.com/kcp-dev/kcp/blob/dfc490d656822da51234c9c18678c3a0c7952c0d/pkg/syncer/syncer.go#L274

**Comment by ncdc** [comment]
It's my fault ☹️
