### ISSUE TITLE
Clarify the requirement and implementation of user "default" workspace

### ISSUE THREAD

**Issue by davidfestal** [kcp-dev/kcp#488]
It has been mentioned several times that when a user connects to KCP (through `kubecl kcp login`) for example, he should "land in" a default user workspace.

For now no workspace is created nor listed by default for a user when he first connects to KCP.

Simplest option is to create the default workspace (if necessary) and switch to it when the user first connects to the system, ie during the `kubectl kcp login` for example.
However approaches could be thought of, and discussed here, with the constraint that we don't want to pre-create workspaces that are not used.
This issue is related to the [following prototype 3 issue](https://github.com/kcp-dev/kcp/issues/415), in [this comment](https://github.com/kcp-dev/kcp/issues/415#issuecomment-1035152794)

**Comment by ncdc** [comment]
Clearing milestone to re-triage

**Comment by ncdc** [comment]
Replaced by #1069
