### ISSUE TITLE
Support explicitly setting the namespace name that will be synced to pclusters

### ISSUE THREAD

**Issue by marun** [kcp-dev/kcp#495]
Currently, the name of a namespace created by the syncer in a pcluster will be transformed from the originating kcp namespace to ensure uniqueness. This is necessary to allow multiple workspaces to contain the same namespace (e.g. foo) yet be scheduled to the same cluster. The transformation is `kcp-<hash of org+workspace+namespace>`.

For applications that need to implement their own scheme for ensuring the uniqueness of synchronized namespace names, it should be possible to specify the name to create a namespace as on pclusters via annotation (e.g. `kcp.dev/use-name: my-unique-name`) on the kcp namespace. The syncer would be responsible for creating the namespace and the resources it contains with this specified name. The syncer would continue to ensure that the kcp namespace could be identified from its pcluster equivalent via labels (currently an annotation but expected to switch).

**Comment by imjasonh** [comment]
Would it be the scheduler's responsibility to ensure two `use-name: foo` namespaces don't end up being scheduled to the same pcluster? Or would the syncer detect the collision and report back to the scheduler that it needs to re-roll and pick a new pcluster?

If a `use-name: foo` namespace can't be assigned to any pcluster due to conflicts, it would just become `Unscheduleable`?

**Comment by ncdc** [comment]
I'd like to suggest we treat this as a power-user configuration, and we don't try to do anything to prevent overlap. This would be similar to deployments/replicasets/pods and label selectors - if you have 2 deployments that overlap on label selection, they're going to fight each other to own & control the replicasets.

**Comment by ncdc** [comment]
Closing as it doesn't look like we actually want to do this any more
