### ISSUE TITLE
Syncer should support targeting existing pcluster namespaces

### ISSUE THREAD

**Issue by marun** [kcp-dev/kcp#496]
Currently, the syncer assumes responsibility for managing the lifecycle of a scheduled kcp namespace and its contained resources on a given pcluster. Internal discussion suggests that some uses cases may require that a non-kcp agent be responsible for creation of a given pcluster namespace and populating it with resources that kcp should not attempt to manage. This suggests that it be possible to indicate (e.g. via `kcp.dev/unmanaged: true` label on a kcp namespace) that only the resources explicitly contained by a kcp namespace are to be managed on a pcluster and that the syncer should not attempt to manage the namespace on the pcluster.

The syncer would respond to such a label by: 

 - never attempting to create/update/delete the namespace on the pcluster
 - never attempting to update/delete resources on the pcluster which do not correspond to resources in the kcp namespace
   - the syncer may need to be able to identify resources it manages (e.g. label with `kcp.dev/synced: true`) to avoid updating or deleting resources without that label in 'unmanaged' pcluster namespaces.

TODO: is 'unmanaged' the right descriptive term for a namespace for which kcp manages some but not all resources in on a pcluster?

**Comment by imjasonh** [comment]
Can you elaborate on the use case for this?

**Comment by ncdc** [comment]
Closing as it doesn't look like we actually want to do this any more
