### ISSUE TITLE
crdpuller: missing defaults in OpenAPI spec for map-keys break compatibility

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#498]
Against Kube `kubectl create deployment --image=gcr.io/kuar-demo/kuard-amd64:blue --port=8080 kuard` works, against kcp it does not (server-side validation error):

```
$ kubectl create deployment --image=gcr.io/kuar-demo/kuard-amd64:blue --port=8080 kuard

error: failed to create deployment: Deployment.apps “kuard” is invalid: spec.template.spec.containers.ports.protocol: Required value
$ kubectl create deployment --image=gcr.io/kuar-demo/kuard-amd64:blue --port=8080 kuard --dry-run=client -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kuard
  name: kuard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuard
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kuard
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:blue
        name: kuard-amd64
        ports:
        - containerPort: 8080 # protocol missing
        resources: {}
status: {}
$ kubectl create -f kuard.yaml
<same error but from client-side validation>
```

The root cause of this is that kube's ContainerPort has an optional field `protocol` [(ref)](https://github.com/kubernetes/kubernetes/blob/49dc22638164c415fd2c13d8a5f2013ca62151d1/pkg/apis/core/v1/defaults.go#L120) with 
1. a default value (`"TCP"`) that is not published via OpenAPI
2. `protocol` is a map-key.

Map-keys by kube API definition must be either required or they need a default [(ref)](https://github.com/kubernetes/kubernetes/blob/c84da4e3e61e08b1bd23c562a86504278eacee9b/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types_jsonschema.go#L129).

In the crdpuller we add map-keys as required fields [(ref)](https://github.com/kcp-dev/kcp/blob/e09328f19af8fe930b23b8d742211a7aa32e7182/pkg/crdpuller/discovery.go#L411).

We can question this behaviour if there is no default provided in OpenAPI because it leads to incompatible APIs, being stricter than the original one from the pcluster.

On the other hand, without a known default value, we can also not make the field non-required because that breaks CRD creation of the imported resources on the kcp side because "required or defaulted" is validated by apiextensions-apiserver.

The only way out it to get default values into the kcp CRDs, whereever from:
1. from OpenAPI from the pcluster. OpenAPI v3 will add defaults to be exported (still under an alpha feature gate) in 1.23, but likely beta in 1.24
2. from some OpenAPI schema patch for know cases in kcp. I.e. for a apps/v1 Deployment imported from a pcluster we would know to fix-up the spec.

TODOs:
1. [ ] Check all `k8s.io/api` types with `x-kubernetes-map-keys` for being optional. They must have a `+default` marker attached. If not, we should open a PR.
2. [ ] Add OpenAPI v3 support to the crdpuller.

**Comment by ncdc** [comment]
Would it also be possible to create a CRD where we can provide kcp with hints for these types of issues? e.g. a "FixDeploymentSchema" CR that says "default `spec.template.spec.containers[*].ports.protocol` to TCP"?

**Comment by varshaprasad96** [comment]
@sttts could you please elaborate on what is to be done to add OpenAPI v3 support to crdpuller. I can work on it. Thanks!

**Comment by ncdc** [comment]
Clearing milestone to re-triage

**Comment by lionelvillard** [comment]
I'd like to work on this. 

/assign
