### ISSUE TITLE
Ability to remove a workload from a physical cluster

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#504]
**Is your feature request related to a problem? Please describe.**
When I'm programming my global load balancer and I want to take a physical cluster out of service, I need to start draining a backend (connections routed to a pod on a physical cluster), wait for the drain to finish, and then remove the pod from that physical cluster.

**Describe the solution you'd like**
I'd like to be able to tell kcp when to remove a workload from a specific physical cluster.

**Describe alternatives you've considered**

**Additional context**

**Comment by ncdc** [comment]
@chirino please let me know if I captured this correctly

**Comment by chirino** [comment]
I think the important thing is that "wait for drain to finish" is also based on an **event that is external** to the physical cluster.  Our ingress control plane will in charge of emitting it.

**Comment by maleck13** [comment]
The functionality here feels very similar to that of a finalizer, except it is applied by a controller at the KCP level and then synced down to the physical cluster. Control plane decides when that finalizer is removed so that the resources can then be removed from the physical cluster.

**Comment by ncdc** [comment]
Clearing milestone to re-triage

**Comment by ncdc** [comment]
Could be done with some of the finalizer work in #914

**Comment by ncdc** [comment]
@davidfestal @sttts @jmprusi action item: please come back and provide an example of how this could be achieved with finalizers

**Comment by sttts** [comment]
Yes, this is exactly what an ingress coordination controller will do by hooking into the deletion via workload finalizers, compare https://github.com/kcp-dev/kcp/blob/main/pkg/apis/workload/v1alpha1/types.go. We might be ready in v0.5 to actually demo this.

**Comment by jmprusi** [comment]
The PR https://github.com/kcp-dev/kcp/pull/1228 has made available per-location virtual-finalizers by default, so your controller can apply backpressure, and block the deletion of a resource by adding an annotation to the resource:

```
finalizers.workload.kcp.dev/"<workloadClusterName>": "finalizer1,finalizer2,..."
```

The syncer expects that annotation to be empty, before deleting the resource. 

Does that cover your use-case?

**Comment by jmprusi** [comment]
As we talked via chat, this issue can be closed as this seems to cover the use-case! Thanks!
