### ISSUE TITLE
Cross-namespace service DNS resolution in physical clusters

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#505]
If a pod in namespace one references a service in another namespace, such as `some-service.two.svc.cluster.local`, how will that work in physical clusters where the namespace names are mapped and no longer retain their original names?

**Comment by ncdc** [comment]
As part of our scheduling investigations, we'll want to ensure that a deployment and the services it needs are scheduled to the same cluster ... or we encourage folks to switch to ingress/routing to go across clusters.

**Comment by ncdc** [comment]
Clearing milestone to re-triage

**Comment by chirino** [comment]
@astefanutti I think it's important that this work first for a single cluster.  It's one thing less that the E/W cross cluster traffic implementation would need to worry about.

Is the remapped namespace name the same across clusters (remapped namespace sameness would simplify things for the E/W traffic impl)?
