### ISSUE TITLE
kubectl kcp workload cordon|drain [cluster]

### ISSUE THREAD

**Issue by imjasonh** [kcp-dev/kcp#525]
**Is your feature request related to a problem? Please describe.**

As a pcluster admin, I want to easily cordon, uncordon and drain clusters using the kcp CLI plugin

**Describe the solution you'd like**

Add CLI surfaces to the `kubectl kcp` CLI plugin to cordon and drain clusters:

- `kubectl kcp workload cordon [cluster]`
- `kubectl kcp workload drain [cluster]`
- `kubectl kcp workload uncordon [cluster]`

**Describe alternatives you've considered**

People can just patch the Cluster resource today, but that's a bit clunkier.

**Additional context**

The behavior of the CLI should mirror the existing `kubectl` surface for (un-)cordoning and draining nodes in a cluster: https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/

**Comment by ncdc** [comment]
Depends on/blocked by #524, right?

**Comment by imjasonh** [comment]
> Depends on/blocked by #524, right?

Yep, should have mentioned that.

**Comment by ncdc** [comment]
Clearing milestone to re-triage

**Comment by chrisahl** [comment]
Wondering how you are expecting the user to list the workload cluster.  When I first looked at this I was thinking `kubectl kcp workloads` or `kubectl kcp workload list`.  But only option I see for `kcp workloads` is `sync`.  Having to use `kubectl get workloadcluster` to figure out the name does not seem as intuitive to me.  Thoughts?

Also want to be sure that the cordon/drain function you are looking for is for the ENTIRE cluster, not just a node in the cluster?  Have not tried to drain/cordon an entire cluster before but what if there is only one workloadcluster to begin with?

**Comment by chrisahl** [comment]
@ncdc I am interested in looking at this.  Can you add me to the kcp group so I can assign this to myself?

**Comment by ncdc** [comment]
Assigned!

**Comment by chrisahl** [comment]
NOTE:  Right now for `kubectl kcp workload drain [cluster]`, I did not see a way to know when the draining was complete.  So the current implementation of the command returns immediately, stating that the cluster is `draining`.  As opposed to `kubectl drain [node]` which waits until the drain is complete before returning.
