### ISSUE TITLE
`make codegen` doesn't work outside of GOPATH

### ISSUE THREAD

**Issue by imjasonh** [kcp-dev/kcp#531]
Repro:

1. clone the repo to somewhere outside of GOPATH
2. update some `types.go` to add a field, etc.
3. `make codegen` (succeeds)
4. deepcopy code isn't updated -- if you push a PR in this state, CI will fail ([example](https://github.com/kcp-dev/kcp/runs/5222837676?check_suite_focus=true))

---

This is using `controller-gen` v0.7.0, and ultimately I think it's a bug on their end.

We could either have `make codegen` detect you're not in GOPATH and fail more loudly, or do something like have it use a temp directory, make it GOPATH, do codegen and copy the result back to the original location.

**Comment by ncdc** [comment]
I fixed this upstream. Couldn't fix it in our fork of kcp due to `hack/update-vendor.sh` issues. I think I know how to work around those, though.
