### ISSUE TITLE
Improve logging readability by ensuring unique file basenames

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#541]
Because klog only logs a file's basename, if we have foo/controller.go and bar/controller.go, log messages originating from both files show up as controller.go, so it's difficult or impossible to know which file a log line is coming from.

Let's rename files to ensure unique basenames. Here is a current list of duplicates (excluding pkg/client and some other files such as doc.go, register.go, types.go that don't usually log and are ok to be duplicated):

# admission.go
- [ ] pkg/admission/clusterworkspacetype/admission.go
- [ ] pkg/admission/clusterworkspace/admission.go
- [ ] pkg/admission/clusterworkspacetypeexists/admission.go
- [ ] pkg/admission/apiresourceschema/admission.go

# bootstrap.go
- [ ] config/organization/bootstrap.go
- [ ] config/crds/bootstrap.go
- [ ] config/universal/bootstrap.go
- [ ] config/admin/bootstrap.go
- [ ] config/root/bootstrap.go
- [ ] config/helpers/bootstrap.go

# cache.go
- [ ] pkg/virtual/workspaces/cache/cache.go
- [ ] pkg/virtual/workspaces/auth/cache.go

# cluster_filtering.go
- [ ] pkg/virtual/framework/wrappers/rbac/cluster_filtering.go
- [ ] pkg/virtual/framework/wrappers/tenancy/cluster_filtering.go

# controller.go
- [x] pkg/reconciler/workspaceshard/controller.go
- [x] pkg/reconciler/cluster/controller.go
- [x] pkg/reconciler/workspace/controller.go
- [ ] pkg/reconciler/workspaceindex/controller.go
- [x] pkg/reconciler/ingresssplitter/controller.go
- [x] pkg/reconciler/namespace/controller.go
- [ ] pkg/reconciler/apiresource/controller.go
- [x] pkg/reconciler/deployment/controller.go

# controllers.go
- [ ] pkg/server/options/controllers.go
- [ ] pkg/server/controllers.go

# handler.go
- [ ] pkg/server/handler.go
- [ ] pkg/sharding/handler.go
- [ ] pkg/sharding/apiserver/handler.go

# kubeconfig.go
- [ ] pkg/server/kubeconfig.go
- [ ] pkg/cliplugins/workspace/plugin/kubeconfig.go

# options.go
- [ ] pkg/server/options/options.go
- [ ] pkg/cliplugins/workspace/plugin/options.go

# server.go
- [ ] pkg/server/server.go
- [ ] pkg/reconciler/workspaceindex/server.go

# validation.go
- [ ] pkg/admission/apibinding/validation.go
- [ ] pkg/admission/apiresourceschema/validation.go

**Comment by marun** [comment]
Ambiguous log lines are definitely a problem worth addressing. iirc that's an unavoidable result of using klog/glog? So unless we switch to something like logrus we're stuck ensuring filename uniqueness across packages? If that's the case a CI check is suggested to prevent regression...

**Comment by ncdc** [comment]
> iirc that's an unavoidable result of using klog/glog?

Correct

> unless we switch to something like logrus we're stuck ensuring filename uniqueness across packages?

Correct

> If that's the case a CI check is suggested to prevent regression...

I'm happy to start with manual curation. Also quite happy if someone wants to implement this.

**Comment by avinal** [comment]
I am in favor of switching to `logrus` or a similar logging package because no matter how hard we try we will run out of meaningful unique names that are also short. In any case please let me know, I would like to work on it. 👍🏼

**Comment by ncdc** [comment]
@avinal FYI please see #221 re a logging interface. Comments welcome!

If you'd like to start working on some of these renames, please let us know which one(s) and we'll add your name next to them.

**Comment by shaunaksen09** [comment]
I can take it up and do some deep dive @ncdc

**Comment by stevekuznetsov** [comment]
We should not implement this anymore, IMHO. With structured logging not only do we get `reonciler="whatever"` labels, but we get we also get filename/caller annotations as well.

**Comment by stevekuznetsov** [comment]
@ncdc are you OK with closing this?

**Comment by ncdc** [comment]
Yes, thanks for checking
/close
