### ISSUE TITLE
Namespace scheduler: only operate on things in Workspaces

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#542]
Rather than trying to assign from any logical cluster, the namespace scheduler should only assign from namespaces in Workspaces.

**Comment by sttts** [comment]
I would rather argue that the namespace scheduler should schedule when the workspace has subscriptions (we will see how that will look like in the API, APIImports or whatever) to workload APIs, and at least one resource ready for sync.

**Comment by ncdc** [comment]
What about for things like `deployments` - would you expect a workspace to need a subscription/APIImport for that?

**Comment by sttts** [comment]
yes, would expect that to be modular in the sense that it must be enabled. It can be that the enablement happens by default for most workspaces.

**Comment by ncdc** [comment]
(I'm happy to refine this over time - for the moment, folks are getting tripped up because namespaces in `""`/`admin` are getting labeled to a physical cluster, and then nothing else happens)

**Comment by sttts** [comment]
ok, quickfix is fine.

**Comment by pweil-** [comment]
Last day of P3, moving to P4

**Comment by sttts** [comment]
isn't this solved with @marun 's `ClusterWorkspaceType.spec.additionalLabels`?

**Comment by marun** [comment]
> isn't this solved with @marun 's `ClusterWorkspaceType.spec.additionalLabels`?

Correct. A namespace is only schedulable if its logical cluster is backed with a ClusterWorkspace labeled with `workloads.kcp.dev/schedulable: true`:

https://github.com/kcp-dev/kcp/blob/main/pkg/reconciler/workload/namespace/namespace_reconcile.go#L424

**Comment by pweil-** [comment]
excellent.  I'll move it back.  Thanks for keep an eye on me.

**Comment by marun** [comment]
Let's close it, the work is done.
