### ISSUE TITLE
Convert cmd/syncer/main.go to be a cobra.Command

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#553]

**Comment by pradeepnnv** [comment]
I would like to give this a try.

**Comment by ncdc** [comment]
Thanks! It's yours!

**Comment by ncdc** [comment]
Thanks @RAMESSESII2 for your interest! I see you submitted a PR for it. Just wondering - @pradeepnnv did you do any work on this?

**Comment by pradeepnnv** [comment]
Hi @ncdc . Sorry I did not get a chance to work on this. Please assign this to @RAMESSESII2 .
