### ISSUE TITLE
CI: don't run e2e & other tests for documentation-only PRs

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#573]
If a PR only touches documentation, we should skip running most of the CI jobs because the documentation changes do not affect e.g. e2e tests.

We can use https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths to accomplish this.

Possible ignore list:
- `docs/**`
- `*.md` (not sure if we want `**/*.md` for every md file, or only those in the repo root)
- `LICENSE`

I'm not sure if we currently have any jobs that we'd want to run for a docs-only change. WDYT?

**Comment by avinal** [comment]
Hello @ncdc, I would like to work on this issue.
