### ISSUE TITLE
unknown command `options` for `kcp`

### ISSUE THREAD

**Issue by avinal** [kcp-dev/kcp#602]
**Describe the bug**
`options` is not a subcommand for `kcp`. By looking at the code, it is a subcommand of `kcp start`. But if we see the help the last line suggests otherwise.

> Use "kcp options" for a list of all flags available.

Relevant lines of code:
https://github.com/kcp-dev/kcp/blob/main/cmd/kcp/kcp.go#L133-L134

![image](https://user-images.githubusercontent.com/74113200/156392653-2883a5d6-39a4-4cb1-87f8-138958d706a1.png)

**To Reproduce**
1. Compile `kcp` cli executable
2. Run `./kcp options`
3. See error
4. Now run `./kcp start options`

**Expected behavior**

`kcp options` should list all available options.

**Possible Solution**
- Fix the docs for `kcp` CLI.

**Comment by ncdc** [comment]
@UtkarshChaurasia assigned to you!

**Comment by UtkarshChaurasia** [comment]
`./kcp start options` shows all the flags. So there can be 2 ways to fix this:

1. Instead of using `options` as subcommand of `./kcp start` use it as subcommand of `./kcp options`
2. Create different `options` subcommands and seggregate flags for `./kcp start options` and `./kcp options`

So which way should I proceed?

**Comment by ncdc** [comment]
@sttts I'm not sure it makes sense to show `Most important flags` for `kcp --help`, since they only apply to `kcp start`. I feel like we should remove them and only show them in `kcp start --help`. WDYT?

**Comment by UtkarshChaurasia** [comment]
Hi @ncdc , Is there any update on how to proceed?

**Comment by ncdc** [comment]
@UtkarshChaurasia can you see about making it show `Most important flags` only shows up when you do `kcp start`?

**Comment by UtkarshChaurasia** [comment]
Do you mean `kcp option` right ? Because wouldn't it be apt to show `Most important flags` on doing `kcp options`

**Comment by ncdc** [comment]
@UtkarshChaurasia no, I mean `kcp start`. This is what we have now.

```
$ kcp start --help
Start the control plane process

The server process listens on port 6443 and will act like a Kubernetes API server. It will initialize any necessary data to the provided start location or as a '.kcp' directory in the current directory. An admin kubeconfig file will be generated at initialization time that may be used to access the control plane.


Usage:
  kcp start [flags]

Most important flags:

      --etcd-servers strings
                List of etcd servers to connect with (scheme://ip:port), comma separated. By default an embedded etcd server is started. (default [embedded])
      --run-controllers
                Run the controllers in-process (default true)
      --run-virtual-workspaces
                Run the virtual workspace apiservers in-process (default true)

Use "kcp start options" for a list of all flags available.
```

This is what we want. But you also see the `Most important flags` text when you just do `kcp --help`:

```
KCP is the easiest way to manage Kubernetes applications against one or more clusters, by giving you a personal control plane that schedules your workloads onto one or many clusters, and making it simple to pick up and move. Advanced use cases including spreading your apps across clusters for resiliency, scheduling batch workloads onto clusters with free capacity, and enabling collaboration for individual teams without having access to the underlying clusters.

To get started, launch a new cluster with 'kcp start', which will initialize your personal control plane and write an admin kubeconfig file to disk.


Usage:
  kcp [flags]

Most important flags:

      --etcd-servers strings
                List of etcd servers to connect with (scheme://ip:port), comma separated. By default an embedded etcd server is started. (default [embedded])
      --run-controllers
                Run the controllers in-process (default true)
      --run-virtual-workspaces
                Run the virtual workspace apiservers in-process (default true)

Use "kcp options" for a list of all flags available.
```

When you do `kcp start --help`, that should show you the most important options. If you want to see all options, you can do `kcp start options`.

**Comment by UtkarshChaurasia** [comment]
Got it. Thanks for clarifying. I will start the implementation.
