### ISSUE TITLE
Change issue template to newer issue forms

### ISSUE THREAD

**Issue by avinal** [kcp-dev/kcp#610]
**Is your feature request related to a problem? Please describe.**
This project uses old Issue templates and currently has no pull request templates.  

**Describe the solution you'd like**
- Upgrade issue template to newer issue forms: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

**Comment by chrisahl** [comment]
@avinal Looking for more info on this. Which issue template are you looking to update in https://github.com/kcp-dev/kcp/tree/main/.github/ISSUE_TEMPLATE?

 For pull request, have you seen https://github.com/kcp-dev/kcp/blob/main/.github/pull_request_template.md ?

**Comment by avinal** [comment]
Hello @chrisahl, I am aiming to upgrade all issue templates to use the newer YAML templates as mentioned in the description. The current pull request template is too minimal. We can add more fields. If we agree to what I have proposed above, I will open a PR :)

**Comment by chrisahl** [comment]
I was looking at issues to see what unassigned ones were out there, did not know you were working on this.  You should assign it to yourself.  

As far as the correct format for the templates, others will have to chime in as I am new to this repo/project and not sure.
