### ISSUE TITLE
Terminology inconsistency in doc on workspaces

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/kcp#623]
**Describe the bug**
https://github.com/kcp-dev/kcp/blob/main/docs/workspaces.md introduces "Enduser Workspace" but not "Cluster Workspace", but in later sections uses "Cluster Workspace" but not "Enduser Workspace".

**To Reproduce**
read the doc

**Expected behavior**
consistency

**Additional context**

**Comment by sttts** [comment]
@MikeSpreitzer can you open a PR? "Enduser" workspaces is not supposed to be a technical term. 

Cluster workspaces is the general term for workspaces accessible at `/clusters/...`, i.e. "end-user" and "cluster" workspaces are supposed to be different.

**Comment by MikeSpreitzer** [comment]
There are more problems with this page, which is now at https://github.com/kcp-dev/kcp/blob/main/docs/content/en/main/concepts/workspaces.md , and they are mixed up with the original problem here.
