### ISSUE TITLE
Need a way to consistently deploy a kcp server + kind clusters for develop/test/demo

### ISSUE THREAD

**Issue by marun** [kcp-dev/kcp#674]
Currently there is no standard way to bring up a kcp instance and workload clusters so that they could be used for development, testing, or demoing. 

Ideally we need a command that, given kind and kcp binaries in the path:

 - can deploy kcp and 0-n (number configurable) kind clusters locally
 - expose the configuration required to use what is deployed in a standard way
   - e.g. copy the kind server configurations to the .kcp/ path for ease of consumption 

It may also be useful to have a command that stops the kcp server and deletes the kind clusters to simplify cleanup.

Past discussion suggests that this functionality be implemented in golang (vs bash) to simplify maintenance and avoid the inevitable bash compatibility issues between darwin and linux.

**Comment by aojea** [comment]
This can be easily adapted as starting point (remove tmux ... )

https://gist.github.com/aojea/7eb651bf2172a1415cf6576d0baeb9f5

> Past discussion suggests that this functionality be implemented in golang (vs bash) to simplify maintenance and avoid the inevitable bash compatibility issues between darwin and linux.

Bash can be used only for setting up the environment, not for adding testing functionality not knobs ... If that is not the case, agree it should be moved to other thing

**Comment by marun** [comment]
I think the consensus was that bash starts simple but never stays that way. Given that being able to deploy consistently is likely to be something we need for the lifespan of the project, best to do the right thing now and switch to golang.

**Comment by marun** [comment]
Note that cluster registration and syncer deployment should be optional to enable arbitrary test configuration (including running the syncer in-process for testing).

**Comment by aojea** [comment]
> I think the consensus was that bash starts simple but never stays that way

I don't think anybody can argue against that XD

**Comment by stevekuznetsov** [comment]
The flow of "start kcp, do something that results in a kubeconfig, register using that as a workload cluster in kcp" seems to be covered in e2e - @marun do you think there's an opportunity for reuse there?

**Comment by marun** [comment]
@stevekuznetsov While there is some potential for reuse, the current e2e code manages kcp as a subprocess. For this issue, I'm hoping for a command that starts background processes and exits (kind of like `kind start cluster` but for kcp+kind).
