### ISSUE TITLE
Split apart our single kubeconfig into multiple

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#707]
We have a single kubeconfig that is shared by kcp in-process, humans (admin.kubeconfig), and potentially components of the architecture such as the virtual workspaces apiserver. We need to split these apart:

- [x] The loopback client must be for internal, in-process use only, by kcp & its built-in controllers. It must not take into account `--external-hostname`. It must not have any kubeconfig contexts.
- [ ] `admin.kubeconfig` is for human consumption. It must honor `--external-hostname`. We may need to add `--external-hostname-port`. This is the only kubeconfig in which we generate contexts.
- [ ] service.kubeconfig, for components such as the virtual-workspaces standalone apiserver

**Comment by kylape** [comment]
Can you explain why the loopback kubeconfig must not have any kubeconfig clients?

For the admin.kubeconfig, are we expecting it to be used in the shared service, or only in local development (or a different use case altogether)?  For our current shared service, I'm only really extracting the token out of it for my own use, and I intend to persist the token in a secret before too long.

>  service.kubeconfig, for components such as the virtual-workspaces standalone apiserver

For our shared service, the virtual workspace server is in the same pod as kcp.  Could it not use the loopback client?

**Comment by kylape** [comment]
As I've worked through trying to implement these changes, I've reduced the iplementation to only two kubeconfigs written to disk: `admin.kubeconfig` and `external.kubeconfig`. The loopback client has always been in-memory, so I see no need to start persisting this now.

I am trying to keep `admin.kubeconfig` similar to how it works now for backwards compatibility*. One change to `admin.kubeconfig`, though, is that it only uses the IP address that the kcp process is bound to as the hostname.  It also uses the port defined by `--secure-port`.

The virtual workspace server can now use `admin.kubeconfig` without modification. `admin.kubeconfig` should always work for local development as well.

`external.kubeconfig` will always honor `--external-hostname`, but it will default to the locally bound IP and port if `--external-hostname` is not set, which makes it idential to `admin.kubeconfig` in that case.

Note that `--external-hostname` accepts a port number in kube-apiserver, so I have tried to reflect that behavior in kcp.

So in summary:

* Loopback clients are never written to disk
* `admin.kubeconfig` is to be used by virtual workspace server and for local development
* `external.kubeconfig` will be used by service admins and for determining the server URL for most users.

\* I know backwards compatibility is not terribly important at this point, but I didn't see much downside to doing it.

### Alternatives

One possible alternative is to simply add another server to the `admin.kubeconfig` that uses `--external-hostname`, but then I suppose you'd need two contexts, right?

Another alternative is to only have `admin.kubeconfig`, but switch the hostname based on the value of `--external-hostname` (this means it would be configured exactly like `external.kubeconfig` above).  The main downside is that there is no kubeconfig available to connect to the local interface.  This would be helpful for the virtual workspace server, but it's likely not an issue for local development.

**Comment by sttts** [comment]
@kylape I think there is a misunderstanding about the core of this issue: all written kubeconfig should use `--external-hostname` and port. The loopback kubeconfig is leaking into the syncer today (at least there, maybe at other places). @jmprusi is fixing the syncer side in https://github.com/kcp-dev/kcp/pull/670.

The remaining tasks here:
1. either verify that `--external-hostname` is supposed to have optional ports or add another flag for that.
2. create a context-less `service.kubeconfig` that does not point to any logical cluster and does not add a wildcard, i.e. pure root path `/` URL.

**Comment by ncdc** [comment]
Clearing milestone to re-triage
