### ISSUE TITLE
Reconcilers: reuse roundtripper

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#714]
Follow-up of https://github.com/kcp-dev/kcp/pull/712:

We use independent (rest) clients for every controller. This means we don't multiplex over the same http2 connection.

Here is an example from @aojea:
```golang
	// share the transport between all clients
	httpClient, err := rest.HTTPClientFor(&configShallowCopy)
	if err != nil {
		return nil, err
	}
    	cs.admissionregistrationV1, err = admissionregistrationv1.NewForConfigAndClient(&configShallowCopy, httpClient)
	if err != nil {
		return nil, err
	}
	cs.admissionregistrationV1beta1, err = admissionregistrationv1beta1.NewForConfigAndClient(&configShallowCopy, httpClient)
	if err != nil {
		return nil, err
	}
	cs.internalV1alpha1, err = internalv1alpha1.NewForConfigAndClient(&configShallowCopy, httpClient)
	if err != nil {
		return nil, err
	}
```

Also k8s.io/controller-manager/pkg/clientbuilder/client_builder.go looks related.

**Comment by sttts** [comment]
Slack thread https://kubernetes.slack.com/archives/C021U8WSAFK/p1647337776878819?thread_ts=1647334252.697989&cid=C021U8WSAFK

**Comment by aojea** [comment]
... or pass the clientset directly to the controllers , but that means they all share the same config user-agent (I guess that can not be tuned per request)

**Comment by sttts** [comment]
user agent is a header and hence should be possible to set by request, in worst case in the roundtripper.

**Comment by sttts** [comment]
To be confirmed that we really have a problem here.

**Comment by aojea** [comment]
> To be confirmed that we really have a problem here.

The client-go caches the transport meanwhile there are no custom dialers or transport options, I think we are good

**Comment by ncdc** [comment]
Clearing milestone to re-triage
