### ISSUE TITLE
Community Meeting March 15, 2022

### ISSUE THREAD

**Issue by pweil-** [kcp-dev/kcp#719]
At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/ohf-kwvd-mrp
Or dial: ‪(US) +1 617-675-4444‬ PIN: ‪936 182 087 7398‬#
More phone numbers: https://tel.meet/ohf-kwvd-mrp?pin=9361820877398
Or join via SIP: sip:9361820877398@gmeet.redhat.com

Meeting recordings available on YouTube at https://www.youtube.com/channel/UCfP_yS5uYix0ppSbm2ltS5Q

This issue will collect prospective agenda topics. Add topics you'd like to discuss below!

**Comment by pweil-** [comment]
P4 scope discussion

**Comment by imjasonh** [comment]
- static deployment YAML for syncer installation (#418)
- determining which resources should be synced to clusters (P4)

**Comment by sttts** [comment]
- service accounts, creation & authentication merged 🎉
- sercice account syncing into workload clusters in the works (@jmprusi)

**Comment by stevekuznetsov** [comment]
[CRDB](https://github.com/kcp-dev/kcp/issues/591) investigation update.

**Comment by njhale** [comment]
KCP use case question.

**Comment by pweil-** [comment]
Prototypes as e2e

**Comment by imjasonh** [comment]
Next: https://github.com/kcp-dev/kcp/issues/751
Recording: https://youtu.be/6ricq5o_YqU
