### ISSUE TITLE
Add ability to configure kcp to prevent recreation of admin token after container restart

### ISSUE THREAD

**Issue by kylape** [kcp-dev/kcp#721]
**Is your feature request related to a problem? Please describe.**
Would like to manage the admin token outside of KCP.  Also need the admin token to persist between container restarts.

**Describe the solution you'd like**

An example flow:

* you start first time
* get an admin.kubeconfig
* secret is used to store token hash
* you delete the admin.kubeconfig after storing it in some safe location
* on restart no new admin.kubeconfig is created

Hash is written to `kube-system/admin-token-hash` secret in system workspace.

Flag to disable writing out token has and admin kubeconfig: `--authentication-admin-token=false`

**Additional context**
[Slack thread](https://kubernetes.slack.com/archives/C021U8WSAFK/p1647361807820709)

**Comment by kylape** [comment]
Note that `--admin-kubeconfig=""` can disable writing out the kubeconfig today.

**Comment by sttts** [comment]
+ client certs for a replacement of the admin token.

**Comment by ncdc** [comment]
Clearing milestone to re-triage

**Comment by ncdc** [comment]
@kylape please re-review to see if we can close this
