### ISSUE TITLE
API import does not work when adding the same cluster into multiple workspaces

### ISSUE THREAD

**Issue by astefanutti** [kcp-dev/kcp#730]
**Describe the bug**

Create a WorkloadCluster resource in a workspace. The API import works as expected.

Then create the same WorkloadCluster resource, in any other workspaces, the APIs are not imported from the cluster into these other workspaces.

**To Reproduce**

```sh
$ kubectl kcp workspace --token user-1-token create workspace1 --use
$ cat <<EOF | kubectl apply -f -
apiVersion: workload.kcp.dev/v1alpha1
kind: WorkloadCluster
metadata:
  name: kind-cluster
spec:
  kubeconfig: |
$(sed 's,^,    ,' cluster.kubeconfig)
EOF
workloadcluster.workload.kcp.dev/kind-cluster created
$ kubectl apply -f contrib/demo/prototype2-script/deployment-kuard.yaml
deployment.apps/deployment created

$ kubectl kcp workspace --token user-1-token create workspace2 --use
$ cat <<EOF | kubectl apply -f -
apiVersion: workload.kcp.dev/v1alpha1
kind: WorkloadCluster
metadata:
  name: kind-cluster
spec:
  kubeconfig: |
$(sed 's,^,    ,' cluster.kubeconfig)
EOF
workloadcluster.workload.kcp.dev/kind-cluster created
$ kubectl apply -f contrib/demo/prototype2-script/deployment-kuard.yaml
error: unable to recognize "contrib/demo/prototype2-script/deployment-kuard.yaml": no matches for kind "Deployment" in version "apps/v1"
```

**Expected behavior**

API import should work in the other workspaces.

**Additional context**

It is caused because the API importer are cached by cluster name key: https://github.com/kcp-dev/kcp/blob/62354fc9bf4f1e4d72f3a72d7f4613b182f0691c/pkg/reconciler/cluster/apiimporter/apiimporter_manager.go#L57

**Comment by ncdc** [comment]
@astefanutti I see you're running against older code (Cluster instead of WorkloadCluster, etc.). I don't expect we've necessarily fixed things, but could you please try with the latest from main, making sure to install the latest kubectl-kcp plugin too? (Also with main, you don't need `--workspace-directory-insecure-skip-tls-verify` any more).

**Comment by astefanutti** [comment]
@ncdc you're right, this is based on the stable `release-prototype-2` branch. However, I've checked in main and it seems the logic of keying API importers by cluster name is still there:

https://github.com/kcp-dev/kcp/blob/6d1c3f4a916ad6896be56ba7b8df30e9beedc66a/pkg/reconciler/cluster/apiimporter/apiimporter_manager.go#L57

That being said, I'm planning to rebase on P3 ASAP, so I'll test it and keep you posted.

**Comment by astefanutti** [comment]
@ncdc I confirm I've been able to reproduce on current `main` as well, and have updated the steps with the new commands accordingly.

**Comment by ncdc** [comment]
Getting rid of push mode will fix this. I believe #810 will close it. If you agree, @marun could you please add the `fixes` verbiage to 810 for this issue?

**Comment by fgiloux** [comment]
As discussed yesterday I am looking at implementing a workaround for this issue till the Location API and virtual workspaces are implemented

**Comment by marun** [comment]
@fgiloux Note that #810 is intended to fix this issue in advance of location api or virtual workspace.

**Comment by fgiloux** [comment]
@marun I have been through PR #810 there is a lot there. I am surely missing something but I did not grok how it allows to match a WorkloadCluster to multiple workspaces, apart from creating an additional syncer for each workspace.
It seems [here](https://github.com/kcp-dev/kcp/pull/810/files#diff-0705d04ebc88b239145fe94b232d72bae8460b6cda37c12cd437ef611107be5cL108-L109) that there is a 1-1 match at the syncer level between a WorkloadCluster and a logical cluster. This is all good when the logical cluster is a virtual workspace but my understanding is that this will come later and that it points to a personal workspace in the meantime. What am I missing?

**Comment by ncdc** [comment]
@fgiloux I'm guessing that's probably a question for #810 itself - do you want to copy your comment over there? 😄

**Comment by fgiloux** [comment]
@ncdc yes you are right. Sorry for the mess.

**Comment by ncdc** [comment]
No worries, not a mess! Just wanted to make sure we have it captured over there, if it means we need to do more work before merging.
