### ISSUE TITLE
Make CRDs and APIBindings conflict on each other for overlapping GVRs

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#748]
Follow-up #702:

CRDs and APIBindings should not have overlapping GVRs, both because only one can be served obviously, but also because both share the same etcd key space and hence there is some risk (💣) that one steals data of the other.

The idea here is to create an admission plugin on both resources that forbids one or the other when GVRs overlap. This also means that that admission plugin might stop binding of the APIBinding to a new export revision that got new GVRs.

Related to #417

**Comment by ncdc** [comment]
> because both share the same etcd key space and hence there is some risk (💣) that one steals data of the other

Note, with #877 now merged, CRs from APIBindings and CRs from normal CRDs are stored distinctly in etcd. So this concern is no longer an issue.

**Comment by sttts** [comment]
Disagree that is no issue anymore. It is less security-critical, but the user-experience is still broken.

**Comment by ncdc** [comment]
Yes, you're right
