### ISSUE TITLE
Get rid of "X-Kubernetes-Cluster" header and use /clusters/<lcluster>

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#750]
The EnabledMultiCluster function uses some custom roundtripper to intercept multi-cluster requests. We can probably just change the request URI instead of injecting a special header. This will simplify the server handler code.

**Comment by rgolangh** [comment]
Can you please assign this to me?

**Comment by ncdc** [comment]
This functionality was removed in https://github.com/kcp-dev/kubernetes/pull/117/files
