### ISSUE TITLE
Support scheduling workloads to multiple clusters 

### ISSUE THREAD

**Issue by maleck13** [kcp-dev/kcp#752]
**Is your feature request related to a problem? Please describe.**

I have attempted to capture a set of use cases below to illustrate the kind of behaviour I think would be useful in a multi cluster scenario. Let me know if we need different issues for these.
These use cases are also captured under the TMC use cases (2.1 and 2.2) https://docs.google.com/document/d/1LeYMt4I1No1W-tj6LCPuXE7kTSD-uggC8IRI6DVpHOM/edit#

Use case: I have a stateless application that can be deployed across multiple clusters. I would like to be able to have this application deployed across a set of clusters without me needing to manually duplicate resources and label them for a particular cluster. I would like to be able to apply my application resources once with a set of "location" requirements (perhaps labels) such as cloud provider or security level and have KCP handle the complexities of syncing my resources into the different clusters based on the capabilities of the locations I have setup.

Use case : I am moving my application to a different cloud provider. I would like to be able to have this workload scheduled to a new cluster without disrupting my service. This means my application would (for a period of time until the new deployment is ready) be deployed to at least two clusters. I would like this to work in a similar way to a rolling deployment. IE the old workload remains in place until the new one is ready where ready is a combination of requirements IE the workload is up and running and traffic for my workload has also been moved to the new workload.

**Describe the solution you'd like**
see above

**Describe alternatives you've considered**
In our controller, to explore these concepts we have a very simple and crude method of achieving these multi cluster use cases. To express which location to use we used a new annotation on the service resource (conceptually similar to the cluster label but can take multiple values). We then find all the objects tied to that service object (Ingress and deployments). We then create "leaf" objects (one for each target cluster) for these discovered resources and add the correct cluster label to trigger the sync.  The key thing was separating the location I want to deploy to from the cluster label itself. 

**Additional context**
The use case around moving existing workloads likely ties into https://github.com/kcp-dev/kcp/issues/504  (being able to schedule the removal of workloads once the requirement for removal have been met)

**Comment by ncdc** [comment]
Related to some of the location & placement work. Folks working on those APIs - please review the use cases here and see if they align w/those APIs, or if not, please discuss the gaps/differences and if there are any additional changes needed in kcp.

@sttts @davidfestal @jmprusi

**Comment by davidfestal** [comment]
You're mainly covering the whole TMC story here :-)

The first use-case (stateless application deployed across multiple clusters) is something which is already available through `Location`s and `Placement`s and the scheduling logic.

The second use-case is something related to coordination controller, and an ongoing work, whose basis is contained in EPIC https://github.com/kcp-dev/kcp/issues/1898. However the complete story for use-case 2, with real transparent move brings us later in time, when Network Homogeneity inside location would be implemented (no EPIC exists for now for it, but it will come)

**Comment by davidfestal** [comment]
@maleck13 is this issue still relevant ?

**Comment by maleck13** [comment]
I think they are covered by the coordination controller and general placement
