### ISSUE TITLE
Write missing e2e tests for the transparent SA rewrite in downstream deployments functionality.

### ISSUE THREAD

**Issue by jmprusi** [kcp-dev/kcp#758]
The functionality added on https://github.com/kcp-dev/kcp/pull/670 is missing e2e tests.

**Comment by geoberle** [comment]
@ncdc i will take this one as mentioned in the community meeting

**Comment by stevekuznetsov** [comment]
Of note: https://github.com/kcp-dev/kcp/issues/917#issuecomment-1102863258

No multi-arch manifest for `kubectl` exists, and in general it might be nice to verify explicitly that in-cluster configuration is what is functional, which would be best done with a Go program doing so. That would mean that we need an image build to get that running in the `kind` cluster.

**Comment by geoberle** [comment]
wdyt about https://hub.docker.com/r/rancher/kubectl/tags? this one is available for multiple archs, including arm64
