### ISSUE TITLE
Code-generate scoping wrappers for arbitrary k8s.io/code-generator generated clients and informers

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#759]
This epic is about generating wrappers for client-gen generated clients and informer-gen generated informers (i.e. those e.g. in k8s.io/client-go) which support scoping to a logical cluster, but **do not require changes to the clients and informers (or their generators) themselves**.

1. For clients this means that we want an interface generated like
```golang
package clusterclientset

import clientset "k8s.io/client-go/kubernetes"

type Interface interface {
    Cluster(lcluster) clientset.Interface
}
```
automatically generated which support to scope the given client down on-demand, the resulting client should talk to `/clusters/<lcluster>` instead of  ´/`.

There is a sketch at https://github.com/ncdc/kcp-client-wrappers/blob/main/kubernetes/cluster_client.go for a (manually created; we want it code generated) wrapper. Moreover, in https://github.com/kcp-dev/kubernetes/blob/feature-logical-clusters-1.23/staging/src/k8s.io/client-go/kubernetes/clientset.go#L79 we have modified upstream clientsets, but this approach is not viable as we have to fork k8s.io/code-generator and every client repo like client-go for that.

2. For informers we want cross-workspace-capable informer factories and informer types that can be scoped down (via some index to be performant) to an lcluster. The scoped down informer/list should only return objects for that lcluster, and behave like a normal non-kcp-aware informer/lister. See https://github.com/kcp-dev/kcp/blob/main/pkg/virtual/framework/wrappers/rbac/cluster_filtering.go for an example of a manually created wrapper. We need this code-generated.

3. We'll also need a ClusterDiscoveryClient that looks like this:

```go
type ClusterDiscoveryClient struct {
// ...
}

func (c *ClusterDiscoveryClient) Cluster(clusterName logicalcluster.LogicalCluster) discovery.DiscoveryInterface {
}
```

**Comment by ncdc** [comment]
@varshaprasad96 @fabianvf @njhale I updated the description to include the need for a ClusterDiscoveryClient

**Comment by fabianvf** [comment]
Sounds good, I'll take a look a that tomorrow. Presumably that client would live in the same place that https://github.com/kcp-dev/apimachinery/pull/21 ends up?

**Comment by fabianvf** [comment]
also linking https://github.com/kcp-dev/code-generator/pull/1 (clientset generator) and https://github.com/kcp-dev/code-generator/pull/2 (listers/informer example)
