### ISSUE TITLE
Forbid CRD creation of kcp.dev groups outside of system:system-crds 

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#772]
*.kcp.dev CRDs should be reserved for the system, i.e. a user should not be able to install these outside of the shadow workspace `system:system-crds` (compare #755 where it was introduced to host the kcp CRDs). This issue is about adding an admission plugin to stop `*.kcp.dev` CRD creation in any other workspace.

**Comment by sttts** [comment]
Note: without this, it's easy to brick kcp by creating a kcp.dev CRD of different schema.

**Comment by pradeepnnv** [comment]
I would like to try this.

**Comment by sttts** [comment]
@pradeepnnv are you still interested? Do you need some pointers? Feel free to start a thread in Slack. We can talk.

**Comment by ncdc** [comment]
@robinbobbitt thanks, please proceed. Hopefully we can find other issues for @pradeepnnv if still interested.
