### ISSUE TITLE
Community Meeting March 29, 2022

### ISSUE THREAD

**Issue by imjasonh** [kcp-dev/kcp#786]
At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/ohf-kwvd-mrp
Or dial: ‪(US) +1 617-675-4444‬ PIN: ‪936 182 087 7398‬#
More phone numbers: https://tel.meet/ohf-kwvd-mrp?pin=9361820877398
Or join via SIP: sip:9361820877398@gmeet.redhat.com

Meeting recordings available on YouTube at https://www.youtube.com/channel/UCfP_yS5uYix0ppSbm2ltS5Q

This issue will collect prospective agenda topics. Add topics you'd like to discuss below!

**Comment by imjasonh** [comment]
https://github.com/kcp-dev/kcp/pull/774#issuecomment-1080377580

---

> > @marun: This would appear to be duplicating the exercise of functionality we're already validating in unit and e2e tests. If we're past the prototype phase and want to best spend our effort, maybe demoing effort is better spent writing documentation for features we implement?
> 
> @pweil-: I think we should discuss if we've passed the prototype phase with P3 in a community call and what that would even mean. I support the idea that we should focus on documentation vs codified demos if the goal of the effort is changing (regular, community call demos still encouraged). I don't think it has, though. Worth discussing.

**Comment by ncdc** [comment]
- Prototype X vs. semver

**Comment by imjasonh** [comment]
[**KubeCon NA CFP is open!**](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/program/cfp/)

- October 24-28 in Detroit
- CFP closes Friday, May 27

Possible topics:
- Steve's CRDB work
- Logical clusters, API multitenancy, API evolution, multi-logical-cluster clients, etc.
- Transparent Multicluster, scheduling, syncing, registration, etc.

**Comment by davidfestal** [comment]
Demo of **adding syncing strategies** in the syncer virtual workspace, **applied to the deployment splitting** use-case, **without** the deployment splitter.

Questions raised:
- `workloads.kcp.dev/cluster` label oriented to 1:1 syncing and not spreading use-case:
  - changed for `workloads.kcp.dev/cluster.<locationName>`, so that we can have several.
- Using "internal" annotations :
  - required allowing the update of internal annotations along with status.
  
A proposal doc related to this demo will come later.

**Comment by sttts** [comment]
Epics for prototype 4 aka v0.4.0 sprint: https://docs.google.com/document/d/1jN6BdhUUIESeHw3_f6HwsNwVM2Ytabr6usUQhYMcNd8/edit#heading=h.v0ybspmfdqn3

**Comment by imjasonh** [comment]
Recording: https://youtu.be/rO-4fwHk7dM

**Comment by imjasonh** [comment]
Next: https://github.com/kcp-dev/kcp/issues/835
