### ISSUE TITLE
Change base image to e.g. distroless

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#798]
I'm not sure if things have changed recently, but at least in the past, alpine builds were not consistently reproducible. Additionally, we should keep our attack surface to a minimum by using a base image with the least amount of extra stuff in it, so something like distroless is a better choice (and consistent with Kubernetes).

**Comment by csams** [comment]
Sounds good. We chose alpine when getting starting so we could shell into the container and poke around to troubleshoot.

**Comment by kylape** [comment]
We should probably just use https://github.com/google/ko.  It used the distroless base image by default.

**Comment by kylape** [comment]
I played with `ko` a little bit, and there are a couple of issues:

1. `ko` only builds one binary per image.  We can accommodate this, but it will require some changes to our deployment manifest and build pipelines.
2. It wasn't obvious to me how to add the build options to get the version info baked into `ko`.  It very well may be possible, but I'll have to spend some more time tinkering with the options to get it working.  This also implies that we can't use the makefile, which means a bit of duplication in terms of build config.

I also ran into a couple of issues with the shared service that we'll have to resolve before we can switch to distroless:

1. We currently use `cat` to extract the `admin.kubeconfig` from the kcp container.  The proposed fix is to externally manage the admin token and configure kcp to use the provided admin token.
2. We currently use `sh` and `sed` to transform the `admin.kubeconfig` into a version usable by the virtual workspaces server.  There are a few ways we could work around this, but I'm not sure which way is best.

**Comment by imjasonh** [comment]
> I played with `ko` a little bit, and there are a couple of issues:
> 
> 1. `ko` only builds one binary per image.  We can accommodate this, but it will require some changes to our deployment manifest and build pipelines.

This is arguably a best practice anyway, over putting a bunch of executables in the same image, but I understand if it works now and isn't worth switching just for that.

> 2. It wasn't obvious to me how to add the build options to get the version info baked into `ko`.  It very well may be possible, but I'll have to spend some more time tinkering with the options to get it working.  This also implies that we can't use the makefile, which means a bit of duplication in terms of build config.

There's a couple ways, you can either [set them in the `.ko.yaml` file](https://github.com/google/ko#overriding-go-build-settings) or [use the GOFLAGS env var when building](https://github.com/google/ko#how-can-i-set-ldflags)

If you're just setting commit SHA, tag, etc., after 1.18 this info will automatically be embedded in the binary if `git` is available when you build (disable with `-buildvcs=false`), and available in [`debug.ReadBuildInfo`](https://pkg.go.dev/runtime/debug#ReadBuildInfo), in `.Settings`, with the keys `vcs.revision`, `vcs.modified`, etc. -- you can see everything that's embedded with `go version -m bin/kcp`.
