### ISSUE TITLE
kube-root-ca.crt was not deleted under syncer-system after cluster was deleted

### ISSUE THREAD

**Issue by gyliu513** [kcp-dev/kcp#80]
After the cluster was deleted, check `cm` under `syncer-system`, found `kube-root-ca.crt` was not deleted.

```console
$ kubectl get cm -n syncer-system
NAME               DATA   AGE
kube-root-ca.crt   1      14m
```

But if we can delete the ns `syncer-system`, then all resources under this ns will be deleted.

**Comment by imjasonh** [comment]
Yeah, let's just delete all of `syncer-system` when uninstalling the in-cluster syncer. A good e2e test scenario would be exercising install/uninstall/reinstall scenarios to make sure we don't leave anything behind. 👍
