### ISSUE TITLE
kubectl plugin should return friendly errors when trying to run create/list/etc in a workspace that doesn't support nested workspaces

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#831]
**Is your feature request related to a problem? Please describe.**
We support a hierarchy of workspaces - root -> org1 -> workspaceA, and sometimes users might feel like they can create an arbitrarily deep nesting of workspaces, e.g. under workspaceA -> foo -> bar -> baz. This is not possible by default unless you create the right type of workspace at each level (e.g. Organization instead of Universal). It can be confusing when you try to create a nested workspace or get a list of workspaces from a workspace that doesn't support nesting - you get errors such as

```
# try to list workspaces from a Universal workspace
kubectl kcp ws list
error: workspaces.tenancy.kcp.dev "test" is forbidden: "root:some-org" workspace access not permitted

# try to create a nested workspace inside a Universal workspace
k kcp ws create inner1
error: the server could not find the requested resource (post clusterworkspaces.tenancy.kcp.dev)
```

**Describe the solution you'd like**
The kubectl plugin code should return errors that are more user-friendly. For example, if you try to list workspaces from a workspace that doesn't support nesting, the plugin could tell that to the user - `workspace "foo" does not support nested workspaces` or something to that effect.

This could be achieved by checking discovery as one possible solution.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by chrisahl** [comment]
Similar slack conversation, https://coreos.slack.com/archives/C020QAF9D46/p1651497368435569.  Would like it to be a little more user friendly.  So I vote for this enhancement

**Comment by rgolangh** [comment]
hi, can one of the maintainers assign this to me please?
