### ISSUE TITLE
Community Meeting April 5, 2022

### ISSUE THREAD

**Issue by imjasonh** [kcp-dev/kcp#835]
At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/ohf-kwvd-mrp
Or dial: ‪(US) +1 617-675-4444‬ PIN: ‪936 182 087 7398‬#
More phone numbers: https://tel.meet/ohf-kwvd-mrp?pin=9361820877398
Or join via SIP: sip:9361820877398@gmeet.redhat.com

Meeting recordings available on YouTube at https://www.youtube.com/channel/UCfP_yS5uYix0ppSbm2ltS5Q

This issue will collect prospective agenda topics. Add topics you'd like to discuss below!

**Comment by imjasonh** [comment]
[0.4 Milestone](https://github.com/kcp-dev/kcp/milestone/5) topics

**Comment by ncdc** [comment]
Syncer evolution

**Comment by imjasonh** [comment]
Recording: https://youtu.be/n_wMyafzu-4

**Comment by imjasonh** [comment]
Next: https://github.com/kcp-dev/kcp/issues/837
