### ISSUE TITLE
Add logical cluster annotation to audit events

### ISSUE THREAD

**Issue by kylape** [kcp-dev/kcp#862]
**Is your feature request related to a problem? Please describe.**
Currently audit events don't have any context regarding logic cluster.  This should be added to help audit events be more useful.

**Describe the solution you'd like**
[Add an annotation to audit events that includes the logical cluster](https://kubernetes.slack.com/archives/C021U8WSAFK/p1649358931928699?thread_ts=1649358177.770489&cid=C021U8WSAFK).

> we have `func AddAuditAnnotation(ctx context.Context, key, value string)`, so we can add an annotation via `pkg/server/handler.go` in kcp

**Comment by geoberle** [comment]
i would like to grab this one

**Comment by ibihim** [comment]
Sorry, I reacted in the slack chat and forgot to mention that I am working on it too.

**Comment by geoberle** [comment]
@ibihim no problem. go for it

**Comment by ibihim** [comment]
thank you :pray:

**Comment by sttts** [comment]
Merged
