### ISSUE TITLE
1.0 blocker: enable APIBinding CR deletion, namespace deletion, GC, workspace deletion

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#875]
All the mentioned deletion mechanisms are necessary for a serious deployment:

1. [x] APIBinding CR deletion https://github.com/kcp-dev/kcp/issues/846
2. [x] namespace deletion
3. [ ] garbage collection
4. [x] workspace deletion

**Comment by ncdc** [comment]
Replacing with individual issues
