### ISSUE TITLE
Syncer: issues with how/where --resources-to-sync is used between APIImporter and spec/status syncers

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#889]
(caveat: I _think_ I'm interpreting this all correctly, but it's a bit confusing, so please correct me if anything is wrong below)

When a syncer starts up and it starts an APIImporter, it's currently telling the APIImporter to import:

1. GroupResources matching [all the compatible+available `APIResourceImports` in the workspace](https://github.com/kcp-dev/kcp/blob/e49b80782b592ffb187e0aed6be70e5f8645d356/pkg/reconciler/workload/syncer/syncer_manager.go#L64-L81)
1. `configmaps`, `secrets`, `serviceaccounts` [if and only if those were specified in `--resources-to-sync`](https://github.com/kcp-dev/kcp/blob/e49b80782b592ffb187e0aed6be70e5f8645d356/pkg/reconciler/workload/syncer/syncer_manager.go#L83-L102)

(oddly, this seems to ignore any direct use of `--resources-to-sync`, instead waiting for them to come in as `APIResourceImports`)

This all goes into `groupResources`, which then flows

1. [To the syncerManagerImpl](https://github.com/kcp-dev/kcp/blob/e49b80782b592ffb187e0aed6be70e5f8645d356/pkg/reconciler/workload/syncer/syncer_manager.go#L134)
2. Which [calls `syncer.StartSyncer`](https://github.com/kcp-dev/kcp/blob/e49b80782b592ffb187e0aed6be70e5f8645d356/pkg/reconciler/workload/syncer/pushmanager.go#L78)
3. Which [starts the APIImporter with the values from `groupResources`](https://github.com/kcp-dev/kcp/blob/e49b80782b592ffb187e0aed6be70e5f8645d356/pkg/syncer/syncer.go#L85) above

That's for the APIImporter. This then goes on to determine [which GVRs the spec and status syncers should be syncing](https://github.com/kcp-dev/kcp/blob/e49b80782b592ffb187e0aed6be70e5f8645d356/pkg/syncer/syncer.go#L107), which [hard-codes syncing namespaces, serviceaccounts, configmaps, and secrets](https://github.com/kcp-dev/kcp/blob/e49b80782b592ffb187e0aed6be70e5f8645d356/pkg/syncer/syncer.go#L274), in addition to `groupResources`.

I had a conversation with @davidfestal and we discussed:

1. `--resources-to-sync` is supposed to control which APIs to import from workload clusters as CRDs
2. The spec/status syncers should sync everything that shows up as a compatible+available APIResourceImport, which could include more than what's in `--resources-to-sync` if someone manually creates additional APIResourceImports
3. Longer-term, we may want to consider removing `--resources-to-sync` and making that a spec field on WorkloadCluster (or some other CR)

**Comment by ncdc** [comment]
> The spec/status syncers should sync everything that shows up as a compatible+available APIResourceImport, which could include more than what's in --resources-to-sync if someone manually creates additional APIResourceImports

I'm not sure if this is right, or if it should just match syncing what's in `--resources-to-sync` (or be a more constrained subset, if the negotiated APIs are fewer)

**Comment by marun** [comment]
#810 ensures that only the specified resources are imported and synced for deployed (not managed) syncers. As per a conversation with @davidfestal, this is a change from the managed syncer which determines the resources from the set of APIResourceImports in the workspace as you're describing here. It probably makes sense to clarify what behavior is desired of deployed syncers before managed syncers go away in #881.

**Comment by ncdc** [comment]
Ok, so I guess this is limited to only being an issue for push managed syncers?

**Comment by davidfestal** [comment]
> Ok, so I guess this is limited to only being an issue for push managed syncers?

That's also my guess

**Comment by ncdc** [comment]
Closing, as we no longer have push managed syncers 😄
