### ISSUE TITLE
Remove syncer management from control plane & switch to external syncers

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#890]
- [x] Move syncer manager + all related code
- [x] Implement kubectl plugin code to make it easy to deploy a syncer to a workload cluster

**Comment by ncdc** [comment]
@marun @jmprusi I filed this to keep track of things. Please feel free to adjust the task list as you see fit. Thanks!

**Comment by marun** [comment]
We already have a task list in #881?

**Comment by ncdc** [comment]
I at least wanted an issue filed for this - I didn't see one.

**Comment by marun** [comment]
* [ ]  Move syncer manager + all related code  - #911
* [ ]  Implement kubectl plugin code to make it easy to deploy a syncer to a workload cluster - #881

**Comment by marun** [comment]
I think this is safe to close now that #881, #909 and #911 have all merged.
