### ISSUE TITLE
Ingress is not synced by the namespace syncer

### ISSUE THREAD

**Issue by maleck13** [kcp-dev/kcp#896]
**Describe the bug**
Ingress objects are not scheduled to a cluster when in synced resources

**To Reproduce**
start kcp with resources to sync (service, deployment, ingress)
create a workspace
create a namespace
create deployment, service and ingress
note service and deployment are synced
Ingress is not synced

**Expected behavior**
Ingress should be synced based on the namespace scheduler label

**Additional context**
The issue here is https://github.com/kcp-dev/kcp/blame/main/pkg/reconciler/workload/namespace/namespace_reconcile.go#L95

Is this line still needed?

**Comment by ncdc** [comment]
@jmprusi

**Comment by ncdc** [comment]
@maleck13 this line exists because for the time being, the namespace reconciler and the ingress splitter conflict with each other (tracking long-term goals in #557). So IIRC you have to manually assign each root ingress to a cluster for the time being (@jmprusi can confirm).

**Comment by jmprusi** [comment]
Yes @ncdc, that was the main reason for that line. For the next release, 0.4, that line will be going away.
