### ISSUE TITLE
Community Meeting April 19, 2022

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#915]
At 11am Eastern, 8am Pacific, 3pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T150000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: https://meet.google.com/ohf-kwvd-mrp
Or dial: ‪(US) +1 617-675-4444‬ PIN: ‪936 182 087 7398‬#
More phone numbers: https://tel.meet/ohf-kwvd-mrp?pin=9361820877398
Or join via SIP: sip:9361820877398@gmeet.redhat.com

Meeting recordings available on YouTube at https://www.youtube.com/channel/UCfP_yS5uYix0ppSbm2ltS5Q

This issue will collect prospective agenda topics. Add topics you'd like to discuss below!

**Comment by sttts** [comment]
- [0.4 Milestone](https://github.com/kcp-dev/kcp/milestone/5) topics
- Incoming issues: https://github.com/kcp-dev/kcp/issues?q=is%3Aissue+is%3Aopen+created%3A2022-03-08..*+no%3Amilestone+

**Comment by stevekuznetsov** [comment]
CRDB benchmarking updates:

- see [the repo](https://github.com/stevekuznetsov/apiserver-benchmarking) for setup
- see [my branch](https://github.com/stevekuznetsov/apiserver-benchmarking) for the k8s code
- preliminary results for client throughput & latency (and server performance)
- preliminary results for high-selectivity queries and indices

**Comment by ncdc** [comment]
* APIExport virtual workspace demo

**Comment by ncdc** [comment]
Recording: https://www.youtube.com/watch?v=Ca3vh3lS6YI
