### ISSUE TITLE
Revert cluster-admin permissions for syncer in negotiation workspace

### ISSUE THREAD

**Issue by sttts** [kcp-dev/kcp#916]
**Describe the bug**

https://github.com/kcp-dev/kcp/pull/881 adds cluster-admin right for the syncer in the negotiation workspace:

```
// Grant the service account cluster-admin on the workspace
```

With the virtual workspace work landing https://github.com/kcp-dev/kcp/pull/754, this will not be needed anymore. Hence, we should (must) revert this as it is a major security blocker.

**Comment by sttts** [comment]
This is crucial for the security story. But in v0.5 nobody will work on it. So moving to v0.6.

**Comment by davidfestal** [comment]
Seems to me it has been done in the following [commit of PR 1176](https://github.com/kcp-dev/kcp/pull/1176/commits/287c0346292ec62b4302f47b1cfd5e363e9ab05b)

@sttts Do you see anything left to be done to close this issue ?

**Comment by ncdc** [comment]
This is done
