### ISSUE TITLE
e2e: Ensure that a synced deployment can contact kcp

### ISSUE THREAD

**Issue by marun** [kcp-dev/kcp#917]
#909 enables kind testing in e2e jobs, and the primary syncer e2e (`test/e2e/syncer/syncer_test.go`) needs to be updated to validate that a synced deployment is configured correctly to contact the kcp api via the 'incluster' configuration path. 

cc: @sttts @jmprusi @ncdc

**Comment by marun** [comment]
Of note is that image that is used for the syncer test is currently `bitnami/kubectl`, which is `amd64` only.  This is fine for CI but the test will fail on apple silicon due to the test checking for available pods and the pod crashlooping due to using an image with the wrong arch. Ideally the test would be using an image that was supported on `arm64` and `amd64`.

**Comment by sttts** [comment]
This is important and kind of urgent, but doesn't block v0.4.

**Comment by stevekuznetsov** [comment]
This is a dupe of the older #758 
/close

**Comment by jmprusi** [comment]
Closing this one in favor of https://github.com/kcp-dev/kcp/issues/758
