### ISSUE TITLE
Clean up contrib/kcp.code-workspace

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#919]
There are a lot of launch configurations that are no longer relevant and should be removed:

- [ ] `Launch all-in-one kcp in push mode` (push mode is almost removed from the codebase)
- [ ] `Launch crd-puller on default cluster` (crd-puller may go away as a standalone tool)
- [ ] `Launch cluster controller - push mode`
- [ ] `Launch cluster controller`

This last one is probably out of date and may need updating:

- [ ] `Launch syncer`

**Comment by hardys** [comment]
Looks like this was resolved via https://github.com/kcp-dev/kcp/pull/1390 ?

**Comment by ncdc** [comment]
👍 
/close
