### ISSUE TITLE
Implement basic import of the `admin` logical cluster CRDs to all other logical clusters. 

### ISSUE THREAD

**Issue by davidfestal** [kcp-dev/kcp#94]
The [CRD virtualization, inheritance, and normalization](https://github.com/kcp-dev/kcp/blob/main/docs/investigations/logical-clusters.md#crd-virtualization-inheritance-and-normalization) part of the *logicial clusters* investigation doc contains the following statement:

> Inheritance allows an admin to control which resources a client might use - this would be particularly useful in more opinionated platform flows for organizations that wish to offer only a subset of APIs. **The simplest approach here is that all logical clusters inherit the admin virtual cluster (the default)**

This is currently not implemented.
Maybe this should already be done even more generically, by using the [`parents`](https://github.com/kcp-dev/kubernetes/blob/658502fe389c76e3b988ab6b8ef7a9034071fa98/staging/src/k8s.io/apiserver/pkg/endpoints/request/context_cluster.go#L34) of the given cluster. Of course this would require defining more precisely how and when the `parents` would be set.

**Comment by ncdc** [comment]
Given that Workspace API inheritance has been implemented, and we are further refining API availability with imports & exports, should we close this? @davidfestal @sttts

**Comment by davidfestal** [comment]
I assume we can close this, but maybe @sttts has a different opinion.

**Comment by ncdc** [comment]
This will be replaced by APIImport/Export work and other things.
