### ISSUE TITLE
logicalcluster machinery refactoring

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#940]
- [x] Create a new repo, github.com/kcp-dev/logicalcluster
    - [x] Move github.com/kcp-dev/apimachinery/pkg/logicalcluster into the root of the above repo, rename `LogicalCluster` to `Name` (put in `name.go`) https://github.com/kcp-dev/logicalcluster/pull/1
    - [x] Add script to verify there are no k8s.io/* imports https://github.com/kcp-dev/logicalcluster/pull/1
    - [x] Enable said script in CI https://github.com/kcp-dev/logicalcluster/pull/1
    - [x] Tag logicalcluster repo v1.0.0 https://github.com/kcp-dev/logicalcluster/releases/tag/v1.0.0
- [x] Remove logicalcluster from kcp-dev/apimachinery https://github.com/kcp-dev/apimachinery/pull/26
- [x] Update kcp-dev/kubernetes to use new repo/package
- [ ] ~Remove the Cluster struct from https://github.com/kcp-dev/kubernetes/blob/feature-logical-clusters-1.23/staging/src/k8s.io/apiserver/pkg/endpoints/request/context_cluster.go#L34-L41 - we only need `logicalcluster.Name` from above~ edit: I'm actually adding something to this struct, so let's keep it for now.

**Comment by fabianvf** [comment]
should we also add an item here to remove logicalcluster from github.com/kcp-dev/apimachinery?

**Comment by fabianvf** [comment]
I've got branch with the cluster struct removed but don't think I got all the references to it cleaned up properly

**Comment by ncdc** [comment]
I actually need it for #1072 - just realized that today. I updated the description to strike through that line.
