### ISSUE TITLE
Fix syncer image name

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#941]
For some reason, the syncer image name we're building via GitHub Actions is `syncer-c2e3073d5026a8f7f2c47a50c16bdbec` followed by a tag - e.g. `ghcr.io/kcp-dev/kcp/syncer-c2e3073d5026a8f7f2c47a50c16bdbec:main`.

The name of the image should be `ghcr.io/kcp-dev/kcp/syncer:TAG` i.e. without `-c2e3073d5026a8f7f2c47a50c16bdbec`.

I'm guessing we need to adjust something in `.github/workflows/syncer-image.yaml`.

Also since we'll be making a change here, we might want to fix #902 while we're at it.

**Comment by geoberle** [comment]
hi @ncdc. i would love to work on this.

**Comment by ncdc** [comment]
@geoberle great, thanks, we'd love the help!
