### ISSUE TITLE
Race condition in syncer: namespace vs. resource event ordering & cache freshness

### ISSUE THREAD

**Issue by qiujian16** [kcp-dev/kcp#947]
**Describe the bug**
see TestSyncerLifecycle fails sometimes in  e2e-test-sharedserver.

log as below

```
fixture.go:458: Waiting for cluster "pcluster-01" condition "Ready" to have reason ""
    fixture.go:480: Cluster "pcluster-01" is Ready
    syncer_test.go:71: Creating upstream namespace...
    syncer_test.go:92: Waiting for downstream service account kcp015dc2d48934724ea9e4592e34ab9b641cd5960514c116524629471b/kcp-default to be created...
    syncer_test.go:106: Waiting for downstream service account secret kcp015dc2d48934724ea9e4592e34ab9b641cd5960514c116524629471b/kcp-default-token to be created...
    syncer_test.go:119: Waiting for downstream configmap kcp015dc2d48934724ea9e4592e34ab9b641cd5960514c116524629471b/kcp-root-ca.crt to be created...
    syncer_test.go:132: Creating upstream deployment...
    syncer_test.go:148: Waiting for downstream deployment kcp015dc2d48934724ea9e4592e34ab9b641cd5960514c116524629471b/syncer-test to be created...
    syncer_test.go:149: 
        	Error Trace:	syncer_test.go:149
        	Error:      	Condition never satisfied
        	Test:       	TestSyncerLifecycle
        	Messages:   	downstream deployment kcp015dc2d48934724ea9e4592e34ab9b641cd5960514c116524629471b/syncer-test was not synced
    syncer_test.go:155: saw an error waiting for downstream deployment kcp015dc2d48934724ea9e4592e34ab9b641cd5960514c116524629471b/syncer-test to be created: context canceled
FAIL
FAIL	github.com/kcp-dev/kcp/test/e2e/syncer	49.501s
?   	github.com/kcp-dev/kcp/test/e2e/virtual/framework/compositecmd	[no test files]
ok  	github.com/kcp-dev/kcp/test/e2e/virtual/workspaces	3.376s
ok  	github.com/kcp-dev/kcp/test/e2e/workspacetype	11.625s
```

**Expected behavior**
the test should pass

**Details**
1. Namespace is scheduled to a workload cluster and has its labels patched

2. Resource (e.g. deployment) is reconciled, but the namespace cache is not up to date, so the deployment is either not scheduled to a workload cluster (namespace label in cache is unset), or is scheduled to the namespace's previous cluster assignment.

Namespace is processed again (update event from label patch), but because it was previously scheduled and its placement hasn't changed, enqueueResourcesForNamespace returns without enqueuing all resources.

**Comment by sttts** [comment]
Hopefully solved through https://github.com/kcp-dev/kcp/pull/949/commits/5b1335486e1ac2a54fbe579621796f482d8b2786. We keep watching whether it got better.

**Comment by ncdc** [comment]
I've updated the title to reflect this is an actual bug, and included details of the issue in the description.

**Comment by ncdc** [comment]
We think #987 fixes this. Closing and will reopen if needed.
