### ISSUE TITLE
When workload cluster is deleted from kcp it should delete all associated elements from the physical cluster and kcp

### ISSUE THREAD

**Issue by kasturinarra** [kcp-dev/kcp#948]
**Describe the bug**
Currently user needs to go through multiple deletes to remove all the objects that are being created when workload cluster is added and there is no single command which does it all. 

**To Reproduce**
1. Deploy kcp
2. Add workload using the workload sync command
3. Now run command kubectl delete workloadcluster <name>

**Expected behavior**
I expect workloadcluster entry and any deployments related to it should be deleted from kcp and physical cluster plus it should remove namespace, serviceaccount clusterrole, clusterrolebinding, secret & deployment.

**Additional context**

**Comment by sttts** [comment]
This is not a bug, but by design on a task of a SyncTarget or its controller. The expected behaviour can/should be part of some high level mechanism that owns the life-cycle of SyncTargets and syncers on the physical clusters.
