### ISSUE TITLE
Add support for ppc64le

### ISSUE THREAD

**Issue by rpsene** [kcp-dev/kcp#968]
Power (ppc64le) is a first class citizen in the cloud space (specially on the enterprise side). As we already have k8s and OCP supporting it (and in order to keep advancing on the OCP ecosystem) we need to ensure that KCP also supports Power. 

This is an initial exploratory request to conduct research on what is needed. We, the Power team, will be working on this and contribute any change back to the community.

**Comment by sttts** [comment]
> We, the Power team, will be working on this and contribute any change to back to the community.

That's awesome! Thank you!

**Comment by snehakpersistent** [comment]
We are able to build and deploy KCP server locally on Power without any source code changes. All the e2e tests are passing as well. Our PR https://github.com/kcp-dev/kcp/pull/1216 for adding support to KCP image has been merged.
We are currently working on adding support for syncer image.

**Comment by snehakpersistent** [comment]
We have contributed changes to add power support to KCP and syncer image - #1216 and #1235 
Also published a tutorial blog about deploying a basic application on KCP on Power - https://sneha-kanekar.medium.com/deploying-simple-application-on-kcp-on-power-7553700da10b
@sttts do we need to contribute anything to docs? Or are we good to say that KCP is officially supported on Power? Let us know if any other contributions/tests are required from our side on this.

**Comment by snehakpersistent** [comment]
@sttts @ncdc I have modified test workflow to execute tests on Power. The sample workflow in my fork is located at https://github.com/snehakpersistent/kcp/blob/588b2d387df7cba7d776bde58330cb408360a7a7/.github/workflows/ci.yaml. It would be great to contribute this upstream. Are you open to add support to more architectures to e2e test workflow? Let me know your inputs/suggestions on this.
Workflow output: https://github.com/snehakpersistent/kcp/actions/runs/2997667971

**Comment by mjudeikis** [comment]
/close
Reopen if still needed
