### ISSUE TITLE
Incomplete RBAC cleanup after failed workspace creation

### ISSUE THREAD

**Issue by geoberle** [kcp-dev/kcp#977]
**Describe the bug**
As describe [here](https://github.com/kcp-dev/kcp/blob/d4720dbf2203179c926d6dc8e70ebb1276054611/pkg/virtual/workspaces/registry/rest.go#L476), the creation logic for workspaces first creates a `ClusterRoleBinding` and a `ClusterRole` before creating the actual workspace. If the `ClusterRoleBinding` already exists, also the corresponding workspace is [assumed to exist](https://github.com/kcp-dev/kcp/blob/d4720dbf2203179c926d6dc8e70ebb1276054611/pkg/virtual/workspaces/registry/rest.go#L566).

If the creation of the workspace fails (e.g. providing an unsupported `spec.type`), only the `ClusterRole` [is deleted](https://github.com/kcp-dev/kcp/blob/d4720dbf2203179c926d6dc8e70ebb1276054611/pkg/virtual/workspaces/registry/rest.go#L597) and the `ClusterRoleBinding` remains. Subsequent workspace creation attempts fail.

**To Reproduce**
```
kubectl kcp ws create invalid-ws-type --type invalid
error: clusterworkspaces.tenancy.kcp.dev "invalid-ws-type" is forbidden: spec.type "invalid" does not exist

kubectl kcp ws create invalid-ws-type --type Team
error: workspaces.tenancy.kcp.dev "invalid-ws-type" already exists

kubectl get workspaces
No resources found
```

Manually deleting the `ClusterRoleBinding` resolves the issue.

Suggested solution: delete `ClusterRoleBinding` just like the `ClusterRole` is deleted.

It it is ok for you, i would love to provide a PR for this.

**Comment by ncdc** [comment]
We definitely should fix this, as the error message is confusing, and the UX is suboptimal.

**Comment by stevekuznetsov** [comment]
Is there a technical reason that the Workspace can't be created first? Owner references on the RBAC + creating them after should allow for this be solved at a more generic level than the driver code?

**Comment by geoberle** [comment]
while i think it is technically not necessary to create the `ClusterRoleBinding` first, it serves as a natural safeguard for workspace pretty name uniqueness in the user personal space, because the CRB name incorporates the pretty workspace name.

https://github.com/kcp-dev/kcp/blob/d4720dbf2203179c926d6dc8e70ebb1276054611/pkg/virtual/workspaces/registry/rest.go#L546
