### ISSUE TITLE
Add e2e test that we store CRs in the right locations

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#990]
Normal CRs: `/registry/$group/$resource/customresources/...`

Bound CRs: `/registry/$group/$resource/$identity/...`

**Comment by ncdc** [comment]
Note, upstream kube has tests that talk to storage (etcd) to verify this. Will want this to be generic enough to work with CRDB too

**Comment by sttts** [comment]
Compare https://github.com/kubernetes/kubernetes/blob/master/test/integration/etcd/etcd_storage_path_test.go in kube. Openshift has another one.

**Comment by sttts** [comment]
1. everything created in a workspace shows up byte-by-byte in the right keys in etcd
2. everything under a key path in etcd for one workspace is expected, no unexpected keys
